### ISSUE TITLE
[BUG] Bare Metal Installation on Debian Buster

### ISSUE THREAD

**Issue by steviehs** [jonaswinkler/paperless-ng#1004]
I tried to do a fresh bare metal install on Buster. Unfortunately pikepdf seems to require a newer libqpdf than installed on Buster. Any hints how to get along with that?

    src/qpdf/qpdf.cpp:892:65: error: ‘ownerPasswordMatched’ is not a member of ‘QPDF’
             .def_property_readonly("owner_password_matched", &QPDF::ownerPasswordMatched,
                                                                     ^~~~~~~~~~~~~~~~~~~~

**Comment by jonaswinkler** [comment]
What architecture are you on? If you use precompiled packages of pikepdf, the libqpdf dev files should not be required.
