### ISSUE TITLE
[BUG] Filter by tag does not work in saved views

### ISSUE THREAD

**Issue by Burschi500** [jonaswinkler/paperless-ng#1020]
### Describe the bug
Using the Filter "has tag" and setting it to an actual tag does not change the view in the main page. When selected all files are shown (no filtering at all).

### To Reproduce
Add a saved view with filter has tag and see result

    Host OS Ubuntu 20.04, bare metal install
    Guest OS EndeavourOS (Arch based)
    Browser Firefox 88.0.1
    Installation method bare metal
    nginx reverse proxy

_Is that filter meant as bool??? If so, how can i get a filtered view by actual tag?_

**Comment by jonaswinkler** [comment]
Are you using the admin panel to create saved views? Well, I guess you can do that, but you're not supposed to.

Instead, filter using the buttons on the front end and then hit "Save as" in the "Views" menu button.

**Comment by Burschi500** [comment]
Ah, ok. But then it is not possible to make use of the extended filters available under admin panel? Is there a list of tag-ids?

**Comment by jonaswinkler** [comment]
You can see the ID of a tag in the URL when you navigate to that tag in the admin UI. Again, the admin UI is not intended to be used for that. It's simply there... because it's pretty much free and entirely generated by the framework.
