### ISSUE TITLE
Improve back button behavior when filtering

### ISSUE THREAD

**Issue by dgz** [jonaswinkler/paperless-ng#103]
When filtering the main Documents view, changing the filtering options and applying just updates the current view with the new results without adding a history entry in the browser (not sure if this is the right terminology). The filtering is not part of the query string in the address bar.

For example, if I either manually filter for tag XYZ or click the XYZ tag on a document preview in the Documents list, I can't get back to the all documents view by pressing the browser's back button. If I do I'll leave Documents entirely for whichever page I was on before that, usually dashboard but could be any other part of the app or a different site.
The only way to see all documents again is to either click out to a different view like Dashboard and then back to Documents or click Clear on filters. 

Fixing this has the side benefit of being able to bookmark filtered views which with the magic of browser syncing is a partial workaround to saved views only working on the machine they were created on.

Version: 0.9.5 on MS Edge browser

**Comment by jonaswinkler** [comment]
This would require many changes in the code. Is this really necessary?

Do you feel putting saved views on the server (see #27) is already enough?

**Comment by dgz** [comment]
The back button behavior going back to the previous view is one of those "this is how other sites work" things so it's instinct (at least for me) to reach for the back button to go back a view. Having saved views on the server makes putting the filter in the query string unnecessary but I wasn't sure if the back button behavior depended on the query string or if there's another way it could be implemented.
For example if I filter this github issues list for the label bug, I get back to the full list or my previous filter just by pressing back in the browser rather than finding the clear filters link on the page.

It isn't a breaking bug for sure since there is still a "clear filters" button but it's a usability feature I think many users would expect. I don't think it needs to rank very high on the priority list, the rest of the app works well and pretty much as I expect so this was the only thing that stood out as odd behavior to me.
