### ISSUE TITLE
[BUG] Permission for users or groups do not restrict user actions in frontend

### ISSUE THREAD

**Issue by LindezaGrey** [jonaswinkler/paperless-ng#1035]
**Describe the bug**

Hi there,

i am not quite sure if this is a bug or if i am misunderstanding the concept of permissions in paperless-ng.
In the admin dashboard, i created a "guest" user which i wanted to assign the permission to only view documents, nothing else.
So i added the permission **documents | Dokument | Can view document** and nothing else.
This user is not an administrator and not allowed to login to the adminstrator page (this permission is working -> so he cannot login). BUT in the normal paperless UI this user can basically do anything, from adding tags to viewing server protocols.

Is this intended? Did i miss something in the documentation, or does it have to do something with the docker installation?

thanks and best regards!

**Expected behavior**

If a user / group has only the permission to view documents, nothing else should be possible like adding or deleting tags

**Relevant information**
 - Host OS Synology NAS, INTEL Atom, DSM 6.2.3
 - Any
 - Installation method: [docker]

**Comment by jonaswinkler** [comment]
There's currently no handling of permissions in paperless, at all.

Multi-User support has been discussed a couple times before, and it's quite a complex topic.

**Comment by LindezaGrey** [comment]
Hi,

wow your responsetime is incredible :D

Ah thanks, that explains why i could not find any documentation! I understand that this is a huge topic and as soon as such a system is implemented, somebody would want different authentication providers such as LDAP etc...

Thanks for the great work anyway!

best regards
