### ISSUE TITLE
Quick filtering does not open the Filters pane automatically

### ISSUE THREAD

**Issue by dgz** [jonaswinkler/paperless-ng#104]
Clicking a tag or correspondent on a document preview in the Documents list causes the view to correctly filter to that tag/correspondent but there is no indication on the page that any filter is active. 

Suggested improvements:
1) Open the Filters pane automatically when doing one of these quick filters to give some hint that the current view is filtered
2) Change the background of the Filters button to filled in (like the current list view mode or sort direction buttons do) any time a filter is active

This is related to #103 because I clicked a correspondent to filter to them and couldn't figure out how to get back to the full list without leaving for the Dashboard and coming back. I first tried clicking back in my browser and it took me entirely out of the Documents view. When I came back to Documents, the filters pane was open so I could see the active filter and clear it so it seems that is the intent to have the pane open automatically.

Version: 0.9.5 on MS Edge

**Comment by jonaswinkler** [comment]
Thanks for your suggestions!

I'm considering either (2), or using the labels that says "123 document(s)" right now, and changing that to "Showing 123 out of 465 document(s)". Maybe both.

I feel that option 1 moves the view around too much.
