### ISSUE TITLE
[BUG] Setting invert thumbnails in dark mode not persistent

### ISSUE THREAD

**Issue by tghdev** [jonaswinkler/paperless-ng#1040]
**Describe the bug**
Deactivation of the setting "inverted thumbnails in dark mode" resets to activated after a restart of the docker container.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'deactivate inverted thumbnails in dark mode' while in dark mode
4. Check deactivation by clicking on 'Documents' and validate thumbnails, see also under 'Settings'
5. Logout and Login to check persistance (see step 4)
6. Restart docker container and check persistance (see step 4)

**Expected behavior**
Deactivating the setting "inverted thumbails in dark mode" should remains deactivated after docker container restart.

**Relevant information**
 - Synology NAS DS218+
 - Firefox 88.0.1 (64-bit)
 - paperless-ng 1.4.3
 - docker container
 - No configuration changes in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.

**Comment by jonaswinkler** [comment]
I am unable to reproduce this.

Remember that most of the settings are stored in your local browsing data, and not on the server, so restarting the container does not have any effect on your settings.

**Comment by jonaswinkler** [comment]
There are no logs about this. Dark mode is entirely handled on the client side.

If you delete your browsing data, that also deletes the local settings for dark mode.

Maybe some browser extension or privacy setting?

I'd try with a different browser as well.
