### ISSUE TITLE
[BUG] pickle data was truncated

### ISSUE THREAD

**Issue by abmurksi** [jonaswinkler/paperless-ng#1044]
First, many thanks for paperless-ng! I love it!
But there is this issue that bugs me as I almost lost some files sending them via mobile-phone and they have not been properly consumed.

**Describe the bug**
Every few days paperless-ng stops consuming new files. It starts to consume new documents but never finishes. The files never show up in paperless and the UI just stops consuming the file (after the status freezes on finding the creation date) and returns to idle. In the logs I see:
[paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-m6t8sskh/convert.png -out /tmp/paperless/paperless-m6t8sskh/thumb_optipng.png
and then nothing else anymore.

In the Admin-Panel under Failed Tasks I see this error showing up for "documents.tasks.train_classifier" as well as "documents.tasks.consume_file":

Args: /tmp/paperless/paperless-upload-54u9db88

Kwargs:  {'override_filename': '***MY-FILENAME.pdf***', 'override_title': None, 'override_correspondent_id': None, 'override_document_type_id': None, 'override_tag_ids': None, 'task_id': '6b2b5909-edd7-4acc-a5aa-a49959566b97'}

Result: pickle data was truncated (details see below)

Removing the classification_model.pickle File from the data-folder fixes the issue until it re-appears.

I use the v4.13 in docker (orchestrated via Nomad), /usr/src/paperless/data, /usr/src/paperless/media, /usr/src/paperless/export & /usr/src/paperless/consume are mapped to a NFS share mounted on the local filesystem.

I suspect it to be related to storing the files on a NFS network share, as I've seen in different applications DB corruption with sqlite files hosted on a network share, but I have no way to confirm this theory atm.

**To Reproduce**
I have not yet figured out how to recreate this.

**Expected behavior**
Paperless-ng can recover from this error.

**Webserver logs**
```
pickle data was truncated : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
task_id=task_id
File "/usr/src/paperless/src/documents/consumer.py", line 278, in try_consume_file
classifier = load_classifier()
File "/usr/src/paperless/src/documents/classifier.py", line 35, in load_classifier
classifier.load()
File "/usr/src/paperless/src/documents/classifier.py", line 81, in load
self.tags_classifier = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated
```

**Relevant information**
 - Debian Buster 10.7
 - Browser Firefox 88.0.1
 - Installation method: Docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.
USERMAP_UID = "1000"
USERMAP_GID = "1000"
PAPERLESS_OCR_LANGUAGES="deu eng"
PAPERLESS_TIME_ZONE = "Europe/Rome"
PAPERLESS_FILENAME_FORMAT = "{correspondent}/{created_year}/{title}"
PAPERLESS_TIKA_ENABLED = "1"

**Comment by jonaswinkler** [comment]
The root cause is that the classification model for the automatic matching algorithm is not written to disk completely after it finished training.

The issue you're seeing here is and effect of this. At some point, the model fails to write to disk for some reason (need to investigate) and then, all subsequent tasks fail since I don't catch that exception. My bad.

* I'll address the effect you're seeing. That's easy.
* The root cause might be harder to track down.

**Comment by jonaswinkler** [comment]
I'd also be interested in the output of any failed `documents.tasks.train_classifier` task.

**Comment by abmurksi** [comment]
I see, thats what I suspected. I see you do not use any wal files for the sqlite db which, in my humble knowledge, should prevent corruption on the DB stored on a network share.

Here you go for the train_classifier task output:
```
Args: (None)
Kwargs: {}
Result:
pickle data was truncated : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 43, in train_classifier
classifier = load_classifier()
File "/usr/src/paperless/src/documents/classifier.py", line 35, in load_classifier
classifier.load()
File "/usr/src/paperless/src/documents/classifier.py", line 81, in load
self.tags_classifier = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated
```
Many thanks for your quick reaction

**Comment by jonaswinkler** [comment]
The classification model is not stored in the database, your database is unaffected by this. I'll keep WAL mode in mind, however, there's an open and still unresolved issue for that on the django tracker: https://code.djangoproject.com/ticket/24018.

I've addressed the consumer crash in 1.4.4.

Regarding the root cause: I'd need the output of the first failed train_classifier task.

**Comment by abmurksi** [comment]
Amazing, thank you for the quick fix!
Unfortunately the first failed train_classifier task does not review more information. I check in the DJango Q Failed Tasks section, where can I get more detailed logs?
```

pickle data was truncated : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 43, in train_classifier
classifier = load_classifier()
File "/usr/src/paperless/src/documents/classifier.py", line 35, in load_classifier
classifier.load()
File "/usr/src/paperless/src/documents/classifier.py", line 81, in load
self.tags_classifier = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated
```

Regarding the wal issue, when it is enabled it can mess up with the sqlite-db on a network share, so I am not concerned about that at the moment :-).
https://sqlite.org/wal.html ("All processes using a database must be on the same host computer; WAL does not work over a network filesystem. ")

**Comment by abmurksi** [comment]
Thanks again, let me know if I can further support in tracking down the root cause.
