### ISSUE TITLE
[BUG] paperless-ng installation fails, folders not writable

### ISSUE THREAD

**Issue by snowy-1** [jonaswinkler/paperless-ng#1056]
I wanted to set up my raspberry 4 and started with a fresh image (Raspberry Pi OS lite) installed all updates and continued with the following steps:

`curl -sSL https://get.docker.com | sh`
`sudo usermod -aG docker pi`
`sudo reboot`

`docker run --rm hello-world`
`sudo apt-get install -y libffi-dev libssl-dev`
`sudo apt-get install -y python3 python3-pip`
`sudo apt-get remove python-configparser`
`sudo pip3 -v install docker-compose`
`sudo reboot`

(Next steps found in #879 [BUG] Webserver not starting after upgrade to 1.4.0)
`wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb`
`sudo dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb`
`sudo reboot`

`wget https://raw.githubusercontent.com/jonaswinkler/paperless-ng/master/install-paperless-ng.sh`
`chmod +x install-paperless-ng.sh`
`./install-paperless-ng.sh`

The last step results in following error-messages:
![fehlermeldung paperless](https://user-images.githubusercontent.com/84738147/119391711-fb47be80-bcce-11eb-8e22-0c7cd5afbef9.PNG)

The second strange thing what happes too: The folders are created by the user "root" and not the standard user "pi"
![WhatsApp Image 2021-05-24 at 20 13 22](https://user-images.githubusercontent.com/84738147/119392007-6db89e80-bccf-11eb-99bc-e0229b5e0f82.jpeg)

Also the sub-folder "logs" is missing:
![WhatsApp Image 2021-05-24 at 20 14 13](https://user-images.githubusercontent.com/84738147/119392100-92147b00-bccf-11eb-811d-43707c5b923b.jpeg)

Any Idea what could cause this? And how to fix it? 

**Relevant information**
 - Host OS of the machine running paperless: Raspberry Pi OS lite (Raspberry Pi 4B)
 - Version: Master (ng-1.4.4)
 - Installation method:  docker (docker version  20.10.6, docker-compose version 1.29.2)
 - no configuration changes performed

**Comment by fantasticle** [comment]
I have a similar problem. Reinstalled docker a thousand times and tried everything. Still comes up with:

`  File "/usr/src/paperless/src/paperless/settings.py", line 336, in <module>
    os.makedirs(LOGGING_DIR, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../data/log'
`

I gave /usr/src/paperless a chmod -R 777 and it still doesn't change a thing.

**Comment by dominicpratt** [comment]
I'm facing the exact same issue on a fresh Ubuntu 20.04 installation...

**Comment by jonaswinkler** [comment]
Are your volumes located on network shares?

**Comment by dominicpratt** [comment]
> Are your volumes located on network shares?

No, all volumes and directories are on a local disk.

**Comment by snowy-1** [comment]
> > Are your volumes located on network shares?
> 
> No, all volumes and directories are on a local disk.

Same in my case. All volumes and directories are on a local disk.

btw: I really like paperless-ng! It's a really cool project!

**Comment by mtvu** [comment]
I got the same issue but resolved it by changing the permission of the consume, media, export and data directory. My setup could be different than yours but essentially I have everything under the same paperless-ng folder as follows

~/docker/install-paperless-ng.sh -> install script
~/docker/paperless-ng/
~/docker/paperless-ng/data -> owned by root 
~/docker/paperless-ng/media -> owned by root 
~/docker/paperless-ng/consume -> owned by root 
~/docker/paperless-ng/export  -> owned by root 
~/docker/paperless-ng/docker-compose.env
~/docker/paperless-ng/docker-compose.yml

**Comment by snowy-1** [comment]
thanx @mtvu this worked for me too:
`sudo chmod 777 -R /home/pi/paperless-ng`

**Comment by 0b11001111** [comment]
I have the same issue but the chmod hack does not work for me. Also, this shouldn't be more than a work around as it comes with security issues.

Thanks for your great work at paperless :)

**Comment by allgoewer** [comment]
Same issue here.
It might be of interest that I could not reproduce the issue on 1.4.3

**Comment by dirtrobber** [comment]
I just dealt with something similar yesterday. Ubuntu 20.04. Most recent Docker, paperless-ng, etc.  I used SQLite. No tika. Keeping it simple. 
Solved by:
First changed the folders of media, data, consume and export (all of which I placed outside the container) to 777. Then I ran the install script again. FYI, I used the script repeatedly so that things were consistent. 

Then I encountered this: 

> I have a similar problem. Reinstalled docker a thousand times and tried everything. Still comes up with:
> 
> ` File "/usr/src/paperless/src/paperless/settings.py", line 336, in <module> os.makedirs(LOGGING_DIR, exist_ok=True) File "/usr/local/lib/python3.7/os.py", line 223, in makedirs mkdir(name, mode) PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../data/log'`
> 
> I gave /usr/src/paperless a chmod -R 777 and it still doesn't change a thing.

And had some more fun with permissions. I don't fully remember what I did, changing the directories with -R didn't function the way I thought they should (I think, can't remember).  I might have changed ownership of some files to paperless.

 However, I am sure that I changed permissions on setup.cfg and manager.py to 777. I probably changed the whole directory to 777. Restarted the container and the web server worked. Connected to the site and uploaded a pdf to work on. 

Then another Errno 13 but this time inside 

```
[Errno 13] Permission denied: '/usr/src/paperless/data/index/_MAIN_0.toc.1622572772.1966264'
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 300, in try_consume_file
    classifier=classifier
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 182, in send
    for receiver in self._live_receivers(sender). 
```

Went into the container, changed the permissions of anything that was mentioned in the error. Then uploaded without restarting the container and it worked. 


I might just try to setup a new container to see what happens.

**Comment by dirtrobber** [comment]
Okay. I'm going to document here. 
Used install script. Put media, consume and data outside of container. 

First errors. 

[FirstScriptRun.txt](https://github.com/jonaswinkler/paperless-ng/files/6587185/FirstScriptRun.txt)

then I do this: 

/paperless-ng$ sudo chmod -R 777 ./..


[SecondScriptRun.txt](https://github.com/jonaswinkler/paperless-ng/files/6587229/SecondScriptRun.txt)

Things look good. Uploads and processing work. Why was it so easy this time? 
To be honest, before yesterday I hardly knew anything about Docker.

**Comment by dirtrobber** [comment]
Just for fun I wiped out docker and did the install again. Twice. This time using docker-compose for sqlite and for sqlite with tika. 

I placed my process in these txt files but it is basically the same situation. The only things different from yesterday is that yesterday I included PAPERLESS_OCR_LANGUAGES=eng deu   in the compose.env. So that would be the next variable to check for me. 

[pullfromdocker_justSQLite.txt](https://github.com/jonaswinkler/paperless-ng/files/6587549/pullfromdocker_justSQLite.txt)
[pullfromdocker_tika_Sqlite.txt](https://github.com/jonaswinkler/paperless-ng/files/6587558/pullfromdocker_tika_Sqlite.txt)

**Comment by dirtrobber** [comment]
And this morning I used the script and installed paperless-ng with Postgres and Tika. 
Same thing every time. 

Install breaks. 
$ sudo chmod -R 777 ./. 
Run install again. 
Everything work. 


`Creating directory /tmp/paperless
Waiting for PostgreSQL to start...
/sbin/docker-prepare.sh: connect: Connection refused
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection refused
Attempt 1 failed! Trying again in 5 seconds...
/sbin/docker-prepare.sh: connect: Connection refused
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection refused
Attempt 2 failed! Trying again in 5 seconds...
/sbin/docker-prepare.sh: line 39: /usr/src/paperless/data/migration_lock: Permission denied
Search index out of date. Updating...
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/settings.py", line 336, in <module>
    os.makedirs(LOGGING_DIR, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../data/log'
tee: /usr/src/paperless/data/.index_version: Permission denied
Executing management command createsuperuser --noinput --username essa --email essa@localhost
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/settings.py", line 336, in <module>
    os.makedirs(LOGGING_DIR, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../data/log'
ERROR: 1
`

**Comment by dominicpratt** [comment]
`chmod 777` definitely can't be the solution. I'm not going to make directories and files read-/writeable for everyone and nobody should do that...

**Comment by dirtrobber** [comment]
I agree that it should not be the solution. I'm just documenting that it works. Now someone has to figure out how to fix it so it isn't a problem.

**Comment by snowy-1** [comment]
Same for me. `chmod 777` shold not be the solution.
@jonaswinkler is there any way we can help?

**Comment by Chiron1991** [comment]
+1, facing a similar issue. Running from a docker-compose setup. The setup went good, but when I added a test file to the consume directory I immediately got this error:  

```
webserver_1  | [2021-06-04 11:41:15,585] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/test.txt to the task queue.
webserver_1  | 11:41:15 [Q] INFO Enqueued 1
webserver_1  | 11:41:15 [Q] INFO Process-1:7 processing [test.txt]
webserver_1  | 11:41:15 [Q] INFO Process-1:7 stopped doing work
webserver_1  | 11:41:15 [Q] ERROR Failed [test.txt] - [Errno 13] Permission denied: '/usr/src/paperless/src/../media/documents/archive' : Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
webserver_1  |     res = f(*task["args"], **task["kwargs"])
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
webserver_1  |     task_id=task_id
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 196, in try_consume_file
webserver_1  |     self.pre_check_directories()
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 106, in pre_check_directories
webserver_1  |     os.makedirs(settings.ARCHIVE_DIR, exist_ok=True)
webserver_1  |   File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
webserver_1  |     mkdir(name, mode)
webserver_1  | PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../media/documents/archive'
```

**Comment by dirtrobber** [comment]
I'm unfamiliar with how docker builds containers. I assumed that if docker is root, it should be able to create these directories external to the container and should be able to put the correct permissions on them. Does anyone know what script creates the external directories? Maybe it needs to be tweaked.

**Comment by dirtrobber** [comment]
I did another install. Same thing but instead of changing permissions to 777, I chown ed it and set them to 700. That worked. This seems better to me than 777 permissions on everything. Could anyone tell me the downsides here?


`/paperless-ng$ sudo chown username ./.
/paperless-ng$ sudo chmod -R 700 ./.
`

**Comment by smseidl** [comment]
I also had similar problems but semi followed @dirtrobber  last post.  I didn't ever touch the permissions, just went root and did a `chown -R/r username *`.  I can't remember if it was -r or -R for recursive.

**Comment by tinfever** [comment]
I was having a similar issue with CIFS volume mounts. Adding `,file_mode=0777,dir_mode=0777` to the docker volumes options fixed it for me. Since this only effects how the client mounts the share, I don't think this has nearly as bad security implications. I suppose any other user on the same docker host could access the mounted directories though?
More details in my longer writeup here: https://github.com/jonaswinkler/paperless-ng/discussions/458#discussioncomment-1146945

**Comment by snowy-1** [comment]
Since I have installed a new version (on a plain new environment) today and this issue didn't occur any more, I am closing this issue. 
Thanks for the help!

**Comment by olli0815** [comment]
Soory to say: it isn't solved:

at least on external shares (which have all the rights in the world...)

Waiting for Redis...
Connected to Redis broker.
/sbin/docker-prepare.sh: line 71: /usr/src/paperless/data/migration_lock: Permission denied
