### ISSUE TITLE
Tags go off the thumbnail and take up most of the page

### ISSUE THREAD

**Issue by SimplyCorbett** [jonaswinkler/paperless-ng#107]
I have some documents that have a lot of tags. When viewing the pages in grid mode with thumbnails (middle 4 box icon next to sort) the tags go clear off the thumbnail and take up most of the page.

Not sure if this is something that can be fixed or not.

**Comment by jonaswinkler** [comment]
Uhm, about how many tags are we talking here?

**Comment by SimplyCorbett** [comment]
I have 21 tags displaying per preview, so it's not limited to 7. Using the latest released paperless-ng.

**Comment by jonaswinkler** [comment]
Alright. Do the other layouts (i.e., large cards, table) look reasonably fine with that many tags?

**Comment by bauerj** [comment]
> I have 21 tags displaying per preview.

May I ask what the use case is here?

**Comment by SimplyCorbett** [comment]
> Alright. Do the other layouts (i.e., large cards, table) look reasonably fine with that many tags?

Yes, the rest are all fine.

**Comment by SimplyCorbett** [comment]
> > I have 21 tags displaying per preview.
> 
> May I ask what the use case is here?

Records dating back to 1990 that need specific tags :)

**Comment by jonaswinkler** [comment]
Well, when the system is working for you there's nothing wrong with that, except the layout.
