### ISSUE TITLE
[BUG] Fatal Python Error, Can't Initialize Time

### ISSUE THREAD

**Issue by KennyStier** [jonaswinkler/paperless-ng#1098]
**Describe the bug**
Trying to start Paperless-NG for the first time on a Raspberry Pi using Docker
The webserver will not start. This is the error it gives
```Paperless-ng docker container starting...
Creating directory /tmp/paperless
Waiting for PostgreSQL to start...
Apply database migrations...
Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f0f010 (most recent call first):
/sbin/docker-prepare.sh: line 39:    24 Aborted                 (core dumped) python3 manage.py migrate
Executing /usr/local/bin/supervisord -c /etc/supervisord.conf
Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time
PermissionError: [Errno 1] Operation not permitted
```

**To Reproduce**
Try to setup Paperless-ng using either Docker or via the installation script

**Expected behavior**
Paperless starts as expected

**Relevant information**
 - Host OS of the machine running paperless: Raspbian 10 (Buster)
 - Version 1.4.4
 - Installation method: Docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: none

**Comment by jonaswinkler** [comment]
Seems to be something related to Raspbian and libsecomp2. A quick google resulted in this: https://github.com/linuxserver/docker-papermerge/issues/4#issuecomment-695779275

**Comment by KennyStier** [comment]
Sorry, my Google-fu must have been weak yesterday
That did the trick, thank you
