### ISSUE TITLE
[BUG] gunicorn crash loop with docker and PAPERLESS_DEBUG

### ISSUE THREAD

**Issue by ebardsley** [jonaswinkler/paperless-ng#1119]
# Crash loop on startup w/ docker and PAPERLESS_DEBUG

## Steps to reproduce

- Setup a clean installation using ```install-paperless-ng.sh```. (Note I'm on MacOS, but I don't think that matters.)
- Set ```PAPERLESS_DEBUG=1``` in ```docker-compose.env```
- ```docker compose up```

## Error Log

(see bolded lines)

> 2021-06-16 03:28:53,380 INFO supervisord started with pid 1
> 2021-06-16 03:28:54,386 INFO spawned: 'consumer' with pid 555
> 2021-06-16 03:28:54,406 INFO spawned: 'gunicorn' with pid 556
> 2021-06-16 03:28:54,451 INFO spawned: 'scheduler' with pid 557
> 2021-06-16 03:28:55,464 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2021-06-16 03:28:55,465 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2021-06-16 03:28:55,466 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
>
> [2021-06-15 20:28:57 -0700] [556] [INFO] Starting gunicorn 20.1.0
> [2021-06-15 20:28:57 -0700] [556] [INFO] Listening at: http://0.0.0.0:8000 (556)
> [2021-06-15 20:28:57 -0700] [556] [INFO] Using worker: paperless.workers.ConfigurableWorker
> [2021-06-15 20:28:57 -0700] [556] [INFO] Server is ready. Spawning workers
> **[2021-06-15 20:29:00 -0700] [556] [WARNING] Worker with pid 561 was terminated due to signal 15**
> **[2021-06-15 20:29:00 -0700] [556] [INFO] Shutting down: Master**
> **[2021-06-15 20:29:00 -0700] [556] [INFO] Reason: Worker failed to boot.**
> **2021-06-16 03:29:01,327 INFO exited: gunicorn (exit status 3; not expected)**
> 2021-06-16 03:29:02,337 INFO spawned: 'gunicorn' with pid 576
> System check identified some issues:
> 
> WARNINGS:
> ?: DEBUG mode is enabled. Disable Debug mode. This is a serious security issue, since it puts security overides in place which are meant to be only used during development. This also means that paperless will tell anyone various debugging information when something goes wrong.
> 20:29:03 [Q] INFO Q Cluster vermont-vermont-nineteen-island starting.
> 2021-06-16 03:29:03,361 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 20:29:03 [Q] INFO Process-1:1 ready for work at 578
> 20:29:03 [Q] INFO Process-1:2 ready for work at 579
> 20:29:03 [Q] INFO Process-1 guarding cluster vermont-vermont-nineteen-island
> 20:29:03 [Q] INFO Process-1:3 monitoring at 580
> 20:29:03 [Q] INFO Process-1:4 pushing tasks at 581
> 20:29:03 [Q] INFO Q Cluster vermont-vermont-nineteen-island running.
> System check identified some issues:
> 
> WARNINGS:
> ?: DEBUG mode is enabled. Disable Debug mode. This is a serious security issue, since it puts security overides in place which are meant to be only used during development. This also means that paperless will tell anyone various debugging information when something goes wrong.
> [2021-06-15 20:29:03,960] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/src/../consume
> [2021-06-15 20:29:04 -0700] [576] [INFO] Starting gunicorn 20.1.0
> [2021-06-15 20:29:04 -0700] [576] [INFO] Listening at: http://0.0.0.0:8000 (576)
> [2021-06-15 20:29:04 -0700] [576] [INFO] Using worker: paperless.workers.ConfigurableWorker
> [2021-06-15 20:29:04 -0700] [576] [INFO] Server is ready. Spawning workers
> **[2021-06-15 20:29:06 -0700] [576] [WARNING] Worker with pid 587 was terminated due to signal 15**
> **[2021-06-15 20:29:06 -0700] [576] [INFO] Shutting down: Master**
> **[2021-06-15 20:29:06 -0700] [576] [INFO] Reason: Worker failed to boot.**
> **2021-06-16 03:29:07,499 INFO exited: gunicorn (exit status 3; not expected)**

## Potential Fix

This stops crash looping if I comment out the following in ```settings.py```:

```python
 if DEBUG:
     INSTALLED_APPS.append("channels")
```

**Comment by jonaswinkler** [comment]
Duplicate of #810.

Also, this is absolutely required for development.
