### ISSUE TITLE
Error when changing OCR language in .env

### ISSUE THREAD

**Issue by thangstad** [jonaswinkler/paperless-ng#113]
I get the following error when changing ocr language parameter .env from default to nor

```

ERRORS:

?: The selected ocr language nor is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

Waiting for PostgreSQL to start...

SystemCheckError: System check identified some issues:

```

My .env file
```

#USERMAP_UID=1000
#USERMAP_GID=1000

PAPERLESS_OCR_LANGUAGES=nor
#PAPERLESS_SECRET_KEY=change-me

PAPERLESS_TIME_ZONE=Europe/Oslo
PAPERLESS_OCR_LANGUAGE=nor

```

I have tried to run apt-get update && apt-get install tesseract-ocr-no inside the container fetching the package manually, however I get the same error message

**Comment by jonaswinkler** [comment]
OH. I'm so sorry. The startup script actually checks for the languages before installing them. Thats pretty bad. I was about to get a new version out, I'm just waiting for some automated checks to complete.
