### ISSUE TITLE
[BUG] paperless-ng does not display a favicon

### ISSUE THREAD

**Issue by SaraSmiseth** [jonaswinkler/paperless-ng#1133]
**Describe the bug**
Paperless-ng does not display a favicon.

**To Reproduce**
1. Go to any site
2. Look at tab
3. No favicon

**Expected behavior**
Display a favicon.

**Screenshots**
![image](https://user-images.githubusercontent.com/51710585/122799828-80b89180-d2c2-11eb-9fb5-b9432b3a78db.png)

**Relevant information**
 - Archlinux
 - Firefox 89.0.1 (64-bit)
 - paperless-ng 1.4.5
 - Installation method: docker

**Comment by shamoon** [comment]
There should be a favicon, its included in the build. Do you see the request in your browser network tab etc? (screenshot below but basically request to `/favicon.ico`)

<img width="388" alt="Screen Shot 2021-06-22 at 6 25 53 AM" src="https://user-images.githubusercontent.com/4887959/122932645-c311bb00-d322-11eb-9ffe-2118e144935c.png">

**Comment by SaraSmiseth** [comment]
I checked again to see the request and now its working fine. 
I think my browser somehow cached something wrong. I have authelia for authentication and had to login yesterday.
