### ISSUE TITLE
[Other] docker-compose + existing postgres 

### ISSUE THREAD

**Issue by tedtms** [jonaswinkler/paperless-ng#1135]
Hi,

Due to some dependency/library issues I can't seem to figure out on 1.4.5, I'm now trying to move from baremetal paperless-ng to docker-compose. 

However, I'm having trouble figuring out how to point my docker-compose.yml to my existing postgres database. I tried removing the service:db section and other references to db in the yml, and I moved all of my paperless.conf options into a docker-compose.env file as instructed in the setup docs. I'm admittedly not very familiar with docker or its utilities, so I may be completely off in how I'm doing this.

Any help would be appreciated! Thanks again for building this awesome project.

Cheers,
Ted

**Comment by jonaswinkler** [comment]
The one thing to keep in mind here is that all services defined in the docker-compose file run in an isolated network that is created specifically for paperless-ng. And for other docker-compose applications as well. Side note: This is also why you can have two separate docker-compose applications both with a "db" service in it. The hostname exists on both networks separately and each application resolves to the "db" service inside this network.

This is also why you're unable to access any services running outside (I'd assume your existing postgres server is such a service) from inside a docker-compose application. I'd suggest to read up on docker-compose networking, maybe there's some port forwarding option. I've not yet came across the need to configure something like that, so I can't provide any details here.

**Comment by tedtms** [comment]
OK thanks, that's what I was afraid of.
