### ISSUE TITLE
Setup without docker-compose (unraid)

### ISSUE THREAD

**Issue by ministryofsillywalks** [jonaswinkler/paperless-ng#114]
I'm trying to get paperless-ng running on an unraid server.
Unraid doesn't come with docker-compose so I went about setting up the docker image using unraids docker templates.
This worked great however I now have the image running but need to create a superuser.
As far as I can tell this can only be achieved with the `docker-compose run --rm webserver createsuperuser` command.
Is there any other way to setup the superuser?
Unraid allows me to `docker exec -it paperless-ng sh` into the container. But none of the commands work here.
I also need to `docker-compose run --rm webserver document_index reindex` to reindex my existing files from paperless.

EDIT:
nevermind solved it.
To anyone looking for a solution.
Open the console from the unraid docker page.
Make ./manage-py executable
`chmod +x manage.py`
then run
`./manage.py createsuperuser`

**Comment by jonaswinkler** [comment]
Be advised that without using the docker-compose service description, you will need to provide a redis server by yourself and point paperless towards that server by configuring the relevant environmental variables.

**Comment by ministryofsillywalks** [comment]
Yeah I did all that manually.
Postgres was already running anyway.
Pretty straight forward except the createsuperuser.
Just thought I'd leave the issue up as unraid is pretty popular and this fork probably should replace most peoples paperless setups soon ;)

**Comment by jonaswinkler** [comment]
Huh, okay. I don't know about unRaid, I still do pretty much everything on plain debian installations and just recently started messing with this docker stuff. Maybe I need to put some information into the documentation about installations without docker-compose.

**Comment by jonaswinkler** [comment]
Also, for future reference.

https://github.com/selfhosters/unRAID-CA-templates/pull/190

**Comment by Tooa** [comment]
@ministryofsillywalks `paperless-ng` is now available via Unraids community application store. I also created a call-for-testing in the paperless support thread [here](https://forums.unraid.net/topic/87196-support-paperless-docker/?do=findComment&comment=923970).
