### ISSUE TITLE
List View: Empty title can't access document 

### ISSUE THREAD

**Issue by ministryofsillywalks** [jonaswinkler/paperless-ng#115]
Using the list view a lot. This doesn't apply to the other views.
Adding Documents I made the mistake to leave one documents title empty.
I saved and exited and then found I couldn't open up the document because there was not title to click on.

![image](https://user-images.githubusercontent.com/10544895/101753464-f30a1700-3ad2-11eb-91b3-13e684c414e5.png)

Maybe add a sanity check when leaving title blank? Or maybe add an edit button to the list view?

**Comment by jonaswinkler** [comment]
Clearly an oversight on my part.

I can't do validation on empty titles. I'd like to, but when I do that, users who actually have empty titles in their collections won't be able to update.

I'm considering to add a "*(no title)*" to the list when none is present, same for the other views as well.

**Comment by jonaswinkler** [comment]
Alright, that's resolved then.

Since you're using the list view a lot: How's the usability? Missing anything? I'm not entirely happy with the layout yet. I've also considered adding buttons for download, view and edit, just like in the other views, but I'm not sure where to put that.

**Comment by ministryofsillywalks** [comment]
I would like it if I could click on the category names and have it then sort by that.
![image](https://user-images.githubusercontent.com/10544895/101948508-6fdfe280-3bf2-11eb-952b-14cf03bc84b9.png)
For example click on "Document Type" and have it sort alphabetically by document types.
Or click on "Correspondent" and have it sort alphabetically by correspondent.
I know that I could click on "sort by" and achieve exactly the same behavior but clicking on the category seems more intuitive (same behavior as in windows explorer for example)

Regarding the edit/download buttons. Maybe have this show on mouse over? That would keep the list looking nice and clean but once you mouse over the title the buttons could show up?
However this wouldn't translate well to a potential mobile interface...
