### ISSUE TITLE
DD MM YYYY in UI instead of MM DD YYYY

### ISSUE THREAD

**Issue by ministryofsillywalks** [jonaswinkler/paperless-ng#116]
The current date format in the webui is the "american" format of "MM DD YYYY" however this feels really odd to me as a European who uses "DD MM YYYY" or "YYYY MM DD"
Is there any way to change the default look?
This is for example in the documents list under created 
![image](https://user-images.githubusercontent.com/10544895/101752724-1b454600-3ad2-11eb-971b-3f18e0a8371a.png)

or editing a document under date created:
![image](https://user-images.githubusercontent.com/10544895/101752692-141e3800-3ad2-11eb-940c-90c439564f0e.png)

**Comment by jonaswinkler** [comment]
I'll look into that. I haven't yet messed with localization at all.
