### ISSUE TITLE
Add ability to disable inotify

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#118]
the inotify mechanism does not fire in all cases e.g. for NFS shares (see this [issue](https://github.com/the-paperless-project/paperless/issues/448)) or SFTP upload (see this [issue](https://github.com/the-paperless-project/paperless/issues/665)). 

Since in paperless-ng the `consumer` is started with `command=python3 manage.py document_consumer` in `supervisord.conf`, there is no way to pass the `-no-inotify`flag at runtime any more. There is a env var for `--loop-time` though.

It would be nice if the user of paperless-ng could disable inotify and use a loop time mechanism instead for those use cases.

**Comment by jonaswinkler** [comment]
This is already in paperless-ng.

https://paperless-ng.readthedocs.io/en/latest/configuration.html#software-tweaks

See `CONSUMER_POLLING`.

**Comment by Tooa** [comment]
Should have done better research. Thank you for the reference that is exactly what I was looking for!

**Comment by zawnk** [comment]
Sorry for re-opening this, but I had the exactly the same issue and looked for 30 mins for a solution and was almost done opening my own issue :) Please add this somewhere in the docs.

In the [paperless docs](https://paperless.readthedocs.io/en/latest/setup.html#docker-method) under point 4 this is specifically mentioned in a warning box. If I search the paperless-ng docs for `inotify` I don't find anything. Thanks!
