### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by wechsler42** [jonaswinkler/paperless-ng#119]
Hi Jonas,
when I try to install image with Digest a80cfcfe7c9f I receive:
`# docker-compose up -d

Creating network "17_default" with the default driver

Building webserver

ERROR: Cannot locate specified Dockerfile: Dockerfile
`

**Comment by jonaswinkler** [comment]
Hey!

Where did you get the docker-compose files from?

**Comment by wechsler42** [comment]
Hi Jonas,
I used docker-compose.sqlite.yml derived from https://github.com/jonaswinkler/paperless-ng/tree/master/docker/local
which I adapted to:
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: always

  webserver:
    build: .
    restart: always
    depends_on:
      - broker
    ports:
      - 8123:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /host path to/paperless_config:/usr/src/paperless/data
      - /host path to/media:/usr/src/paperless/media
      - /host path to/export:/usr/src/paperless/export
      - /host path to/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
ersion: "3.4"
services:
  broker:
    image: redis:6.0
    restart: always

  webserver:
    build: .
    restart: always
      PAPERLESS_REDIS: redis://broker:6379


volumes:
  data:
  media:

**Comment by jonaswinkler** [comment]
Please download the release archive instead. The bigger release contains the files you need to build the image yourself. This is was this docker compose file is trying to do, but it needs more files to do that. If you just want to have the docker image downloaded for you (which is what you probably want if you're on a regular computer), use the compose-files from the /hub/ directory.

**Comment by wechsler42** [comment]
Hi Jonas,
thanks for helping me out, it seems that I took the wrong turn. With a docker-compose file from 
paperless-ng/docker/hub/  and the docker-compose.env-file from paperless-ng/docker/docker-compose.env   everything works fine.
Perhaps you may want to improve the documentation a bit, then I would like to suggest:
a) Link directly to the docker-compose files from 
paperless-ng/docker/hub/  and the docker-compose.env-file from paperless-ng/docker/docker-compose.env 
b) add a docker-compose section to https://hub.docker.com/r/jonaswinkler/paperless-ng as the folks of linuxserver.io do it as default. See https://hub.docker.com/r/linuxserver/nginx (web server) as an easy example and https://hub.docker.com/r/linuxserver/lychee as a more complex one (web server and database). The explicit docker-compose samples there  simplify the the deployment of the containers significantly.

**Comment by jonaswinkler** [comment]
Alright, I'll keep that in mind. As for now, I'd very much like to focus on actually getting bugs fixed and features done, since the deployment seems to be working for most users.
