### ISSUE TITLE
[BUG] Unable to add document, Paperless thinks it is a duplicate...but is is not.

### ISSUE THREAD

**Issue by abctje** [jonaswinkler/paperless-ng#1192]
[2021-07-27 10:10:11,990] [ERROR] [paperless.consumer] Not consuming Jaarnota-2020-07-27T00_00_00.pdf: It is a duplicate.

The document is a yearly report from the electricity company. It is largely the same but the usage data and financial data is different. Paperless won't import it. Changing the document name does not fix the problem.

I forgot to mention that I am using the 1.4.5 Docker version.

**Comment by abctje** [comment]
I found a workaround to upload and consume the document. It is a quick fix for now but not one for future documents.

Temp fix: edit the top of  the document and upload. The document is now consumed and added.

**Comment by mweimerskirch** [comment]
That's strange. Are you absolutely sure it's not a duplicate? I read through the source code and Paperless compares the MD5 sum of the imported document to that of the documents in the database (for both originals and processed versions). Finding an MD5 colision (where both documents would have the same MD5) is also very unlikely.

**Comment by abctje** [comment]
Absolutely sure, the document has minor differences. I can delete the files and upload again if that helps. What do you want me to collect?

**Comment by abctje** [comment]
Found the problem, for some reason it did already exist. I must have missed a correct upload and tried again. Sorry guys! I'll buy you a beer sometime ;-)
