### ISSUE TITLE
Uploading PDF stuck

### ISSUE THREAD

**Issue by AnarchyCent** [jonaswinkler/paperless-ng#1195]
### Discussed in https://github.com/jonaswinkler/paperless-ng/discussions/1194

<div type='discussions-op-text'>

<sup>Originally posted by **njeri123** July 27, 2021</sup>
When uploading a PDF file, the file is stuck in this state:
![sqT1lAwqhv](https://user-images.githubusercontent.com/18693679/127140915-e77a0bfe-d0de-4439-90c7-45a909a7d7b0.png)

I have the latest version of paperless-ng running in a Docker container on a Synology NAS DS918+.

The installation was done with Docker compose using portainer and then the command "python3 manage.py createsuperuser" was executed in the container.
docker-compose.portainer.yml:

    # docker-compose file for running paperless from the Docker Hub.
    # This file contains everything paperless needs to run.
    # Paperless supports amd64, arm and arm64 hardware.
    #
    # All compose files of paperless configure paperless in the following way:
    #
    # - Paperless is (re)started on system boot, if it was running before shutdown.
    # - Docker volumes for storing data are managed by Docker.
    # - Folders for importing and exporting files are created in the same directory
    #   as this file and mounted to the correct folders inside the container.
    # - Paperless listens on port 8010.
    #
    # In addition to that, this docker-compose file adds the following optional
    # configurations:
    #
    # - Instead of SQLite (default), PostgreSQL is used as the database server.
    #
    # To install and update paperless with this file, do the following:
    #
    # - Open portainer Stacks list and click 'Add stack'
    # - Paste the contents of this file and assign a name, e.g. 'Paperless'
    # - Click 'Deploy the stack' and wait for it to be deployed
    # - Open the list of containers, select paperless_webserver_1
    # - Click 'Console' and then 'Connect' to open the command line inside the container
    # - Run 'python3 manage.py createsuperuser' to create a user
    # - Exit the console
    #
    # For more extensive installation and update instructions, refer to the
    # documentation.
    
    version: "3.4"
    services:
      broker:
        image: redis:6.0
        restart: unless-stopped
    
      db:
        image: postgres:13
        restart: unless-stopped
        volumes:
          - pgdata:/var/lib/postgresql/data
        environment:
          POSTGRES_DB: paperless
          POSTGRES_USER: paperless
          POSTGRES_PASSWORD: paperless
    
      webserver:
        image: jonaswinkler/paperless-ng:latest
        restart: unless-stopped
        depends_on:
          - db
          - broker
        ports:
          - 8010:8000
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8000"]
          interval: 30s
          timeout: 10s
          retries: 5
        volumes:
          - data:/usr/src/paperless/data
          - media:/usr/src/paperless/media
          - /volume1/Dateien/Documents/ScannedDocuments:/usr/src/paperless/export
          - /volume1/Dateien/Documents/ToBeScanned:/usr/src/paperless/consume
        environment:
          PAPERLESS_REDIS: redis://broker:6379
          PAPERLESS_DBHOST: db
    # The UID and GID of the user used to run paperless in the container. Set this
    # to your UID and GID on the host so that you have write access to the
    # consumption directory.
          USERMAP_UID: 1026
          USERMAP_GID: 100
    # Additional languages to install for text recognition, separated by a
    # whitespace. Note that this is
    # different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
    # language used for OCR.
    # The container installs English, German, Italian, Spanish and French by
    # default.
    # See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
    # for available languages.
          #PAPERLESS_OCR_LANGUAGES: tur ces
    # Adjust this key if you plan to make paperless available publicly. It should
    # be a very long sequence of random characters. You don't need to remember it.
          #PAPERLESS_SECRET_KEY: change-me
    # Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
          PAPERLESS_TIME_ZONE: Europe/Zurich
    # The default language to use for OCR. Set this to the language most of your
    # documents are written in.
          PAPERLESS_OCR_LANGUAGE: deu
    
    volumes:
      data:
      media:
      pgdata:

I hope you can help me.
</div>

**Comment by iwconfig** [comment]
Hello,

please select the pasted content of your `docker-compose.portainer.yml` and press <TAB> two times (2) to indent it with 4 whitespace characters. This is syntax for code block in the Markdown language which is used for formatting here on Github.

**Comment by iwconfig** [comment]
Duplicate #1194 is now solved. This one can be closed.
