### ISSUE TITLE
Allow Splitting PDFs

### ISSUE THREAD

**Issue by bwoodworth** [jonaswinkler/paperless-ng#120]
It would be nice to be able to split a PDF document into separate documents. Being able to split would allow scanning many documents together instead of having to scan each one separately. You would then being to split them out into separate documents within Paperless and categorize accordingly.

**Comment by jonaswinkler** [comment]
Uhm, I don't see the point, sorry.

Besides being a ton of work for something that can be done by scanning documents individually, this causes multiple issues:

- paperless adds metadata after importing them. It cannot do that reliably if the "document" contains multiple documents.
- paperless keeps checksums, documents are immutable.
- It would require a new, probably very complex interface. I want to keep the interface simple.

**Comment by bwoodworth** [comment]
Fair enough.  I only mentioned it because I saw the feature in PaperMerge and used it there a bit before I decided the UI was too clunky and was a resource hog.  I much prefer the look and simplicity of Paperless, but this was one feature that I missed.  Like you said, there are workarounds so it isn't necessary.  It would just speed up the process of scanning many different documents.

Thanks for the hard work on this.

**Comment by jonaswinkler** [comment]
I immediately thought about PaperMerge when you mentioned this. Not sure why =)

I see one scenario where its page editing feature is useful. Duplex scanners usually come with blank page detection, however, my scanner sometimes adds two pages per sheet, even though the back is blank. I've got quite a few documents with blank pages in between that I'd like to cut out, but on the other hand, they really don't get in the way.

**Comment by bwoodworth** [comment]
My use case would be if I have a stack of bills that came in this month.  You throw them all on the scanner and press scan.  They all get put into one PDF and consumed into Paperless.  You would then be able to split them all out in the Paperless UI which would be faster than standing over the scanner and doing each one at a time. Obviously, this wouldn't be a minor effort to add the feature so the benefit may not be worth it.

**Comment by Maximus48p** [comment]
> My use case would be if I have a stack of bills that came in this month. You throw them all on the scanner and press scan. They all get put into one PDF and consumed into Paperless. You would then be able to split them all out in the Paperless UI which would be faster than standing over the scanner and doing each one at a time. Obviously, this wouldn't be a minor effort to add the feature so the benefit may not be worth it. Thanks again!

I agree. Same here. Often i put multiple documents on the sheetfeeder for scanning. So an easy functionality to split and rollover the consuming rules again, would be fantastic feature. :)
