### ISSUE TITLE
Internationalization / localization of frontend

### ISSUE THREAD

**Issue by C0nsultant** [jonaswinkler/paperless-ng#123]
Thank you for picking up work on paperless again, Jonas!
I've been experimenting with both the old paperless and mayan for a while. With both, it just didn't click for me.
NG on the other hand is more approachable and intuitive to use, kudos!
While not sure if the barebones simplicity of NG will do it for me in the long run, I know a lot of people that could and would benefit from it... If it weren't for the fact that it currently only offers an english interface. Most of my friends and family that I have in mind simply are not proficient enough in a foreign language. As a result, the barrier to entry would likely be high enough for most and they would simply not use it because of that.

Given that the current frontend is reasonably sized and only contains a handful of static text, will you consider maintaining an internationalized version of NG? You don't even have to do the translation yourself, django's [i18n](https://docs.djangoproject.com/en/3.1/topics/i18n/) allows for a lot of flexibility and community contributions.

At a basic level, the whole installation would be switched to a static language (i.e. through ` paperless.conf` or the admin page).
More advanced versions could include automatic switching based on `Accept-Language` headers and/or per-user configuration.

**Comment by jonaswinkler** [comment]
Hello!

I've got internationalization in mind. I'm aware that we can create simple language files and have translation done by users who speak that language. However, we're still doing lots of work on the front end and change things around quite a bit (adding menu options for bulk updates, changing the filter interface) and all these updates add or remove strings I'd need to translate / have translated.

Once we have a stable release, I expect the interface to remain the same, mostly. Then we can start thinking about translation.

**Comment by jonaswinkler** [comment]
Also see #116

**Comment by jonaswinkler** [comment]
Alright, I've just looked into that and figured out how to serve different versions of the front end based on the requested language, and it's certainly nice to have paperless available in your native language.

Angular creates some XLIFF format files, and translation seems to be fairly simple with these: https://angular.io/guide/i18n#translate-each-translation-file

Once I've got #170 sorted out I'll add localization support.

**Comment by jonaswinkler** [comment]
Does anyone know about some nice tools that could help us with translating paperless? I guess we could just edit the XLF files directly, but some online tool that tracks completeness of translations and handles updates to the message files (new and obsolete translation units) would be nice.

File to translate looks like this right now. [messages.xlf.txt](https://github.com/jonaswinkler/paperless-ng/files/5749199/messages.xlf.txt)

**Comment by zjean** [comment]
Maybe the open source version of crowdin?

**Comment by jonaswinkler** [comment]
This is in fact pretty damn nice. Lets see how they like the project...

**Comment by C0nsultant** [comment]
[Transifex](https://docs.transifex.com/projects/open-source-project) offers free serivce to open source projects under a few loose conditions that NG should satisfy.

> Transifex offers an Open Source Program to Open Source projects that have no funding, revenue, and/or commercialization model. The intent is to support small and independent Open Source projects.
[...]
Open Source projects are ones with publicly available source codes licensed under an OSI-approved license, such as GPL or BSD.

**Comment by jonaswinkler** [comment]
Set up a project at transifex, which can be accessed here: https://www.transifex.com/--261/paperless-ng/

**Comment by jonaswinkler** [comment]
See #212.

**Comment by jonaswinkler** [comment]
Also see #215.

This is now done in two separate tickets, so I'll close this.
