### ISSUE TITLE
[BUG] module 'aioredis' has no attribute 'create_redis'

### ISSUE THREAD

**Issue by harleypig** [jonaswinkler/paperless-ng#1230]
**Relevant Information**
- System is Archlinux, updated this morning.
- Chromium Version 89.0.4389.90 (Official Build) (64-bit)
- Paperless-NG version is 1.4.5, installed from [AUR package](https://aur.archlinux.org/packages/paperless-ng/).
- Paperless is installed on virtual bare-metal.
- Redis is installed, using AUR package, and running.
- I'm able to log in to the app, everything else--that I've tested--seems to be running ok.
- Could not find anything relevant in the online documentation.
- Could not find anything relevant in issues.
- Could not find anything relevant in discussions.

**/etc/paperless.conf**

    PAPERLESS_REDIS=redis://localhost:6379
    PAPERLESS_DBHOST=localhost
    PAPERLESS_DBPORT=5432
    PAPERLESS_DBNAME=paperless
    PAPERLESS_DBUSER=paperless
    PAPERLESS_DBPASS=mysUp3rs3kr3tp4ssw0rd
    PAPERLESS_DBSSLMODE=prefer
    PAPERLESS_CONSUMPTION_DIR=/var/lib/paperless/consume
    PAPERLESS_DATA_DIR=/var/lib/paperless/data
    PAPERLESS_MEDIA_ROOT=/var/lib/paperless/media
    PAPERLESS_STATICDIR=/usr/share/paperless/static
    PAPERLESS_SECRET_KEY='4n0th3rsUp3rs3kr3tp4ssw0rd'
    PAPERLESS_OCR_LANGUAGE=eng
    PAPERLESS_OCR_MODE=skip
    PAPERLESS_OCR_OUTPUT_TYPE=pdfa
    PAPERLESS_OCR_PAGES=0
    PAPERLESS_OCR_IMAGE_DPI=300
    PAPERLESS_OCR_CLEAN=clean
    PAPERLESS_OCR_DESKEW=true
    PAPERLESS_OCR_ROTATE_PAGES=true
    PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD=12.0
    PAPERLESS_CONVERT_MEMORY_LIMIT=0
    PAPERLESS_CONVERT_TMPDIR=/var/lib/paperless/tmp
    PAPERLESS_TIME_ZONE=America/Denver
    PAPERLESS_OPTIMIZE_THUMBNAILS=true
    PAPERLESS_SCRATCH_DIR=/var/lib/paperless/uploads
    GUNICORN_CMD_ARGS='--bind=localhost:7000 --access-logfile /var/log/paperless/gunicorn.access.log --error-logfile /var/log/paperless/gunicorn.error.log'

**Describe the bug**
When uploading a pdf, named `test.pdf`, via the 'Browse files' button on the dashboard, I get an `Upload complete, waiting...` message that doesn't change until I give up and look at the logs. The logs say this:

    [2021-08-15 04:21:22,371] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: 
    /var/lib/paperless/consume

    [2021-08-15 04:22:52,252] [DEBUG] [paperless.management.consumer] Not consuming file
    /var/lib/paperless/consume/__paperless_write_test_2606971__: File has moved.

    [2021-08-15 04:24:17,170] [DEBUG] [paperless.management.consumer] Not consuming file 
    /var/lib/paperless/consume/__paperless_write_test_2607143__: File has moved.

    [2021-08-15 04:24:23,029] [INFO] [paperless.sanity_checker] Sanity checker detected no issues.

    [2021-08-15 04:24:41,619] [WARNING] [paperless.management.consumer] Not consuming file 
    /var/lib/paperless/consume/__paperless_write_test_2607214__: Unknown file extension.

That doesn't make any sense. I looked at `Admin -> Failed Tasks` and this is what I see in the result field for that upload attempt.

    module 'aioredis' has no attribute 'create_redis' : Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
    File "/usr/share/paperless/src/documents/tasks.py", line 74, in consume_file
    document = Consumer().try_consume_file(
    File "/usr/share/paperless/src/documents/consumer.py", line 186, in try_consume_file
    self._send_progress(0, 100, 'STARTING', MESSAGE_NEW_FILE)
    File "/usr/share/paperless/src/documents/consumer.py", line 63, in _send_progress
    async_to_sync(self.channel_layer.group_send)("status_updates",
    File "/usr/lib/python3.9/site-packages/asgiref/sync.py", line 223, in __call__
    return call_result.result()
    File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
    File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
    File "/usr/lib/python3.9/site-packages/asgiref/sync.py", line 292, in main_wrap
    result = await self.awaitable(*args, **kwargs)
    File "/usr/lib/python3.9/site-packages/channels_redis/core.py", line 647, in group_send
    async with self.connection(self.consistent_hash(group)) as connection:
    File "/usr/lib/python3.9/site-packages/channels_redis/core.py", line 884, in __aenter__
    self.conn = await self.pool.pop()
    File "/usr/lib/python3.9/site-packages/channels_redis/core.py", line 78, in pop
    conn = await aioredis.create_redis(**self.host)
    AttributeError: module 'aioredis' has no attribute 'create_redis'

I don't know if this is an issue with redis installation, or with my paperless-ng configuration. Any pointers?

**Webserver logs**

The only thing my error log:

    2021/08/15 09:27:45 [warn] 2607504#2607504: *9670 an upstream response is buffered to a temporary file /var/lib/nginx/proxy/3/01/0000000013 while reading upstream, client: 0.0.0.0, server: my.paperless.domain, request: "GET /static/frontend/en-US/main.js HTTP/2.0", upstream: "http://127.0.0.1:7000/static/frontend/en-US/main.js", host: "my.paperless.domain", referrer: "https://my.paperless.domain/"
    2021/08/15 09:27:45 [warn] 2607504#2607504: *9670 an upstream response is buffered to a temporary file /var/lib/nginx/proxy/4/01/0000000014 while reading upstream, client: 0.0.0.0, server: my.paperless.domain, request: "GET /static/frontend/en-US/polyfills.js HTTP/2.0", upstream: "http://127.0.0.1:7000/static/frontend/en-US/polyfills.js", host: "my.paperless.domain", referrer: "https://my.paperless.domain/"
    2021/08/15 09:27:45 [info] 2607504#2607504: *9729 client 0.0.0.0 closed keepalive connection
    2021/08/15 09:28:02 [warn] 2607504#2607504: *9670 a client request body is buffered to a temporary file /var/lib/nginx/client-body/0000000015, client: 0.0.0.0, server: my.paperless.domain, request: "POST /api/documents/post_document/ HTTP/2.0", host: "my.paperless.domain", referrer: "https://my.paperless.domain/dashboard"

**Comment by jonaswinkler** [comment]
Archlinux version of aioredis is at 2.0.0, whereas paperless-ng depends on 1.3.x - they have changed some interfaces, and other dependencies of paperless that use aioredis have not updated yet.

Similar, but not quite the same: https://github.com/aio-libs/aioredis-py/issues/1082#issuecomment-890129597
