### ISSUE TITLE
Mobile view on 10" laptop screen

### ISSUE THREAD

**Issue by mrwolf78** [jonaswinkler/paperless-ng#1237]
I'm struggling with a (forced?) mobile view of paperless on my Surface 10" laptop (resolution 1800x1200). SInce this is also a crippled view compared to the normal view, I would really like to be able to choose the normal interface when logged in. On a 14" laptop the normal view works fine.

Is there a way to switch between the two views, or change the resolution (or screen size?) on which paperless decides to show the mobile view?

**Comment by shamoon** [comment]
The site uses a so-called responsive design where window size determines layout, fairly standard on the modern web. It is not meant to be ‘crippled’ but rather a compromise based on available screen size.

But that resolution is pretty large, what specifically is the issue for you? Screenshots could help. It is a challenge to keep all interface elements usable and visually uncluttered.

**Comment by mrwolf78** [comment]
I was hoping it was responsive, but on my laptop it won't shift to the 'normal' view with the previews and more options. All I get is the mobile version with less options available.

<img width="900" alt="paperless-sp" src="https://user-images.githubusercontent.com/643348/129741537-d6b870f3-91c9-4788-877d-541f30516710.png">

**Comment by shamoon** [comment]
That screenshot is the admin interface, not the actual frontend of paperless.

**Comment by mrwolf78** [comment]
You are right (obviously), but on my Surface laptop, when I go to my paperless-server 192.168.x.x:8001, it automatically redirects to /admin after logging in. I hadn't noticed that. 

On my other laptop /dashboard is loaded. When I go to /dashboard on my Surface, it works fine indeed. It's just strange why it loads the admin interface by default at first.

**Comment by jonaswinkler** [comment]
You may have installed paperless (old) before. This one installed a permanent redirect in your browser from / to /admin. Clear your browser data and it should work.

**Comment by mrwolf78** [comment]
Yes, that did it, thanks!
