### ISSUE TITLE
document_retagger -T -f removes inbox tag from all documents

### ISSUE THREAD

**Issue by rssfed23** [jonaswinkler/paperless-ng#125]
I'm not sure if this is intentional, but if document_retagger -T with the -f force option is run, it removes the inbox tag from all documents.

I can understand why it's done this, as with no other matching criteria specified by the user the -f option would remove the tag, but I'm logging this as it might be "safer" to have the -f option exclude inbox tags from removal when running it as it might be unexpected behaviour for users (or at least make it clear in the docs).

**Comment by rssfed23** [comment]
Related, but if you've set up tags for manual assignment and have not put in any matcher, these will also have the tags removed. 
So perhaps a flag to not run removal on any tag with an empty matcher might be a way to solve both aspects.

**Comment by jonaswinkler** [comment]
Regarding inbox tags: agreed. These should not get removed.

 Regarding tags without matching rules: Probably. I'll think about that.
