### ISSUE TITLE
[BUG] I can see scans from other users

### ISSUE THREAD

**Issue by polaroidkidd** [jonaswinkler/paperless-ng#1265]
Hi

Started using paperless-ng and its awesome so far! Much props for all the work here!

Regarding my issue (I'm not sure if its a bug or if I somehow managed to not find it in the docs/issue page).

I have three users configured in my instance

Admin: Does admin-y stuff
Me and my SO.

I currently use the android scan client to push "scans" to the paperless instance, using my credentials (not the admin credentials). 

I did hope that if I scanned things using this process the images scanned would only show up in my view, however, what I'm seeing is that it pops up in my SO's view as well.

**So, to reproduce:**

1. Setup paperless-ng using docker-compose (psql)
2. Create Users
3. Install Android App
4. Log in to android app using one of the users
5. Scan a document

EXPECTED:
 * Only the user tied to the android app sees the scanned document in the web-interface

ACTUAL:
 * All users see the scanned document in the web-interface 

**Relevant information**
 - Host OS of the machine running paperless:  Ubuntu 20.04
 - Installation method: docker
 - Docker-Compose configurations:
   * setting the variables for PAPERLESS_ADMIN_USER, PAPERLESS_ADMIN_PASSWORD, PAPERLESS_DBPASS, PAPERLESS_DBUSER, PAPERLESS_DBNAME,

**Comment by TheFehr** [comment]
This is known limitation:
Discussion about this you can find here:
https://github.com/jonaswinkler/paperless-ng/discussions/52

**Comment by polaroidkidd** [comment]
Ah, yes I saw that issue but forgot about it while making this ticket. Closing in favor of continuing discussion in #52
