### ISSUE TITLE
Quick access to "clear filter"

### ISSUE THREAD

**Issue by ministryofsillywalks** [jonaswinkler/paperless-ng#127]
Clicking on a correspondent or document type filters the view by this.
I really like this functionality.
However a easy access to "clear filter" would be a good addition imho.
Once something is filtered it actually tells you "4 documents filtered" maybe just add a button next to that to "clear filter"
![image](https://user-images.githubusercontent.com/10544895/101949013-44112c80-3bf3-11eb-8c1a-0a8a98727a97.png)
Currently the workflow for this is a bit clunky as you have to click on "filter" in the top right corner which opens the info on the filter and then click on clear.

**Comment by shamoon** [comment]
This will be in #111 !
