### ISSUE TITLE
[BUG] Paperless webserver not honoring port specified in docker-compose.yaml

### ISSUE THREAD

**Issue by padraigkitterick** [jonaswinkler/paperless-ng#1273]
**Describe the bug**
Run paperless-ng via one of the docker compose scripts provided by paperless. Change the default port 8000 and url of the health check in the compose script prior to running with docker compose. Webserver container (specifically Gunicorn) does not use port specified in compose file, because the port 8000 is hardcoded in the docker/gunicorn.conf.py file ([line 1](https://github.com/jonaswinkler/paperless-ng/blob/3b17f9d6ecc6d1e3459619458ea3fefb260a116d/docker/gunicorn.conf.py#L1)).

**To Reproduce**
1. Download one of the sample docker compose files
2. Modify default port (8000) for the webserver to an alternative port
3. Start docker stack using the modified compose file
4. Observe that the log file for the webserver container still reports gunicorn using port 8000 and that the web interface to Paperless is not available on the specified non-default port

**Expected behavior**
Paperless should honour the webserver port specified in the compose file and make the web interface available on that port and avoid binding to the default port (8000) if a different port is specified.

**Webserver logs**
After specifying port 8001 in the compose file, the webserver container log confirms gunicorn still binds to port 8000.
```
Paperless-ng docker container starting...
Mapping UID and GID for paperless:paperless to 1027:100
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Executing /usr/local/bin/supervisord -c /etc/supervisord.conf
2021-08-31 12:56:21,791 INFO Set uid to user 0 succeeded
2021-08-31 12:56:21,795 INFO supervisord started with pid 1
2021-08-31 12:56:22,797 INFO spawned: 'consumer' with pid 47
2021-08-31 12:56:22,799 INFO spawned: 'gunicorn' with pid 48
2021-08-31 12:56:22,801 INFO spawned: 'scheduler' with pid 49
[2021-08-31 12:56:23 +0000] [48] [INFO] Starting gunicorn 20.1.0
[2021-08-31 12:56:23 +0000] [48] [INFO] Listening at: http://0.0.0.0:8000 (48)
[2021-08-31 12:56:23 +0000] [48] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2021-08-31 12:56:23 +0000] [48] [INFO] Server is ready. Spawning workers
```

**Relevant information**
 - Host OS of the machine running paperless: Synology NAS DS220+
 - Browser: Same result in chrome and edge
 - Version: 1.5.0
 - Installation method: docker
 - Changes made in `docker-compose.yml`: webserver port changed to anything other than 8000 on both the ports declaration for the webserver and for the health check test url; e.g.

```
webserver:
    ports:
      - 8001:8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
```

**Comment by maks3332** [comment]
You should not change the second port, only first. It must be like that:
```
webserver:
    ports:
      - 8001:8000
```

**Comment by padraigkitterick** [comment]
Many thanks - I can see the error I made now. I'll submit a pull request
with a suggested update to the setup documentation re: docker just to make
sure other users don't make the same mistake.
