### ISSUE TITLE
Generate TOC from ASN numbers

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#131]
> Hi,
> thank you for this nice project! :)
> 
> My question is rather workflow related: is it possible to generate some sort of table of contents from ASN e.g. 1 - 343 to have some sort of backup index in case paperless goes down? I'd like to print this TOC and put it together with all the documents in the binder then.
> 
> Thank you again!

_Originally posted by @vestingz in https://github.com/jonaswinkler/paperless-ng/discussions/126_

**Comment by jonaswinkler** [comment]
I'll just collect some ideas here.

I though about doing something fancy with Latex, but then I also thought that I don't want to pull latex as a dependency into the project.

enscript + ps2pdf don't require a whole lot of additional dependencies and ps2pdf is already part of paperless, this works. The output isn't particularly beautiful, but gets the job done.

I don't exactly know yet where and how this should appear in the UI though.

And I'd still focus on other stuff first, since this is a function that will get used rarely (I absolutely see its benefits though).

**Comment by vestingz** [comment]
Sure, no worries, it's not an essential function at all :) Thanks for all your hard works!
