### ISSUE TITLE
Display paperless-ng version number in the web user interface

### ISSUE THREAD

**Issue by wechsler42** [jonaswinkler/paperless-ng#134]
Hi Jonas,
I would suggest to display the version number, like "version 0.95" for example, of paperless-ng  in:

- bottom left corner of the web ui
- Misc section above or below "Documentation"

I would prefer the the first option.

**Comment by jonaswinkler** [comment]
Agreed.

**Comment by wechsler42** [comment]
Thanks.

**Comment by jonaswinkler** [comment]
This is not implemented yet, I'll close this as soon as it is.
