### ISSUE TITLE
When logging in to paperless, I get logged-out from paperless-ng (vice-versa)

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#138]
For the time being I do have `paperless` and `paperless-ng` running in parallel with the same username and password. I've encountered the following issue with this setup:

```
When I'm logged in to the paperless Web UI
and I login to paperless-ng Web UI
and I refresh paperless Web UI
then I am no longer logged in to the paperless Web UI
and I am no longer logged in to the paperless-ng Web UI after I hit refresh
```

The same holds for the other direction.

Paperless docker version: thepaperlessproject/paperless 22935f812943 (image id)
Paperless-ng  docker version: jonaswinkler/paperless-ng ec83d8ac9716 (image id)

**Comment by jonaswinkler** [comment]
Although username and password are the same, the session identifier stored in the cookie is probably not, and -ng will overwrite whatever cookies already exists from paperless, and vice versa. The next release will have a configuration option that allows custom cookie names. This will allow you to be logged into both instances at the same time.

See also #122.

**Comment by Tooa** [comment]
> Edit. I probably should have foreseen this and should have added custom cookie names in the first place.

No worries. I think this problem is not a big deal.

**Comment by jonaswinkler** [comment]
Please check if the new configuration option `PAPERLESS_COOKIE_PREFIX` helps you to resolve this issue. If so, please close.

**Comment by jonaswinkler** [comment]
This should be resolved now, if not, please reopen.

**Comment by Tooa** [comment]
> Please check if the new configuration option PAPERLESS_COOKIE_PREFIX helps you to resolve this issue. If so, please close.

Sorry, for being this late. It works fine with the `PAPERLESS_COOKIE_PREFIX` variable now. Thank you!
