### ISSUE TITLE
Additional parameters for header authentication

### ISSUE THREAD

**Issue by oeiber** [jonaswinkler/paperless-ng#1386]
In addition to
https://github.com/jonaswinkler/paperless-ng/pull/260
it would be nice if there where an option to restrict header auth to ip addresses of trusted proxies, only.
It would also be nice if there where an option to pass the full name of the user and also for its email address.

**Comment by amenk** [comment]
What would be your use case and how would you test that?

I guess you have a SSO-proxy and want to allow only requests from that one? Not sure if this needs to be handled in paperless NG - you might also be able to put an IP filter in front of paperless-ng? Which setup are you using? docker?

**Comment by ybizeul** [comment]
Is there a ref for this change ?
