### ISSUE TITLE
Missing thumbnails in the extended list view

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#139]
I found 6 documents  where the thumbnail just shows fine in the grid view, but not in the extended list view. See the following example: 

![list_icon_1](https://user-images.githubusercontent.com/5375334/102239220-ea607900-3ef6-11eb-863a-3c9ac95a5a0c.png)
![list_icon_2](https://user-images.githubusercontent.com/5375334/102239230-edf40000-3ef6-11eb-8792-5d2ab35d02e5.png)

The installation was done with a existing paperless database and documents using the migration guide in the documentation. 
Let me know how I can assist you with debugging.

*  Paperless-ng docker version: jonaswinkler/paperless-ng ec83d8ac9716 (image id)

**Comment by jonaswinkler** [comment]
Thanks for reporting. This is a layout issue. The thumbnails will be hidden when the layout gets too small, but apparently that's not working here. Maybe some issues with how the content is taking up space on the card, will have to investigate.

**Comment by jonaswinkler** [comment]
Could you please check if the following is true:

* For the document in question, the content shown on the card contains a very long sequence of characters with no spaces in between.

**Comment by Tooa** [comment]
> For the document in question, the document content shown on the card contains a very long sequence of characters with no spaces in between.

Yes, that true for all documents. So, this might cause the issue.

**Comment by jonaswinkler** [comment]
Please check if this is gone with the new version. If so, please close.

**Comment by Tooa** [comment]
Works with `0.9.8`
