### ISSUE TITLE
[Other] Display Scanned Date as it appears on the document

### ISSUE THREAD

**Issue by bm55** [jonaswinkler/paperless-ng#1395]
Paperless seems to accurately scans a date that appears on the document but it displays on the "Date created" field with date and month swapped. I have noticed this on many documents. Here is an example:
![image](https://user-images.githubusercontent.com/7528001/137643298-4b2c697b-5d83-442f-9426-3511e2c8e5b9.png)

**Comment by amenk** [comment]
For clarification @bm55  was this a bill from September or Feburary?

I think it is worth mentioning that paperless can have no fully reliable way to determine from 2/9/2020 whether it is the 2nd September or the 9th February. Of course the solution of @rsmuc will help if most of your documents are in the same order.

You also have to change the display format in the frontend.

In the background, paperless-ng is parsing the date and storing it as timestamp in the database.

So all the dates will be shown in the same order in the frontend, regardless of the document date format.

So there will probably never be a displaying as-is on the document, for this, it would have to be stored as a string and search by data range could not work anymore.

**Comment by bm55** [comment]
The PAPERLESS_DATE_ORDER=MDY seems to be working!

**Comment by bm55** [comment]
@amenk in US, typically all documents have Month/Day/Year so by adding PAPERLESS_DATE_ORDER=MDY so far it is showing the correct order.
