### ISSUE TITLE
Show matching documents when clicking on document count

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#140]
I would like to make a feature request proposal: 

```
When I click on Tags in the Manage Menu
And I click on the document count of a specific tag
Then I see all associated documents in the document view using the tag as a filter

When I click on Correspondents in the Manage Menu
And I click on the document count  of a specific correspondent 
Then I see all associated documents in the document view using the correspondent as a filter

When I click on Document types in the Manage Menu
And I click on the document count of a specific document type
Then I see all associated documents in the document view using the document type as a filter
```

* Maybe this is obsolete with the new filter UX redesign, but I find it useful to reach the documents from these views
* I don't mind if the link is from document count, tag name, or else

**Comment by jonaswinkler** [comment]
I thought about this myself a couple days ago and now I've got a reason to do it. I'd probably add a button with a magnifying glass or funnel icon or something.

**Comment by jonaswinkler** [comment]
Two options. What do you think is better, left or right?

![image](https://user-images.githubusercontent.com/17569239/102288645-31715d00-3f3d-11eb-93dc-e6ae4943bd29.png)

**Comment by Tooa** [comment]
In my opinion the solution with the button on the right side is more in line with the other user interactions on that view.

I don't like the rather lenghty "Show documents" text on the left side. There, I would prefer making the number count a href style link.

Howecer, I tend to vote for the right side.

**Comment by shamoon** [comment]
Yea I agree with above FWIW, number can be a link cause why not, but buttons are nice. Only thought is perhaps change the word “Filter” to something like “View documents” or “Show documents” or something like that. To me it’s just slightly confusing (confusing is too strong of a word even but I think you get what I mean) because the filter button will show documents whereas edit and delete are actions for the tag itself.
