### ISSUE TITLE
[BUG] After Login Server Error (500)

### ISSUE THREAD

**Issue by TheRealFlori** [jonaswinkler/paperless-ng#1400]
**Describe the bug**
After the installation on my Raspberry Pi 3 Model B Plus running Docker compose i want to login on the web Interface. I type in my Username and Password and will be directed to http://myip:8000/accounts/login/?next=/ where Server Error (500) is shown.

Because of an Password error i've used the tipp from this issue to install paperless-ng: https://github.com/jonaswinkler/paperless-ng/issues/1220#issuecomment-896168181 

**To Reproduce**
1. Go to http://myip:8000/
2. Type in Username and Password 
3. Click "Log In"

**Expected behavior**
Log in into Webinterface

**Screenshots**

<img width="573" alt="2021-10-18 18_13_40-Server Error (500)" src="https://user-images.githubusercontent.com/55324241/137769448-5d7ed797-16a3-409e-a6ce-395b739fddaf.png">

**Webserver logs**
```
If available, post any logs from the web server related to your issue.
```
How do i get this? 

**Relevant information**
 - Host OS of the machine running paperless: Raspberry Pi 3 Model B Plus Rev 1.3
 - Browser Google Chrome
 - Version Version 94.0.4606.81 (Offizieller Build) (64-Bit)
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`. --> no 

Did i something wrong? I've tried it several times and with complete clean installation of rasbian ...

**Comment by TheRealFlori** [comment]
Thank you @xsean93, this works also for me. Now i can finally log in :)

I've got now a new Problem, if i run `docker container ls ` the apache tika is restarting all the time ....

`55c433928c82   apache/tika                                                "/bin/sh -c 'exec ja…"   21 hours ago    Restarting (1) Less than a second ago                                               paperless_tika_1`

`docker logs -f paperless_tika_1
standard_init_linux.go:228: exec user process caused: exec format error`

i think apache tika is not running on arm or?

**Comment by TheRealFlori** [comment]
Okay, i'm now using redis:6.0-alpine and iwishiwasaneagle/apache-tika-arm after reinstalling the raspberry with rasbian os lite with 64 Bit.
With the help of https://github.com/jonaswinkler/paperless-ng/issues/1220#issuecomment-896168181 and the tipp from @xsean93 with adding "privileged: true" at the webserver section in the docker-compose.yml it now finally works.

Thanks everyone! :)

**Comment by Schrello** [comment]
Hey, I have got the same problem and I am realy new to linux ^^ Where can I find the docker-compose.yml file? I was not able to find it yet.
