### ISSUE TITLE
Cant run the install script

### ISSUE THREAD

**Issue by baschior** [jonaswinkler/paperless-ng#1401]
I am on proxmox and I cant install paperless-ng via the script.
Either on LXC or on a debian VM with installed docker and compose. 
I can start the script, but it doesnt stop or halt for the configuration, it just runs through and gives out several errors ...
Any idea what I am doing wrong?

**Comment by baschior** [comment]
Thanks for the quick respond. VM with debian Buster. Executing the script as a nom root user from ssh.

**Comment by baschior** [comment]
I would say the script just doesnt wait for inputs ...

Invalid folder: CONSUME_FOLDER=$ask_result

**Comment by TheFehr** [comment]
I just ran it on a WSL Ubuntu 20.04 and it is the exact same problem

**Comment by TheFehr** [comment]
Use this:
`bash <(curl -L https://raw.githubusercontent.com/jonaswinkler/paperless-ng/master/install-paperless-ng.sh)`

**Comment by TheFehr** [comment]
@mg1067 was this by any chance the same problem you faced in #1303

**Comment by baschior** [comment]
> My email should be visible on my profile. And can you reopen this issue?

Sorry Done
> 
> We should probably update the Docs as this problem will be the same for everybody trying the script on at least debian based systems.

Yep but the documentation doesnt say anything about recommended distro
