### ISSUE TITLE
[BUG] docker-compose fails with "pair interfaces: operation not supported" on raspberry pi

### ISSUE THREAD

**Issue by kuyper** [jonaswinkler/paperless-ng#1402]
**Describe the bug**
I fail to start paperless on a raspberry pi 4 using the docker-compose configuration provided on github. 

**To Reproduce**
1. Copy docker-compose.yml, docker-compose.env and .env into a directory on a raspberry pi 4 running raspbian buster.
2. Run 'docker-compose pull' - images are pulled correctly
3. Run 'docker-compose up' --> error messages 

**Expected behavior**
I tried the exact same setup on a Mac and the paperless server started as expected. That should also happen on the raspberry.

**Console logs**
`Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting paperless_broker_1 ... error
Starting paperless_db_1     ... 

ERROR: for paperless_broker_1  Cannot start service broker: failed to create endpoint paperless_broker_1 on network paperless_default: failed to add the host (vStarting paperless_db_1     ... error

ERROR: for paperless_db_1  Cannot start service db: failed to create endpoint paperless_db_1 on network paperless_default: failed to add the host (veth79241da) <=> sandbox (veth6972904) pair interfaces: operation not supported

ERROR: for broker  Cannot start service broker: failed to create endpoint paperless_broker_1 on network paperless_default: failed to add the host (vethc5195d2) <=> sandbox (veth4bd3fc7) pair interfaces: operation not supported

ERROR: for db  Cannot start service db: failed to create endpoint paperless_db_1 on network paperless_default: failed to add the host (veth79241da) <=> sandbox (veth6972904) pair interfaces: operation not supported
ERROR: Encountered errors while bringing up the project.`

**Relevant information**
 - Host OS of the machine running paperless: raspberry pi 4, raspbian buster
 - Browser: N/A
 - Version: N/A
 - Installation method: [docker-compose]

**Comment by cristiano-belloni** [comment]
@kuyper I have the same problem - how did you solve this?
