### ISSUE TITLE
[BUG] Passwords did not match x 100

### ISSUE THREAD

**Issue by Schrello** [jonaswinkler/paperless-ng#1429]
Hey, 
while trying to install paperless-ng via the DockerHub using the installation script I am getting the following output on the consol. (See at the end)

After the standard information text "This script will download, configure and start paperless-ng.[...]" it immediately prints "Passwords did not match" statements multiple times. It doesn't ask for any input or password.  

I did not change anything in docker. It is a fresh installation. 
I am using Raspbian GNU/Linux 10 (buster)

############################################
############################################

This script will download, configure and start paperless-ng.

1. Folder configuration
=======================

The target folder is used to store the configuration files of 
paperless. You can move this folder around after installing paperless.
You will need this folder whenever you want to start, stop, update or 
maintain your paperless instance.

The consume folder is where paperles will search for new documents.
Point this to a folder where your scanner is able to put your scanned
documents.

CAUTION: You must specify an absolute path starting with / or a relative 
path starting with ./ here. Examples:
  /mnt/consume
  ./consume

Invalid folder: CONSUME_FOLDER=$ask_result

The media folder is where paperless stores your documents.
Leave empty and docker will manage this folder for you.
Docker usually stores managed folders in /var/lib/docker/volumes.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Invalid folder: MEDIA_FOLDER=$ask_result

The data folder is where paperless stores other data, such as your
SQLite database (if used), the search index and other data.
As with the media folder, leave empty to have this managed by docker.

CAUTION: If specified, you must specify an absolute path starting with /
or a relative path starting with ./ here.

Invalid folder: DATA_FOLDER=$ask_result

2. Application configuration
============================

The port on which the paperless webserver will listen for incoming
connections.

Paperless requires you to configure the current time zone correctly.
Otherwise, the dates of your documents may appear off by one day,
depending on where you are on earth.

Database backend: PostgreSQL and SQLite are available. Use PostgreSQL
if unsure. If you're running on a low-power device such as Raspberry
Pi, use SQLite to save resources.

Invalid option: DATABASE_BACKEND=$ask_result

Paperless is able to use Apache Tika to support Office documents such as
Word, Excel, Powerpoint, and Libreoffice equivalents. This feature
requires more resources due to the required services.

Invalid option: TIKA_ENABLED=$ask_result

Specify the default language that most of your documents are written in.
Use ISO 639-2, (T) variant language codes: 
https://www.loc.gov/standards/iso639-2/php/code_list.php
Common values: eng (English) deu (German) nld (Dutch) fra (French)

Specify the user id and group id you wish to run paperless as.
Paperless will also change ownership on the data, media and consume
folder to the specified values, so it's a good idea to supply the user id
and group id of your unix user account.
If unsure, leave default.

3. Login credentials
====================

Specify initial login credentials. You can change these later.
A mail address is required, however it is not used in paperless. You don't
need to provide an actual mail address.

Password cannot be empty.

Passwords did not match

Password cannot be empty.

Passwords did not match

Passwords did not match

Password cannot be empty.

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Password cannot be empty.

Passwords did not match

Password cannot be empty.

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Password cannot be empty.

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Password cannot be empty.

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

Passwords did not match

##################
End Output on the consol.

**Comment by TheFehr** [comment]
Duplicate of #1401

**Comment by Schrello** [comment]
Thank yout. That helped a lot :)
