### ISSUE TITLE
Unable to delete correspondent

### ISSUE THREAD

**Issue by mikkelnl** [jonaswinkler/paperless-ng#143]
When I try to delete a correspondent or a tag, nothing happens.
While in the list view for all correspondents, when I click the DELETE button, I see this in the browser console log (the confirmation popup does show, but the buttons won't work there):

> [Error] ERROR – TypeError: undefined is not an object (evaluating 't.componentInstance.confirmPressed.subscribe') — main.js:1:855073
TypeError: undefined is not an object (evaluating 't.componentInstance.confirmPressed.subscribe') — main.js:1:855073
	Ar (main.js:1:308105)
	handleError (main.js:1:308276)
	ys (main.js:1:328040)
	Jo (main.js:1:349232)
	i (main.js:1:349371)
	(anonieme functie) (main.js:1:445063)
	onInvokeTask (main.js:1:397985)
	runTask (polyfills.js:1:3339)
	invokeTask (polyfills.js:1:8977)
	k (polyfills.js:1:21231)
	_ (polyfills.js:1:21471)

This happens in both Safari and Edge.

**Comment by jonaswinkler** [comment]
My bad.

I'll have that updated soon.

**Comment by mikkelnl** [comment]
Thanks!

**Comment by jonaswinkler** [comment]
Fixed that. Also some other changes I was too eager to push. I'm sorry.
