### ISSUE TITLE
[BUG] document_create_classifier not working

### ISSUE THREAD

**Issue by LouisFaure** [jonaswinkler/paperless-ng#1433]
Automatic algorithm does not seem to work for me, I keep seeing in the logs that the document classification model does not exists:

```
[2021-11-09 10:43:41,487] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2021-11-09 10:43:48,236] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
```

When running the following command:

```bash
docker-compose exec webserver document_create_classifier -v 3
```

Nothing shows up, no error, no messages either (even in most verbose mode)
Am I missing something?

**Relevant information**
 - Debian on raspberry pi, linux 5.10.63-v7l+
 - Version 1.5.0 using docker

**Comment by TheFehr** [comment]
I don't get any ouput either but for me it works, as in my documents get automatically assigned all the auto tags/correspondent and such.
Same version using docker. Not raspberry pi though but standard x86_64 ubuntu server

**Comment by LouisFaure** [comment]
Thanks for your reply @TheFehr 

Does paperless-ng have the auto algorithm activated right away? Do I need to specify which tag needs to be automatically assigned?

If not maybe I do not have enough documents for training the classifier? Right now in total I have 32 documents.

**Comment by TheFehr** [comment]
According to the (docs)[https://paperless-ng.readthedocs.io/en/latest/administration.html#managing-the-automatic-matching-algorithm] there should be no need to do anything, when using the docker.

I am not sure after how many documents I saw the tag's starting to appear automatically I am at ~180 documents at the moment.
One thing that might not be obvious, auto tags only work on new documents. It will currently never go though old/existing documents and re-auto-match them.

**Comment by LouisFaure** [comment]
Understood, then I assume that I don't have enough documents for making a classifier, I will close this issue until I get more of these!

**Comment by canDry** [comment]
I don't get why classification isn't working!  
  
Just installed the newest version, added a couple correspondents (using regular word match - NOT auto/ML) uploaded a bunch of documents, updated the correspondent manually, uploaded a bunch more... NOPE.  The correspondent isn't getting automatically set based on the match criteria.  It shouldn't need any training when the criteria is simply: see this word, assign this!
