### ISSUE TITLE
Adding date filters without the calendar popup doesn't work - also removing a date filter doesn't

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#144]
What I did is enter a specific date and pushed Enter and clicked away the filter drop-down, nothing happened. I had to open the calendar-pop (wanted date was already selected), click the date again and it worked.

Also I couldn't find a way to remove one of the two date filters, I guess this is solved when the first part is solved. (of course removing all date filters and then set the wanted would work)

P.S.: Amazing progress!!

**Comment by jonaswinkler** [comment]
Regarding manual enter: Never tried that. Will see what I can do.

Regarding clearing before/after individually: This was actually in the PR from @shamoon. However, I've had lots of issues getting it to clear the fields correctly, without affecting the other, and therefore removed that. Then discovered some more issues when setting the field `before` after selecting one of the quick options, moved some code. I might be able to get that working now.

**Comment by shamoon** [comment]
Oh I didn’t realize you removed the clear date buttons. I can take a stab at this unless you’ve already done it?

**Comment by jonaswinkler** [comment]
Well, not removed, but rather unified into a single clear button. As stated above, I couldn't get it to reliably clear a field without affecting the other field. However, with the change to the way the date drop down announces changes to the editor (both dates as a single event), it will probably work.

I haven't done anything yet.

**Comment by shamoon** [comment]
Cool, sorted these out in #148
