### ISSUE TITLE
[Other] Rerun OCR on uploaded documents

### ISSUE THREAD

**Issue by sprnza** [jonaswinkler/paperless-ng#1474]
Hi there!
Thanks for the wonderful project!
 Just uploaded my first documents to paperless and found out that it's seems like OCR uses `eng` language which is set as default one. I've changed the default language to `rus` and I don't see an option to rerun OCR on the uploaded files. Is there a way to perform this?

**Comment by cryptoluks** [comment]
Try to use the manage command `document_archiver --overwrite` or `document_archiver --overwrite --document <id>`. This should force redo OCR.

I use a docker container from linuxserver.io, so for me the command is:

`docker exec -it paperless-ng manage document_archiver --overwrite`

Let me know if this works for you.

**Comment by sprnza** [comment]
Thanks @cryptoluks ! I've tried the command. The document is being processed and `xmp:ModifyDate | 2022-01-15T19:11:19+00:00` is being changed but it's seems like document's OCR language remains `eng` as it was set during uploading.

**Comment by cryptoluks** [comment]
> The document is being processed and `xmp:ModifyDate | 2022-01-15T19:11:19+00:00` is being changed but it's seems like document's OCR language remains `eng` as it was set during uploading.

How do you set the appropriate second language in your config? Like this? `PAPERLESS_OCR_LANGUAGE=eng+rus`

Is the appropriate tesseract package installed? Personally, I use the `linuxserver.io` `paperless-ng` container, which needs some customization for other OCR languages other than `en`. I additionally use german and had to install `tesseract-ocr-deu`.

After I rerun OCR, the Umlauts (like ä, ö, ü) were recognized, so I think the process should theoretically work.

Also, did you check the log output of `paperless-ng`?

**Comment by denilsonsa** [comment]
Please note that you set [`PAPERLESS_OCR_LANGUAGE`](https://paperless-ng.readthedocs.io/en/latest/configuration.html#ocr-settings) to tell tesseract which language(s) it should use. Additionally, if you run paperless-ng in docker, you have a second configuration key [`PAPERLESS_OCR_LANGUAGES`](https://paperless-ng.readthedocs.io/en/latest/configuration.html#docker-specific-options), which tells the docker container which additional tesseract language packages it has to install. Also note that their syntaxes are slightly different: one is `+`-separated, the other is space-separated.

**Comment by sprnza** [comment]
Thanks guys! It does work, but I've found out that the content tab is being cached somehow so Ctrl+F5 doesn't refresh it's content. I had to close and open browser to get it updated. Sorry for bothering and thank you for help!
