### ISSUE TITLE
[BUG] Email Account Password is not Obscured

### ISSUE THREAD

**Issue by evilsidekick293** [jonaswinkler/paperless-ng#1483]
**Describe the bug**
In the admin view when adding an email account, the password will always be displayed as clear text. Also when returning to that tab, the email account password is still not obscured (e.g. by dots).

**To Reproduce**
1. Add Email Account
2. Enter Password
3. See that Password is not obscured

**Expected behavior**
Obscure password upon entry and do not ever show it in clear text.

**Screenshots**
not applicable

**Webserver logs**
irrelevant

**Relevant information**
irrelevant

**Comment by TheFehr** [comment]
Duplicate of #1233

**Comment by torbengb** [comment]
**Who can close this issue** as dupe of the mentioned?

**Comment by evilsidekick293** [comment]
Me.. :D
