### ISSUE TITLE
0.9.8 Api forbidden (when using PAPERLESS_COOKIE_PREFIX)

### ISSUE THREAD

**Issue by praul** [jonaswinkler/paperless-ng#149]
Hi, thanks for implementing PAPERLESS_COOKIE_PREFIX.
I tried it and there seems to be an issue
![image](https://user-images.githubusercontent.com/38807639/102457160-919df700-4042-11eb-8de5-b85049cfb587.png)
and document meta cannot be edited anymore

It is directly related to the Cookie Prefix, if I remove this from the .env file, the error does not occur.

For PAPERLESS_COOKIE_PREFIX I used "paul_" (don't know if the underscore is important in this issue)

Apart from that, 0.9.8 is great, thank you for your time and effort!

**Comment by jonaswinkler** [comment]
Underscore is not relevant.

I've missed to pass the prefix to a certain part of the front end that is responsible for all edit and deletion operations.

**Comment by praul** [comment]
thanx :)
