### ISSUE TITLE
Add page navigation controls to PDF viewer

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#150]
Hey, with the new preview I cannot see the number of pages a document has got any longer? The old module/plugin showed it straight away in the top bar.

Any chance to activate that or at least show it in the metadata tab?

**Comment by jonaswinkler** [comment]
What's the use case for that?

**Comment by totti4ever** [comment]
Well, mainly control and plausibility check:
 * check against the scanned paper document whether all pages came through (to make it easy I sometimes write the number of pages on the first page)
 * compare two versions of a document whether they have the same count or one has more and is the correct version (after a page had been dropped in the first try)

In addition, one could use it for a fancy statistic and show the total page count next to the total document count ;-)

**Comment by jonaswinkler** [comment]
I see. I'll add some controls to the PDF viewer, at least a page selection tool.

Regarding statistics: Would be neat. Multiply that with an average paper thickness and paperless could show you how much paper (height when stacked on top of each other) you stored in the system. But for a features that's just a neat thing to have, this would require quite a few additions (namely, I'd need to store the page count in the database). Not going to happen soon.

**Comment by totti4ever** [comment]
> Regarding statistics

Haha, was rather a thing from the fancy pot for fun anyway. Though I like your refined thoughts on this ;-)

**Comment by shamoon** [comment]
https://github.com/VadimDez/ng2-pdf-viewer/blob/HEAD/README.md#page

**Comment by shamoon** [comment]
I created a [#157](PR) for this, I debated where to put it a little but ultimately the toolbar a little further from the buttons made sense to me.
<img width="594" alt="Screen Shot 2020-12-18 at 2 30 51 PM" src="https://user-images.githubusercontent.com/4887959/102667236-c6db3f80-413d-11eb-9e63-3fd5a64b45e5.png">

I didn't think we need additional navigation buttons or something. You can just step the `<input type="number">` or enter a page number (or ya know, scroll! 😀)

**Comment by jonaswinkler** [comment]
Hm, we need to get this coordinated.

![image](https://user-images.githubusercontent.com/17569239/102668430-311ad100-418c-11eb-99a7-d84803904f66.png)

Agreed on the buttons, no need.

But: Either the buttons need to be within the `<div *ngIf="getContentType() == 'application/pdf'">`, or have that guard in the toolbar. Paperless could theoretically serve images, text files or other documents as well, and the page controls don't apply there. What option do you think would be better?

**Comment by shamoon** [comment]
Ah, sorry didn't realize you were working on it yet =/

I can just put that guard around that element, just pushed [a commit](https://github.com/jonaswinkler/paperless-ng/pull/157/commits/e0293db16dde23829e77717a7e7a4e7432b4a65f) for that.
