### ISSUE TITLE
FR: Import E-Mails themselves (eml)

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#153]
Hey, I found it super helpful if the mail consumer would be able to also consume emails. This way one could also add some important mails to the archive.

For usability reasons I would suggest to only import them, when they are attached as an eml file. This way one could also easily manage what is intended by adding extensions filters to the mail consumption rules (to e.g. allow pdf and eml but not png or jpg)

**Comment by totti4ever** [comment]
With the mentioned extension filter #70 could also be solved by allowing inline attachments.

To make it extra sweet that could be an extra switch, so I could have a rule saying that pdf are allowed inline while png is not

**Comment by jonaswinkler** [comment]
> For usability reasons I would suggest to only import them, when they are attached as an eml file. This way one could also easily manage what is intended by adding extensions filters to the mail consumption rules (to e.g. allow pdf and eml but not png or jpg)

Maybe simple wildcard matching for filenames (`*.pdf`), I can see that happening.

> With the mentioned extension filter #70 could also be solved by allowing inline attachments.

I don't see the relation to inline attachments here? Please elaborate. Allowing inline attachments will lead to all inline images in matching mails to be added as documents to paperless.

**Comment by totti4ever** [comment]
Well, if you can set a filter on the filename, i.e. also on the extension, there is no problem allowing inline attachments. As I am not interested in graphics anyway (to be more precise: only pdf and maybe eml), I would just allow inline in all mail consumers and filter on *.pdf and *.eml and would be happy (I actually din't manage to forward the landline bill in the proper way to the scanned mailbox!).

Default configuration would be of course no inline as the default filter would allow all file types and there consume all embedded graphics, exactly as you stated

**Comment by totti4ever** [comment]
by the way: I gave it some more tries and I just cannot manage to send mails using _Mail_ on macOS, which are not skipped because they seem to be added inline :-/

**Comment by shamoon** [comment]
As a macOS/iOS user as well Im seeing the value of the extension filter. I think it would in many / most cases solve the issue about not wanting inline JPG/PNGs in HTML emails getting imported because the rule would be along the lines of "import all inline/non-inline attachments with *.pdf", if I correctly understand the proposal.

**Comment by totti4ever** [comment]
that is exactly what I thought, indeed

**Comment by jonaswinkler** [comment]
Alright, so two new options for mail rules:

- Attachments only / everything (including inline).
- Attachment filename filter with glob matching.

**Comment by shamoon** [comment]
> Alright, so two new options for mail rules:
> 
> * Attachments only / everything (including inline).
> * Attachment filename filter with glob matching.

Sounds great to me. You could perhaps consolidate them into something like: “include inline attachments with file type: ___” and maybe a hint like “if none are specified all files including embedded images will be imported”.

But obviously either way works. Thanks for considering this one.

**Comment by totti4ever** [comment]
> Alright, so two new options for mail rules:
> 
> * Attachments only / everything (including inline).
> * Attachment filename filter with glob matching.
> 
> Does that sound right?

To me that sounds absolutely right. @shamoon, I think filtering on the whole name is better than only extension. Though, your basic points are worth a thought!

> Regarding import of actual emails:
> 
> * That's pretty tough, the mail library I'm using doesn't provide an option for downloading .eml formatted messages as far as i can tell.

Okay, so it only provides access to the attachments? Because I'd say eml is basically plain text and is the same as writing the mail in raw format to a file. So that is nothing, the library offers? Still, one would need to convert this file to pdf then, that's right.

**Comment by jonaswinkler** [comment]
> Okay, so it only provides access to the attachments? Because I'd say eml is basically plain text and is the same as writing the mail in raw format to a file. So that is nothing, the library offers? Still, one would need to convert this file to pdf then, that's right.

The library downloads mails, parses them (finds lines such as "Subject: xyz" and translates them into a format that's very easy to use in the software) and only returns that parsed representation. With this, implementing the mail functionality was dead simple and is pretty much fail-proof, since all the hard work (networking, interpreting the IMAP protocol) is done by that library. However, no access to the raw mails due to that.

Anyway, I'd like to know whether the new updates made the mail client more usable.

**Comment by shamoon** [comment]
> Anyway, I'd like to know whether the new updates made the mail client more usable.

New release works awesome for importing inline attachments eg on macOS / iOS, thanks JW!

**Comment by totti4ever** [comment]
Indeed, great work!

Still, for some future usage importing mails themselves would still be something I'd appreciate
