### ISSUE TITLE
[Other] Support setting password in automatic superuser creation

### ISSUE THREAD

**Issue by nebulade** [jonaswinkler/paperless-ng#1531]
Hi there. I am currently looking to package paperless-ng for [Cloudron](https://cloudron.io) and hit an issues about the automatic superuser creation. Usually we try to package apps in a way so they are ready to go after installation without the user ever needing to hit the terminal. So, depending on the app, we also setup the initial superuser account with pre-defined credentials, then after installation we warn the user to immediately change the default password upon first login.
So far I have found the very useful command `python3 manage.py createsuperuser --username admin --email admin@cloudron.local` but no way to programmatically also set a default password. The `--no-input` option seems to still require some later password change via terminal. 

My question basically is, if I am missing something obvious here, and if not, I am happy to work on a pull request, in case there is a chance for something like this to be merged.

Thanks a lot!

**Comment by ruihildt** [comment]
Django 3 allows you to pass an admin password as an environment variable, See: https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-createsuperuser

**Comment by nebulade** [comment]
At least in my tests the cli tool was still asking for a password using `DJANGO_SUPERUSER_PASSWORD`

**Comment by stefanorth** [comment]
You can add the `--noinput` option to suppress the password prompt.

**Comment by nebulade** [comment]
Ah perfect, I didn't expect the prompt to be there is the password would be accepted, but I guess it makes sense. Thanks for the help!
