### ISSUE TITLE
Stuck at "Paperless-ng is loading..." on fresh bare-metal install

### ISSUE THREAD

**Issue by brettfk** [jonaswinkler/paperless-ng#1543]
Fresh bare metal install on latest Debian 11 minimal. Followed the instructions at https://paperless-ng.readthedocs.io/en/latest/setup.html#bare-metal-route.

Can get the login page and log in, but just get a white screen with Paperless-ng is loading...

The static content files exist, and I ran the python script to re-download them, and have checked permissions, so not sure where I've gone wrong. Not using a reverse proxy at this stage, and not sure how/where to obtain web server logs.

**Comment by Adrian-456** [comment]
I did have the same problem 2 days ago on Linux Mint. I "solved" it by changing the PAPERLESS_STATICDIR Directive in paperless.conf from a SMB share (/mnt/paperless/static) to a local dir (/opt/paperless/static) and rerunning the last commands in https://paperless-ng.readthedocs.io/en/latest/setup.html#bare-metal-route

**Comment by brettfk** [comment]
I'll be damned... never would have worked that one out despite it being so obvious.
