### ISSUE TITLE
[Other] Convert from PostgreSQL back to SQLite?

### ISSUE THREAD

**Issue by CorneliousJD** [jonaswinkler/paperless-ng#1550]
I had originally setup Paperless-ng with Postgres, however after using it for a few years my actual document-to-paperless use is less than anticipated, and I am trying to clean up my unused databases, and right now paperless-ng is the only Postgres database I have left, so I'd like to blow away postgres alltogether, but I would need to convert the data from Postgres back to SQLite. Is this possible?

**Comment by mskg** [comment]
The process described here https://paperless-ng.readthedocs.io/en/latest/setup.html also works in reverse.

**Comment by CorneliousJD** [comment]
> The process described here https://paperless-ng.readthedocs.io/en/latest/setup.html also works in reverse.

@mskg  so if I try to run 
`
python3 manage.py dumpdata --database=postgres --exclude=contenttypes --exclude=auth.Permission > data.json
`

It fails, I tried database=postgres, postgresql, pgsql and paperless (name of the DB) 

It just says the connection postgress or paperless does not exist.

Any ideas on what command to run instead? Thanks in advance.

**Comment by mskg** [comment]
1. Just use `manage dumpdata --exclude=contenttypes --exclude=auth.Permission > data.json` that exports the data. 
2. Change database configuration in config
3. Run the import command

**Comment by CorneliousJD** [comment]
Thanks, that worked. Running now back on SQLite :) 

Much appreciated.

**Comment by DonkiKoi** [comment]
You can also use the document exporter, change the database type and then import everything.

An example with docker.
1. All paperless container are running (db, webserver, redis).
`docker exec <container_name_webserver> document_exporter ../export`.
The document exporter exports all your data from paperless into a folder for backup or migration to another DMS.
2. Change database configuration to sqlite.
3. Start a complete new paperless environment but mount the export folder to it.
4. Run the import command. `docker exec <container_name_webserver>  document_importer ../export`
