### ISSUE TITLE
Remove guesswork features

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#156]
Paperless parses filenames using some predefined rules such as

`Correspondent - Title - Tag1,Tag2.pdf`

or 

`Date - Correspondent - Title`.

More often than not, the resulting properties aren't what you would except (correspondent gets parsed as a tag, title gets split up due to containing a dash surrounded by spaces)

Apart from extracting dates from filenames, I'd like to remove this feature entirely.

Also see #155 and #83.

Edit. In addition to that, paperless offers tag / correspondent / type matching which user-definable rules, which is much more capable at assigning these items to new documents.

**Comment by brianwanderson** [comment]
>More often than not, the resulting properties aren't what you would except (correspondent gets parsed as a tag, title gets split up due to containing a dash surrounded by spaces)

I agree.  I think the guesswork feature should be removed entirely.  I like to name my files "YYYY.MM.DD - Some Descripion - That Makes Sense - To Me.pdf"  and the guesswork feature end up trying  to be too helpful.
