### ISSUE TITLE
[BUG] Duplicate file error reported, but no duplicate found

### ISSUE THREAD

**Issue by chooban** [jonaswinkler/paperless-ng#1592]
**Describe the bug**
When I try to add a particular file, I get a warning saying it is a duplicate. This is only happening with one file, and one that contains personal information in the filename so I'm not keen on posting screens and logs, sorry! 

The file is not findable from the dashboard, and to further check it's not hidden in some way, I've performed a backup operation as well. There's no file with that name, and it's not mentioned at all in the manifest.json that is written to the backup directory.

I've tried adding `PAPERLESS_CONSUMER_DELETE_DUPLICATES=true` to my docker-compose, but that doesn't seem to have changed anything.

I imagine I could get around this by restoring this backup to a clean install, but I'm hopeful there's something I can do to work out what's going on in case it happens again.

**To Reproduce**
1. Attempt to upload this document

**Expected behavior**
I would expect the document to be added normally. 

**Screenshots**
Sorry, personal info in the name.

**Webserver logs**
Same.

**Relevant information**
 - Host OS of the machine running paperless: Linux on QNAP Nas.
 - Browser: Firefox
 - Version: 1.5.0
 - Installation method: docker

**Comment by mweimerskirch** [comment]
I replied to a similar issue a few weeks ago, that turned out to be a user error in the end. 
Maybe you can have another look.
https://github.com/jonaswinkler/paperless-ng/issues/1192
If you're absolutely sure it's not a duplicate, generate the md5sum of the document and connect to your database to see if that hash is used anywhere.

**Comment by chooban** [comment]
Thank you! It is a user error. 🤦 I'd uploaded some of those documents after changing the names and forgotten about it. Looking it up by md5 in the database and finding the filename showed me where I was going wrong. Thank you!

I guess there might be some usefulness in linking to the duplicate document when trying to upload, but the main thing is that this isn't a bug.
