### ISSUE TITLE
Still seeing the paperless style UI when logging into -ng

### ISSUE THREAD

**Issue by jcpsantiago** [jonaswinkler/paperless-ng#160]
I use paperless via `docker-compose`. To try -ng, I made sure everything was stopped, `docker system prune -a` to have a clean env, downloaded the latest 0.9.8 release dockerfiles, renamed the postgres file to `docker-compose.yml` and edited my consumption dir, also modified the `docker-compose.env` file with my UIDs and edited the `.env` with some random project name (I went with donkeyballs).

then `docker-compose up -d` and I see this

![image](https://user-images.githubusercontent.com/789796/102693229-6faa9d00-4219-11eb-9ed8-cc8f90078355.png)

wasn't I supposed to see the latest UI?

Seems similar to #158 but I never had the `Loading...` issue

**Comment by jcpsantiago** [comment]
fixed, had to clear my cache. it's mentioned in https://paperless-ng.readthedocs.io/en/latest/setup.html#migration-to-paperless-ng but not in the normal setup. I can add this, I'll do a PR later :)

**Comment by jonaswinkler** [comment]
Oh yeah, the normal setup assumes that paperless was never installed.

Should be mentioned there as well!
