### ISSUE TITLE
[BUG] PAPERLESS_LOGOUT_REDIRECT_URL not working

### ISSUE THREAD

**Issue by ybizeul** [jonaswinkler/paperless-ng#1633]
**Describe the bug**
`PAPERLESS_LOGOUT_REDIRECT_URL` doesn't seem to be working

**To Reproduce**
1. Log in with a proxy to paperless, having `PAPERLESS_ENABLE_HTTP_REMOTE_USER `
2. Make sure the user in the one logged in with on the upper right hand corner
3. Logout
4. Browser is sent to `[...]/accounts/logout/` instead of the configured logout URL

**Expected behavior**
User should be redirected to configured URL

**Relevant information**
 - container
 - Safari
 - 1.5.0

**Comment by yschroeder** [comment]
The current docker image 1.5.0 does not include this functionality yet. See here:

https://github.com/jonaswinkler/paperless-ng/pull/1258#issuecomment-937991424

You would need to build it yourself or wait for the first release of paperless-ngx:

https://github.com/paperless-ngx/paperless-ngx

**Comment by tribut** [comment]
Hey,

unfortunately, the feature is not yet included in 1.5.0 (cf https://github.com/jonaswinkler/paperless-ng/pull/1258#issuecomment-938046653). You can check out [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx), a fork that tries to revive the project. Our image at ghcr.io/paperless-ngx/paperless-ngx:dev already includes this and a lot more. There will also be a proper release very soon.

**Comment by ybizeul** [comment]
Thanks guys. So there is a need to _revive_ paperless-ng ? Is it no longer maintained ?

**Comment by ybizeul** [comment]
DUP https://github.com/jonaswinkler/paperless-ng/pull/1258#issuecomment-937991424

**Comment by tribut** [comment]
Hey. Yes unfortunately there has not been any activity in paperless-ng for many month, so a revival was in order. paperless-ngx should be a drop-in replacement, see https://github.com/paperless-ngx/paperless-ngx/blob/dev/docs/setup.rst#migrating-from-paperless-ng
Currently, paperless-ngx:latest is just paperless-ng 1.5.0 while paperless-ngx 1.6.0 is in beta. The release should only be a few days away now. If you want to help us test the upcoming release, please check out https://github.com/paperless-ngx/paperless-ngx/pull/213

**Comment by ybizeul** [comment]
Seems to be working with the beta. Thanks !
