### ISSUE TITLE
Exporter: Export files according to PAPERLESS_FILENAME_FORMAT?

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#166]
Should the exporter respect the configuration option PAPERLESS_FILENAME_FORMAT when exporting files? Should it create files and folders as specified in that option? Right now it simply outputs a flat folder, with predefined filenames for all files.

**Comment by Sup3rlativ3** [comment]
My initial thought would be yes. The other option is to have a checkbox when exporting giving the option.
