### ISSUE TITLE
[BUG] Blank Document - Error reading a content stream. The page may be incomplete. Output may be incorrect.

### ISSUE THREAD

**Issue by TheDarthFather** [jonaswinkler/paperless-ng#1684]
**Describe the bug**
When uploading a specific file, the result is an empty document (besides a small picture header as in imgur sceenshot)

**To Reproduce**
It does not happen for all my documents. But I can reproduce every time for this specific document.

**Expected behavior**

**Screenshots**
https://imgur.com/a/p8fpdfi

**Webserver logs**
https://pastebin.com/Z6wMpuj9

**Relevant information**
 - Docker install on Ubuntu VM
 - Chrome
 - French language installed in docker

**Comment by jhf2442** [comment]
Looks like same issue as described in https://github.com/jonaswinkler/paperless-ng/issues/1140

Also tracked at https://github.com/paperless-ngx/paperless-ngx/issues/277

**Comment by TheDarthFather** [comment]
Indeed seems the same and also happens only for one doc for me. I am closing this.
Thank you!
