### ISSUE TITLE
No parsers available

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#176]
Hey, great stuff you guys are producing! Still I ran into an error which seems to be somewhat similar to #75.
```
No parsers abvailable for Scan 21. Dez. 2020.pdf : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
override_tag_ids=override_tag_ids)
File "/usr/src/paperless/src/documents/consumer.py", line 106, in try_consume_file
raise ConsumerError(f"No parsers abvailable for {self.filename}")
documents.consumer.ConsumerError: No parsers abvailable for Scan 21. Dez. 2020.pdf
```

Same happens after renaming, so it is not the filename. It is a private file, so I cannot upload it and after putting a black square on it and saving it again (preview, macOS) the problem is gone.

P.S.: The log has a typo --> No parsers a**b**vailable

**Comment by jonaswinkler** [comment]
Are you on linux?

Could you please do a `file --mime-type Scan 21. Dez. 2020.pdf` and a `file Scan 21. Dez. 2020.pdf` on the file that paperless refused to accept?

I assume this file comes from your scanner, and other files from that same source consume just fine?

**Comment by totti4ever** [comment]
Hah, great to know that you can check the filetype using `file`. Of course, you were on the right path:
```
$ file Scan\ 21.\ Dez.\ 2020.pdf
Scan 21. Dez. 2020.pdf: data
$ file Scan\ 21.\ Dez.\ 2020.pdf --mime-type
Scan 21. Dez. 2020.pdf: application/octet-stream
```

<img src="https://user-images.githubusercontent.com/49901208/103027001-5ecd9480-4555-11eb-9004-8f685bfd09d4.png" height=150 />


So, who is responsible? I guess the iOS scanner app by Adobe? Could that be, that they create bad PDF files?
And how to fix besides using Preview to resave? From what I found on a quick research, that is not that easy or just using GhostScript to resave...

Question is: Is it necessary to check the mime type before processing? I guess the answer is yes, because you have to decide which parser is used, right? That is how I understand the error log and that makes sense...

**Comment by jonaswinkler** [comment]
> So, who is responsible? I guess the iOS scanner app by Adobe?

Is that app on Android as well? Or could you create some bogus document with that for me? I'd really like to see what's up.

> Could that be, that they create bad PDF files?

Maybe.

> Question is: Is it necessary to check the mime type before processing? I guess the answer is yes, because you have to decide which parser is used, right?

Well, yes. This is the safest way to ensure that the parsers get valid input only. The PDF parser expects PDF documents (or images) and I don't even know what would happen if you renamed a .exe file to pdf and throw that into the consumption folder. This is especially important when adding documents from mails. I'm considering to add file type checking to the consumer as well, as a fall-back option.

**Comment by totti4ever** [comment]
Okay, I installed Adobe Scan on both iOS and Android and both produced proper PDF files. The file I had the problem with was sent to me via mail, therefore I cannot tell what went wrong (maybe an older version of the App?!).

What consumers do with undentified objects? ocymypdf throws an error similar to yours, I tried it:
```
Input file is not a PDF, checking if it is an image...
cannot identify image file 'Scan 21. Dez. 2020.pdf'
UnsupportedImageFormatError
```

As this seems to have been an unusual case at my side, I propose to just ignore it and close this issue!

**Comment by jonaswinkler** [comment]
The consumer ignores unsupported files and does nothing.

Good thing we're doing the file type checks, since this prevents errors like this. I'll clarify the errors messages a bit.

**Comment by ghaberek** [comment]
I'm getting this error when scanning documents directly to my `\\paperless\consume` network share via my printer's scan-to-network feature.

```
INFO 2020-12-30 11:17:55,679 loggers Consuming 20201230_111752.PDF
11:17:55 [Q] ERROR Failed [20201230_111752.PDF] - No parsers abvailable for 20201230_111752.PDF : Traceback (most recent call last):
  File "/opt/paperless/.local/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/opt/paperless/src/documents/tasks.py", line 73, in consume_file
    override_tag_ids=override_tag_ids)
  File "/opt/paperless/src/documents/consumer.py", line 106, in try_consume_file
    raise ConsumerError(f"No parsers abvailable for {self.filename}")
documents.consumer.ConsumerError: No parsers abvailable for 20201230_111752.PDF
```

The file type is correct:

```
$ file /mnt/paperless/consume/20201230_111752.PDF
/mnt/paperless/consume/20201230_111752.PDF: PDF document, version 1.6
```

If I manually restart the `paperless-consumer` service, it picks up the document just fine:

```
INFO 2020-12-30 11:20:24,644 loggers Consuming 20201230_111752.PDF
INFO 2020-12-30 11:20:25,042 pdfdocument xref found: pos=b'713692'
INFO 2020-12-30 11:20:25,043 pdfdocument read_xref_from: start=713692, token=/b'xref'
INFO 2020-12-30 11:20:25,043 pdfdocument xref objects: {1: (None, 713438, 0), 2: (None, 713601, 0), 3: (None, 15, 0), 4: (None, 713536, 0), 5: (None, 111, 0), 6: (None, 713378, 0), 7: (None, 214, 0), 8: (None, 713325, 0), 9: (None, 232, 0), 10: (None, 713347, 0), 11: (None, 713484, 0)}
INFO 2020-12-30 11:20:25,044 pdfdocument trailer: {'Root': <PDFObjRef:1>, 'Info': <PDFObjRef:2>, 'ID': [b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2', b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2'], 'Size': 12}
INFO 2020-12-30 11:20:25,579 pdfdocument trailer: {'Root': <PDFObjRef:1>, 'Info': <PDFObjRef:2>, 'ID': [b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2', b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2'], 'Size': 12}
INFO 2020-12-30 11:20:25,582 pdfpage Pages: Kids=[<PDFObjRef:4>]
INFO 2020-12-30 11:20:25,583 pdfpage Pages: Kids=[<PDFObjRef:3>]
INFO 2020-12-30 11:20:25,585 pdfpage Page: {'Parent': <PDFObjRef:4>, 'MediaBox': [0, 0, 612, 792], 'Contents': <PDFObjRef:5>, 'Resources': <PDFObjRef:6>, 'Type': /'Page'}
INFO 2020-12-30 11:20:25,587 pdfinterp Processing page: <PDFPage: Resources={'ProcSet': <PDFObjRef:10>, 'XObject': {'strip0': <PDFObjRef:9>}}, MediaBox=[0, 0, 612, 792]>
INFO 2020-12-30 11:20:25,587 pdfinterp render_contents: resources={'ProcSet': <PDFObjRef:10>, 'XObject': {'strip0': <PDFObjRef:9>}}, streams=[<PDFStream(5): raw=53, {'Length': <PDFObjRef:7>}>], ctm=(1, 0, 0, 1, 0, 0)
INFO 2020-12-30 11:20:26,117 pdfinterp Processing xobj: <PDFStream(9): raw=712936, {'Type': /'XObject', 'Subtype': /'Image', 'Width': 2550, 'Height': 3300, 'ColorSpace': /'DeviceRGB', 'BitsPerComponent': 8, 'Length': <PDFObjRef:8>, 'Filter': /'DCTDecode'}>
INFO 2020-12-30 11:20:49,892 _sync Postprocessing...
INFO 2020-12-30 11:20:51,639 optimize Optimize ratio: 1.00 savings: 0.0%
INFO 2020-12-30 11:20:51,646 _sync Output file is a PDF/A-2B (as expected)
INFO 2020-12-30 11:21:01,931 filelock Lock 140705460141976 acquired on /mnt/paperless/media/media.lock
INFO 2020-12-30 11:21:01,938 filelock Lock 140705460141976 released on /mnt/paperless/media/media.lock
INFO 2020-12-30 11:21:01,941 filelock Lock 140705680339296 acquired on /mnt/paperless/media/media.lock
INFO 2020-12-30 11:21:01,941 filelock Lock 140705680339296 released on /mnt/paperless/media/media.lock
INFO 2020-12-30 11:21:01,954 loggers Document 20201230_111752 consumption finished
```

I haven't had the issue when dropping documents directly into the network share from Windows 10. Could it be that Paperless is trying to consume the file before the printer has finished writing to it? What type of ionotify is Paperless using to detect new files?

Also "abvailable" is spelled wrong in the error message. I'm running release 0.9.9 on Ubuntu 18.04 bare metal.

**Comment by ghaberek** [comment]
I'm wondering if a simple solution might be to implement a `PAPERLESS_CONSUMER_DELAY=<num>` setting that will cause the consumer to wait until the file is `<num>` minutes old before trying to parse it.

**Comment by jonaswinkler** [comment]
The Inotify watcher reacts to the CLOSE_WRITE and MOVED_TO events. This *should* take care of not opening incomplete files, but apparently it's not. Even wrote some test cases to verify that the consumer does not pick up files early.

The polling watcher checks found files every second and only if the date/size (unsure which at the moment) did not change, it fires up the consumer.

`PAPERLESS_CONSUMER_DELAY=` How long should we wait? Doesn't seem like a solution to me.

I'm not entirely sure how to debug this.

**Comment by ghaberek** [comment]
> The Inotify watcher reacts to the CLOSE_WRITE and MOVED_TO events. This _should_ take care of not opening incomplete files, but apparently it's not. Even wrote some test cases to verify that the consumer does not pick up files early.

I agree, those options should be enough to properly ensure the file is ready to be processed.

> The polling watcher checks found files every second and only if the date/size (unsure which at the moment) did not change, it fires up the consumer. This might be an option for you.

If I enable `PAPERLESS_CONSUMER_POLLING` does that disable the inotify watcher altogether? That may be the simplest solution.

> `PAPERLESS_CONSUMER_DELAY=` How long should we wait? Doesn't seem like a solution to me. You could use polling and set the polling interval to some minutes to achieve a similar effect.

I think as little as a few seconds would technically be enough, but perhaps one minute? If polling disables inotify then I suppose it's moot to implement this setting as well.

> I'm not entirely sure how to debug this.

Short of going out and buying this particular model scanner, I don't see how you could either. 😄 

It looks like `ConsumerError` is [thrown](https://github.com/jonaswinkler/paperless-ng/blob/master/src/documents/consumer.py#L106) when `parser_class` is **None** so I'd recommend including the `mime_type` value in the error string to see what type of file it at least _thought_ it was dealing with:

    raise ConsumerError(f"No parsers abvailable for {self.filename} ({mime_type})")

**Comment by jonaswinkler** [comment]
> If I enable `PAPERLESS_CONSUMER_POLLING` does that disable the inotify watcher altogether? That may be the simplest solution.

Exactly. It's either inotify or polling.

> It looks like `ConsumerError` is [thrown](https://github.com/jonaswinkler/paperless-ng/blob/master/src/documents/consumer.py#L106) when `parser_class` is **None** so I'd recommend including the `mime_type` value in the error string to see what type of file it at least _thought_ it was dealing with:

I think that's already on the dev branch.

**Comment by jonaswinkler** [comment]
Regarding this issue: 

> I'm getting this error when scanning documents directly to my `\\paperless\consume` network share via my printer's scan-to-network feature.
> 
> ```
> INFO 2020-12-30 11:17:55,679 loggers Consuming 20201230_111752.PDF
> 11:17:55 [Q] ERROR Failed [20201230_111752.PDF] - No parsers abvailable for 20201230_111752.PDF : Traceback (most recent call last):
>   File "/opt/paperless/.local/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
>     res = f(*task["args"], **task["kwargs"])
>   File "/opt/paperless/src/documents/tasks.py", line 73, in consume_file
>     override_tag_ids=override_tag_ids)
>   File "/opt/paperless/src/documents/consumer.py", line 106, in try_consume_file
>     raise ConsumerError(f"No parsers abvailable for {self.filename}")
> documents.consumer.ConsumerError: No parsers abvailable for 20201230_111752.PDF
> ```
> 
> The file type is correct:
> 
> ```
> $ file /mnt/paperless/consume/20201230_111752.PDF
> /mnt/paperless/consume/20201230_111752.PDF: PDF document, version 1.6
> ```
> 
> If I manually restart the `paperless-consumer` service, it picks up the document just fine:
> 
> ```
> INFO 2020-12-30 11:20:24,644 loggers Consuming 20201230_111752.PDF
> INFO 2020-12-30 11:20:25,042 pdfdocument xref found: pos=b'713692'
> INFO 2020-12-30 11:20:25,043 pdfdocument read_xref_from: start=713692, token=/b'xref'
> INFO 2020-12-30 11:20:25,043 pdfdocument xref objects: {1: (None, 713438, 0), 2: (None, 713601, 0), 3: (None, 15, 0), 4: (None, 713536, 0), 5: (None, 111, 0), 6: (None, 713378, 0), 7: (None, 214, 0), 8: (None, 713325, 0), 9: (None, 232, 0), 10: (None, 713347, 0), 11: (None, 713484, 0)}
> INFO 2020-12-30 11:20:25,044 pdfdocument trailer: {'Root': <PDFObjRef:1>, 'Info': <PDFObjRef:2>, 'ID': [b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2', b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2'], 'Size': 12}
> INFO 2020-12-30 11:20:25,579 pdfdocument trailer: {'Root': <PDFObjRef:1>, 'Info': <PDFObjRef:2>, 'ID': [b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2', b'\x12y\xaa\xfe\x06\xa2|t(\x80%\x9aH_\xa6\xb2'], 'Size': 12}
> INFO 2020-12-30 11:20:25,582 pdfpage Pages: Kids=[<PDFObjRef:4>]
> INFO 2020-12-30 11:20:25,583 pdfpage Pages: Kids=[<PDFObjRef:3>]
> INFO 2020-12-30 11:20:25,585 pdfpage Page: {'Parent': <PDFObjRef:4>, 'MediaBox': [0, 0, 612, 792], 'Contents': <PDFObjRef:5>, 'Resources': <PDFObjRef:6>, 'Type': /'Page'}
> INFO 2020-12-30 11:20:25,587 pdfinterp Processing page: <PDFPage: Resources={'ProcSet': <PDFObjRef:10>, 'XObject': {'strip0': <PDFObjRef:9>}}, MediaBox=[0, 0, 612, 792]>
> INFO 2020-12-30 11:20:25,587 pdfinterp render_contents: resources={'ProcSet': <PDFObjRef:10>, 'XObject': {'strip0': <PDFObjRef:9>}}, streams=[<PDFStream(5): raw=53, {'Length': <PDFObjRef:7>}>], ctm=(1, 0, 0, 1, 0, 0)
> INFO 2020-12-30 11:20:26,117 pdfinterp Processing xobj: <PDFStream(9): raw=712936, {'Type': /'XObject', 'Subtype': /'Image', 'Width': 2550, 'Height': 3300, 'ColorSpace': /'DeviceRGB', 'BitsPerComponent': 8, 'Length': <PDFObjRef:8>, 'Filter': /'DCTDecode'}>
> INFO 2020-12-30 11:20:49,892 _sync Postprocessing...
> INFO 2020-12-30 11:20:51,639 optimize Optimize ratio: 1.00 savings: 0.0%
> INFO 2020-12-30 11:20:51,646 _sync Output file is a PDF/A-2B (as expected)
> INFO 2020-12-30 11:21:01,931 filelock Lock 140705460141976 acquired on /mnt/paperless/media/media.lock
> INFO 2020-12-30 11:21:01,938 filelock Lock 140705460141976 released on /mnt/paperless/media/media.lock
> INFO 2020-12-30 11:21:01,941 filelock Lock 140705680339296 acquired on /mnt/paperless/media/media.lock
> INFO 2020-12-30 11:21:01,941 filelock Lock 140705680339296 released on /mnt/paperless/media/media.lock
> INFO 2020-12-30 11:21:01,954 loggers Document 20201230_111752 consumption finished
> ```
> 
> I haven't had the issue when dropping documents directly into the network share from Windows 10. Could it be that Paperless is trying to consume the file before the printer has finished writing to it? What type of ionotify is Paperless using to detect new files?
> 
> Also "abvailable" is spelled wrong in the error message. I'm running release 0.9.9 on Ubuntu 18.04 bare metal.

My best guess would be that the scanner software is writing an empty file to "20201230_111752.PDF" first, maybe to reserve the file name, and closes the file (and thus paperless picks it up). Then it maybe updates that file when the scanning process completes. However, even then paperless should pick up the file when it is closed again; I have no idea what's happening here.

**Comment by Matthias84** [comment]
Same here on a docker container.
I copy manually  a bunch of TIFF files produced by my scanner. There are some, which result in failed tasks with similar logs:

```
: Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 176, in parse
ocrmypdf.ocr(**ocr_args)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/api.py", line 326, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_sync.py", line 353, in run_pipeline
original_filename, start_input_file, work_folder / 'origin.pdf', options
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_pipeline.py", line 143, in triage
triage_image_file(input_file, output_file, options)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_pipeline.py", line 82, in triage_image_file
raise UnsupportedImageFormatError()
ocrmypdf.exceptions.UnsupportedImageFormatError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/paperless/src/documents/consumer.py", line 179, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 197, in parse
raise ParseError(e)
documents.parsers.ParseError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
override_tag_ids=override_tag_ids)
File "/usr/src/paperless/src/documents/consumer.py", line 196, in try_consume_file
raise ConsumerError(e)
documents.consumer.ConsumerError
```
If we inspect via info, they seem to be valid TIFFs? 
`file DB\ Fahrt.tiff --mime-type
DB Fahrt.tiff: image/tiff`
This issue occures on single and multipage tiffs, which seem to valid:
```
tiffinfo DB\ Fahrt.tiff
TIFF Directory at offset 0x7331cc (7549388)
  Image Width: 3300 Image Length: 2550
  Bits/Sample: 8
  Compression Scheme: AdobeDeflate
  Photometric Interpretation: RGB color
  Extra Samples: 1<unassoc-alpha>
  FillOrder: msb-to-lsb
  Samples/Pixel: 4
  Rows/Strip: 2550
  Planar Configuration: single image plane
```
I added files again and again, with altered names, but error persists. Files van be viewed fine :confused:

**Comment by jonaswinkler** [comment]
Do you have sample file that you're able to share?

This is an issue with one of the libraries that paperless uses to perform OCR, and not an issue of paperless itself. I'll forward the issue once I've got it reproduced over here.

**Comment by jonaswinkler** [comment]
Not enough input on this one. Feel free to reopen if you still encounter this issue.
