### ISSUE TITLE
paperless to paperless-ng migration with sqlite to postgresql

### ISSUE THREAD

**Issue by thisisamateurhour** [jonaswinkler/paperless-ng#181]
First off, thanks for this amazing next step, love the new interface!

I ran through the migration steps from original paperless and was able to get all my docs to show up in paperless-ng using the  
command:
`docker-compose run --rm webserver document_index reindex` 

So everything's working and I wanted to shift over to postgresql
I did a docker-compose down, updated my docker-compose file to include 

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - (my specific pgdata directory):/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

I also updated the webserver component to include the db dependency 

 webserver:
     image: jonaswinkler/paperless-ng:0.9.9
     restart: unless-stopped
     depends_on:
       - db
       - broker

I then ran 
`docker-compose run --rm webserver /bin/bash`
and was able to attach to the container

When I attempted to run through step 4 of the moving to postgresql section is where I ran into an issue https://paperless-ng.readthedocs.io/en/latest/setup.html#migration-to-paperless-ng
Command:
`python3 manage.py dumpdata --database=sqlite --exclude=contenttypes --exclude=auth.Permission > data.json`
Response:
`CommandError: Unable to serialize database: The connection sqlite doesn't exist`

Not sure where to go from here, I'm unsure how my docs and tags and correspondents could exist without there being a database. 

I'm pretty amateur as the name suggests, so hoping someone can help.  Happy to provide more explanation/ include any additional information as necessary.

**Comment by jonaswinkler** [comment]
Simply including the DB dependency does not tell paperless to use that database. Paperless still uses your SQLite database.

You need to configure `PAPERLESS_DBHOST` for the webserver, see the `docker-compose.postgres.yml` in the repo / in the release for reference.

Only then will PostgreSQL be used by default. This will also make the `sqlite` connection available as a fallback.

**Comment by thisisamateurhour** [comment]
My fault for missing that.  Adding the host worked perfectly
