### ISSUE TITLE
FR: clicking the logo navigates to the home page

### ISSUE THREAD

**Issue by zjean** [jonaswinkler/paperless-ng#182]
I would love to have a click on the paperless logo being me to the home page.

What do you think?

**Comment by totti4ever** [comment]
I have actually thought about this as well, though the Dashboard (being home) ist positioned just beneath the logo.

Still, some action on the app icon in the upper left corner is something I'd consider standard and I already tried to click it a couple times myself ;-)

**Comment by zjean** [comment]
@totti4ever yeah, that's true, but on mobile you have to perform an extra tap to open the menu. It would be nice to save this tap :-)
