### ISSUE TITLE
FR: Iterate through documents

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#183]
Only option right now it to save and go to the next document, also if I didn't change anything. Maybe one could just show "Next" instead unless anything is changed or even add controls to go to the next and the previous document.

What I also found is that when opening a document from a view on the dashboard, there is no next.

**Comment by jonaswinkler** [comment]
See #29

**Comment by totti4ever** [comment]
Sorry, just saw the title and thought of some processing queue
