### ISSUE TITLE
[Docker] Please export port 8000 for plesk

### ISSUE THREAD

**Issue by jens108** [jonaswinkler/paperless-ng#185]
Hi there, merry Christmas!

I am trying to install paperless-ng on a server using Plesk. It's working and I got it all running - but Plesk does not recognize the port you're exposing, which prevents me from actually accessing the service. I am using your docker image from https://hub.docker.com/r/jonaswinkler/paperless-ng

I found this article, where they describe in the comments what needs to be done
https://support.plesk.com/hc/en-us/articles/115003142213-Unable-to-add-Docker-Proxy-rules-in-Plesk-no-container-is-displayed

The way I see it, all we'd need would be an EXPOSE 8000 in the docker file. But I am no expert and just guessing wildly. Would be much appreciated!

Best,
Jens

**Comment by totti4ever** [comment]
That's indeed how I understand the best-practice for docker images anyway. If it was helpful I could provide the PR, but I guess the time thinking about it takes longer than the actual adaption.

**Comment by jonaswinkler** [comment]
From the Dockerfile documentation:

> The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published. To actually publish the port when running the container, use the -p flag on docker run to publish and map one or more ports, or the -P flag to publish all exposed ports and map them to high-order ports.

You'd still need to supply `-p` or `-P` command line arguments, but I'll add the `EXPOSE` line to the Dockerfile anyway.
