### ISSUE TITLE
new tags being created automagically

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#191]
After I had problems with not parsable document I found new tags named like them plus some postfix:
`Scan 21. Dez. 2020.pdf.sb-25bf0640-ALVVPA`

Don't know whether it's been something temporarily, but wanted to let you know

**Comment by jonaswinkler** [comment]
The only logic in paperless that created tags from filenames was the filename guesswork feature, which I've removed in 0.9.9. If this happened on 0.9.9, you need to provide some more details about that, such as:

- What action leads to the creation of that tag
- What did the original filename look like

If this happened on previous versions, please reproduce that on the current version. I believe that it's not an issue anymore.

**Comment by totti4ever** [comment]
I'll reopen in case it pops up again

**Comment by totti4ever** [comment]
Okay, it happened again (on 0.9.9)!

Tag name: `AGB Montana.pdf.sb-25bf0640-JB4AQh`
File name: `AGB Montana.pdf`

Log:
```
12/29/20, 6:10 AM INFO Consuming AGB Montana.pdf
12/29/20, 6:10 AM INFO Consuming AGB Montana.pdf
```

It happened for two documents, didn't happen for others, though. Documents are not long or big or anything, TOS document is 1 page.

**Comment by jonaswinkler** [comment]
Just let me get this straight: The tag was created while consuming that document and is also attached to the new document?

**Comment by jonaswinkler** [comment]
Are you using `CONSUMER_SUBDIRS_AS_TAGS` by any chance?

**Comment by totti4ever** [comment]
Oh, good point! I actually set it to 1, when it was introduced! I guess this comes from some temporary thing during the copy job?!

Files are copied to root consume dir...

Hmm, hard to say what to do, to prevent this. Add a timeout wouldn't work for bigger sized files..hmm

**Comment by jonaswinkler** [comment]
Are you using polling or inotify?

How are you moving files into the folder? (Explorer, is your scanner putting files there)

Are you accessing the folder directly or via Samba / NFS etc?

**Comment by totti4ever** [comment]
I am using inotify, I guess I moved them through Samba (using Finder @ macOS)

**Comment by jonaswinkler** [comment]
I actually have no idea and cannot get this to reproduce your issue in any way over here.

My best guess is that whatever tool you're using to copy (or maybe its also some configuration option of the samba server) copies your file to `consume/AGB Montana.pdf.sb-25bf0640-JB4AQh/AGB Montana.pdf` and after that's done, moves it to `consume/AGB Montana.pdf`. The idea would be to copy stuff to a temporary directory (that's what the tag name looks like) until the copy operation is complete, and then move it into the final place (which is super fast). There's no way for me to catch that without breaking the feature.

Many scanners also do something like this. Copy a file to `file.pd~` until done, then move to `file.pdf`.

**Comment by jonaswinkler** [comment]
Did some digging, apparently some weird behavior of mac OS when saving to SMB shares. Often mentioned in combination with MS Word.

See https://github.com/osxfuse/osxfuse/issues/485.

Not much I can do about that.

**Comment by totti4ever** [comment]
I'll experiment with veto files in smb.conf, will report!
Thank you very much for researching!
