### ISSUE TITLE
[Feature Request] Dark Theme

### ISSUE THREAD

**Issue by SaraSmiseth** [jonaswinkler/paperless-ng#194]
Hello,
is it possible to have a dark theme?
At night, white background is a little violent for the eyes :)

Thank you for the very good job.

**Comment by jonaswinkler** [comment]
I'll look into that. Not exactly sure how to swap out colors at runtime.

If that's possible, We can also add an option to change the default accent color, which is this dark-ish green right now.

**Comment by shamoon** [comment]
I can tackle this, changing color is usually easiest with CSS custom properties. Personally I vote we just go for dark mode for now, it’s less complex and I feel like changing the accent color is the kind of feature that doesn’t get a ton of use. How does that sound?

We’ll also need to sort out where to put this option. If we’re going to save the preference to the db perhaps under General Settings, otherwise we could put a toggle like at the bottom of the main sidebar menu? What do people think?

**Comment by qcasey** [comment]
> We’ll also need to sort out where to put this option. If we’re going to save the preference to the db perhaps under General Settings, otherwise we could put a toggle like at the bottom of the main sidebar menu? What do people think?

It'd be very nice if it supported [following the system theme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). I have my theme change based on sunset / sunrise and a lot of websites follow it. I think MacOS supports this as well?

**Comment by shamoon** [comment]
Yea, then I think we should stick it in settings.

**Comment by shamoon** [comment]
What does everyone think (excuse the low fps on the video, the transition is actually much nicer 🙂)? Easy enough to tweak the theme (@jonaswinkler I forgot about Bootstrap so cant use CSS custom properties, ended up just using some SCSS).

https://user-images.githubusercontent.com/4887959/103194806-9316bd00-4895-11eb-88d5-4b6c238e75ed.mov

<img width="1510" alt="Screen Shot 2020-12-27 at 10 51 13 PM" src="https://user-images.githubusercontent.com/4887959/103195019-3b2c8600-4896-11eb-9ab7-78163c7959b9.png">
<img width="1510" alt="Screen Shot 2020-12-27 at 10 52 32 PM" src="https://user-images.githubusercontent.com/4887959/103195021-3d8ee000-4896-11eb-82fc-0c79719199e0.png">

**Comment by jonaswinkler** [comment]
Looks good!

- `$primary` and `$secondary` need to be much brighter for the buttons. Top bar looks good though, no need to change it there in dark mode.
- See how the predefined text color on the tags got inverted? That's not so good.
- Maybe its possible, with some image blending magic, to make black text on the thumbnails appear as white, not sure.

**Comment by jonaswinkler** [comment]
> Yea, then I think we should stick it in settings.

I'll eventually get the settings stored on the server as well, but yes, that's where it should go now.

**Comment by shamoon** [comment]
> * `$primary` and `$secondary` need to be much brighter for the buttons. Top bar looks good though, no need to change it there in dark mode.

I messed with this a bit, dont want it to feel too "neon" and bright. It also looks brighter against an actual dark screen, but again I tweaked it.
<br/>
> * See how the predefined text color on the tags got inverted? That's not so good.

Ah, I see, I was explicitly changing the text color of the tags to black but easy to remove that. I do drop the brightness on the tags to 90% to make them less jarring.
<br/>
> * Maybe its possible, with some image blending magic, to make black text on the thumbnails appear as white, not sure.

Great idea, this looks really cool. Colors are inverted but still pretty great IMHO.

<br/><br/>

Updated screenshot below.

<img width="1425" alt="Screen Shot 2020-12-28 at 11 43 01 AM" src="https://user-images.githubusercontent.com/4887959/103239348-166df800-4902-11eb-8797-0467b1e8e471.png">

**Comment by jonaswinkler** [comment]
try

`filter: invert(100%) hue-rotate(180deg);`

to preserve colors. This looks quite good with documents. Maybe even `invert(90%)` to make it less dark.

**Comment by shamoon** [comment]
Heh, figured that out right after I posted the last one. New screenshot!
<img width="1505" alt="Screen Shot 2020-12-28 at 12 49 48 PM" src="https://user-images.githubusercontent.com/4887959/103242543-67ceb500-490b-11eb-86e7-4d928fbdbaf0.png">

**Comment by jonaswinkler** [comment]
![image](https://user-images.githubusercontent.com/17569239/103242781-d0dc1a00-4957-11eb-8529-f7b6edf55ec8.png)

I like the highlighting, is that on the light theme as well? :)

**Comment by shamoon** [comment]
No it looks odd in light theme because of the borders (easy enough to remove those of course).

One last thing, I have this now defaulting to `Use system settings = true`, we good with that? I think its safe to say anyone with they machine in dark mode wants as many apps / sites to respect that as possible.

If all good I can submit the PR

**Comment by jonaswinkler** [comment]
Sure, make a PR.
