### ISSUE TITLE
Missing search results

### ISSUE THREAD

**Issue by Perry3D** [jonaswinkler/paperless-ng#195]
Hi,

i am currently using the version 0.9.9 docker-compose version.

I added some documents and they were correctly processed. I can see the content of the documents.
But if i search with the top bar the results are not appearing:
![image](https://user-images.githubusercontent.com/986287/103173006-26310200-4858-11eb-9d99-caa00d5cfda1.png)

But the auto completion is working:
![image](https://user-images.githubusercontent.com/986287/103173036-57a9cd80-4858-11eb-8d09-2bd3bc6bc2cb.png)

The container log doesn't show any hint:
```
webserver_1  | WARNING 2020-12-27 14:30:16,799 log Bad Request: /api/search/
webserver_1  | 172.23.0.3 - - [27/Dec/2020:14:30:19 +0000] "GET /api/search/autocomplete/?term=leben HTTP/1.1" 200 164 "https://pl.xxx.de/search?query=lebenslauf%20" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
webserver_1  | 172.23.0.3 - - [27/Dec/2020:14:30:20 +0000] "GET /api/search/autocomplete/?term=lebens HTTP/1.1" 200 164 "https://pl.xxx.de/search?query=lebenslauf%20" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
webserver_1  | 172.23.0.3 - - [27/Dec/2020:14:30:20 +0000] "GET /api/search/autocomplete/?term=lebensl HTTP/1.1" 200 14 "https://pl.xxx.de/search?query=lebenslauf%20" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
webserver_1  | 172.23.0.3 - - [27/Dec/2020:14:30:20 +0000] "GET /api/search/autocomplete/?term=lebensla HTTP/1.1" 200 14 "https://pl.xxx.de/search?query=lebenslauf%20" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
webserver_1  | 172.23.0.3 - - [27/Dec/2020:14:30:21 +0000] "GET /api/search/autocomplete/?term=lebenslau HTTP/1.1" 200 14 "https://pl.xxx.de/search?query=lebenslauf%20" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
webserver_1  | 172.23.0.3 - - [27/Dec/2020:14:30:22 +0000] "GET /api/search/autocomplete/?term=lebenslauf HTTP/1.1" 200 14 "https://pl.xxx.de/search?query=lebenslauf%20" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
webserver_1  | 127.0.0.1 - - [27/Dec/2020:14:30:31 +0000] "GET / HTTP/1.1" 302 0 "-" "curl/7.64.0"
```

**Comment by jonaswinkler** [comment]
To temporarily fix this issue, you need to run [this](https://paperless-ng.readthedocs.io/en/latest/administration.html#managing-the-document-search-index) with `reindex` as the argument.

For me to permanently fix this issue, I need to know:

- Did you also delete some documents, perhaps using the new 'Bulk Edit' feature?

**Comment by Perry3D** [comment]
Thank you for the fast reply. The reindex solved the issue.

Yes, i also deleted documents. Probably with the bulk feature, but i am not sure.

**Comment by jonaswinkler** [comment]
fyi.

I've forgot to update the search index after performing bulk deletions, which left documents in the index that do not exist anymore.

**Comment by Perry3D** [comment]
But this issue is about missing documents in the index and not about too many documents?

That means the reindex is probably necessary again after the next upgrade?

**Comment by Skylinar** [comment]
> To temporarily fix this issue, you need to run [this](https://paperless-ng.readthedocs.io/en/latest/administration.html#managing-the-document-search-index) with `reindex` as the argument.
> 
> For me to permanently fix this issue, I need to know:
> 
> * Did you also delete some documents, perhaps using the new 'Bulk Edit' feature?

I am quiet new to this, could you please let me know exactly how to reindex? I am using Unraid as a host and docker exec into the container. How would look the command?

Thanks

**Comment by jonaswinkler** [comment]
When you docker exec into the container, verify with

`pwd`

that you are in

`/usr/src/paperless/src`

and if not, `chdir` to that directory.

Then run

`python3 manage.py document_index reindex`
