### ISSUE TITLE
Update the values for "Documents in Inbox" and "Total Documents" in the Statistics box dynamically

### ISSUE THREAD

**Issue by wechsler42** [jonaswinkler/paperless-ng#200]
Hi Jonas,
I would like to suggest to update the values for "Documents in Inbox" and "Total Documents" in the Statistics box dynamically triggered by changes in the database, finishing of the consumption of a document etc.. At the moment the values get updated  when I reload the page in the Browser.

**Comment by jonaswinkler** [comment]
Yes, this would be nice. However: Apart from polling the web server regularly (getting statistics every 5 seconds or so), there's no way to have changes in the database get passed to the web site in real time. That is, not at this point.

**Comment by wechsler42** [comment]
Thanks for the feedback. I see, so perhaps in the future.
