### ISSUE TITLE
Mail parser not working for PDF: mime type detected is application/octet-stream

### ISSUE THREAD

**Issue by jovandeginste** [jonaswinkler/paperless-ng#201]
I configured the paperless mail plugin to connect to a new mailbox. I forwarded a single mail with a PDF in attachment to that mailbox. After figuring out the correct connection settings, I saw this error coming up:

> Rule documents.document parsing: Processing mail [mail subject] from [my mail address] with 1 attachment(s)
> Rule documents.document parsing: Skipping attachment filename.pdf since guessed mime type application/octet-stream is not supported by paperless

Anyone knows what silly mistake I made?

I selected "Use attachment filename as title", all other options are default or not relevant at this stage...

**Comment by jonaswinkler** [comment]
If you're on linux (not sure about mac), please run `file --mime-type filename.pdf` on that file and report back if this is still `application/octet-stream`. If so, there's something wrong with that particular document. Even if I were to lift the restrictions on mime types, the part of paperless that performs PDF conversion (which is an external library) would still reject the file.

If you have a non-confidential PDF document that gets rejected by paperless with the above error message, I'd be interested in that. I've got PDF documents from a wide variety of sources in paperless and they all process fine.

If `file ...` reports `application/pdf`, this is a bug and I need to figure out what's going on.

**Comment by jovandeginste** [comment]
File reports `application/pdf`. Anything more I can do to help debug? I can't really send this PDF, since it could be misused. I can try with any other PDF, will do that later today after I finish the parser and PR

**Comment by jovandeginste** [comment]
You're right: it is the PDF. Another PDF ingested just fine, and this PDF didn't even work through the web UI. I should have tried that first.

**Comment by jonaswinkler** [comment]
It's still curious that file identifies this document correctly outside the image (I suppose you're using docker), so maybe some dependencies are missing.

**Comment by jonaswinkler** [comment]
Apparently `libmagic1` suggests `file` as an optional dependency, which is not installed in the image. I'll add that to the image and maybe that'll increase compatibility.

**Comment by jovandeginste** [comment]
So, I added this in the code; now it picks the PDF up, with a little warning:

> INFO 2020-12-28 23:15:17,580 _sync Output file is a PDF/A-2B (as expected)
   **** Warning: File has some garbage before %PDF- .

Unsure what the implications are of blanket-allowing "octet-stream" as "pdf":

> application/octet-stream: bin deploy msu msp

```diff
diff --git a/src/paperless_tesseract/parsers.py b/src/paperless_tesseract/parsers.py
index 80e200f..2c56c96 100644
--- a/src/paperless_tesseract/parsers.py
+++ b/src/paperless_tesseract/parsers.py
@@ -23,7 +23,8 @@ class RasterisedDocumentParser(DocumentParser):
         namespace_pattern = re.compile(r"\{(.*)\}(.*)")
 
         result = []
-        if mime_type == 'application/pdf':
+        if (mime_type == 'application/pdf' or
+            mime_type == 'application/octet-stream'):
             pdf = pikepdf.open(document_path)
             meta = pdf.open_metadata()
             for key, value in meta.items():
diff --git a/src/paperless_tesseract/signals.py b/src/paperless_tesseract/signals.py
index 1e1cd1e..9a8e230 100644
--- a/src/paperless_tesseract/signals.py
+++ b/src/paperless_tesseract/signals.py
@@ -7,6 +7,7 @@ def tesseract_consumer_declaration(sender, **kwargs):
         "weight": 0,
         "mime_types": {
             "application/pdf": ".pdf",
+            "application/octet-stream": ".pdf",
             "image/jpeg": ".jpg",
             "image/png": ".png",
             "image/tiff": ".tif",
```

**Comment by jonaswinkler** [comment]
`application/octet-stream` is pretty much anything that's not something else. This also includes any binary files that aren't PDF documents at all.

**Comment by jovandeginste** [comment]
I installed `file` in my image, but that doesn't change anything ...

**Comment by jovandeginste** [comment]
Perhaps we need some form of fallback to eg `file --mime-type` if the type is unknown or in a list of "catch-all" types (such as this `octet-stream`)?

**Comment by jovandeginste** [comment]
This diff seems to work in order to ingest the file through the consume directory. There are many more `magic` occurences - can/should we replace them all?

```diff
diff --git a/src/documents/consumer.py b/src/documents/consumer.py
index ab4912a..c7ed8f8 100755
--- a/src/documents/consumer.py
+++ b/src/documents/consumer.py
@@ -1,4 +1,5 @@
 import datetime
+import mimetypes
 import hashlib
 import logging
 import os
@@ -99,7 +100,7 @@ class Consumer(LoggingMixin):
 
         # Determine the parser class.
 
-        mime_type = magic.from_file(self.path, mime=True)
+        mime_type, _ = mimetypes.guess_type(self.filename, strict=False)
 
         parser_class = get_parser_class_for_mime_type(mime_type)
         if not parser_class:
diff --git a/src/documents/serialisers.py b/src/documents/serialisers.py
index f9fde9a..d11738e 100644
--- a/src/documents/serialisers.py
+++ b/src/documents/serialisers.py
@@ -1,4 +1,6 @@
 import magic
+import mimetypes
+
 from django.utils.text import slugify
 from rest_framework import serializers
 from rest_framework.fields import SerializerMethodField
@@ -289,13 +291,14 @@ class PostDocumentSerializer(serializers.Serializer):
     )
 
     def validate_document(self, document):
-        document_data = document.file.read()
-        mime_type = magic.from_buffer(document_data, mime=True)
+        mime_type, _ = mimetypes.guess_type(document.file, strict=False)
 
         if not is_mime_type_supported(mime_type):
             raise serializers.ValidationError(
                 "This file type is not supported.")
 
+        document_data = document.file.read()
+
         return document.name, document_data
 
     def validate_title(self, title):
```

**Comment by jonaswinkler** [comment]
This will not account for miss-named files. A rare occurrence, but it happens.

Rather, I'd like to find out why python magic refuses to report the correct type, while file seems to correctly identify the file, and for that I'd really need a sample file.

Could you do a `hexdump -C test.pdf --length 16` (or more) and paste the output until you see a `%PDF-1.x` in the rightmost column (only if not confidential). Since `**** Warning: File has some garbage before %PDF- .` happens, maybe this will help me to produce a similar file myself.

**Comment by jovandeginste** [comment]
I assume `file` and `mimetypes` _only_ check the file extension.

I can share that info:

```text
00000000  ef bb bf 25 50 44 46 2d  31 2e 34 0d 0a 25 f5 e4  |...%PDF-1.4..%..|
```

**Comment by jovandeginste** [comment]
So, perhaps: [byte order mark](http://www.herongyang.com/Unicode/Notepad-Byte-Order-Mark-BOM-FEFF-EFBBBF.html)?

**Comment by jovandeginste** [comment]
From what I read, you could just strip those three chars if they occur at the beginning of the file. Is that doable here?

**Comment by jovandeginste** [comment]
The plot thickens! I run this code on my desktop:

```python
import magic
m = magic.from_file("/path/to/file.pdf")
print(m)
```

Result:
> PDF document (UTF-8), version F.1

I run the same inside the container; result:
> data

**Comment by jovandeginste** [comment]
I tried with [magicfile](https://pypi.org/project/magicfile/) instead; this seemd to work flawlessly...

**Comment by jonaswinkler** [comment]
> I assume `file` and `mimetypes` _only_ check the file extension.
> 
> I can share that info:
> 
> ```
> 00000000  ef bb bf 25 50 44 46 2d  31 2e 34 0d 0a 25 f5 e4  |...%PDF-1.4..%..|
> ```

BOM? Now THAT'S interesting.

> The plot thickens! I run this code on my desktop:
> 
> ```python
> import magic
> m = magic.from_file("/path/to/file.pdf")
> print(m)
> ```
> 
> Result:
> 
> > PDF document (UTF-8), version F.1
> 
> I run the same inside the container; result:
> 
> > data

See? I want to find out why this happens only inside the container. (could you try installing the debian package `mime-support` inside the container? just a wild guess.)

> I tried with [magicfile](https://pypi.org/project/magicfile/) instead; this seemd to work flawlessly...

I see. Well, I'm trying to stay away from unpopular libraries, but oh well. If this will make it work, why not.

**Comment by jovandeginste** [comment]
I have mime-support installed in that container.

**Comment by jonaswinkler** [comment]
No need to test a file separately with multiple consumption methods though, they all use the same logic for validation.

**Comment by jovandeginste** [comment]
Yes, except there is `from_file` and `from_buffer` ...

**Comment by jovandeginste** [comment]
I tried a number of other things (different python versions, clean debian/ubuntu base image, stracing, etc), but I can't figure out the difference.

I tried both python (v2) and python3.

On a base debian:10, it always fails.
On a base ubuntu:focal, it always works.

**Comment by jonaswinkler** [comment]
I see.

Well, I've got a test file now and I'm able to reproduce the issue, which is something, I guess. Not entirely keen on adding hacks (BOM removal from files that shouldn't have that in the first place), but I'll make it work somehow. Sooner or later I'll also switch to a newer base image, which will also fix this, based on your results.

**Comment by jovandeginste** [comment]
Well, I can understand your issue with this. I was rather interested in finding the root cause, and maybe an elegant fix.

A totally different approach, might be a "generic" octet-stream parser, that does more in-depth checks. Again something to either enable or disable, depending on the user's preferences...

**Comment by jonaswinkler** [comment]
I've pulled in an updated dependency from debian testing that's responsible for mime type detection; the new versions of `file` and associated libraries detect more file types. I'll remove that as soon as bullseye (Debian 11) releases, and python3.8 wheels become available for armhf.
