### ISSUE TITLE
Fix thumbnail orientation for images with EXIF orientation

### ISSUE THREAD

**Issue by jonashaag** [jonaswinkler/paperless-ng#218]
EXIF (?) has an orientation feature that tells when the photo has been recorded with the device (smartphone) being rotated. For example, see the attached photo, which has an orientation info of "6 (Rotated 90 deg CCW)", but is displayed in correct rotation (ie. with rotation accounted for), at least on Mac.

Would be great if paperless uses the photo orientation for

- ~OCR~ works correctly
- Displaying the photo in correct rotation

**Comment by jonashaag** [comment]
![IMG_1459](https://user-images.githubusercontent.com/175722/103354103-f3327c80-4aaa-11eb-8fff-8ccdf6b35b7c.JPG)
![Uploading Screenshot 2020-12-30 at 14.24.44.png…]()

**Comment by jonashaag** [comment]
![IMG_1459](https://user-images.githubusercontent.com/175722/103354141-05acb600-4aab-11eb-9f1b-4616345934b8.JPG)
<img width="250" alt="Screenshot 2020-12-30 at 14 24 44" src="https://user-images.githubusercontent.com/175722/103354148-0ba29700-4aab-11eb-979f-243ceec81a31.png">

**Comment by jonaswinkler** [comment]
I'm getting "orientation=upper-left" on this file. Maybe some process modified that when you uploaded that to GitHub?

Where exactly is this an issue?

**Comment by jonashaag** [comment]
Sorry, must have uploaded the wrong file. Fixed it above.

Example of the problem:

<img width="195" alt="Screenshot 2020-12-30 at 14 52 15" src="https://user-images.githubusercontent.com/175722/103355516-bbc5cf00-4aae-11eb-9805-6105365c2456.png">

**Comment by jonaswinkler** [comment]
Alright, it seems only thumbnails are affected.

**Comment by jonaswinkler** [comment]
I suppose we'll also need some tool to regenerate thumbnails.

**Comment by jonashaag** [comment]
You're right, OCR failed due to me providing a 180 deg rotated image, which I consider a user error :) Just double checked, OCR seems to work equally well for 0 deg rotated and 90 deg rotated images.
