### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by ghaberek** [jonaswinkler/paperless-ng#222]
My Paperless instance suddenly stopped processing new documents and it throws this error instead. There was an out-of-memory event on the machine prior to this happening, but I'm not sure if it's related. I'm running several services on a Proxmox host and Paperless instance is running in an LXC container with 2 cores and 1 GB of memory. Running version 0.9.9.

I have several questions about this:

- Did my `classification_model.pickle` file get corrupted? If so, how can I check that? (I'm not strong on Python development.)
- I assume this is where it stores the machine learning data for the "automatic" classifications, correct?
- Would it be safe to just delete the pickle file and let it start learning again from scratch?
- Is this the only place this information is stored? Can (or should) it be stored in the database or cached in Redis?

```
14:42:13 [Q] ERROR Failed [20201230_143423.PDF] - Ran out of input : Traceback (most recent call last):
  File "/opt/paperless/.local/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/opt/paperless/src/documents/tasks.py", line 73, in consume_file
    override_tag_ids=override_tag_ids)
  File "/opt/paperless/src/documents/consumer.py", line 158, in try_consume_file
    classifier.reload()
  File "/opt/paperless/src/documents/classifier.py", line 64, in reload
    self.tags_binarizer = pickle.load(f)
EOFError: Ran out of input
```

**Comment by jonaswinkler** [comment]
Well, seems something crashed while updating this file.

I'll add some catch all handlers there and will especially take care of invalid/incomplete files.

Just delete the file, paperless will recreate it.

**Comment by lukyjay** [comment]
I'm having the same issue.

I have just updated to the latest version and I have deleted the pickle file as suggested. After rebooting I still cannot upload documents:

```
12/30/20, 1:49 PM INFO Saving updated classifier model to /mnt/Documents/Paperless/classification_model.pickle...

12/30/20, 1:49 PM INFO Document 2020-12-20 Scan2020-12-19_213237 consumption finished

12/30/20, 1:49 PM WARNING Cannot classify documents: [Errno 2] No such file or directory: '/mnt/Documents/Paperless/classification_model.pickle'.

12/30/20, 1:49 PM WARNING Thumbnail generation with ImageMagick failed, falling back to ghostscript. Check your /etc/ImageMagick-x/policy.xml!

12/30/20, 1:48 PM INFO Consuming Scan2020-12-19_213237.pdf

12/30/20, 1:48 PM INFO Using inotify to watch directory for changes: /mnt/Documents/input 
```

**Comment by jonaswinkler** [comment]
Not an issue. I still need to silence these warnings. This happens when the mentioned file hasn't been created yet and the logs state that consumption was performed successfully.

**Comment by lukyjay** [comment]
> Not an issue. I still need to silence these warnings. This happens when the mentioned file hasn't been created yet and the logs state that consumption was performed successfully.

It wont let me upload files.. I'll raise a new ticket for my issue if it's unrelated  to the above :) Thank you
