### ISSUE TITLE
Removing tags in bulk edit : list contains all the tags existing in paperless-ng

### ISSUE THREAD

**Issue by Philmo67** [jonaswinkler/paperless-ng#225]
Little usability glitch when removing tags in bulk edit : the tags proposed in the drop-down list should only be those actually present on the selected documents and not the list of all tags existing in paperless-ng.

**Comment by jonaswinkler** [comment]
I've got the new bulk editor almost ready, which will improve usability by a huge margin. These dialogs won't exist anymore.
