### ISSUE TITLE
Cannot classify documents: [Errno 2]

### ISSUE THREAD

**Issue by isentropik** [jonaswinkler/paperless-ng#226]
Seems I'm getting this error prior to every record being saved to the database:

`Cannot classify documents: [Errno 2] No such file or directory: '/usr/src/paperless/src/../data/classification_model.pickle'.`

I'm installed through Docker on Ubuntu 20.04.

If you need anything else let me know. It seems that things show up OK though I'm very new to Paperless so I couldn't tell you if things are missing or not.

Thanks!

**Comment by jonaswinkler** [comment]
This is a warning I'll still need to silence.

This is not an issue and happens on new installations when this file hasn't been created yet (paperless will do that once some requirements are met).

If everything appears to be working: Don't mind the message.

**Comment by isentropik** [comment]
Perfect, thanks for the quick response!
