### ISSUE TITLE
PDF view does not work without internet

### ISSUE THREAD

**Issue by kinglike1337** [jonaswinkler/paperless-ng#232]
I am testing paperless-ng in a restricted environment without direct internet access.
The PDF view of a document does not work in this scenario, because an external java-script library is required:
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.5.207/pdf.worker.min.js

It would be nice for a self-hosted application to not rely on any external resources.

Tested with version 0.9.11.

**Comment by jonaswinkler** [comment]
Agreed!

-----------

Notes to myself:

https://github.com/VadimDez/ng2-pdf-viewer/blob/master/README.md#set-custom-path-to-the-worker

or even better, just tell angular to include the worker, which is already in paperless as a dependency anyway.
