### ISSUE TITLE
Non-existing pre and post hooks stop consumption

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#236]
While I reconfigured my paperless-ng instance I wrongly linked the pre and post hooks to a host path instead of a mapped container path. Today I tried to import new documents and and it occurred to me that those documents were not imported. The web UI logs looked the following:

```
12/31/20, 3:51 PM INFO Consuming 20190122Z - corr1 - title1 - tax,work.pdf
12/31/20, 3:47 PM INFO Consuming 20180220Z - corr2 - title2.pdf
...
```

The docker logs then receilved the actual problem

```
15:58:05 [Q] ERROR Failed [20190122Z - corr1 - title1 - tax,work.pdf] - [Errno 2] No such file or directory: '/mnt/user/appdata/paperless-ng/data/pre': '/mnt/user/appdata/paperless-ng/data/pre' : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
override_tag_ids=override_tag_ids)
File "/usr/src/paperless/src/documents/consumer.py", line 119, in try_consume_file
logging_group=self.logging_group
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in send
for receiver in self._live_receivers(sender)
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
for receiver in self._live_receivers(sender)
File "/usr/src/paperless/src/documents/signals/handlers.py", line 155, in run_pre_consume_script
Popen((settings.PRE_CONSUME_SCRIPT, filename)).wait()
File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/user/appdata/paperless-ng/data/pre': '/mnt/user/appdata/paperless-ng/data/pre'
```

It worked fine after I fixed the path. However, I have the following questions:

* Is it intended that the web UI logs do not tell that there is a problem with the consumption?
* Should the consumption be blocked when those scripts are not existing, but configured?

**Comment by jonaswinkler** [comment]
> While I reconfigured my paperless-ng instance I wrongly linked the pre and post hooks to a host path instead of a mapped container path. Today I tried to import new documents and and it occurred to me that those documents were not imported. The web UI logs looked the following:
> 
> ```
> 12/31/20, 3:51 PM INFO Consuming 20190122Z - corr1 - title1 - tax,work.pdf
> 12/31/20, 3:47 PM INFO Consuming 20180220Z - corr2 - title2.pdf
> ...
> ```
> 
> The docker logs then receilved the actual problem
> 
> ```
> 15:58:05 [Q] ERROR Failed [20190122Z - corr1 - title1 - tax,work.pdf] - [Errno 2] No such file or directory: '/mnt/user/appdata/paperless-ng/data/pre': '/mnt/user/appdata/paperless-ng/data/pre' : Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
> res = f(*task["args"], **task["kwargs"])
> File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
> override_tag_ids=override_tag_ids)
> File "/usr/src/paperless/src/documents/consumer.py", line 119, in try_consume_file
> logging_group=self.logging_group
> File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in send
> for receiver in self._live_receivers(sender)
> File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
> for receiver in self._live_receivers(sender)
> File "/usr/src/paperless/src/documents/signals/handlers.py", line 155, in run_pre_consume_script
> Popen((settings.PRE_CONSUME_SCRIPT, filename)).wait()
> File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
> restore_signals, start_new_session)
> File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/mnt/user/appdata/paperless-ng/data/pre': '/mnt/user/appdata/paperless-ng/data/pre'
> ```
> 
> It worked fine after I fixed the path. However, I have the following questions:
> 
> * Is it intended that the web UI logs do not tell that there is a problem with the consumption?

When something silently fails, it is, in almost all cases, not intended. I'll add some error messages and proper exception handling.

> * Should the consumption be blocked when those scripts are not existing, but configured?

Not sure about this. I think it should fail.

**Comment by jonaswinkler** [comment]
On a side note, since I'm doing this right now:

Should the pre-consume script be able to cancel consumption by returning a non-zero exit code?

**Comment by Tooa** [comment]
> Should the pre-consume script be able to cancel consumption by returning a non-zero exit code?

Sounds interesting, but I can't imaging a use case right now. Personally, I use these scripts to execute web hooks in order to check via home assistant whether the processing failed for uploaded documents. Thereby, I receive notifications about the import status. Finally, I only throw away physical documents with a successful import message.

I'm tented to not implement features when there is no user request. So, either we just implement it or we open a feature request and see if people comment on it and describe their use case for that feature. I leave that decision to you.

**Comment by jonaswinkler** [comment]
Alright, I'll not change that then
