### ISSUE TITLE
Installation instructions for Docker don't work

### ISSUE THREAD

**Issue by oregonpillow** [jonaswinkler/paperless-ng#237]
Hi,
followed the docker-route instructions as written.

Get this error:
"Step 5/17 : COPY docker/imagemagick-policy.xml /etc/ImageMagick-6/policy.xml"

I'm new to docker. Is this a problem within the image or on the host?

**Comment by jonaswinkler** [comment]
This is not an error message.

**Comment by jonaswinkler** [comment]
If the build fails at this step, there should be an actual error message.

Some steps may take a while, depending on hardware.

Based on this, I don't really know how to help you. Please provide more details and something that actually goes wrong. Feel free to reopen if the issue persists.
