### ISSUE TITLE
paperless.wsgi missing?

### ISSUE THREAD

**Issue by doodlemania2** [jonaswinkler/paperless-ng#247]
New here :) Hi! Is it possible the current release is missing the paperless.wsgi in the src folder or am I just not seeing it where I thought it should be?

**Comment by jonaswinkler** [comment]
`paperless.wsgi` is not a file. That's just the application name you need to hand to your wsgi-enabled web server.

**Comment by doodlemania2** [comment]
well i feel stupid :) thanks
