### ISSUE TITLE
Mass-Import via Consumer -> Assign ASN from Title or 6-digit-number from document

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#252]
Just started using paperless-ng coming from Devonthink Pro Office (Using for 5+ years!). When i import my documents from Devonthink via Consumer i would like to set the ASN from the filename, better by lookup a 6-digit-number with leading zeros in the document. Is this somehow possible?

I am running paperless-ng in Docker.

Thank you for this software.

**Comment by jonaswinkler** [comment]
No, that's not possible at this point.

**Comment by andbez** [comment]
Ok. Thank you. How about updating the Database for my Mass-Import? As far as i can see, the ASN is stored in the table documents_document in the field "archive_serial_number". I am a professional database developer and if there are no more dependencies to the ASN-Field i would like to update the field.

**Comment by jonaswinkler** [comment]
Sure, just extract your 6-digit number from the title and store it there, no issues with that! There's no caching, except for what the DB does by itself.

**Comment by andbez** [comment]
Hi,
just in case somebody has a similar problem. My Solution for setting ASN from Title (i tested it and it worked on Postgres-Server ;-)):
Connect To paperless-Database 

First Create a helper function on the database (found it on the internet!):
 
`create function isnumeric(text) returns boolean
    immutable
    language plpgsql
as $$
begin
    if $1 is not null then
     return (select $1 ~ '^(([-+]?[0-9]+(\.[0-9]+)?)|([-+]?\.[0-9]+))$');
    else
     return false;
    end if;
end;
$$
;`


Update Rows with Tag = Devonthink and Title = Numeric and  empty ASN:

`update public.documents_document udd
SET archive_serial_number = cast(dd.title as int)
FROM public.documents_document dd
left join public.documents_document_tags dt 
	on dt.document_id = dd.id
left join public.documents_tag dtag
	on dtag.id  = dt.tag_id 
where isnumeric(dd.title)
	and dtag."name" = 'Devonthink'
	and dd.archive_serial_number is null
	and udd.id = dd.id;
`
