### ISSUE TITLE
Pre-Hook Paperless in Docker: Python-Script to split PDF-File by Separation-Page

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#253]
I am interested in developing (there are some sources on the internet) a python-script to split PDF-Files in the Consumer-Directory by Separation-Pages (e.g. special QR Codes). To achieve this, i need some python-dependencies in the Docker-Image. What would be the best way to handle this dependencies? Adding pip-Statements in the docker-compose.yml?

Thank you.

**Comment by jonaswinkler** [comment]
Hi!

Once files are in the consumption directory, paperless discovers them and starts adding them to the database. Therefore, you should not modify files once they are there.

Your best approach is to run your script on files outside the consumption directory and moving the separated files into the consumption directory afterwards. This way, you don't have to modify the image at all.

**Comment by andbez** [comment]
So i understand: When i put a file into the consumer-dir, paperless starts working with the file and the Pre-Hook-Script can only adjust the file but not the filename, correct?
I thought first to solve the problem outside of paperless. But i often read that people (and myself) like to scan just a pile of paper and the software splits the scan into several pdf-files. It would also be possible to use special separation-pages for several document-types (in paperless-speech ;-)). This is the reason for asking. Then i will develop a solution outside of paperless (but with paperless in mind ;-)).
