### ISSUE TITLE
Post-Hook - How to set ASN

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#259]
Every scanned Document which is archived as paper get's a Number (Always 6-digits, the first 2 Digits are a long time 0 ;-)). This would be in the File-Content after Consumption and OCR by Paperless. Now i would like to extract the number by RegEx 00\d{4} and setting the ASN of the consumed document. I did not find any solution using the manage.py Script.
Any Idea how to handle this? Is it possible to use a self developed SQL-Statement? 

Thx.

**Comment by jonaswinkler** [comment]
You could set up a post-consume script: https://paperless-ng.readthedocs.io/en/latest/advanced_usage.html#post-consumption-script

This receives the ID of the newly created document. That's all you need to connect to your database, get the document's content, do some regex matching on the content, and update the `archive_serial_number` field.

However, you'd have to wait for the next version for that. Currenctly, the script is called during a database transaction, not after, so the document won't be there yet by the time it is called. (Has been that for years in paperless, wonder why noone noticed)

**Comment by andbez** [comment]
Thank you (again ;-). The link you posted links to what i mean with post-hook. But i have to handle the DB-Connection by myself and there is no support by paperless-ng? i also have basic knowledge of python (i prefer to use python for this kind of solution), but there is no paperless-django-module which i can use for this? I only just need to send one sql-statement. Any hint is appreciated.

**Comment by jonaswinkler** [comment]
There's no support in paperless for this. If you want to modify the source directly, I can give you some directions where to make these changes.

**Comment by andbez** [comment]
Can you point me where to find Database-Settings (URL, Database, User, Password) in the Docker-Container? When i like to connect to the database i think it is better to use this information instead of hardcoding.

**Comment by jonaswinkler** [comment]
These settings should be available as environment variables, as specified in the docker-compose.env file / in the environment section of the docker-compose.yml file.

**Comment by andbez** [comment]
That's what i hoped for but unfortunately not:
root@3b15426806a8:/usr/src/paperless/src/paperless# export
declare -x GPG_KEY="0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D"
declare -x HOME="/root"
declare -x HOSTNAME="3b15426806a8"
declare -x LANG="C.UTF-8"
declare -x OLDPWD="/usr/src/paperless/src/paperless/static"
declare -x PAPERLESS_DBHOST="db"
declare -x PAPERLESS_OCR_LANGUAGE="deu"
declare -x PAPERLESS_REDIS="redis://192.168.4.20:6379"
declare -x PAPERLESS_TIKA_ENABLED="1"
declare -x PAPERLESS_TIKA_ENDPOINT="http://192.168.4.24:9998"
declare -x PAPERLESS_TIKA_GOTENBERG_ENDPOINT="http://192.168.4.25:3000"
declare -x PAPERLESS_TIME_ZONE="Europe/Berlin"
declare -x PATH="/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/usr/src/paperless/src/paperless"
declare -x PYTHON_GET_PIP_SHA256="6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c"
declare -x PYTHON_GET_PIP_URL="https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py"
declare -x PYTHON_PIP_VERSION="20.2.4"
declare -x PYTHON_VERSION="3.7.9"
declare -x SHLVL="1"
declare -x TERM="xterm"
declare -x USERMAP_GID="1001"
declare -x USERMAP_UID="1007".

**Comment by jonaswinkler** [comment]
Oh, right.

`PAPERLESS_DBHOST` is set, and is the hostname of the database server.

Database name, username and password all default to `paperless` if not specified otherwise as per

https://github.com/jonaswinkler/paperless-ng/blob/master/src/paperless/settings.py#L253

**Comment by andbez** [comment]
So, when the environment variable is not set, it is the default, otherwise i will find a given environment variable.

**Comment by jonaswinkler** [comment]
Yes.

**Comment by andbez** [comment]
I am finished with the post-hook-script. Unfortunately the script is not called or there are permission problems.
Setup:
Post-Hook-Script in Subdir from consume -> /usr/src/paperless/consume/post-hook
1. I can run the script within the docker-container with root- and paperless-user -> Works
2. I tried to call by the Env-Variable PAPERLESS_POST_CONSUME_SCRIPT pyhton3 /usr/src/paperless/consume/post-hook -> Na Call (no information about the call of the script in the Log-Files)
3. i put the call in a bash-script, set chmod a+x and to the paperless-user in docker. Exec the bash in Docker stops with 
paperless@bc121151aab5:~/consume/post-hook$ ls -la
total 36
drwxr-sr-x 2 paperless paperless  4096 Jan 12 13:57 .
drwxrwsrwx 3 paperless paperless 24576 Jan 12 13:54 ..
-rw-r--r-- 1 paperless paperless  3838 Jan 12 13:53 asn.py
-rwxr-xr-x 1 paperless paperless   326 Jan 12 13:57 asn.sh
paperless@bc121151aab5:~/consume/post-hook$ ./asn.sh
bash: ./asn.sh: Permission denied
paperless@bc121151aab5:~/consume/post-hook$ python3 asn.py 2423 2 3 4 5 6 7 8
ASN nach Content : -1 
-1 
Connection closed!

Questions:
1. Is there a Log-Entry, when the Post-Consume-Script is executed?
2. What about permissions?
3. Can i use the first ENV-Call (python3 asn.py) and the Arguments are supplied by paperless?

**Comment by andbez** [comment]
Ok. Worked it out. The Filesystem, where the script resides was mounted with noexec! This is the reason, why the bash-script gets "Permission denied". I bind a new folder to the docker-container, which is mounted "exec". Now the script is executed. Information regarding this issue is found only in the docker-logs. Now there are only remain my questions 3 and 4.

**Comment by jonaswinkler** [comment]
3. No, the post consume script is expected to be a file. However, you can
  - chmod +x the python script
  - add `#!/usr/bin/python3` to the first line
  - provide an absolute or relative (starting with `./`) path to the python file to paperless.
4. Yes.

**Comment by andbez** [comment]
Finished. Everythink works. My first post-hook-script. It tries to extract a 6-digit number from the title and content of the document. If it finds a matching number and it is not used already by any other document it writes it to the ASN-Field in the database (currently only postgresql is supported). If somebody is interested, i can provide the file. May be it can be find a repository to provide such hook-scripts. Thx for your support.
