### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by TKroenert** [jonaswinkler/paperless-ng#263]
$ docker-compose up -d 
ERROR: Service 'webserver' failed to build: COPY failed: stat /share/lib/docker/tmp/docker-builder1234567/requirements.txt: no such file or directory

https://github.com/jonaswinkler/paperless-ng/blob/70cb27bf0a04eab157bc1d91d7084f1a29a6bbc3/docker/local/Dockerfile#L5

how to proceed?
A) $ wget https://github.com/the-paperless-project/paperless/blob/master/requirements.txt
B) $ mv Pipfile requirements.txt
C) $ sed 's/requirements.txt/Pipfile/g' Dockerfile

**Comment by jonaswinkler** [comment]
Please download the release archive. This has everything where it should be.

**Comment by TKroenert** [comment]
>Do not to pull the entire git repository.
Overread that warning - my bad.

I have now grabed the release archive for docker-compose and it works. TOP!

**Comment by jonaswinkler** [comment]
I'm working on making all that a little bit more straight forward to use.
