### ISSUE TITLE
Clear all filters does not reset saved view filter

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#267]
The `clear all filters` control does not reset the saved view selection.

## Steps to reproduce

* Create a saved view `Inbox` that filters for documents with the tag `inbox`
* Click on the saved view `Inbox`
* Click on the control `Clear all filters`
* Click on the saved view `Inbox`

## Expected behaviour 

* The view filters documents that have the tag `inbox` assigned

## Actual behaviour 

* Nothing happens

## Issue type

* cosmetic, minor, annoying

## Details

* Docker installation
* Version 0.9.11

**Comment by jonaswinkler** [comment]
Should the "clear all filters" control reset the filters on saved views to the saved state instead of clearing them entirely? I'd rename that to "reset filters" then.

Clicking on an already active menu item does not fire any event I can listen for, as far as I know.

**Comment by Tooa** [comment]
> Should the "clear all filters" control reset the filters on saved views to the saved state instead of clearing them entirely? I'd rename that to "reset filters" then.

Yeah, that would be better than the current mechanism since the menu is still active after applying "clear all filters". Would you rename the control in the document view too?

**Comment by jonaswinkler** [comment]
> Would you rename the control in the document view too?

If you're referring to the "Clear all filters" control, yes, that's what I was referring to.

**Comment by shamoon** [comment]
So it would be like: if viewing a saved view "Clear filters" becomes "Reset", if youre in the general document view it stays "Clear".

I can take a look at this one @jonaswinkler , if you'd like.

**Comment by jonaswinkler** [comment]
I'd name it reset on both. Since the default on the document list is to show all documents, it will be quite clear that reset clears all filters there.

Sure, go at it.
