### ISSUE TITLE
Add ASN filter

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#268]
With version `0.9.9` and the implementation of 

> New select interface for tags, types and correspondents allows filtering. This also improves tag selection.

I cannot filter for documents with assigned ASN any more. Previously, there was a `has ASN` filter. My workaround is to use `Sort by ASN`.

**Comment by jonaswinkler** [comment]
I'll figure out a way to add that into the new editor.

**Comment by Tooa** [comment]
If this overloads the interface and makes it more troublesome for mobile I would rather live without that feature. I started to import documents with an ASN and was checking if I could filter somehow by ASN. I think one can also find those physical documents by combining other filters. Thanks for taking a look.

**Comment by jonaswinkler** [comment]
Btw, there never was a "has ASN" filter to begin with, just a "ASN is <number>", which wasn't particularly useful anyway.

**Comment by Tooa** [comment]
> Btw, there never was a "has ASN" filter to begin with, just a "ASN is <number>", which wasn't particularly useful anyway.

Yes, you are right. Should we postpone this feature then until there is more demand? What do you think?

**Comment by tedtms** [comment]
I just came here to see if this had already been suggested -- it would be great to have this feature!

For the moment, I've created an "asn" tag that I apply to all my documents with ASNs, which I then turned into a view. But it would be nice to see ASN filtering support at a deeper level.

**Comment by jonaswinkler** [comment]
Alright. Suggestion on how to add that to the existing interface?

**Comment by tedtms** [comment]
If you mean placement and UX, I think it would be good to add as another filter button alongside the tag, document type, etc filters. It could probably just be a checkbox, on or off. The title filter could be shrunk a little to accommodate.

**Comment by Tooa** [comment]
Another way could be a hard-coded predefined view called ASN showing all documents with an ASN. Then we don't need an additional filter control.

To find a specific ASN one has to click still on each document. Would it make sense when the view shows the ASN similar to tags? Or do we need a find document by ASN?

**Comment by jonaswinkler** [comment]
> To find a specific ASN one has to click still on each document. Would it make sense when the view shows the ASN similar to tags then? Or do we need a find document by ASN?

Large cards and the table view already have that. The small cards are just very cramped and I'm not sure where to put that.

> Another way could be a hard-coded predefined view called ASN showing all documents with an ASN. Then we don't need an additional filter control.

Some users don't use this at all, I don't think adding a permanent unused menu item for those is a good idea.

**Comment by shamoon** [comment]
A couple thoughts:

1.  Adding a checkbox for "has ASN" to the `FilterEditor`
2. We could add some kind of icon / image or something and have the ASN show only on hover, like a tooltip (Bootstrap has these built in).

Both of these ideas may have some challenges in terms of finding the [right] place for them. I'm happy to look at these JW, if you'd like.

**Comment by jonaswinkler** [comment]
1. I also thought about an additional dropdown "More filters" / "Misc" or similar, and have that in there. However, apart from maybe a filetype filter I can't think of anything else to put there.
2. I tried adding that in (# 123) brackets after the title on small cards, and this works pretty well.

**Comment by shamoon** [comment]
Yea Ive thought about a "More" too but agreed not sure what else would go there, still might work to keep things less cluttered. 

I also thought about something like an "advanced" editor which would look more like the old editor with individual rules, but so much has changed that would be a lot to implement (and I think our suspicion is that the current filterEditor will satisfy vast majority of users' needs)
