### ISSUE TITLE
Unraid docker not uploading anything

### ISSUE THREAD

**Issue by bpivk** [jonaswinkler/paperless-ng#269]
So here goes...

I have tried setting up a docker on my server and I can't upload any files. I have tried TXT and PDF files and all I get is "An error has occurred while uploading the document. Sorry!".

I have checked the logs and they are empty. The only error is "redis.exceptions.ConnectionError: Error -2 connecting to ip:6379. Name or service not known." as I haven't bothered to set redis yet as the base upload is not working.

**Comment by jonaswinkler** [comment]
Redis is required by the back end to pass messages from the web server to the task processing queue. These run in different processes and redis acts as a mediator. That's exactly why you're getting that error.

**Comment by bpivk** [comment]
Great. I was under the assumption that it would work without it for documents uploaded through the web portal. I'll set up redis and see if it clears the problem.

**Comment by Tooa** [comment]
@bpivk In case you missed it, we have a support thread for the paperless-ng Unraid template over [here](https://forums.unraid.net/topic/100843-support-paperless-ng-docker/). Redis as a required service is mentioned there too. Feel free to post questions about paperless-ng regarding Unraid over there.

**Comment by jonaswinkler** [comment]
Please close if this issue is resolved.

**Comment by bpivk** [comment]
> @bpivk In case you missed it, we have a support thread for the paperless-ng Unraid template over [here](https://forums.unraid.net/topic/100843-support-paperless-ng-docker/). Redis as a required service is mentioned there too. Feel free to post questions about paperless-ng regarding Unraid over there.

I didn't miss it. I have read through everything including that page and the wiki and it was only mentioned that it's needed to parse the folders. Or at least that's how I understood.
