### ISSUE TITLE
Permanent data (such as saved views) should be saved on the server.

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#27]

**Comment by jonaswinkler** [comment]
Also, settings!

**Comment by totti4ever** [comment]
The more I use this app, the more I am missing this feature! Obviously especially the views are always "lost", when working on different devices for instance.

**Comment by jonaswinkler** [comment]
This requires new database tables, new API endpoints, and access to these settings isn't as straight forward as your browsers local storage (which is dead simple to implement). I am aware of the issue, but will postpone this for now.

**Comment by jonaswinkler** [comment]
See #101
