### ISSUE TITLE
Dark mode issues

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#276]
I've found some more issues with dark mode.

![image](https://user-images.githubusercontent.com/17569239/103571442-28840380-4ecb-11eb-8e7a-2b36fec7fe07.png)

No red border on dark mode:

![image](https://user-images.githubusercontent.com/17569239/103571487-3e91c400-4ecb-11eb-9eea-d5faf450ce3f.png)

Sortable directive:

![image](https://user-images.githubusercontent.com/17569239/103571547-61bc7380-4ecb-11eb-9c25-71999045d43f.png)

Search errors (uses bootstrap alerts) could use some dark theming as well:

![image](https://user-images.githubusercontent.com/17569239/103571752-c081ed00-4ecb-11eb-8fcd-1e6ca5e56767.png)

All delete buttons are red, just not the one on the saved views settings page:

![image](https://user-images.githubusercontent.com/17569239/103572332-ad235180-4ecc-11eb-8617-9be761f76e5d.png)

@shamoon could you have a look at these?

**Comment by shamoon** [comment]
Sure thing, will do 👍🏼
