### ISSUE TITLE
Suggestion: "Save and Next" - Focus Cursor to Title-Field

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#278]
When editing Inbox-Documents i try to use the keyboard only. When i edit a document and click "Save and Next" the Focus stays on the Button. So i have to jump back with Tab-Key to the fields i like to edit. I think it is nicer for to workflow to focus the cursor on Title (first field on Top).

What do you think?

**Comment by jonaswinkler** [comment]
agreed, and should be an easy fix.
