### ISSUE TITLE
add yunohost app

### ISSUE THREAD

**Issue by Aaaamu** [jonaswinkler/paperless-ng#288]
[https://github.com/the-paperless-project/paperless/issues/707#issue-731707796](https://github.com/the-paperless-project/paperless/issues/707#issue-731707796)

**Comment by jonaswinkler** [comment]
You're free to package paperless as an application over there.

There are simply too many ways to deploy linux applications these days an I cannot possibly support them all. I've chosen to support bare metal and docker installations, and that's about it.
