### ISSUE TITLE
Doc Edit Mode: AutoFill fails, when correspondent includes "&" 

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#292]
In Doc Edit Mode i start in the field correspondent typing and as soon i input "&" the suggestions are empty (e.g. the correspondent is 1&1 Internet AG and i start typing 1& -> No more suggestions). 

Also the selection by cursor-keys (up/down) does not work, when hitting an input field first time.

**Comment by jonaswinkler** [comment]
What browser?

I can't reproduce any of that.

- When I type a "&" in the box, it brings up all the correspondents with "&" in their names.
- When I tab through the input fields and stop on the correspondent drop down, pressing down on the keyboard brings up the drop down menu and selection with up/down is possible.

**Comment by shamoon** [comment]
Yea I cant reproduce either, works as expected for me. But it does point out a tiny issue with keyboard navigation in the dark theme, will add to #289 =)

**Comment by andbez** [comment]
I tested with Opera dev, Chrome and Safari. Always the same problem. Please have a look at the attached Screenshots. May be a setting from my environment in Docker for Database or similar? Also you can hardly (or not) see the selected entry in the drop down list in dark mode. I think thats , what shamoon already addressed?

<img width="172" alt="Bildschirmfoto 2021-01-08 um 23 24 12" src="https://user-images.githubusercontent.com/63553946/104071133-cbf55100-5208-11eb-8be2-b689dc038931.png">
<img width="136" alt="Bildschirmfoto 2021-01-08 um 23 24 23" src="https://user-images.githubusercontent.com/63553946/104071132-cb5cba80-5208-11eb-98b4-785f202e9e81.png">

**Comment by shamoon** [comment]
Weird, see attached, wonder if its an encoding issue. Yes I addressed the dark mode highlighting in that PR.
<img width="216" alt="Screen Shot 2021-01-08 at 10 10 18 PM" src="https://user-images.githubusercontent.com/4887959/104084722-6e5c0700-51fe-11eb-97e4-c6fb46fdc6e6.png">
<img width="202" alt="Screen Shot 2021-01-08 at 10 10 24 PM" src="https://user-images.githubusercontent.com/4887959/104084724-6ef49d80-51fe-11eb-983a-68479c9501a0.png">
<img width="131" alt="Screen Shot 2021-01-08 at 10 10 38 PM" src="https://user-images.githubusercontent.com/4887959/104084725-6ef49d80-51fe-11eb-92b5-7d9e348ce154.png">
