### ISSUE TITLE
Giant logo under firefox

### ISSUE THREAD

**Issue by Philmo67** [jonaswinkler/paperless-ng#293]
Under firefox (latest version, cache cleared), the Paperless logo on the dashboard under the welcome message takes the whole width of the frame (at least for me).
Can you reproduce ? Do you need more infos ?

**Comment by shamoon** [comment]
Sounds like an svg  thing, I’ll take a look once I’m back in front of my computer

**Comment by jonaswinkler** [comment]
Screenshot would be nice!

![image](https://user-images.githubusercontent.com/17569239/104048926-524b6c00-51e4-11eb-8f5e-7f07b58b4ddf.png)

Might be related.

**Comment by Philmo67** [comment]
![firefox_rspGW4NyON](https://user-images.githubusercontent.com/16903094/104049782-d2be9c80-51e5-11eb-9a68-84b5f8381d96.png)

**Comment by shamoon** [comment]
Yea, Firefox can be odd with svgs & flex. Will make sure to test in FF more in the future.
Submitted a PR, simple fix.

**Comment by BeecherNetworks** [comment]
Firefox on Android has a similar problem with the top-left logo, attached. Note that this is Fennec, I haven't upgraded to Fenix yet, and would prefer to avoid it for the foreseeable.

![Screenshot_20210323-162840_Firefox](https://user-images.githubusercontent.com/179583/112182812-889a6400-8bf5-11eb-9422-b4db5e93c89c.png)

**Comment by shamoon** [comment]
Hmm, am I correct in understanding that Fennec is an older (outdated?) version of FF for Android? I dont have the ability to test this, not sure if others do. Also, that svg has an explicit width set `1rem` so Im surprised by the behavior

**Comment by BeecherNetworks** [comment]
Yes. Fenix is the current version, with the address bar at the bottom and the restricted set of addons. Fennec is the previous version that still supports the older addons, which is why I (and many others) don't want to upgrade. It's available from F-Droid, [version 68.11](https://www.apkmirror.com/apk/mozilla/fennec-f-droid/fennec-f-droid-68-11-0-release/) is the last one. I would of course understand if you didn't have time to debug this, but in that case perhaps you could give me a pointer where to look? I'm ok with HTML & CSS, although I'm not very au fair with SVG! :)

**Comment by shamoon** [comment]
I would mess with the width / height either directly on the svg (you only need to specify one, which is how it is now, width only) or in CSS. Of course if could have nothing to do with that but that’s my guess. Let us know if you figure it out

**Comment by BeecherNetworks** [comment]
Thanks @shamoon. Will do, would you have a rough pointer where to start looking in the filesystem? I'm running in Docker.

**Comment by shamoon** [comment]
Actually I may have coincidentally just found the issue. I cant actually test this but here's the PR: #819 , found this bug report: See https://bugzilla.mozilla.org/show_bug.cgi?id=1231147 which may be relevant
