### ISSUE TITLE
Tika parser does not pick up files from the consumption directory

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#300]
It seems, the consumer does not consume xlsx-Files (Excel-Spreadsheet OOXML). XLS-Files/docx-Files are consumed. 
Log: Not consuming file /usr/src/paperless/src/../consume/2009 - Analyse - Telekommunikation.xlsx: Unknown file extension.

**Comment by jonaswinkler** [comment]
Strange. The xlsx files I've tested this with are getting processed just fine. You did set the three configuration variables, right?

**Comment by andbez** [comment]
As documented:
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://192.168.4.25:3000
      PAPERLESS_TIKA_ENDPOINT: http://192.168.4.24:9998

I am using an external VLAN-Network in Docker. Thats the reason for the ip-Addresses. But as i mentioned, xls and docx are working perfect for consuming.

**Comment by jonaswinkler** [comment]
If you come across a file that does not work and does not contain any confidential information, I'd be interested in that.

**Comment by jonaswinkler** [comment]
Could you please confirm that web upload works?

**Comment by andbez** [comment]
Yes, i can confirm that web upload works!

09.01.21, 14:18 INFO Document 2008-12-29 2009 - Analyse - Telekommunikation consumption finished
09.01.21, 14:18 INFO Consuming 2009 - Analyse - Telekommunikation.xlsx
