### ISSUE TITLE
Instructions on how to build release archive

### ISSUE THREAD

**Issue by C0nsultant** [jonaswinkler/paperless-ng#304]
As a potential follow-up to #171 , I have been experimenting with building the whole NG package from source. For testing ansible deployment that includes changes from PRs, this is mandatory (otherwise, only building from published archives is possible, defeating the purpose of triggering it by a PR).
 So far, I have not managed to reproduce it successfully once :disappointed:.

The process for creating any `paperless-ng-X.Y.Z.tar.xz` involves running `scripts/make-release.sh X.Y.Z` as far as I can tell. What are prerequisites for this? System, dependencies, env variables?

**Comment by jonaswinkler** [comment]
- dependencies from pipenv, +dev
- npm
- all runtime dependencies for executing tests
- docker

However, once #178 is done, making that archive will change quite a lot, so I wouldn't put too much effort into that yet. The resulting archive will stay the same.

**Comment by C0nsultant** [comment]
The main problems I am having are with pipenv.
The `Pipfile` and `.lock` are pinned to Python 3.6 (not directly available in ANY [debian](https://wiki.debian.org/Python) release). Maybe widen this requirement to the Python versions that are supported according to the [documentation](https://paperless-ng.readthedocs.io/en/latest/setup.html#bare-metal-route)?
Also, `pipenv install --dev` results in errors involving not finding packages on `piwheels`. Don't know why, but it seems like pipenv does not check `pypi` and instead defaults to `piwheels` on my systems :confused:.

**Comment by jonaswinkler** [comment]
> The `Pipfile` and `.lock` are pinned to Python 3.6 (not directly available in ANY [debian](https://wiki.debian.org/Python) release). Maybe widen this requirement to the Python versions that are supported according to the [documentation](https://paperless-ng.readthedocs.io/en/latest/setup.html#bare-metal-route)?

Yes, will do that.

> Also, `pipenv install --dev` results in errors involving not finding packages on `piwheels`. Don't know why, but it seems like pipenv does not check `pypi` and instead defaults to `piwheels` on my systems 😕.

Uh. Getting pipenv to cooperate with piwheels at all wasn't all that easy, I'll look into it again as well

**Comment by jonaswinkler** [comment]
Current plan is to build the release with github actions as well.

See here for a preview: https://github.com/jonaswinkler/paperless-ng/actions/runs/476158814.

I still need to check whether everything is where it should be.

The `release` action will create a `release` artifact that contains the compressed release and uploads that to the workflow. I believe this is what you need?

Within the same workflow, I'm able to download artifacts in other jobs as well. I'm not sure if its possible to depend on the release job in your `ansible.yml` action file and download the artifact there.

**Comment by jonaswinkler** [comment]
I believe that this is resolved with the CI workflow online.

Regarding `pipenv install --dev`: I have no idea how to approach this, sadly. Would you mind sharing the actual errors?

**Comment by C0nsultant** [comment]
> I believe that this is resolved with the CI workflow online.

Well it's resolved partially. For the ansible build in CI, it works. Simply pulling the built archive artifact is great.
But this again makes the build from source not reproducible without GitHub actions (or whichever CI will be used at X point in time). The idea behind this issue was to reproduce the archive from within ansible locally on a machine. Thanks to the [`ci.yml`](https://github.com/jonaswinkler/paperless-ng/blob/80aa8474578c062013d2775700f818bc3354227d/.github/workflows/ci.yml), I have managed to do so. Will create a PR for this including actual documentation for the ansible role over the next few days.

> Would you mind sharing the actual errors?

I honsestly can't reproduce the initial problem anymore. From memory, it was about no suitable verions of `pdftotext` and `pikepdf` being found. The problem may have been that `libpoppler-cpp-dev` was not installed when `pipenv install` was being run (newer versions of pipenv have improved error reporting significantly).
