### ISSUE TITLE
Dark mode issues

### ISSUE THREAD

**Issue by rYR79435** [jonaswinkler/paperless-ng#314]
Log-coloring is missing in dark mode

![2021-01-10-155523_917x1004_scrot](https://user-images.githubusercontent.com/60985157/104126618-edb41c80-535d-11eb-9a84-63b389101310.png)
![2021-01-10-155421_918x1003_scrot](https://user-images.githubusercontent.com/60985157/104126622-f0167680-535d-11eb-8b02-61e59621761d.png)

**Comment by shamoon** [comment]
Ah, thanks. I'll sort this out.
