### ISSUE TITLE
Consumer doesn't remove folders

### ISSUE THREAD

**Issue by rYR79435** [jonaswinkler/paperless-ng#316]
I have `PAPERLESS_CONSUMER_RECURSIVE` and `PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS` set to `true`.

Once the consumer finishes the empty folders remain:
![2021-01-10-155706_524x306_scrot](https://user-images.githubusercontent.com/60985157/104130267-04636f00-5370-11eb-86b1-855fb3dc7e58.png)

You can see in the first listing the folders have content while in the second listing, after the consumer has finished, they are empty.
(Screenshot was taken an hour after the consumer finished)

**Comment by Tooa** [comment]
I think this is expected. What made you think they will be removed?

Having those folders help to assign tags without remembering them.

**Comment by jonaswinkler** [comment]
The intended use case is to have reusable folders such as `todo` or `car`. This feature enables you to force certain tags on consumed documents.

**Comment by rYR79435** [comment]
Ok. I didn't see this use case.

**Comment by jonaswinkler** [comment]
I'll update the documentation.
