### ISSUE TITLE
Display document metadata in the UI

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#32]
such as PDF metadata (application, PDF version, author, creator, etc. Anything that's available.)

**Comment by totti4ever** [comment]
That's also a really great idea as I add some of those automatically using exiftool. Maybe a small _i_ icon? :-)

**Comment by rssfed23** [comment]
Further to this, if people are scanning documents as PDFs, it might be wise to give the configuration option to choose the PDF created date from exiftool as the document creation date, as this is likely to be more accurate than the auto detection (at least in my experience playing with paperless-NG today) :).

**Comment by jonaswinkler** [comment]
> choose the PDF created date from exiftool as the document creation date

The "created" dated in paperless isn't necessarily the date the PDF file was created. It's rather the date the actual document was created (i.e., the date of an invoice, the date a letter was written, the date a contract was signed). When scanning physical documents that already are quite old, the created-date in paperless and the created-date of the pdf document are quite different.

Or maybe I didn't quite get your idea.

**Comment by jonaswinkler** [comment]
> That's also a really great idea as I add some of those automatically using exiftool. Maybe a small _i_ icon? :-)

I'm thinking about tabs left to the document, with one tab for editable fields, and one tab for PDF metadata.

**Comment by totti4ever** [comment]
You think of vertical or horizontal tabs? Would have thought of horizontal.
Guess tabs could be the right way, indeed

**Comment by jonaswinkler** [comment]
![image](https://user-images.githubusercontent.com/17569239/101420665-f181f880-38f2-11eb-9ff9-1dcb252617d0.png)

Like this.

**Comment by shamoon** [comment]
Looks great. Looking forward to next release!

**Comment by totti4ever** [comment]
That look great indeed!

Any chance to also include the pdf-specific metadata like this?
<img src="https://user-images.githubusercontent.com/49901208/101445852-86e8b100-3922-11eb-8287-62e8b35589b2.png" height= 300 />

**Comment by jonaswinkler** [comment]
Paperless will report any metadata included in the documents.
