### ISSUE TITLE
Quotation marks in PAPERLESS_FILENAME_FORMAT cause malformed filenames

### ISSUE THREAD

**Issue by niarbx** [jonaswinkler/paperless-ng#324]
Hi Jonas,

I just tried to change the filename format by setting (in docker-compose.env)

`PAPERLESS_FILENAME_FORMAT="{created_year}/{correspondent}/{created_year}-{created_month}-{created_day} - {title}"`. 

Paperless does not complain and starts up as usual. I let paperelss consume a new file, which also works but results in the following filename

`/paperless/media/documents/originals/\"2009/CorespondentXYZ/2009-06-16\ -\ totallySecretDocument\".pdf`

So the variables work fine but paperless also interpretes the quotation marks as part of the filename.

Best regards
Tobi

**Comment by jonaswinkler** [comment]
Don't use quotation marks.

**Comment by jonaswinkler** [comment]
Don't use quotation marks.

**Comment by niarbx** [comment]
Hi Jonas,
ok this is strange. I will have another look. Luckily the file was just for testing and i could easily delete it. But thanks for the hint.

**Comment by jonaswinkler** [comment]
Paperless should still keep track of the correct file name, even if it contains quotes.

**Comment by jonaswinkler** [comment]
Is this resolved?
