### ISSUE TITLE
Add date display / time setting to user preferences

### ISSUE THREAD

**Issue by mvdkleijn** [jonaswinkler/paperless-ng#325]
**What**
Allow a user to determine how to display dates (and time).

**Why**
- Multiple users may be from different regions and are used to different formats; 12/01/2020 vs 01/12/2020 for example
- The system might use different region settings from what a user wants / needs

**Comment by jonaswinkler** [comment]
Paperless displays dates using the format associated with the current display language. For example, if the browser is configured to display pages in German, paperless will serve the front end in German, and use German formatting for dates. Same for all other supported languages. If a language is not supported, paperless will fall back to en-US for both the display language and date formats.

**Comment by jonaswinkler** [comment]
I'll look into this.

**Comment by d3wy** [comment]
Found this trying to identify why all the dates were 'wrong' in my new Paperless install today. After review of https://aruljohn.com/language.php I had adjusted my Firefox settings to have it only show en (it was showing en-US) however date picker/dates are still showing month/day/year. To the best of my understanding 'en' should match UK/Australia formatting of dd/mm/yy. I'm not entirely sure if I'm facing an error on my part or a bug or simply working as expected. But if there is further information I could gather to clarify I'd love to assist.

**Comment by shamoon** [comment]
Yes currently UI isnt so helpful in terms of date input / display. Changes in the works for 1.0,  #177 or another solution in progress

**Comment by SonicPotions** [comment]
I would also welcome a config option for this. I run an english system, but am from germany. I prefer english language but german date formats.

**Comment by SonicPotions** [comment]
btw. the date entry in document edit is still in the wrong format, even when the german localisation is active (MDY instead of DMY)

**Comment by jonaswinkler** [comment]
> btw. the date entry in document edit is still in the wrong format, even when the german localisation is active (MDY instead of DMY)

Yes, and getting this right is surprisingly hard.

![image](https://user-images.githubusercontent.com/17569239/104824820-a0501780-5855-11eb-8bed-c7e08daebd20.png)
