### ISSUE TITLE
Offer ISO 8601 date format as an option

### ISSUE THREAD

**Issue by mvdkleijn** [jonaswinkler/paperless-ng#326]
Unless users can / have set their preference, it would be nice to have the system display dates and times in a clearly defined standard such as https://en.wikipedia.org/wiki/ISO_8601

**Comment by jonaswinkler** [comment]
Are you referring to dates displayed in the front end?

**Comment by gajewsky** [comment]
@jonaswinkler  is it possbile to change date format displayed in front end? I was hoping that using setting european PAPERLESS_TIME_ZONE env will help, but it did not :(

**Comment by jonaswinkler** [comment]
Apart from changing the language of your browser to one of the supported languages, no.

**Comment by shamoon** [comment]
Maybe in a future release, see eg https://github.com/jonaswinkler/paperless-ng/pull/177#issuecomment-751137205

**Comment by jonaswinkler** [comment]
Closing this as it is pretty much part of #325.

Unless more users request this, paperless will continue to use a format that matches the current language.

I'm aware about the issues with the date input.

**Comment by stueja** [comment]
Chiming in to say: yes, I am also a big fan of ISO 8601. There should be an option to choose this format.

**Comment by jonaswinkler** [comment]
I've also read some comments in the survey that ISO-8601 is a must. I'll get to it!

**Comment by jonaswinkler** [comment]
Added in 1.1.4.

**Comment by stueja** [comment]
Maybe I am missing something. I already had 1.1.4, and I have just upgraded to 1.2.0. Still, I fail to see where I could set this up. In the settings, I only have the options English, German, Dutch, and French, and short, medium, long. Where is it hidden so that I cannot see it?

**Comment by jonaswinkler** [comment]
![image](https://user-images.githubusercontent.com/17569239/108885646-59013780-7608-11eb-88e5-f54373819010.png)

**Comment by stueja** [comment]
Thanks. Here's mine:

![2021-02-23 19_14_26-Clipboard](https://user-images.githubusercontent.com/9169222/108888225-7683d080-760b-11eb-80e6-0e111fb18007.png)

**Comment by shamoon** [comment]
Did you try clear browser cache? Front end can get cached even after version update (might explain #416 too)

**Comment by stueja** [comment]
I tried with 3 different browsers, even Edge, which I normally don't use, in InPrivate mode. In Firefox, which I mainly use, I deleted Cookies and website data. I reloaded using shift-ctrl-r. I had to re-login, but still the same version tag and languages.

**Comment by stueja** [comment]
Ah -- I might have found the culprit. Give me a moment, please.

**Comment by stueja** [comment]
No, still not working.

I thought (my) nginx instance was the problem. But even calling <host>:8000 without using (my) nginx will give me 1.1.0 and no ISO-8601 date. (Also with clearing cache etc.)

**Comment by stueja** [comment]
So. Got it. It was the `docker-compose.yml` file, which, after testing and migration from paperless, contained entries to statically served files. Deleted the entries, restarted the containers -- voilá. Sorry for the noise.
