### ISSUE TITLE
Inconsistent naming of paperless.conf between new and old releases

### ISSUE THREAD

**Issue by C0nsultant** [jonaswinkler/paperless-ng#330]
Nice to see that #151 is now complete!

In the current dev CI, `paperless.conf.example` files are copied *without* being renamed:
https://github.com/jonaswinkler/paperless-ng/blob/8f946074095817022df0d12e1673faed12c241a5/.github/workflows/ci.yml#L122'
In previous release builds, the file *was* renamed to `paperless.conf`:
https://github.com/jonaswinkler/paperless-ng/blob/a02ddeb7222fd822c7db139d6dc9d9eae2b439e6/scripts/make-release.sh#L80

Is the plan to actually ship the `.example` in the realease?

**Comment by jonaswinkler** [comment]
No, that's an oversight and I think shipping that file as paperless.conf is better.
