### ISSUE TITLE
Keep losing the gui while consuming multiple files

### ISSUE THREAD

**Issue by mannp** [jonaswinkler/paperless-ng#332]
Have things running quite well at the moment except I keep losing the gui while consuming documents.

Consuming 1 or 2 files seems fine with no ill effects, but 10+ docs seems to bork the gui while consuming continues according to the docker log.

No obvious errors in the log to say that the gui has gone down though.

Currently have PAPERLESS_TASK_WORKERS set at 4 and PAPERLESS_THREADS_PER_WORKER set at 2.

I previously had them at 2 and 1 respectively but its hard to tell what effect they are having based on the log. 

Otherwise the standard setting in the Unraid template.

Any ideas on the best way of tracking this down?

Thanks in advance.

**Comment by jonaswinkler** [comment]
When consuming that many documents in parallel, could you open something like `htop` and see how much CPU resources are used?

**Comment by mannp** [comment]
Oh wow, qcluster 100%, qs -dbatch 100% overall server at 92% of 32g memory and 4 of the 8 cores maxed.

Pretty obvious now, but I guess how to configure to allow consume sensible resources without taking the rest of the system down :)

PAPERLESS_TASK_WORKERS set at 1 and PAPERLESS_THREADS_PER_WORKER at 1 too?

**Comment by jonaswinkler** [comment]
> PAPERLESS_TASK_WORKERS set at 1 and PAPERLESS_THREADS_PER_WORKER at 1 too?

That should slow down consumption and leave resources free. However, as long as the product of WORKERS and THREADS is not greater than your total cpu count, the UI should still respond, at least. I've got a 16 core machine over here, and the web UI remains responsive even when it's completely busy with consumption tasks.

> Shouldn't paperless-ng ensure the consume task does not take down the other tasks?

Yes, and I thought I did that by providing sensible defaults for these two variables, based on the number of cpu cores in the system. Are you able to run python on that machine? Could you do

```
$ python3
>>> import multiprocessing
>>> multiprocessing.cpu_count()
```

and verify that this matches your actual CPU core count?

> Are there some other intensive tasks going on at the start of consuming that then drop off?

The consumption process for a single file is as follows:

1. Read PDF 
2. Start OCRmyPDF, which will use up to PAPERLESS_THREADS_PER_WORKER parallel tasks to process multiple pages in parallel
3. When that's done, convert the first page of the PDF to a thumbnail, which uses a single core.
4. Save document

And this is performed in parallel for multiple documents as well (up to PAPERLESS_TASK_WORKERS).

**Comment by mannp** [comment]
> >>> import multiprocessing
>>> multiprocessing.cpu_count()
8
>>> 

This is what the paperless-ng docker is reporting, as I don't have python3 installed on Unraid.

**Comment by jonaswinkler** [comment]
For 8 cores, its 4 workers with 2 threads each by default.

Actually, I'll adjust that so that at least one core will remain free, no matter what the CPU core count is.

**Comment by mannp** [comment]
I've adjusted my settings to your new default and will give this a try today.

Will close and reopen if the issue isn't resolved.

Thanks.

**Comment by mannp** [comment]
This one hasn't gone away for me, even with the revised worker settings, my gui keeps randomly stopping...only a docker restart get it back again.

**Comment by jonaswinkler** [comment]
Uhm, well; I don't exactly know how to help here. I've got three different machines here, and all of them remain reasonably responsive even under full load. Except for the Pi 3, but that's to be expected. They all also don't ever come even close to using all available memory.

What's your setup?

**Comment by jonaswinkler** [comment]
Not enough input on this one.

**Comment by mannp** [comment]
> Not enough input on this one.

Fair enough, can't get to the bottom of it :)
