### ISSUE TITLE
Tag relations and browsing via Tag

### ISSUE THREAD

**Issue by shrippen** [jonaswinkler/paperless-ng#333]
Hello,

I recently looked out for a DMS for my freelancer documents and stumbled upon this and other solutions. Sofar paperless-ng looks to be my favorite due to the workflow of dropping the files from the scanner into a folder and paperless sorts the rest.

But Teedy has two features that would benefit paperless.

1st - Tag Trees. So for example I have different companies I work for. I could tag an document as "Company 1", another as "Company 2". Both tags are grouped into another tag called "Companies". If I open up the tag "Companies" i see the documents related to "Company 1" and "Company 2".

2nd - Browsing via tag tree. Teedy shows me a folder like structure where I can select tags in the tree to navigate documents.

Thank you for your energy and time!

**Comment by jonaswinkler** [comment]
See #56.

This has been requested multiple times and it's on the road map!

I'm currently trying to get to a stable 1.0 release, fix the issues as they pop up, and get the continuous integration/deployment process ironed out. After that, more time for new features, and nested tags are pretty high on the list.

I'm also considering to run a survey and include a question about what features you'd like to see next; This way, I would get a better idea about what to focus on.
