### ISSUE TITLE
Fetch Mails

### ISSUE THREAD

**Issue by alucard856** [jonaswinkler/paperless-ng#334]
Hey,

If I try to fetch mails I get this error message. If I try to access via Thunderbird everything works.

Mailaccount Config:

SSL via 993 (Tested with STARTTLS via 143 same issue)
Password no special character

Mailserver Config:

Dovecot
min TLS 1.2
Certificate Let's Encrypt

> python3 manage.py mail_fetcher
> Traceback (most recent call last):
>   File "manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/usr/src/paperless/src/paperless_mail/management/commands/mail_fetcher.py", line 13, in handle
>     tasks.process_mail_accounts()
>   File "/usr/src/paperless/src/paperless_mail/tasks.py", line 12, in process_mail_accounts
>     account)
>   File "/usr/src/paperless/src/paperless_mail/mail.py", line 157, in handle_mail_account
>     account.imap_security) as M:
>   File "/usr/src/paperless/src/paperless_mail/mail.py", line 97, in get_mailbox
>     mailbox = MailBox(server, port)
>   File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 230, in __init__
>     super().__init__()
>   File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 26, in __init__
>     self.box = self._get_mailbox_client()
>   File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 245, in _get_mailbox_client
>     return imaplib.IMAP4_SSL(self._host, self._port, self._keyfile, self._certfile, self._ssl_context)
>   File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
>     IMAP4.__init__(self, host, port)
>   File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
>     self.open(host, port)
>   File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
>     IMAP4.open(self, host, port)
>   File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
>     self.sock = self._create_socket()
>   File "/usr/local/lib/python3.7/imaplib.py", line 1291, in _create_socket
>     sock = IMAP4._create_socket(self)
>   File "/usr/local/lib/python3.7/imaplib.py", line 289, in _create_socket
>     return socket.create_connection((host, self.port))
>   File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>   File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known

**Comment by jonaswinkler** [comment]
I should probably provide better error messages for this, but this error exactly indicates the problem: Paperless cannot contact the mail server.

It seems you're using this to connect to a self-hosted mail server? If so, make sure that the server is reachable from within the paperless docker container. docker-compose usually isolates all services in a private network, and with the default configuration, no other services running on the same host can be accessed.

**Comment by alucard856** [comment]
It's a self-hosted mail server on the internet. It isn't running on the same host. 
Domain and DNS are fine. 

imap.rije.de

**Comment by jonaswinkler** [comment]
Sounds like an issue with your networking setup to me and not an issue of paperless. Try with IP address; if that works, you'll need to figure out why DNS name resolution is not working for you.
