### ISSUE TITLE
Feature request: Option to switch back to old embed-style pdf viewer

### ISSUE THREAD

**Issue by praul** [jonaswinkler/paperless-ng#337]
Hi, I get the decision to switch to a rendering pdf-viewer.
Unfortunately, it's very slow for me, especially on large documents. I would really like the option to switch back to the old default embed pdf-view. 

Could this be implemented, either as environment-variable or as configurable option? I would be very happy :)

Thanks a lot, I love paperless-ng

**Comment by jonaswinkler** [comment]
Agreed, I don't like the new PDF viewer either, and a switch in the settings makes everyone happy.

**Comment by praul** [comment]
You always respond and fix so fast. Thanks a lot!

**Comment by jonaswinkler** [comment]
That largely depends on how easy something is to fix or add and also on whether I want the feature for myself :)
