### ISSUE TITLE
Where is the difference or advantages/disadvantages to the Tika Docker-Compose?

### ISSUE THREAD

**Issue by unknownFalleN** [jonaswinkler/paperless-ng#339]
First of all, thanks for the cool project. Is there a list where the different Docker variants are explained. Where is the difference or advantages/disadvantages to the Tika version? Postgres and Sqlite are clear to me.

**Comment by jonaswinkler** [comment]
I'll add some comments to the compose files.

The Tika compose file adds support for Office documents to paperless (Word, Excel, Power Point, and their LibreOffice counterparts). This compose file adds the necessary configuration options as described here: https://paperless-ng.readthedocs.io/en/latest/configuration.html#tika-settings
