### ISSUE TITLE
Export feature

### ISSUE THREAD

**Issue by Sblop** [jonaswinkler/paperless-ng#343]
First of all I must say I absolutely love this version of Paperless. I was sad when development on the old version ceased, and I was soo extremely happy when I found this.
It is NOT overly complicated. It is easy to manage. I understand it. PERFECT!
The reason I am writing is however a small feature request.
The ./manage.py document_exporter will not export when files is present in the folder.
I suggest a -f <force> argument, where it will either overwrite the backup, but even better, only update changed documents.

**Comment by jonaswinkler** [comment]
Thanks for the feedback! I appreciate it.

There are some issues with the exporter, I know. This has also been mentioned in #282 and I'll do it eventually. This is particularly important for incremental backups with `rsync`.

**Comment by jovandeginste** [comment]
In case it helps, I use btrfs and snapshots to get incremental backups with history:

```bash
#!/bin/bash -eux

EXPORT_DIR="/home/containers/documents/export/"
CURRENT_DIR="/mnt/backups/documents/current"
DATE_DIR="/mnt/backups/documents/$(date +%F_%H-%M-%S)"

if [[ -d "${DATE_DIR}" ]]; then
  echo "Target snapshot dir already exists."
  exit 1
fi

docker exec paperless_paperless_1 python manage.py document_exporter /usr/src/paperless/export/ -v0

sudo rsync -av --size-only --delete --remove-source-files "${EXPORT_DIR}" "${CURRENT_DIR}"
sudo btrfs subvolume snapshot -r "${CURRENT_DIR}" "${DATE_DIR}"
```
