### ISSUE TITLE
export function

### ISSUE THREAD

**Issue by Sblop** [jonaswinkler/paperless-ng#344]
First of all I must say I absolutely love this version of Paperless. I was sad when development on the old version ceased, and I was soo extremely happy when I found this.
It is NOT overly complicated. It is easy to manage. I understand it. PERFECT!
The reason I am writing is however a small feature request.
The ./manage.py document_exporter will not export when files is present in the folder.
I suggest a -f <force> argument, where it will either overwrite the backup, but even better, only update changed documents.

**Comment by jonaswinkler** [comment]
Closing as duplicate of #343
