### ISSUE TITLE
0.9.14 Docker-Hub Tag dev

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#345]
In Docker the Version 0.9.14 has the tag dev, not latest or 0.9.14. Is this correct?

**Comment by jonaswinkler** [comment]
Of course that's not correct, give me some time to figure these things out :)

**Comment by andbez** [comment]
Sure. Again i could not wait to use the new version 👍

**Comment by jonaswinkler** [comment]
This looks good now.
