### ISSUE TITLE
Holding shift should select multiple elements

### ISSUE THREAD

**Issue by chriscn** [jonaswinkler/paperless-ng#347]
Within the `documents` field, holding shift and selecting should allow one to select multiple elements in order to bulk delete for example.

**Comment by shamoon** [comment]
"Should" aka "wouldn't it be nice if?" 

I can do this one unless you prefer otherwise @jonaswinkler

**Comment by jonaswinkler** [comment]
Sure!

I'd probably add a 'selectRange(from, to)` function to the document list service, or something like that.

This will also not work across pages, which is okay.

**Comment by shamoon** [comment]
Sounds good, that’s what I was thinking! I’ll take a crack at it when I have some time off in the next few days
