### ISSUE TITLE
Consumption folder/inbox not processing any files or only processing a few files before quitting.

### ISSUE THREAD

**Issue by armandomisc** [jonaswinkler/paperless-ng#348]
My paperless inbox seems to stop processing after only a few files or sometimes not doing any at all until i restart the docker paperless on windows. I can get the system to process (very slowly after a few files) if I drag and drop, but then I have to go back into the folder and delete the processed files which is less than ideal. Is there already an issue out there that I missed on this or is this something unexpected?

Thanks.

**Comment by jonaswinkler** [comment]
On docker for Windows, you'll need to configure PAPERLESS_CONSUMER_POLLING (See https://paperless-ng.readthedocs.io/en/latest/configuration.html#software-tweaks, scroll down a bit), since the default mechanism to detect new files in the consumption folder does not work there.

Set this to "10", and paperless will check for new files every 10 seconds.

If you already did this or it does not resolve your issue, we'll have to figure out what's going on here.

**Comment by armandomisc** [comment]
Thanks Jonas. I went ahead and changed this in the yml file. From what I understand I have to rerun the docker-compose command in the folder to get the updates. However, I'm still only able to get 1 or 2 files processed before it stops processing. Also, my inbox count never updates. Although I understand the update is not dynamic, I would expect it to update if I switch to another tab, then come back to the dashboard. Here is an example of my updated docker-compose.yml file.






version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: always

  webserver:
    image: jonaswinkler/paperless-ng:0.9.13
    restart: always
    depends_on:
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "path1":/usr/src/paperless/data
      - "path2":/usr/src/paperless/media
      - "path3":/usr/src/paperless/export
      - "path4":/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_CONSUMER_POLLING: 10

volumes:
  data:
  media:

**Comment by jonaswinkler** [comment]
I'll test later on windows.

**Comment by armandomisc** [comment]
Looking through the logs it appears that paperless is failing on the one file that it's not consuming. So it sees it but for some reason fails.

When I restart the service it identifies and processes it no problem. I'll test with more documents later tonight or tomorrow.

**13:48:23 [Q] INFO Process-1:2 processing [geico_car_insurance-2.pdf]

INFO 2021-01-14 13:48:23,124 document_consumer Polling directory for changes: /usr/src/paperless/src/../consume

INFO 2021-01-14 13:48:23,696 loggers Consuming geico_car_insurance-2.pdf

13:48:23 [Q] ERROR Failed [geico_car_insurance-12.pdf] - disk I/O error : Traceback (most recent call last):

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute**

**Comment by armandomisc** [comment]
Apologies for the delayed response. I haven't been able to try this again because my docker started to break. However, after factory resetting and fixing the errors on docker, paperless-ng has started to process the inbox flawlessly. I'm going to guess this is a docker issue and not a paperless-ng issue. Closing this issue.
