### ISSUE TITLE
Create Type/Correspondent/Tag -> Set Focus to "Name"-Input-Field when opening

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#350]
If you want to create a new Type/Correspondent/Tag, then the focus is set to the "x" (Close Frame/Window). I think it is better, if the focus is set to the "Name"-Input-Field (Esc-Key for Exit works in every other field, so i think there is no need to focus to the X.)

**Comment by shamoon** [comment]
@jonaswinkler As usual, I can do if you haven't already

**Comment by jonaswinkler** [comment]
@shamoon 

Sure thing.

I tried adding `ngbAutofocus` to the controls on the `app-input-text` components, and trying to listen to that inside the input component, but that did not work out. Maybe it's best to not use these components for the name input field on these dialogs at all.
