### ISSUE TITLE
How to set default language?

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#352]
If i like to use Paperless in English (and the system is set to german and paperless is shown in german), how can i configure this? I do not find anything in the documentation, paperless.conf and in the web-frontend. It is easier to use the original english description of e.g. fields/menu-entries, when i have to describe something in an issue.

**Comment by jonaswinkler** [comment]
![image](https://user-images.githubusercontent.com/17569239/104724535-11e27580-5731-11eb-8778-cb6910a0d0a8.png)

**Comment by andbez** [comment]
Perfect! Thx.
