### ISSUE TITLE
Provide a way to search for correspondent/type/tag (+bulk edit) ?

### ISSUE THREAD

**Issue by Philmo67** [jonaswinkler/paperless-ng#356]
Now that I have a lot of documents integrated to Paperless-ng, I have several pages of correspondents, document types and tags. 
It seems useful to me to be able to search/filter in these 3 screens.
In addition, it could even be interesting to use what has been done for bulk editing documents but applied to all the documents of selected correspondents/document types/tags.
For example, if you are a customer of several banks ("bank xxx", "bank yyy", "bank zzz"), this would allow you to assign the tag "finance" to all the documents of the correspondents you would have searched for by the keyword "bank", omitting none of them.

**Comment by jonaswinkler** [comment]
Regarding filtering for tags, types and correspondents, that sounds useful.

Regarding bulk edit:
Unless I'm missing something, doing the following actions should already support this?
- Filter for a specific bank
- Select all
- Apply tag "finance"

**Comment by Philmo67** [comment]
Yes, so maybe allowing to select multiple correspondents or document types in the bulk edit screen could do the trick

**Comment by shamoon** [comment]
> Yes, so maybe allowing to select multiple correspondents or document types in the bulk edit screen could do the trick

Hmm @jonaswinkler so trying to interpret, this sounds like having ability to OR instead of AND in filter editor? Interesting thought, would have to brainstorm about UI / solution, wouldn’t want it to make things overly-complicated. Also API would need to accommodate but that’d be straightforward. Overall would still be a big task and at the moment this is already achievable you just have to do in separate batches so sort of debating value/cost...

**Comment by jonaswinkler** [comment]
* We *could* do multiple selections for correspondents and types, this is not difficult at all.

However:

* We do have multiple selection for tags already, and that filters for documents having ALL of the selected tags. Correspondent and tag filters must filter for documents having ANY of the selected items. Wouldn't that be confusing?

Name filtering is in.

**Comment by shamoon** [comment]
I agree that would be confusing. That’s kinda what I meant, I think we’d have to add a way for the user to be able to specify if it’s AND vs OR for tags if we chose to do this and yea doc/corresp would always be OR...

**Comment by shamoon** [comment]
Maybe just a checkbox / select within the tags drop down (“ALL” or “ANY”) but again more to it than that

**Comment by Philmo67** [comment]
perhaps providing 2 "checkable" columns (meaning ALL ANY) instead of 1 in front of the tags dropdown ?
use different symbols (on multiple clicks) ? + x ✓ (even - for "not" logic ? :-) )

**Comment by shamoon** [comment]
Was thinking more like:
<img width="286" alt="Screen Shot 2021-01-19 at 9 11 36 PM" src="https://user-images.githubusercontent.com/4887959/105130263-8acc2f00-5a9b-11eb-800b-0758990128ee.png">

But again, more considerations to implementing than just the UI.

**Comment by shamoon** [comment]
@jonaswinkler I have a branch for this, hopefully ready for you to look at soon
