### ISSUE TITLE
Created Dates Aren't Carried Over

### ISSUE THREAD

**Issue by russdyer** [jonaswinkler/paperless-ng#366]
PAPERLESS_FILENAME_FORMAT = {correspondent} - {title} - {created_year}-{created_month}-{created_day}
real filename = "bank - statement - 2020-01-31"

using the above syntax, paperless-ng still brings over the created/modified date showing in Windows instead of using the "created" attributes in the syntax example?  Am I naming the files wrong or is this a bug?

**Comment by jonaswinkler** [comment]
I think you got the purpose of this configuration option wrong. If not, please clarify your question.

* This is the filename that paperless will generate for your files when stored in the media directory / volume.
* This filename is generated from document metadata as specified in the format string.
* Whenever you edit documents, paperless renames the files in the media directory accordingly.

Especially:

* This is not a format string to "guess" attributes for newly consumed documents from their original filename.

**Comment by russdyer** [comment]
Oh, I thought naming the files according to these attributes would work in
conjunction with auto settings tags/dates/doc types - is this not true?

I thought using the {created_*} tags would tell paperless to change the
created date in paperless. Settings {tags} applies tags so I assumed this
would be true for dates as well.

**Comment by jonaswinkler** [comment]
> Oh, I thought naming the files according to these attributes would work in
> conjunction with auto settings tags/dates/doc types -  is this not true?

Yes, that's not true and I don't think the documentation mentions this feature working in this way anywhere.

**Comment by russdyer** [comment]
Ok thank you for the clarification.
