### ISSUE TITLE
Addition to Export

### ISSUE THREAD

**Issue by pagogc** [jonaswinkler/paperless-ng#376]
Referencing #343 for feature addition (docker only / document_exporter).

**German:**
Um die Backup-Strategie so automatisch wie moeglich zu machen, waere es super, Backups im laufenden Betrieb zu machen, selbst wenn #343 umgesetzt wird.
Koennte man hier eventuell einen "Lock" Mechanismus fuer die Datenbank einbauen, um so den document_exporter trotz laufender Instanz zu starten?
Bedeutet:

- Einzelne Prozesse, die aktiv die Datenbank benutzen/schreiben (nehme an zb Consumer/AI etc und document_exporter) schreiben einen Lock in die Datenbank.
- Wartende Prozesse versuchen es X mal einen Lock selbst zu fassen, wenn es fehlschlaegt:
-- bei document_exporter abbrechen
-- bei consumer/Ai etc. Logeintrag schreiben und spaeter nochmal versuchen.

So koennte man auch die Backup-Strategie im vollen Umfang umsetzen, ohne das System offline zu nehmen.

Derzeit muss ich gezielt einen komplizierten cronjob machen, der:
- den Docker-Container runterfaehrt
- den Exporter startet
- rsync (oder andere Werkzeuge) durchfuehrt
- Export Verzeichnis aufraeumt (schon geklaert in Issue #343)

PS: Kann ruhig in English geantwortet werden, wollte nur mal Deutsch niederschreiben :).

======================================

**English:**
For high availability, backups should be possible, even if the service is running.
Would it be possible to introduce a locking mechanism into the database? 

Meaning:
- seperate processes which need the database would lock it (eg.: consumer / Ai or document_exporter)
- waiting processes tries x times. If it fails:
- - document_exporter fails and writes logs
- - consumer / ai writes logs and tries again later

With this system in place, it would be possible to backup even the running system.

As it stands for now, a manual / complex cronjob is involved:
- stopping docker
- starting document_exporter
- rsync (or other means)
- cleaning export folder (already discussed in issue #343

**Comment by jonaswinkler** [comment]
Thank you for your suggestions! The primary project language is English, so everyone can read and contribute.

I'll look into running the exporter in a database transaction, at least the part that reads the data. I'll also look into locking the media directory, so that no change to file names is possible during export. These mechanisms are already there, I just need to check them for unintended side effects when used during export.
