### ISSUE TITLE
Email consumer: emails send from scanner not recognized/processed

### ISSUE THREAD

**Issue by Flight777** [jonaswinkler/paperless-ng#379]
First of all, thanks for all the amazing work, I'm just configuring everything and when in regular use I'd sure like to buy you a coffee :)

I've noticed a small issue or bug perhaps:

Any e-mail send by my printer to the e-mail that Paperless is scanning (documents@xxxx), is **not** recognized somehow by Paperless. The printer sends a PDF attached, with subject "Attached Image" and no message content (HTML version attached). I do see it in the e-mail box (Zoho) of the mail address.

As soon as I forward this same message from the printer from my personal e-mail to the same mail box (documents@xxxx), it does recognise it immediately!

No specific mail rules in place look at "from" etc., it is only set to scan "Inbox" without any filtering.

Not sure how to best explain/troubleshoot it further for you, happy to take some suggestions.

[Attached Image.zip](https://github.com/jonaswinkler/paperless-ng/files/5829879/Attached.Image.zip)

**Comment by jonaswinkler** [comment]
Hello!

First of all, paperless checks mails every 10 minutes, so paperless will never *immediately* add documents from mails. But I think you already now that. 

Paperless also creates some logs about what is happening during mail consumption. See the "Logs" section, set the filter to DEBUG and watch out for suspicous messages.

**Comment by Flight777** [comment]
Hi Jonas,

Yes, that was an exeggaration, but you know what I mean (actually I set it to every 2 minutes) ;)

The logs I did have a look at and don't show anything errornous, other than:

![image](https://user-images.githubusercontent.com/5236143/104916737-c202e900-5992-11eb-9667-0a4bd1141519.png)

So that is what I mean with not being "found" somehow. In any other mail client the e-mail IS visible. My suspicion is that Paperless is expecting some mail body content to consider it as e-mail?

**Comment by jonaswinkler** [comment]
Just a wild guess without actually testing that right now: The default inbox folder in most IMAP account is usually uppercase `INBOX`, and I'm not sure if that's case sensitive. Might be worth a try!

**Comment by Flight777** [comment]
Yep, tried both. Both work with e-mails sent other than from the scanner directly.

"Inbox" is the official IMAP mapping given by the provider (Zoho), so hence I settled on that one in the end.

**Comment by shamoon** [comment]
I use zoho with default imap settings and no issues, must be something specific about the emails themselves...

**Comment by Flight777** [comment]
I've now also added the same IMAP inbox in Outlook, emails are coming through correctly there as well. The only difference I can imagine is that the emails from the printer are coming from the same mail server (printer@xxxxx.xx) as the receiving email box (documents@xxxxx.xx).

Even with the scanner adding a body message to the e-mail, Paperless is not recognising them as valid e-mail...

**Comment by jonaswinkler** [comment]
- What mail action are you using?

**Comment by Flight777** [comment]
Assuming you are meaning the following:

![image](https://user-images.githubusercontent.com/5236143/104936587-0307f700-59ad-11eb-9945-130f9c61ab90.png)

This is the scheduled task:

![image](https://user-images.githubusercontent.com/5236143/104936675-1f0b9880-59ad-11eb-9b6e-2cbc4d429e3f.png)

These are the e-mail currently in the Inbox, Paperless only recognizes the test message judging from the log:

![image](https://user-images.githubusercontent.com/5236143/104936873-64c86100-59ad-11eb-955e-736e9d2f4949.png)

Log:

![image](https://user-images.githubusercontent.com/5236143/104937036-9f31fe00-59ad-11eb-8454-5145bb05a21a.png)

**Comment by jonaswinkler** [comment]
Thanks for all the input. I'll try to get that reproduced over here.

**Comment by jonaswinkler** [comment]
> ![image](https://user-images.githubusercontent.com/5236143/104936873-64c86100-59ad-11eb-955e-736e9d2f4949.png)

Are these mails encrypted by any chance?

I've configured paperless, an empty mailbox, and the filter rules just as in your screenshots and it picks up documents (and deletes mails) from mails that I've sent there using the same mailbox just fine. That includes mails without body and/or subject.

**Comment by Flight777** [comment]
Hmmm not that I know...

Just checked their FAQ:

You are always kept in the loop about the security level of the emails you send and receive. All emails between Zoho Mail servers are encrypted in transit using TLS and are marked accordingly. Whereas if the other provider involved does not support TLS, the email is marked as Plain to keep you informed.

But that is just TLS Is guess?

**Comment by jonaswinkler** [comment]
Probably.

I don't have an account there, and they want my phone number, which they won't get. I can't test this any further, sadly.

**Comment by Flight777** [comment]
If you can send me an email on: serversheits@outlook.com on which I can contact you, I can send you some OTP for that document mailbox so you can test with it directly.

**Comment by Flight777** [comment]
Did not receive anything yet, is that correct?

**Comment by Flight777** [comment]
Hi there, if there is another way you'd like me to give you the credentials, then please let me know. I just don't understand the silence suddenly? Trying to help by giving direct access to the Zoho mailbox so it may be easier for you to troubleshoot.

**Comment by jonaswinkler** [comment]
Alright, mail is on its way. Lets see if I can figure this out.
