### ISSUE TITLE
Mail consumer - "It is not a file"

### ISSUE THREAD

**Issue by rssfed23** [jonaswinkler/paperless-ng#381]
Couldn't seem to see this on another bug.

Just set up the imap consumer to pull from a folder. Action to move it to another one. Processing attachments only, and using the attachment filename as the document title.

The following appears in the logs for all the files. These files consume fine when uploading the pdf to the UI.

```
webserver_1  | ERROR 2021-01-18 16:45:13,629 loggers Cannot consume /tmp/paperless/paperless-mail-e6fpeh_h: It is not a file.
webserver_1  | 16:45:13 [Q] INFO Process-1:1 processing [19 11 TV TERMS OF BUSINESS inc PRIVACY NOTICE.pdf]
webserver_1  | 16:45:13 [Q] INFO Process-1:3 processing [19 04 Distance Selling.pdf]
webserver_1  | ERROR 2021-01-18 16:45:13,634 loggers Cannot consume /tmp/paperless/paperless-mail-ii6js02q: It is not a file.
webserver_1  | 16:45:13 [Q] ERROR Failed [CCL Knight.pdf] - Cannot consume /tmp/paperless/paperless-mail-e6fpeh_h: It is not a file : Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
webserver_1  |     res = f(*task["args"], **task["kwargs"])
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
webserver_1  |     override_tag_ids=override_tag_ids)
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 138, in try_consume_file
webserver_1  |     self.pre_check_file_exists()
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 48, in pre_check_file_exists
webserver_1  |     self.path))
webserver_1  | documents.consumer.ConsumerError: Cannot consume /tmp/paperless/paperless-mail-e6fpeh_h: It is not a file
webserver_1  |
webserver_1  | ERROR 2021-01-18 16:45:13,636 loggers Cannot consume /tmp/paperless/paperless-mail-_qbqazmv: It is not a file.
webserver_1  | 16:45:13 [Q] ERROR Failed [19 11 TV TERMS OF BUSINESS inc PRIVACY NOTICE.pdf] - Cannot consume /tmp/paperless/paperless-mail-ii6js02q: It is not a file : Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
webserver_1  |     res = f(*task["args"], **task["kwargs"])
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
webserver_1  |     override_tag_ids=override_tag_ids)
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 138, in try_consume_file
webserver_1  |     self.pre_check_file_exists()
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 48, in pre_check_file_exists
webserver_1  |     self.path))
webserver_1  | documents.consumer.ConsumerError: Cannot consume /tmp/paperless/paperless-mail-ii6js02q: It is not a file
```

**Comment by jonaswinkler** [comment]
Are you using the docker image? If not, please share some more details about your setup.

**Comment by rssfed23** [comment]
Yep, I'm using the docker image with postgres backing.

I've noticed it has successfully created the Correspondents based on sender email address so it's got part way through.

I've just tried dropping the same file into the consumption directory, and it processes okay.

**Comment by jonaswinkler** [comment]
Paperless copies mail attachments to a temporary directory, and processes them from there. This error indicates that
* Paperless cannot read that temporary file due to permission errors
* Paperless cannot read that temporary file, because it does not exist, does not exist anymore, or does not exist in that location.

The test cases verify that this file exists just before starting the consumption process. Therefore, I'm not exactly sure what's going on here.

Do you use `USERMAP_UID` or any other non-standard configuration options in your `docker-compose.env` file?

**Comment by rssfed23** [comment]
I am using USERMAP_UID and GID to UID 1000.

I think it does have something to do with file permissions when using those options.

I found a workaround:
- Put /tmp/paperless into a bind mount (in my case /opt/paperless/tmp).
- Recreate the container
- Manually chown the /opt/paperless/tmp/paperless directory to 1000, as when the container starts it's creating that directory with UID 0 and as such the IMAP puller can't seem to put files there.

That works for me and everything is processing.

So if I were to hazard a guess, it would be that the process creating the /tmp/paperless directory within the container is doing so as UID 0 rather than respecting the USERMAP_UID/GID values (or it comes with the container at that ownership and a script to chown doesn't hit that directory). 
The files downloaded into that directory after I change the permissions do have the correct ownership.

**Comment by rssfed23** [comment]
Reviewing the Dockerfile I can see the chown happen to /usr/src/paperless/src/
But it looks like /tmp/paperless/* is where the files download to.
So this makes sense now why /tmp/paperless is owned by root and might explain the issue. 

I did a manual rebuild of the Dockerfile including the chown to /tmp and didn't run into the issue again without needing a bindmount.

**Comment by jonaswinkler** [comment]
Usually, /tmp has a special "t" sticky flag in its permission, which allows everyone to create files there. However, only the user who created any particular file or folder has permissions to change and delete it.

Thanks for investigating, I'll try to figure out what part of paperless creates that /tmp/paperless/ folder as root.

> or it comes with the container at that ownership and a script to chown doesn't hit that directory

This might be it! I'll have a look.

**Comment by jonaswinkler** [comment]
* I checked the image, and the Dockerfile for building the image does not create `/tmp/paperless`.

* I checked every code section that creates and uses that directory, and all of them are run as the paperless user, and should therefore create that directory with correct permissions.

Did you by any chance run some of the management commands manually, inside the container, as root?

* If you run `docker-compose run --rm webserver mail_fetcher` (example), the startup script runs that as the paperless user.
* If you run `docker-compose run --rm webserver /usr/local/bin/python3 manage.py mail_fetcher` or similar, that is run as root.

**Comment by rssfed23** [comment]
Hmmm that's a bit odd.

I did run `docker-compose run --rm webserver mail_fetcher`, and not the long form version. Definitely didn't run anything inside the container manually either.

**Comment by jonaswinkler** [comment]
I'm not sure if this will help (*especially* since this is working for many other users), but I'll add instructions to the startup script that create `/tmp/paperless` and assign the correct ownership.

**Comment by jonaswinkler** [comment]
Please check if this is still an issue with the newest version (still building).

**Comment by rssfed23** [comment]
Yep seems to be good now on a new deploy!
