### ISSUE TITLE
Match-Expressions are always stored as lower-case

### ISSUE THREAD

**Issue by ignoreigor** [jonaswinkler/paperless-ng#397]
Hi,

first of all: great work! I am fascinated of the ease and beauty of your paperless-ng, though I am asking whether one needs more filters, more attributes, more whatever.

But, please correct me, if i am wrong, there is a problem with string-expressions to match. No matter if I say, it should match case-sensitive or not, the expression is always stored in lowercases. But if I want a case-sensitive match, I have to save uppercase letters in the expression. 

Best regards.

Paperless-ng 0.9.14 via simple docker installation

**Comment by jonaswinkler** [comment]
> But, please correct me, if i am wrong, there is a problem with string-expressions to match. No matter if I say, it should match case-sensitive or not, the expression is always stored in lowercases. But if I want a case-sensitive match, I have to save uppercase letters in the expression.

Good catch, will fix.

> first of all: great work! I am fascinated of the ease and beauty of your paperless-ng, though I am asking whether one needs more filters, more attributes, more whatever.

Thank you!
