### ISSUE TITLE
Paperless-ng survey

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#402]
Hello!

First of all, thanks to everyone for your continued interest in the project, and all of your suggestions on how to make paperless better. :+1: 

There's no telemetry or tracking of any kind in paperless (and will never be), however, I'd still like to know what parts of paperless are used extensively, which features work out great, and what needs improvements. Therefore, I've created a survey. The results will help me get the priorities right.

A couple notes.
* Please take this survey only if you already used Paperless for a period of time that exceeds your initial testing of the software.
* This will take you about 10 to 15 minutes.
* Your responses are valuable even if you're entirely happy with how the software works right now.
* The section "Next steps" asks about what feature's you'd like to see next in paperless. This is probably the most important part of the questionaire.
* Apart from a very rough estimate on the size of your paperless instance, no personal details.
* No sign-up required. You could potentially do this multiple times to skew the results, but please don't do that.
* Everything is optional.

Thank you for your time!

https://forms.gle/pKdJiAkuqUc7mjzx7

**Comment by jonaswinkler** [comment]
So far, 40 responses. Awesome! Thanks for all your kind comments.

I'll eventually make the results public, but doing so will influence new answers especially regarding the "Next steps" question, so this will run for a little longer. However, the key take aways so far are:

* I just installed Firefox and will use that for testing as well.
* Surprisingly few installations on Raspberry Pi. Not sure if it was worth setting up multiarch builds.
* No major issues.
* I'll think about a way to disable the ASN feature. Maybe add that as a custom metadata field once that feature is in.
* Automatic matching works good, but might need some indication on the front end if its working / not working.
* Full text search is excellent and should stay the way it is right now.
* More advertisement for the Tika integration, I've added a note to the README.
* Along all listed features, not a single feature with over 60% votes. That means: No feature on that list is absolutely essential. However, clear indication that some features are much more useful than others.

**Comment by jonaswinkler** [comment]
Not everyone would be okay with that.

Also, opinions and subjective feedback (e.g., is a feature working as expected) are pretty hard to catch with that, and that's the important thing here.

**Comment by saikimecky** [comment]
Thanks for your great work! And please release a docker image for arm64 in the future. i really like it and use it heavily on my raspis.

**Comment by shamoon** [comment]
@jonaswinkler et al. I just noticed the GitHub discussions section actually lets people “vote” up threads which means, now that the survey is done, we could use that area as a means to prioritize what to work on. I think the biggest challenge to that succeeding is just drawing people’s attention to it so could be highlighted in read me, pinned issue, explained in the new issue template etc

https://github.com/jonaswinkler/paperless-ng/discussions/categories/ideas

Advantages are keeping things in one place, discussions can be easily converted into issues etc.

If we do want to go this route I can submit PRs for stuff above, we could even add a button in the app UI with something like “suggest a feature” etc (though that might be asking for trouble 😜)

**Comment by jonaswinkler** [comment]
> Thanks for your great work! And please release a docker image for arm64 in the future. i really like it and use it heavily on my raspis.

I'll always keep ARM in mind when updating dependencies. And since the CI/CD pipeline works fine, providing ARM images in addition to amd64 does not involve any additional effort.


> 

> @jonaswinkler et al. I just noticed the GitHub discussions section actually lets people “vote” up threads which means, now that the survey is done, we could use that area as a means to prioritize what to work on. I think the biggest challenge to that succeeding is just drawing people’s attention to it so could be highlighted in read me, pinned issue, explained in the new issue template etc
> 
> https://github.com/jonaswinkler/paperless-ng/discussions/categories/ideas
> 
> Advantages are keeping things in one place, discussions can be easily converted into issues etc.
> 
> If we do want to go this route I can submit PRs for stuff above, we could even add a button in the app UI with something like “suggest a feature” etc (though that might be asking for trouble )

Good idea. Except for the "suggest a feature" link. Well, it is a good idea, but we already got a link to the project page, and that should be enough.

The advantage of survey is that you can do faceted evaluation. For example, features requested by users who migrated from another DMS. Or full text search performance of users with <1000 documents vs users with > 1000 documents.

**Comment by shamoon** [comment]
> Good idea. Except for the "suggest a feature" link. Well, it is a good idea, but we already got a link to the project page, and that should be enough.

Cool, I'll draft a PR for this stuff. For a link in the app, definitely don't feel strongly but was thinking to just add something like the lightbulb icon next to the GH link with the title "suggest a feature", eg screenshot. Again, dont feel strongly about this little part, screenshot:
<img width="225" alt="Screen Shot 2021-01-31 at 9 09 47 AM" src="https://user-images.githubusercontent.com/4887959/106391849-25821300-63a4-11eb-9b54-e37b0cebdb24.png">

**Comment by shamoon** [comment]
> The advantage of survey is that you can do faceted evaluation. For example, features requested by users who migrated from another DMS. Or full text search performance of users with <1000 documents vs users with > 1000 documents.

Oh yea I just mean for new feature requests
