### ISSUE TITLE
Feature Request -> Navigating within Tag-Field with keyboard

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#403]
Environment: paperless-ng (Docker latest, 0.9.14)

Currently it is not possible to navigate within the Tag-Field in Document-Edit-Mode with the keyboard. Only backward-delete is possible. 

So, if i want to delete the first of several set tags in this field i have to use the mouse (or delete all tags and set the wanted tags).

Better is navigating by cursor-keys (left/right) to jump between the tags and then delete the tag with backward-delete.
See example attached. Try to delete the first tag #inbox# with the keyboard only :D
<img width="319" alt="Bildschirmfoto 2021-01-21 um 17 34 37" src="https://user-images.githubusercontent.com/63553946/105381224-11554d80-5c0f-11eb-8696-797df106b272.png">

**Comment by shamoon** [comment]
TBH this sounds like "harder than it sounds" for a small gain but more importantly those dropdowns are from [another Angular library](https://ng-select.github.io/ng-select#/multiselect) and adding support for this on top of their component is at least messy if not impossible. If you'd like to see this perhaps better to submit a PR or open an issue there: https://github.com/ng-select/ng-select

**Comment by jonaswinkler** [comment]
> TBH this sounds like "harder than it sounds" for a small gain but more importantly those dropdowns are from [another Angular library](https://ng-select.github.io/ng-select#/multiselect) and adding support for this on top of their component is at least messy if not impossible. If you'd like to see this perhaps better to submit a PR or open an issue there: https://github.com/ng-select/ng-select

This.
