### ISSUE TITLE
[BUG] Mail consumption fails for mails with defects / Mails don't get picked up

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#404]
See #379 

When the python mail parsing backend reports errors on mails, the library `imap-tools` silently ignores these mails. Either provide error messages, or investigate if we can allow mail processing despite certain errors.

The error in the related issue is `email.errors.InvalidMultipartContentTransferEncodingDefect`.

**Comment by Flight777** [comment]
Maybe have a look at the friend over at Teedy for this? :)

**Comment by jonaswinkler** [comment]
Oh, I already did. Teedy is written in a different programming language, and they've got other libraries that handle things differently.

**Comment by Flight777** [comment]
Ah ok, too bad, otherwise might have been easy to borrow some ideas.

**Comment by r3d00** [comment]
Same issue here, the documents get send to my mailbox with a simple text body and several attachments, but they don't get picked up by paperless

```
[2021-04-09 16:07:38,491] [DEBUG] [paperless_mail] Account docs@redacted.xyz: Processing 1 rule(s)
[2021-04-09 16:07:38,494] [DEBUG] [paperless_mail] Rule docs@redacted.xyz.default: Selecting folder INBOX
[2021-04-09 16:07:38,500] [DEBUG] [paperless_mail] Rule docs@redacted.xyz.default: Searching folder with criteria (SINCE 10-Mar-2021 UNFLAGGED)
[2021-04-09 16:07:38,971] [DEBUG] [paperless_mail] Rule docs@redacted.xyz.default: Processed 0 matching mail(s)
[2021-04-09 16:07:38,972] [DEBUG] [paperless_mail] Rule docs@redacted.xyz.default: Running mail actions on 0 mails
```
Message Content & Headers
`
Date: Fri, 9 Apr 2021 15:55:12 +0200
From: "scan@redacted.xyz" <scan@redacted.xyz>
To: "Scan" <docs@redacted.xyz>
Subject: Scan
MIME-Version: 1.0
X-Priority: 3
X-Mailer: Canon MFP
Message-ID: <20210409155512.0001.CanonTxNo.0021@home>
Content-Type: multipart/mixed; boundary="----_CANON_2104091555120021_"
Content-Transfer-Encoding: quoted-printable
------_CANON_2104091555120021_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Scan from Scanner
------_CANON_2104091555120021_
Content-Type: Application/pdf;
 name="0021_210409155512_001.pdf"
Content-Disposition: attachment;
 filename="0021_210409155512_001.pdf"
Content-Transfer-Encoding: base64
`

**Comment by jonaswinkler** [comment]
Recent updates to `imap-tools` should resolve this issue.
