### ISSUE TITLE
Update docker to 0.19.4?

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#405]
_(Sorry I'm pretty new to docker and not familar with all the details)_

I installed 0.19.3 with the `dockerfiles.tar.xz`. To get the most recent 0.19.4 I tried to upgrade like [the docs say](https://paperless-ng.readthedocs.io/en/latest/administration.html#docker-route):
```
docker-compose down
docker-compose pull
docker-compose up
```
Unfortunatly the UI says still 0.19.3, but the pull didn't report any errors?

**Comment by jonaswinkler** [comment]
Up until now, the docker-compose.yml file specified the exact version and updating required replacment of that file.

Either grab the new version of the file from /docker/compose in the repository, or find the line that says:

`image: jonaswinkler/paperless-ng:0.9.13`

and replace that with 

`image: jonaswinkler/paperless-ng:latest`

This way, you'll always update to the latest version when executing the pull command. Also works very nicely in combination with [watchtower](https://containrrr.dev/watchtower/) for automatic updates.

I'll add a note to the next changelog.

**Comment by jonaswinkler** [comment]
Please close this if your issue is resolved.
