### ISSUE TITLE
Fresh Installation - Test Upload

### ISSUE THREAD

**Issue by doodlemania2** [jonaswinkler/paperless-ng#409]
Hi there - trying a fresh install with a PDF (nothing else setup other than a superuser) and get this:
Jan 21 18:42:51 ERROR 2021-01-22 02:42:51,265 loggers The following error occured while consuming Trinity Forest Adult.pdf: User matching query does not exist.
Jan 21 18:42:51 02:42:51 [Q] ERROR Failed [Trinity Forest Adult.pdf] - User matching query does not exist. : Traceback (most recent call last):
Jan 21 18:42:51 File "/app/code/src/documents/consumer.py", line 186, in try_consume_file
Jan 21 18:42:51 classifier=classifier
Jan 21 18:42:51 File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 179, in send
Jan 21 18:42:51 for receiver in self._live_receivers(sender)
Jan 21 18:42:51 File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
Jan 21 18:42:51 for receiver in self._live_receivers(sender)
Jan 21 18:42:51 File "/app/code/src/documents/signals/handlers.py", line 322, in set_log_entry
Jan 21 18:42:51 user = User.objects.get(username="consumer")
Jan 21 18:42:51 File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 85, in manager_method
Jan 21 18:42:51 return getattr(self.get_queryset(), name)(*args, **kwargs)
Jan 21 18:42:51 File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 431, in get
Jan 21 18:42:51 self.model._meta.object_name
Jan 21 18:42:51 django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
Jan 21 18:42:51
Jan 21 18:42:51 During handling of the above exception, another exception occurred:
Jan 21 18:42:51
Jan 21 18:42:51 Traceback (most recent call last):
Jan 21 18:42:51 File "/usr/local/lib/python3.6/dist-packages/django_q/cluster.py", line 436, in worker
Jan 21 18:42:51 res = f(*task["args"], **task["kwargs"])
Jan 21 18:42:51 File "/app/code/src/documents/tasks.py", line 73, in consume_file
Jan 21 18:42:51 override_tag_ids=override_tag_ids)
Jan 21 18:42:51 File "/app/code/src/documents/consumer.py", line 224, in try_consume_file
Jan 21 18:42:51 raise ConsumerError(e)
Jan 21 18:42:51 documents.consumer.ConsumerError: User matching query does not exist.

**Comment by jonaswinkler** [comment]
* How did you install paperless?
* In the administration section, did you delete the "consumer" user?

**Comment by doodlemania2** [comment]
Thanks for the quick reply. Manual bare metal install. I backed everything out and tried again - and this time it worked. One difference this time, I wised up and ran migrations from the src folder (instead of referencing it from my root path) and I suspect that's where my wheels were coming off.
