### ISSUE TITLE
New date format option not being applied to date picker

### ISSUE THREAD

**Issue by ministryofsillywalks** [jonaswinkler/paperless-ng#410]
First of all HUGE thanks for the incredible development of this. 
In its current state this is the paperless I had always dreamed of!

I (as a german) am really happy about the new date options, as DD.MM.YYYY is the standard here.
I just upgraded and activated the new format, however it still shows the old format in the date picker.

Settings:
![image](https://user-images.githubusercontent.com/10544895/105457152-a182a980-5c86-11eb-8907-e4e187a5e9dc.png
)
Date Picker:
![image](https://user-images.githubusercontent.com/10544895/105457178-ac3d3e80-5c86-11eb-9768-4f2895251041.png)

Should be 28.12.2020 following the new format.
When opening the date picker and changing the date manually it still stays in the old format of MM.DD.YYY
In the overview of all documents the format is correct:
![image](https://user-images.githubusercontent.com/10544895/105457412-148c2000-5c87-11eb-8bd8-d09eeaa9f454.png)

**Comment by shamoon** [comment]
Date inputs haven't been updated to match display, yet. This has been a bit complicated but on the list. See #177 for example (but again, still in progress)

**Comment by ministryofsillywalks** [comment]
Ok thanks! Good to know. Maybe amend that in the patchnotes that its only for the display?
