### ISSUE TITLE
installed Version info somewhere

### ISSUE THREAD

**Issue by kaiserbene** [jonaswinkler/paperless-ng#416]
can't find a version hint in paperless-ng - can you put this info on the config-page?

**Comment by jonaswinkler** [comment]
It's on the bottom left section of the sidebar.

**Comment by kaiserbene** [comment]
Omg - sorry..too stupid to read

**Comment by stueja** [comment]
I have just updated to 1.2.0 (docker-compose pull), and the version information reads ` Paperless-ng 1.1.0 `. Is that known or should I open a separate issue for that? Or does `docker-compose pull` really pull 1.1.0?

**Comment by jonaswinkler** [comment]
The update instructions are available [in the documentation](https://paperless-ng.readthedocs.io/en/latest/administration.html#docker-route).

The gist of it is that you need to restart the container.

**Comment by stueja** [comment]
Well, I updated according to this exact documentation
```
docker-compose down
docker-compose pull
docker-compose up -d
```

**Comment by stueja** [comment]
So. Got it. It was the `docker-compose.yml` file, which, after testing and migration from paperless, contained entries to statically served files. Deleted the entries, restarted the containers -- voilá. Sorry for the noise.
