### ISSUE TITLE
Docker volume mounts and inotify

### ISSUE THREAD

**Issue by scavone** [jonaswinkler/paperless-ng#418]
When the webserver container would first start, it would consume files sitting in the mapped folder but subsequent files being dropped would remain and not be imported. 

I did some digging in the issue trackers upstream and here and noticed that it has to do with inotify. The recommendation was to change the command in the upstream `docker-compose.yml` file to `["document_consumer", "--no-inotify"]`

Obviously that isn’t how this fork executes things but I do see that the command is executed on Line 9 in the [paperless-consumer.service](https://github.com/jonaswinkler/paperless-ng/blob/ced6a61869cf30b31124afc114b9d9e4087e6996/scripts/paperless-consumer.service#L9)  

What do you think would be the best way to implement the `--no-inotify` flag?

**Comment by shamoon** [comment]
https://github.com/jonaswinkler/paperless-ng/issues/118

**Comment by jonaswinkler** [comment]
The configuration option you're looking for is `PAPERLESS_CONSUMER_POLLING`.

**Comment by scavone** [comment]
Thank you! I had searched the documentation for `document_consumer` but not `inotify`. Obvious in hindsight. I really appreciate the quick reply. Made the change and it works like a charm!
