### ISSUE TITLE
Setting to delete / compress / ... original documents?

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#422]
Hi, I know that paperless-ng has the basic concept to never touch the original documents. I understand this important aspect of a (reliable) DMS, but like to ask, if it wouldn't be possible to add option, where the user / superuser can decide, how to deal with the documents?

So default would be to keep originals untouched, but we can offer different ways:
* remove - just delete originals after processing archived versions
* compress (printing) - keep an max. compressed version with best results for printing
* compress (screen) - keep an max. compressed version but only for viewing on screen
* ....

Usecase: I add documents as 300dpi multipage TIFFs, to get best results on OCR. The originals take a lot of space, but usually I don't need to keep them, as I get all details from archived versions and could also print a paper hardcopy if needed.

**Comment by jonaswinkler** [comment]
I won't add any functionality to delete originals.

Regarding OCR, even with lower dpi, non ideal contrast or jpeg compression artifacts, tesseract is still able to do a pretty good job, so it's not necessarily required to use (uncompressed?) high resolution pictures.

**Comment by Matthias84** [comment]
I guess I will change my workflow, not a huge problem!
