### ISSUE TITLE
Show documenttype at lists

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#423]
The documenttype is only visible at the detailed listview, but not on the other 2 styles. Unfortunately the same, if you pin searches on the dashboard, which makes it IMHO hard to understand the nature of a document.
As the documenttype labels might be to long, we might use emojis as shortcuts?

**Comment by jonaswinkler** [comment]
We can certainly fit that somewhere on the large cards, but the small cards are already very cramped and I don't want to add too much visual elements to these.

**Comment by Matthias84** [comment]
Great! Is there already any specs. / definition on which usecases a list layout should satisfy?
Personally I like the thumbnails as visual impression on paper, but the details lists are very usefull as well.

**Comment by Spoker** [comment]
Would love the display of the documenttype on the other layouts as well. I mostly use the cards view and in my use case, I don't feel it would be too much information on the card.

**Comment by jonaswinkler** [comment]
Any suggestions about where to add that information?

**Comment by sbrunner** [comment]
Add by the same way as the tag starting with a #:
![v1](https://user-images.githubusercontent.com/353872/110789130-d31ff600-826f-11eb-8921-fe1eac926d2b.png)

Or to don't have many texts add a field like ref in the document type, and add this ref after (or before) the correspondent with a title for the full name:
![v2](https://user-images.githubusercontent.com/353872/110789227-eaf77a00-826f-11eb-9a7c-5252fa00f44f.png)
A variant can be used an icon, but it will probably be more complex...

The 'ref' and 'title' can be used for the tag and correspondent?

**Comment by Spoker** [comment]
I would add it below the thumbnail, next to correspondent. 

```
Correspondent, documenttype:
Title
```
or variations:

```
Correspondent #documenttype:
Title
```

```
Correspondent (documenttype):
Title
```

**Comment by shamoon** [comment]
Had some ideas in #439

**Comment by sbrunner** [comment]
I think that we should be able to quickly show the type of a document, it shouldn't be in a tooltip...

**Comment by shamoon** [comment]
It looks like your second screenshot a tooltip, no?

I hear you about showing them all the time but the cards are sorta small and between the fact that some people will have many tags and titles and correspondents can be very long we have to try to find a balance that works across different installs. Basically making this helpful for those that want this and not disruptive for those that don’t.

Definitely many ways to do it, not sure what’s “best”...

**Comment by sbrunner** [comment]
> It looks like your second screenshot is a tooltip, no?

In this solution I propose to add a short name in the Document type, and display directly the short name, and have the full name in a tooltip :-)

> I hear you about showing them all the time but the cards are sorta small and between the fact that some people will have many tags and titles and correspondents can be very long we have to try to find a balance that works across different installs. Basically making this helpful for those that want this and not disruptive for those that don’t.

Good question :-) to target that we can show the document type only if a short name is defined?

**Comment by sbrunner** [comment]
Another proposition that can better fit with all requirements, define an optional colour in the document type, and add a border around the document with this colour =>

![v3](https://user-images.githubusercontent.com/353872/110841155-d9c96000-82a5-11eb-8987-967730bb7281.png)

And the idea from #439 can also be added :-)

What do you think?

**Comment by shamoon** [comment]
Personally I dont love the colored outline, I think it will get visually very messy with all the colors and you cant really tell what each color means without knowing which means what. Just my opinion, of course.

**Comment by sbrunner** [comment]
And what about the second proposition of  #439 and change the document type color with an optional color defined in the Document type?
Do you have another proposal?

**Comment by shamoon** [comment]
I agree I like option 2 of #439 the best, or adding doc type as text somewhere. But I’m not sold on introducing a color to document type at all, I think it could be confusing with the colored tags.

But again, pros / cons to any solution, of course. Curious about other folks’ thoughts.

**Comment by jonaswinkler** [comment]
![image](https://user-images.githubusercontent.com/17569239/110854394-33855680-82b5-11eb-97f3-2ec6ff4d206e.png)

This is approx. what I did in old paperless with document types, maybe that's an option too.

**Comment by shamoon** [comment]
Sure, though I thought we were trying avoid making the cards taller but 🤷🏽‍♂️

**Comment by jonaswinkler** [comment]
Just tossing that in here for thought. So far, I feel that adding a special #-prefixed badge might work best.

**Comment by shamoon** [comment]
Let me play with some mockups...

**Comment by shamoon** [comment]
So what do people think about this (screenshot below)? It combines a few things that have come up:

- Info immediately visible without tooltips
- Cards dont change height overall even with all 3 metadata items
- Doc type is clickable to quick filter documents (like correspondent)
- Bigger action buttons
- Looks nice (IMHO 😉)

<img width="1029" alt="Screen Shot 2021-03-11 at 3 28 29 PM" src="https://user-images.githubusercontent.com/4887959/110869420-47ae6100-827f-11eb-983c-5cb4c202909a.png">

**Comment by sbrunner** [comment]
Looks Good :-)

**Comment by jonaswinkler** [comment]
> though I thought we were trying avoid making the cards taller but 🤷🏽‍♂️

Hmmmmm.... :)

**Comment by shamoon** [comment]
> > though I thought we were trying avoid making the cards taller but 🤷🏽‍♂️
> 
> Hmmmmm.... :)

I know, but not much. Even with all 3 metadata items cards are only about 10% taller than before. And again thats worst case, if theres no ASN or document type they'll get a tiny bit _shorter_. Ultimately Im happy with this compromise. You ok with it? (And if so, ready for a PR?)

**Comment by jonaswinkler** [comment]
What about clicking on the document type for filtering purposes?

**Comment by shamoon** [comment]
> What about clicking on the document type for filtering purposes?

Yep, that works

**Comment by jonaswinkler** [comment]
go ahead with the PR, lets see how that works out.
