### ISSUE TITLE
Consume folder is processed only at app start

### ISSUE THREAD

**Issue by ignazioc** [jonaswinkler/paperless-ng#432]
How often the webserver is supposed to process the `consume` folder?

I configured `paperless-ng` on my mac using docker-compose. When the app starts (`docker-compose up -d` or `docker-compose restart`) the `consume` folder is correctly processed and the PDFs are imported as expected. But new files added into the folder after the app start are not imported. 

The `docker-compose.yml` is based on this example: https://github.com/jonaswinkler/paperless-ng/blob/master/docker/compose/docker-compose.sqlite.yml

How can I check if the `consumer` process is running?

**Comment by jonaswinkler** [comment]
See https://paperless-ng.readthedocs.io/en/latest/troubleshooting.html#consumer-fails-to-pickup-any-new-files

**Comment by ignazioc** [comment]
thanks @jonaswinkler the polling is now working properly. I'm using Mac with big sur, no nfs.  I'm happy to see it work now. 🥳
