### ISSUE TITLE
Sidebar menu items click

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#435]
Hi, the sidebar menu items are a tip to big, so the mouse can click not only on the label itself, but even on the background. This is sometimes confusing, if you open lists and get to close to the menu bar :wink: 

![paperlessng cursor sidebar](https://user-images.githubusercontent.com/217511/105635153-d5fe8d00-5e61-11eb-9d1a-e45144656c45.png) (cursor is indeed a picker to click at this menuitem)

**Comment by shamoon** [comment]
I think the large target areas are a good thing, its built into the CSS framework we use intentionally that they're full width buttons. Your screenshot is pretty small but looks like youre very far away from the dropdown... not sure what the issue really is.

**Comment by jonaswinkler** [comment]
I don't see any issues with this.
