### ISSUE TITLE
Rule to assign documents to users?

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#436]
Hi, could we add a feature where the consumer can analyze documents and assign them based on rules to different users? So based on rules it triggers on my name or on the name of my family members and assigns documents to their different users. If it fails, it defaults to a specific user or a common inbox which is accessible to all users, to pick documents from.

To me this isn't related to security, but to keep document storages separated. Currently it can only be modelled by tags, but it can be anoyed, if users remove this filter and see / change documents which don't belong to them.

**Comment by shamoon** [comment]
Holy cow man. That's a lot of issues you created (and no PRs)... Please remember no one gets paid for this and it's done in peoples free time. IMHO I think you have to prioritize your requests to what's most important not just submit every one as an issue. Not trying to give you a hard time but 😲
![image](https://user-images.githubusercontent.com/4887959/105639180-9ddc5780-5e2b-11eb-82bf-99d4b12e56ad.png)

**Comment by shamoon** [comment]
Ps. in reference to this issue, it is dependent on implementation of a more robust multi-user setup e.g. https://github.com/jonaswinkler/paperless-ng/discussions/52

**Comment by jonaswinkler** [comment]
Assigning documents to users is by itself pretty simple, but comes with a couple issues in practice:
* There's only one consumption folder. Who do the documents belong to?
* What about shared documents?

I don't have any specific plans for multi user at this point.

**Comment by Matthias84** [comment]
> Holy cow man. That's a lot of issues you created (and no PRs)... Please remember no one gets paid for this and it's done in peoples free time. IMHO I think you have to prioritize your requests to what's most important not just submit every one as an issue. Not trying to give you a hard time but astonished.

Maybe this is a misunderstanding. I like paperless-ng a lot and tried & learned it in the past weeks. I noticed some issues and some ideas, how it might become more useful to me and maybe others. This issues are only to show it to jonas and see if this is something worth to think about it.
Even if familar with python+django I don't know if I'm skilled and have enough time to contribute. If there are minor features / bugs to work on, I will see if I could participate via PRs.
