### ISSUE TITLE
Upload document via app successful but nothing shown in web interface

### ISSUE THREAD

**Issue by brettks** [jonaswinkler/paperless-ng#437]
I have been able to upload several documents via android paperless app but did a series of three in a row with this same problem: It uploads and I see the consumption process start and finish in the logs. The document count on the dashboard increases but I cannot see the document in the web interface itself. I know it is uploading appropriately because I can see the document with the URL http://IP:Port/api/documents/63/preview/, just not in the document list. No filters are applied, it's just default view. Any ideas?

**Comment by brettks** [comment]
I just found them. I changed from sort by date added to a different sort then back, somehow that refreshed the view. It's strange I had to do that because I previously tried to restart the web browser, refresh the webpage, and restart the docker container with no success.

**Comment by jonaswinkler** [comment]
I'll check with the back end, maybe some issues with default sorting. If that happens again, it would be nice if you could F12, open the networking tab, and see if there are any errors.

**Comment by brettks** [comment]
Will do

**Comment by Matthias84** [comment]
I started using the app and it seems basics working fine also for paperless-ng.

**Comment by brettks** [comment]
I was able to reproduce the problem today. Nothing obvious wrong skimming through the HTTP status codes on the networking tab. Changing sort to ASN then back to Added makes it so I can see the recently uploaded document.

**Comment by jonaswinkler** [comment]
When no filters are applied, I cannot get the document API to return no documents, no matter what sorting is applied.

You aren't expecting the document list to update after adding documents with out a reload, are you?

**Comment by brettks** [comment]
When you say reload, do you mean refreshing the page? If so, no I do not expect that. Even after a page refresh I get no changes.

And the problem is not that *no* documents are loading, just that the newest upload is not loading until I change the sort a few times. I can try creating a video if that makes it easier to understand.

**Comment by jonaswinkler** [comment]
This sounds really odd to me.

1. The document list shows your current documents.
2. Add new documents with the app.
3. Verify in the logs that consumption has completed.
3. Reload the document list. The document list does not show the new document.
4. Restart the container. The document list still won't show the new document.
5. Change the sort. The document list shows the new document.

Did I get that right? If so, A video won't be necessary.

- What's your database backend?
- Does changing filters instead of the sorting cause the new document to appear as well?
- Does this happen on the primary document list, or on a saved view?

**Comment by brettks** [comment]
All of the above is correct. However, I've been playing around with it again today and cannot reproduce is again. I wonder if this was some kind of user error with sorting that I didn't realize. I will let you know if it happens again and try to confirm.

**Comment by jonaswinkler** [comment]
Please re-open this if it happens again.
