### ISSUE TITLE
Consumer running in supervisor

### ISSUE THREAD

**Issue by doodlemania2** [jonaswinkler/paperless-ng#438]
When I start my container, I've specified a supervisor script like so:
```
[program:paperless-consumer.service]
priority=10
directory=/app/code/src
environment=HOME=/home/runner
command=python3 manage.py document_consumer
user=runner
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```

The other services (scheduler and webserver) are similar and run just fine. However, in consumer, I get a line that says it started:

```
Jan 24 17:06:01 2021-01-25 01:06:01,265 INFO spawned: 'paperless-consumer.service' with pid 26
Jan 24 17:06:02 2021-01-25 01:06:02,909 INFO success: paperless-consumer.service entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

But, checking services (ps | ax) shows it is not running:
```
  PID TTY      STAT   TIME COMMAND
     1 pts/0    Ss+    0:00 /usr/bin/python /usr/bin/supervisord --configuration /etc/supervisor/supervisord.conf --nodaemon -i Paperless
    25 pts/0    S      0:02 python3 manage.py qcluster
    26 pts/0    S      0:00 /usr/bin/python3 /usr/local/bin/gunicorn paperless.wsgi -w 2 -b 0.0.0.0:8000
    29 pts/0    S      0:02 /usr/bin/python3 /usr/local/bin/gunicorn paperless.wsgi -w 2 -b 0.0.0.0:8000
    30 pts/0    S      0:03 /usr/bin/python3 /usr/local/bin/gunicorn paperless.wsgi -w 2 -b 0.0.0.0:8000
    44 pts/0    S      0:00 python3 manage.py qcluster
    45 pts/0    S      0:00 python3 manage.py qcluster
    46 pts/0    S      0:00 python3 manage.py qcluster
    47 pts/0    S      0:00 python3 manage.py qcluster
    48 pts/0    S      0:00 python3 manage.py qcluster
    55 pts/1    Ss     0:00 /bin/bash
    69 pts/1    R+     0:00 ps -ax
```

and when I restart the container, it shuts the others down:

```
Jan 24 17:05:52 2021-01-25 01:05:52,399 WARN received SIGTERM indicating exit request
Jan 24 17:05:52 2021-01-25 01:05:52,399 INFO waiting for paperless-scheduler.service, paperless-consumer.service to die
Jan 24 17:05:52 [2021-01-25 01:05:52 +0000] [131] [INFO] Handling signal: term
Jan 24 17:05:52 [2021-01-25 01:05:52 +0000] [134] [INFO] Worker exiting (pid: 134)
Jan 24 17:05:52 [2021-01-25 01:05:52 +0000] [135] [INFO] Worker exiting (pid: 135)
Jan 24 17:05:52 [2021-01-25 01:05:52 +0000] [131] [INFO] Shutting down: Master
Jan 24 17:05:52 2021-01-25 01:05:52,945 INFO stopped: paperless-consumer.service (exit status 0)
Jan 24 17:05:52 01:05:52 [Q] INFO Q Cluster speaker-monkey-october-princess stopping.
Jan 24 17:05:52 01:05:52 [Q] INFO Process-1 stopping cluster processes
Jan 24 17:05:53 01:05:53 [Q] INFO Process-1:4 stopped pushing tasks
Jan 24 17:05:53 01:05:53 [Q] INFO Process-1:2 stopped doing work
Jan 24 17:05:53 01:05:53 [Q] INFO Process-1:1 stopped doing work
Jan 24 17:05:54 01:05:54 [Q] INFO Process-1 waiting for the monitor.
Jan 24 17:05:54 01:05:54 [Q] INFO Process-1:3 stopped monitoring results
Jan 24 17:05:54 01:05:54 [Q] INFO Q Cluster speaker-monkey-october-princess has stopped.
Jan 24 17:05:54 2021-01-25 01:05:54,627 INFO stopped: paperless-scheduler.service (exit status 0)
```

But, of course, consumer doesn't shut down cause it isn't running. But here's the funny part:
```
root@a13fab28-7e51-49f6-a8ec-50080f900ff7:/app/code# supervisorctl
paperless-consumer.service       RUNNING   pid 26, uptime 0:05:49
paperless-scheduler.service      RUNNING   pid 25, uptime 0:05:49
```

Supervisor thinks it is running, but the log for supervisor shows nothing happens when I drop a file into the consume directory. Relevant config entries:
```
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_POLLING=10
PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
PAPERLESS_CONSUMPTION_DIR=/app/data/consume
PAPERLESS_DATA_DIR=/app/data/data
PAPERLESS_MEDIA_ROOT=/app/data/media
PAPERLESS_STATICDIR=../static
PAPERLESS_FILENAME_FORMAT={created_year}/{title}
```

Now, the really funny part - if I interactively go into the container, switch to `./src` and run `python3 manage.py document_consumer`, it works - it grabs things that are there and when new items drop in, it picks them up right away.

Stuck :( Any ideas?

**Comment by jonaswinkler** [comment]
Hello!

*Please use proper formatting when posting code / logs.*

> But, of course, consumer doesn't shut down cause it isn't running.

The logs above clearly state that supervisor is attempting to shut down the consumer, and does so successfully (exit code 0)

I have no idea. Might be an issue with permissions. This might especially the case when you tried to run `python3 manage.py document_consumer` as root.

Out of curiosity, why are you rolling your own container? The docker image on the Hub starts a container that has everything configured properly.

**Comment by doodlemania2** [comment]
Apologies for forgetting the formatting. Thank you for correcting.
I am rolling my own as I'm packaging this most excellent app as a volunteer project for https://cloudron.io. Everything is working great minus this one piece. You're most welcome to see our progress here: https://git.cloudron.io/doodlemania2/paperless-ng.

That makes perfect sense on the permissions - let me see if I can replicate it when running manually as the application user instead of root. Will report back!

**Comment by jonaswinkler** [comment]
Neat!

Just had a quick look, and I don't see where you create that consume directory or ensure that permissions on that are correct. Some notes.

* PAPERLESS_CONSUME_SECRET is not a valid configuration option.
* The entire email support has changed. No more configuring that with environment variables.
* I'll probably swap out `gunicorn` (the wsgi web server that serves paperless) for another server that supports asgi and web sockets, so keep an eye out for changelogs.
* Not sure if it's possible to provide a permanent url that always points towards the latest release. That might surely come in handy here.

**Comment by doodlemania2** [comment]
> * Not sure if it's possible to provide a permanent url that always points towards the latest release. That might surely come in handy here.
Definitely possible - I'd like to set this up to track a named version so we can run our unit tests automatically once I get the app published. That way, each time you do a release, we will update and run our tests and then publish automatically.

Removed the consume_secret and email bits.

Will watch for gunicorn changes!

Still tinkering with the supervisor - tried running it non-interactively as root, no change, but the cloudron lead dev will take a peak and point to where I've gone off the deep end :)

Excited to get this into the store!
