### ISSUE TITLE
Trigger re-parsing or auto-assignment of consumed documents

### ISSUE THREAD

**Issue by peete1311** [jonaswinkler/paperless-ng#44]
Hi there,

first of all - I'm really impressed by the work you did on paperless. I've noticed the issue you opened on the original paperless project and then quickly decided to give it a go. The resource optimizations and feature enhancements you made are quite impressive. Wow!

One thing I'm kind of missing though is - I've now imported a bunch of PDF documents. It all went fine but I went on creating correspondents, document types and tags on-the-fly. Now I've got the most common information in there and I'd like to re-run auto assignment on my existing documents. I didn't (yet) find it in the awesome documentation. Can this somehow be accomplished?

Thank you so much for the great work you're doing with this project!

**Comment by jonaswinkler** [comment]
See document_retagger in the administration section. I think this is what you're looking for. Be aware that the automatic matching algorithm needs some data to work properly and is updated hourly.

**Comment by peete1311** [comment]
Oh great, that's some more good news for me. Thanks!
