### ISSUE TITLE
Web-UI Login not working after installation

### ISSUE THREAD

**Issue by igno2k** [jonaswinkler/paperless-ng#441]
Hi there,

I have followed the setup guide "Install Paperless from Docker Hub" and installed the PostgreSQL / Tika version on an Archlinux x86 server.

After creating the supervisor user everything seems to run normally.

But I cannot login to the Web-UI via HTTP - it will stuck on "Loading".

This is the error I see in in Docker container logs:

```172.18.0.1 - - [25/Jan/2021:10:08:03 +0000] "GET / HTTP/1.1" 200 769 "http://192.168.1.2:8000/accounts/login/?next=/" "Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36"
[2021-01-25 10:08:04 +0000] [40] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 190, in handle_request
    util.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 625, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 396, in write_file
    if not self.sendfile(respiter):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 386, in sendfile
    sent += os.sendfile(sockno, fileno, offset + sent, count)
OSError: [Errno 22] Invalid argument
```

I tried it with several browsers and clients (Desktop/mobile) without luck.

I have also tried the Paperless Android app - it runs fine! I can also add files via consumer directory.

Any idea whats wrong?

**Comment by jonaswinkler** [comment]
Did you use any additional configuration options in `docker-compose.env`? Any modifications made to `docker-compose.yml`?

**Comment by igno2k** [comment]
Here are the changes I've made:

docker-compose.env:
```34c34
< #PAPERLESS_OCR_LANGUAGE=eng
---
> PAPERLESS_OCR_LANGUAGE=deu
```
docker-compose.yml:
```
67,68c67,68
<       - ./export:/usr/src/paperless/export
<       - ./consume:/usr/src/paperless/consume
---
>       - /tank/docs/export:/usr/src/paperless/export
>       - /tank/docs/in:/usr/src/paperless/consume
```

**Comment by jonaswinkler** [comment]
* This is an issue with the webserver used in the docker container (`gunicorn`).

Is there anything unusual about your networking setup? This error might indicate that the web server is unable to write responses to the connection socket.

* I searched for similar issues with gunicorn, but couldn't find anything.
* The current development branch of gunicorn made changes to the code that's causing this issue; that might change things. Not sure about their release cycle.

However: I'll swap out `gunicorn` for a different server soon. If this issue is really caused by the current web server and not some configuration issue, doing so will probably resolve this issue.

**Comment by igno2k** [comment]
I have disabled iptables (set `"iptables": false` in `/etc/docker/daemon.json`). Otherwise docker breaks my kvm bridget networking setup. Maybe this setting causes the problem.
Will try out later with iptables enabled and give you a feedback.

**Comment by igno2k** [comment]
If I use docker without zfs storage it seems to work fine (tested on the same host and on a different one).

I have found someone with similar problems. This could be fixed by starting gunicorn with the parameter --no-sendfile

But I have no clue how to change the webserver container to start gunicorn with this parameter. Could you help me?

**Comment by igno2k** [comment]
Found a fix by myself: I have set the environment variable SENDFILE to 0 for the webserver container via the docker-compose.yml - now it works fine!

**Comment by jonaswinkler** [comment]
Great. I'd have suggested to download `gunicorn.conf.py`, modify that (`sendfile = False`), and bind mount that  to the appropriate location, but this works as well.
