### ISSUE TITLE
RSS and OPDS read-only endpoints?

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#443]
_Hi, first let me say, that I see that this feature makes a lot of work, even if you use existing packages. I like just to present the idea, so others might want to support it._

[RSS feeds](https://en.wikipedia.org/wiki/RSS) are a common way to get listings and updates for hierarchical content. By polling this XML documents, client software can browse content libraries and analyse documents metadata catalogues. It's still in use for blogosphere, news planets, podcasts, ...

[OPDS](https://en.wikipedia.org/wiki/Open_Publication_Distribution_System) 1.2 makes use of RSS and [Dublin Core](http://dublincore.org/specifications/) schemas originally to share ebook libraries with client software. There is opensource software as calibre to selfhost your personal ebook library. But the concept is flexible as well and can be used for any platforms which share documents, so to subscribe to technical / research / political portals.

I suggest to add both features with different endpoints, so users can subscribe to changes on documents
- by tag
- by contact
- by type
- by create-date, scan-date

OPDS itself adds ability to perform full text search and discovery & navigate trough the catalog.
For RSS there is the Django syndication framework, which allows custom model customization, following different formats.
For OPDS it is possiible to use the same framework, but there are also some Django projects which implement it already [SOPDS](https://github.com/mitshel/sopds), [pathagar](https://github.com/PathagarBooks/pathagar), ... , python as [calibre-web](https://github.com/janeczku/calibre-web) and there are also addons to calibre or nextcloud to spread documents.

IMHO paperless can benefits to implement this standards, so (external) users and scripts on different hosts to trigger on added content and to work with listings. It allows to access, read and search & navigate trough hierarchies via existing native apps esp. for non mainstream OS (coolreader, fbreader, libera, ...) and via ebook reader hardware (kindle, kobo, tolino, ...). I think they are easier to use by non tech users, which don't maintain the setup. And a DMS is usually used by many more users to search & consume documents, than by only a limited amount of users add the documents or have to curate them.
This interface might also allow to cascade & federate between different paperless instances to find documents in a global manner.

**Comment by jonaswinkler** [comment]
I believe you're thinking bigger than I am. A Paperless instance isn't really supposed to be shared across hundreds of users, and I see limited benefit for adding these interfaces to paperless.

Of course, if someone wants to implement (*and maintain*) that feature, sure, why not.

**Comment by jonaswinkler** [comment]
Closing this as out of scope.
