### ISSUE TITLE
Consuming stops, when Mail-Task starts

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#446]
Still migrate lots of Documents via Consumer to paperless-ng (Docker, Version 1.0.0, using inotify for consumer). When i put Documents (10-50) into the consumer-folder the consumer starts consuming. But when the task paperless_mail.tasks.process_mail_accounts starts while consuming, consuming stops and all waiting documents in the consumer-folder will not be consumed.  I have to restart paperless to start the consuming process again or copy the doc to another folder and back to the consuming folder.

**Comment by jonaswinkler** [comment]
* How many CPU cores?

Paperless runs background tasks in parallel, if possible. Both mail checking and document consumption are background tasks. I might have to adjust the defaults here.

In the menatime, you can also adjust `PAPERLESS_TASK_WORKERS` to a higher number (up to your cpu core count) to have paperless do things in parallel.

**Comment by andbez** [comment]
Cpu-Cores: 4 (Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz)

I will try with 2/2 for Workers/per Worker.

**Comment by andbez** [comment]
Worked with the new Parameters. Thx!

**Comment by jonaswinkler** [comment]
I'll adjust the defaults then and close this after that.
