### ISSUE TITLE
[BUG] Filesize issue

### ISSUE THREAD

**Issue by sowoi** [jonaswinkler/paperless-ng#475]
**Describe the bug**
I tried to upload a PDF that is about 70 MB in size via the web interface. During the upload the message appears that an error has occurred. Unfortunately, the logs do not say anything. When I copy the same file to the consumer directory, this file is simply ignored. Is there a file size limit? Is there a way to adjust it? 

The same file is accepted in compressed size without any problems.

**To Reproduce**
I tried to upload a PDF that is about 70 MB in size via the web interface. During the upload the message appears that an error has occurred. Unfortunately, the logs do not say anything. When I copy the same file to the consumer directory, this file is simply ignored. The same file is accepted in compressed size without any problems.

**Expected behavior**
No file size limit

**Webserver logs**
```
Webserver logs doesn't show anything.
```

**Relevant information**
 - Debian 10
 - Firefox
 - Version [e.g. 1.0.0]
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: no

**Comment by jonaswinkler** [comment]
Cannot reproduce with an 80MB file and your environment.

* Regarding the logs: turn on DEBUG logging on the front end and see if there's anything noteworthy.
* Also see if docker itself produces any relevant logs by running paperless without "-d", e.g. "docker-compose up". This way, you'll be able get more detailed logs.

Also, paperless will have much better notifications about error messages in the next version.

**Comment by sowoi** [comment]
I suspect something didn't work with the initial upload and something was blocked as a result. 
I have now renamed the 70 MB PDF and now the upload works. 
Maybe it is also because I restarted the instance with docker-compose up. 

There was nothing in the logs even in DEBUG mode at the time of the initial upload. As if I had never uploaded the file. 

FYI:
There was a message here somewhere in the bug reports that someone had a similar problem caused by a limit on NGINX.  I use NGINX only as reverse proxy. Even when uploading directly without reverse proxy it didn't work. 

However, thank you for your efforts. I switched from papermerge to paperless-ng and I don't regret it.

**Comment by jonaswinkler** [comment]
Maybe #239 is related to this?

**Comment by jonaswinkler** [comment]
With nginx, I had to include the following configuration for larger files:

```
http {
    client_max_body_size 100M; <-- configure as needed
}
```

If that same file is not getting picked up from the consumption folder, that's a different issue.

**Comment by jonaswinkler** [comment]
Please re-open if this is still an issue.
