### ISSUE TITLE
Docker Image: use a more recent version of binary dependencies.

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#48]
Paperless-ng uses tesseract 4.0.0. It gets the job done, but a more recent version would be nice. Same goes for ghostscript, magick, etc.

The issue is as follows.

- Paperless-ng requires numpy.
- In order to install paperless on the Raspberry Pi within a reasonable time (I've heard people use this on the Pi), numpy needs to be pulled from https://www.piwheels.org/. For this to work, python-3.7 is required, since there is no python-3.8 wheel for numpy on ARM. Building the wheel on Pi requires several additional dependencies and many hours of compilation time.
- Therefore, a base image with python-3.7 has to be used, which will also imply that older versions of other binaries get installed.

Any pointers on how to fix this situation while still using python 3.7 are appreciated.

**Comment by totti4ever** [comment]
Does the compiled numpy version work together with python-3.8 once it is installed? So the problem is having the compiled numpy and python 3.8 together in an image?

And all of this would be in a special (i.e. separate) image for the Pi, right?

**Comment by jonaswinkler** [comment]
No, python wheels / binary packages only work with the python version they were compiled for. Therefore, python 3.7 has to be used.

**Comment by totti4ever** [comment]
So, it is about numpy's dependencies? So having both python versions installed is no option?

**Comment by tido-** [comment]
Duplicate of #151  ?   And fixed by now?

**Comment by jonaswinkler** [comment]
No, tesseract still at 4.0.0.

**Comment by jonaswinkler** [comment]
Updated tesseract to 4.1.1.
