### ISSUE TITLE
[Feature Request] Pop-out modal to preview documents from search / view

### ISSUE THREAD

**Issue by jovandeginste** [jonaswinkler/paperless-ng#487]
I am often checking a number of similar documents (from the thumbnail view) to find the correct one in a search query. This means clicking on the "edit" or "open in browser" button, then on the back button if it's not the one I was searching.

This causes a number of first-world-issues (that may or may not need fixing too), such as:

- extra page loads
- forgetting which results-page I was on when going back
- forgetting already-selected documents

I solve this by middle-clicking the preview button to open in new tabs. It also somewhat breaks immersion (for what that's worth) by opening the PDF in full view (in the browser).

I would like a way to open previews (the full PDF is okay) in a modal-style popup, which pops (partially, but mostly) over the current view / search results. Perhaps it can have "next" / "previous" links to show the next / previous document in the list.

A quick search brought this (using Bootstrap): http://dotnetqueries.com/Article/162/how-to-display-pdf-in-bootstrap-modal-popup

**Comment by jonaswinkler** [comment]
Very good idea!

**Comment by shamoon** [comment]
Obviously if the community wants this Im good with that but personally Im not sold on it. Perhaps its that my workflow is a little different in that I usually have found the doc I want by the time I click the preview button, in which case I'd rather just open it as large as possible. Seems like this change just basically prevents the need to command-click (i.e. open in a new tab) for the sake of increasing 'immersion' (as OP noted, not sure thats such a user-centric goal. Not saying Im against it but not yet convinced. We could put this behind a preference flag (though we are accruing a bunch of these random flags but maybe thats OK)?

One other thought: what if we implement this as a 'popover' that appears on hover for ~1s, then the user gets a larger preview of the document but we can retain the click to open. The biggest disadvantage i can see is that I think the next / previous buttons wouldn't work. Here's a **quick** video to illustrate:

https://user-images.githubusercontent.com/4887959/106630819-049af880-6531-11eb-96ee-d0aebd8400fe.mov

Whatever direction is decided, happy to help with this one!

**Comment by jonaswinkler** [comment]
Well, if at all, it should be a modal that spans the entire screen vertically and also darkens the background like the other modals.

I could see this working. Not sure yet.

**Comment by shamoon** [comment]
Well yes, popover is an alternative. Feels less proscriptive IMHO. using hover still makes it easy & useful. But yea, whatever folks think

**Comment by shamoon** [comment]
I know you think modal but Im actually really liking the popover implementation. Modals are just so invasive I feel like if you want to explore the document that closely just open it. You know, IMHO =)

In case you want to try this out I published a branch. Theres a delay on hover so its not always popping up unintentionally, e.g. if youre planning to click the preview button but its also very easy to access the preview as it requires 0 clicks. I also use that hover delay to 'pre-load' the content which often makes it popup seamlessly (both native viewer and `pdf-viewer`).

Again, GitHub has similar popover previews and I really enjoy them for similar reasons. https://github.com/shamoon/paperless-ng/tree/feature/popover-previews
(That branch isnt done but not far off I think)

https://user-images.githubusercontent.com/4887959/107131236-7c4a8980-6889-11eb-9adb-e0436c9d39e5.mov

**Comment by jovandeginste** [comment]
In case you were waiting for my opinion: I have no strong opinion here... So I'm willing to go with whatever you come up with, and iterate over that solution.

Maybe, just maybe, an option to pick the "size" of that preview pop-out (eg. small, medium, large) might help people with different workflows achieve their own goals?

**Comment by shamoon** [comment]
After playing with the preview in my dev version I've found myself missing it on the official one, Im sold on its usefulness.

Having a toggle for the popover size does sound useful, maybe just small vs large

**Comment by jovandeginste** [comment]
> After playing with the preview in my dev version I've found myself missing it on the official one, Im sold on its usefulness.
> 
> Having a toggle for the popover size does sound useful, maybe just small vs large

Sure, we can probably add more later (aka iterate) if the need is really there: the hard work will be done already. And, since it's open source, I could add/change my own size-preset in my copy of the code base easily. I just have a strong preference for built-in solutions: less chance of breaking in the long run.

**Comment by d8sychain** [comment]
I can definitely see this being useful in my workflow. I'm using Paperless to help manage business receipts (and it's been great I might add). Some receipts are on small slips of paper, others are printed on 8.5x11 paper. Occasionally I need to go back and see the cost of a specific item real quick. IMHO the preview pop-out would help speed up this workflow.

**Comment by jovandeginste** [comment]
So happy to see this land! It's really nice!! Thanks!
