### ISSUE TITLE
Django Q with ORM broker?

### ISSUE THREAD

**Issue by jayme-github** [jonaswinkler/paperless-ng#49]
I was wondering if you decided to use redis as default broker because you had issues with the [Django ORM](https://django-q.readthedocs.io/en/latest/brokers.html#django-orm) broker?

I would have guessed that the ORM broker is good enough for the majority of paperless setups and it would remove the need to run redis.

**Comment by jonaswinkler** [comment]
The ORM broker would be in fact good enough and would allow some easier monitoring in the admin, however, I've also had an idea about displaying the consumer progress (especially the OCR part) on the dashboard. That would be done with web sockets and requires a broker to get messages from the consumer to the web sockets, and the framework used for that (django-channels) supports redis. So I'm sticking with that for now.

**Comment by jayme-github** [comment]
I see, thanks for clarifying!
