### ISSUE TITLE
[BUG] Doesn't remember PDF-viewer setting

### ISSUE THREAD

**Issue by praul** [jonaswinkler/paperless-ng#495]
Hey, thanks for introducing the setting to switch back to the built-in embed pdf-viewer.
However, the system does not remember the setting. If I close the session, it is set back to default.

I am using two containers with cookie-prefix, if that is an information you may need.

Thank you :)

**Comment by jonaswinkler** [comment]
> If I close the session

What exactly do you mean?

Settings are not stored on the server (yet), so if you remove some local data in your browser (depends on what closing the session means), that's to be expected.

**Comment by praul** [comment]
Okay, I see. It is somehow saved in browser cache, not in cookies? The setting is gone, once I clear the cache.

**Comment by jonaswinkler** [comment]
This is called `localStorage` and yes, that's stored inside your browser.

After thinking a bit about that, I don't want to store settings on the server. Might be that you want to use different settings on different browsers.
