### ISSUE TITLE
[Feature Request] Custom CSS

### ISSUE THREAD

**Issue by praul** [jonaswinkler/paperless-ng#496]
Hi :)
Could we have an option for adding custom css to paperless-ng. Preferably as a text-field somewhere @ settings?

Thank you :)

**Comment by jonaswinkler** [comment]
What exactly do you want to do with that?

**Comment by praul** [comment]
For now, I have very long tag names, I use them to sort out my contracts. So 
![image](https://user-images.githubusercontent.com/38807639/106706918-ae8d8a00-65f0-11eb-8d95-cbd750ebdbde.png)

Personally, I can live with the rest of the tags being cut, so I would apply
max-width: 180px to .badge
![image](https://user-images.githubusercontent.com/38807639/106707092-f4e2e900-65f0-11eb-93c4-b4964e24531f.png)

Apart from that, since I use two instances of paperless-ng, I would probably change the accent color on one, so I can directly see, where I am.

I can do this with an browser extensions, but I always like custom css fields :)

**Comment by jonaswinkler** [comment]
> For now, I have very long tag names, I use them to sort out my contracts.

That's an issue that doesn't need custom css, I need to fix that for everyone.



> Apart from that, since I use two instances of paperless-ng, I would probably change the accent color on one, so I can directly see, where I am.
> 
> I can do this with an browser extensions, but I always like custom css fields :)

I don't want to add a custom css field, since most people would not even know how to use that or what to use that for. However, a way to change the accent color of paperless surely sounds nice.

**Comment by praul** [comment]
Fine by me :)
I can still mount my own css in the docker container :)
I suppose this is the right one?
/usr/src/paperless/static/frontend/[LANG]/styles.css
