### ISSUE TITLE
Python dependencies

### ISSUE THREAD

**Issue by ThisIsTenou** [jonaswinkler/paperless-ng#497]
A bare-metal install requires the following package for launchpadlib to function properly aswell:
`python3-testresources`

This is being indicated by the following line when installing the python requirements in step 7:
`ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.`

Additionally, the specified version of python-levenshtein (0.12.0) is affected by security vulnerabilites and should be changed to 0.12.1.

I also believe, it should be made clearer that the steps 7-9 have to be run as the paperless user and that this requires the user to have a home directory.

**Comment by jonaswinkler** [comment]
> A bare-metal install requires the following package for launchpadlib to function properly aswell:
> `python3-testresources`

Not exactly sure where that comes from; Paperless does not depend on `launchpadlib`, it's not part of the requirements files, and not installed in any of my virtual environments.



> Additionally, the specified version of python-levenshtein (0.12.0) is affected by security vulnerabilites and should be changed to 0.12.1.

Thanks for letting me know, will update dependencies soon.



> I also believe, it should be made clearer that the steps 7-9 have to be run as the paperless user and that this requires the user to have a home directory.

Probably, yes. Will look into that. The bare metal setup isn't exactly a step by step guide right now that can be executed blindly.

**Comment by jonaswinkler** [comment]
Closing this as the package has been updated and I don't have any info on launchpadlib.
