### ISSUE TITLE
Error Cannot Consume.... It is not a file

### ISSUE THREAD

**Issue by VonHohenheim** [jonaswinkler/paperless-ng#505]
Pretty much every file uploaded via the upload drag-and-drop section or consumption folder generates this error. Despite the error the file still able to upload and is stored correctly.

![image](https://user-images.githubusercontent.com/10605309/107103651-a80f3600-67db-11eb-987f-0216f78755d0.png)

![image](https://user-images.githubusercontent.com/10605309/107103760-020ffb80-67dc-11eb-9493-11731692e3a8.png)

**Comment by jonaswinkler** [comment]
Hello!

Please provide more information about your system and installation method. Host OS, docker used, and if so, did you change anything in the configuration files? Where are your volumes stored?

**Comment by jonaswinkler** [comment]
Furthermore: You indicated that you upload files using the file drop box on the dashboard. However, these messages indicate that paperless can't files in the consumption folder, and that's not where paperless stores uploaded files.

**Comment by VonHohenheim** [comment]
@jonaswinkler I'm going to close this issue. Updated to v1.1.0 and I the error is not being thrown anymore. Many thanks.
