### ISSUE TITLE
[BUG] Documentation footer still reads "© Copyright 2015, Daniel Quinn."

### ISSUE THREAD

**Issue by fdw** [jonaswinkler/paperless-ng#506]
**Describe the bug**
In the online documentation (https://paperless-ng.readthedocs.io/en/latest/), the footer still reads "© Copyright 2015, Daniel Quinn." I think this is wrong 😉

**To Reproduce**
1. Go to https://paperless-ng.readthedocs.io/en/latest/
3. Scroll down to the footer

**Expected behavior**
I expected to see at least "2021", but maybe also some other names.

**Comment by jonaswinkler** [comment]
I'm not very well versed in these things.

It probably should say "(c) 2021, Daniel Quinn, Jonas Winkler", right?

**Comment by fdw** [comment]
I'm not a lawyer, either, but I can see several possible variants:
* "(c) 200x - 2019 Daniel Quinn, (c) 2020 - 2021 Jonas Winker"
* "(c) 2021 Daniel Quinn, Jonas Winkler and others"

Also, I don't think you need the copyright notice at all if you don't want it.

**Comment by jonaswinkler** [comment]
alright, changed.
