### ISSUE TITLE
[BUG] mail_fetcher management command results in 'File not found' errors with docker installation

### ISSUE THREAD

**Issue by nroach44** [jonaswinkler/paperless-ng#509]
**Describe the bug**
After setting up a new docker-compose postgres instance, and configuring the email account and a simple "mark read when done" import rule, new documents are found, marked as read, but fail to import. I've completely re-setup the image to confirm and it still performs the same way

**To Reproduce**
1. Install pre-reqs on a Debian 10 VM
2. Download source
3. CD into docker/compose
4. cp docker-compose.postgres.yml  to docker-compose.yml
5. Change no details in the documents other than the UID
6. sudo docker-compose pull
7. sudo docker-compose up -d
8. sudo docker-compose run --rm webserver createsuperuser
9. Log in
10. Add basic IMAP 993 email account
11. Add basic "grab attachment, mark read when done" mail rule
12. Add scanned documents (attached to email in PDF format) into email account, marked unread
13. sudo docker-compose run --rm webserver mail_fetcher
14. Observe the errors above in either the docker console or in the failed tasks page.

**Expected behavior**
PDF attachments should have imported without error.

**Webserver logs**
```
Name:
image.pdf
Func:
documents.tasks.consume_file
Hook:
-
Args:
Kwargs:
{'path': '/tmp/paperless/paperless-mail-zonwbc_l', 'override_filename': 'image.pdf', 'override_title': 'Scanned document', 'override_correspondent_id': None, 'override_document_type_id': None, 'override_tag_ids': None}
Result:
image.pdf: Cannot consume /tmp/paperless/paperless-mail-zonwbc_l: File not found. : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 82, in consume_file
task_id=task_id
File "/usr/src/paperless/src/documents/consumer.py", line 185, in try_consume_file
self.pre_check_file_exists()
File "/usr/src/paperless/src/documents/consumer.py", line 88, in pre_check_file_exists
f"Cannot consume {self.path}: File not found."
File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: image.pdf: Cannot consume /tmp/paperless/paperless-mail-zonwbc_l: File not found.
```

**Relevant information**
 - Host OS of the machine running paperless: Debian 10
 - Browser: Firefox
 - Version: 78
 - Installation method: docker-compose
 - Any configuration changes you made in `docker-compose.yml` (none), `docker-compose.env` (uncommented UID and GID) or `paperless.conf` (none).

**Comment by jonaswinkler** [comment]
Do files uploaded on the dashboard also raise this error?

**Comment by nroach44** [comment]
Nope. I used a file from one of the emails to be sure:

```
webserver_1  | 10:56:37 [Q] INFO Enqueued 1
webserver_1  | 10:56:37 [Q] INFO Process-1:1 processing [image.pdf]
webserver_1  | [2021-02-07 10:56:37,484] [INFO] [paperless.consumer] Consuming image.pdf
webserver_1  | [2021-02-07 10:57:14,974] [INFO] [paperless.consumer] Document 2021-02-03 image consumption finished
webserver_1  | 10:57:14 [Q] INFO Processed [image.pdf]
```
As compared to one from earlier (since the one above is missing context):

```
webserver_1  | 08:28:31 [Q] INFO Process-1:1 processing [image.pdf]
webserver_1  | [2021-02-07 08:28:31,398] [ERROR] [paperless.consumer] Cannot consume /tmp/paperless/paperless-mail-gi6fw08i: File not found.
webserver_1  | 08:28:31 [Q] ERROR Failed [image.pdf] - image.pdf: Cannot consume /tmp/paperless/paperless-mail-gi6fw08i: File not found. : Traceback (most recent call last):
```

**Comment by jonaswinkler** [comment]
Thank you! Confirmed.

1. Note that this only happens with the mail_fetcher command.
2. This does not happen when paperless runs the mail fetcher on its own internal 10 minute schedule.

On a side note, you should not need to use sudo for any of the commands.

**Comment by nroach44** [comment]
@jonaswinkler  Aha, thanks for narrowing it down!

I found that when running the first docker-compose command it failed with permissions denied as a normal user, so I just defaulted to sudo for the time being (not experience with docker at all, so just trying to get stuff working).

I'll see if I can confirm that issue separately, at a later date.

Cheers!

**Comment by jonaswinkler** [comment]
Another alternative for running the mail fetcher manually is

```
docker-compose exec -u paperless webserver python3 manage.py mail_fetcher
```

The reason why `docker-compose run` fails is that `run` starts a new temporary container. That container and the container that runs paperless don't share the `/tmp` folder. The file is put in `/tmp` in the temporary container, and paperless expects to find it there in its own container, which does not work.

I should probably advertise the above call as the proper method to invoke management commands manually.

**Comment by nroach44** [comment]
I did notice that it seemed to be doing everything again and was wondering...

Thanks a lot for looking into it!
