### ISSUE TITLE
Automatic tag and correspondent colors

### ISSUE THREAD

**Issue by jayme-github** [jonaswinkler/paperless-ng#51]
Inspired by what for example Grafana does (and due to the limited set of colors available in paperless), I patched it to auto-color tags and correspondents with a https://github.com/zenozeng/color-hash like implementation:

- https://github.com/jayme-github/paperless/commit/db0390cff12efe6bdb5d53d75a6b46d2016f0953
- https://github.com/jayme-github/paperless/commit/9def166811a0caec3adfe0c7b481390e174b462d

I understand that people might like choosing the colors themselves, so feel free to close this. :smile: It's just that I don't care about the actual color of tags, I just want them to have different ones and I don't want to bothered with selecting them.

**Comment by jonaswinkler** [comment]
Nah, I like having red TODO and missing_date tags :)

**Comment by totti4ever** [comment]
But couldn't this be used to set the initial color for new tags? @jonaswinkler
