### ISSUE TITLE
[BUG] OCRmyPDF rotate_pages is not working 

### ISSUE THREAD

**Issue by seeers** [jonaswinkler/paperless-ng#515]
I tried to set the option `{"rotate_pages": true, "rotate_pages_threshold": 10}` via ENV `PAPERLESS_OCR_USER_ARGS`.
Unfortunately, a page rotated by 180 ° is not automatically rotated correctly when it is made available in the consumption directory.

when I call ocrmypdf directly the page is rotated:
**ocrmypdf -l deu --rotate-pages --rotate-pages-threshold 10 abs.pdf out.pdf**

**Relevant information**
 - Host OS of the machine running paperless: Debian / Docker
 - Version [e.g. 1.1.0]
 - Installation method: docker

**Comment by jonaswinkler** [comment]
Part of #246. I know that certain options are incompatible right now.
