### ISSUE TITLE
Multi-User options

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#52]
Hey, I was wondering whether there was an idea how to cope with the situation of multiple users (i.e. wife and me) with common documents plus those which are not of interest for the other one (does not necessarily mean a physical protection)

Would tags plus user defined dashboards be the answer? Would that be possible already today?

Cheers

So I set ng up and had a look. I found groups and users, but can't really do anything besides allowing admin access for users. Plus changelog says they should have been removed in 0.4?

**Comment by jonaswinkler** [comment]
Simple solution: have a tag for both of you that marks documents private for you. We'd need an additional filter ("Does not have tag X"), so each of you could save a filter that does not show these documents. However, that's not ideal.

We could investigate limiting the documents users get to see based on the metadata they have. For example, you could define a rule so that your wife does not get to see whatever is tagged with "private".

However, I don't have a need for that, so we have to get some more input on what's actually needed and figure out a solution that's versatile enough to meet the needs of everyone.

I've enabled user management simply so that you can change your password. It's not integrated with anything as of now.

**Comment by totti4ever** [comment]
What is great is that you can already add different users and they can have their own views! Guess this might already be enough for me right now.

Maybe a quick win could be to enable admins to attach a default filter to a user like `tag not contains xx`. This is kind of similar to Jira's boards. If that somehow plays together with the normal searches and so on (additive) this could be nice?!

**Comment by jonaswinkler** [comment]
Before jumping onto anything I'd like to see if django's built-in permission and authorization system can be extended to fit our needs.

**Comment by Exordian** [comment]
I'd also be interested in such a feature as well as i'd be fine with the simple solution to filter specific tags (default search filter) for other users.

btw thanks for your work on paperless-ng !

**Comment by jonaswinkler** [comment]
Hello, and thanks for your interest in the project and your suggestions!

--> I'm not feeling too excited about adding new entity types to paperless, if it's not absolutely necessary. That doesn't mean that I wont implement this, I'm just trying to work with what we already have and go for simple, yet versatile solutions. 

The ideas in the PR don't look to promising. A document can belong to multiple users.

Right now, I'm thinking about something like this:

- Ability to define inclusive / exclusive rules based on metadata in the admin. Think about: define a set of tags/correspondents/document types for a user and then have a switch that selects whether that user has access only to documents with selected metadata (inclusive), or to all documents except those with the selected metadata (exclusive).

- This comes with its fair share of implications.
  1. The user can only see documents when everything matches. When a users is allowed to see the correspondent, but not a specific tag of a document, it is not shown.
  2. The user can only assign metadata for which access is configured.
  3. With inclusive rules: When the user creates new metadata, the users must automatically gain access to that metadata as well.
  4. When creating metadata: If the user chooses a name that already exists but is inaccessible to them, they'll get a weird error message. With multi user systems, There should be no way to figure out what other data exists in the system.

--> You see, this isn't all that easy. Honestly, I am wondering if it's really necessary to have a system that enforces this kind of stuff. You could just use saved views.
