### ISSUE TITLE
[BUG] Unable to process JPG file

### ISSUE THREAD

**Issue by mikkelnl** [jonaswinkler/paperless-ng#531]
I added a JPG file (a photo of a document) but got this respons:

[ERROR] [paperless.consumer] Error while consuming document IMG_0821.jpg: SyntaxError: not a TIFF file (header b'http://n' not valid)

I added this file via the webinterface, running latest version.

**Comment by jonaswinkler** [comment]
Is there anything special about this image? Did other images from the same source get processed correctly?

Are you sure that this is a JPG file and not a TIFF file? What does the command `file IMG_0821.jpg` say?

Are you able to share the file?

This is most likely

* An issue with one of the libraries python uses for image processing, or
* An issue with the image itself, as the message suggests.

If anything, I could forward this issue to `Pillow`, which is the library that's responsible for  image processing. But they'd also need the file to do anything.

**Comment by mikkelnl** [comment]
Weird! I tried a different JPG, and that went fine, I'll check if there's anything strange with the first one.

**Comment by mikkelnl** [comment]
When I rotate the JPG to portrait (it was landscape), it works fine... ;-)

**Comment by jonaswinkler** [comment]
That's probably because the software that you used for rotating saved the file again, and by doing so fixed the error in the file.
