### ISSUE TITLE
[BUG] 1012_fix_archive_files migration fails

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#534]
**Describe the bug**

After updating the paperless-ng docker container from `v1.1.0` to `v1.1.1` the container stops with the following exception in the docker logs:

```bash
Paperless-ng docker container starting...
Mapping UID and GID for paperless:paperless to 99:100
creating directory /tmp/paperless
Apply database migrations...
Operations to perform:
Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
Traceback (most recent call last):
File "manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
res = handle_func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 245, in handle
fake_initial=fake_initial,
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
state = migration.apply(state, schema_editor)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
self.code(from_state.apps, schema_editor)
File "/usr/src/paperless/src/documents/migrations/1012_fix_archive_files.py", line 244, in move_old_to_new_locations
f"Archived document ID:{doc.id} does not exist at: "
ValueError: Archived document ID:191 does not exist at: /usr/src/paperless/src/../media/documents/archive/2018-02-01-Acorrespondent-ATitle.pdf
Applying documents.1012_fix_archive_files...*Paperless-ng docker container starting...
creating directory /tmp/paperless
Apply database migrations...
Operations to perform:
Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
Traceback (most recent call last):
File "manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
res = handle_func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 245, in handle
fake_initial=fake_initial,
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
state = migration.apply(state, schema_editor)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
self.code(from_state.apps, schema_editor)
File "/usr/src/paperless/src/documents/migrations/1012_fix_archive_files.py", line 244, in move_old_to_new_locations
f"Archived document ID:{doc.id} does not exist at: "
ValueError: Archived document ID:191 does not exist at: /usr/src/paperless/src/../media/documents/archive/2018-02-01-Acorrespondent-ATitle.pdf
Applying documents.1012_fix_archive_files...
```

```bash
root@server:~# ls /mnt/user/paperless-ng/media/documents/archive/ | grep Acorrespondent
2015-12-31-Acorrespondent-other1.pdf
2018-02-01-Acorrespondent-ATitle.pdf
2018-10-06-Acorrespondent-other2.pdf
```

**To Reproduce**

1. Upgraded the docker container from `v1.1.0` to `v1.1.1`
2. Started the container
3. Checked the docker logs

Same behavior every time I restart the container

**Expected behavior**

The container starts successfully 

**Relevant information**
 - Host OS of the machine running paperless: Unraid 6.8.3
 - Browser: Firefox
 - Version: `v1.1.1`
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: `PAPERLESS_FILENAME_FORMAT={created}-{correspondent}-{title}`

**Comment by jonaswinkler** [comment]
Well, I've verified that this works both with test cases and on multiple docker and bare metal setups. So...

* This indicates that files that should be present are not there.
* Are you certain that the folder you posted is actually the folder that gets mounted as a volume in the container by docker?

**Comment by Tooa** [comment]
Thanks for your reply. The mapping is as follows:

```bash
/usr/src/paperless/data - /mnt/user/appdata/paperless-ng/data
/usr/src/paperless/media - /mnt/user/paperless-ng/media/
/usr/src/paperless/consume - /mnt/user/paperless-ng/webdav-consume/paperless-ng-inbox/
/usr/src/paperless/export - /mnt/user/paperless-ng/export/
```

Maybe an encoding issue, because the document title contains the German character `Ü` (2018-02-01-Acorrespondent-ATitle.pdf = 2018-02-01-1und1-Kündigung.pdf)?

```
root@server:~# ls /mnt/user/paperless-ng/media/
documents/  media.lock  
root@server:~# ls /mnt/user/paperless-ng/media/
documents/  media.lock*
root@server:~# ls /mnt/user/paperless-ng/media/documents/
archive/  originals/  thumbnails/
root@Zeus:~# ls /mnt/user/paperless-ng/media/documents/archive/ | grep 1und1
2015-12-31-1und1-other1.pdf
2018-02-01-1und1-Kündigung.pdf
2018-10-06-1und1-other2.pdf
```

**Comment by jonaswinkler** [comment]
* /usr/src/paperless is where everything of paperless is stored in the image.
* the additional src subdirectory is where the python source files of paperless reside.
* This subdir is also the base directory, and all other directories are derived from that. For example, the media directory is <basedir>/../media by default.
* I could normalize these paths, but I'm not sure how not doing that could cause this issue.

Furthermore:

* Upgrades with files containing umlauts works over here. What file system are you working on?

**Comment by Tooa** [comment]
> Upgrades with files containing umlauts works over here. What file system are you working on?

`/mnt/user/paperless-ng` is `XFS` and `/mnt/user/appdata/` is `btrfs`

> It's a safe guard and nothing has been changed yet.

Thanks for letting me know. So, I downgraded to v1.0.0 and the container just starts fine. Web UI is reachable too. Therefore, I would assume my configuration is fine.

**Comment by jonaswinkler** [comment]
I just tried to get that reproduced with a new media volume stored on XFS and with custom uid/git mapping, and your `PAPERLESS_FILENAME_FORMAT`. Migration works fine, including documents with umlauts. So that's not the reason.

* When you open that document in 1.1.0, does the metadata tab correctly report file sizes (and other metadata) for both the archived and original document?

**Comment by Tooa** [comment]
> When you open that document in 1.1.0, does the metadata tab correctly report file sizes (and other metadata) for both the archived and original document?

![issue](https://user-images.githubusercontent.com/5375334/107850234-2f266480-6e01-11eb-9cfb-942db2cc02d2.png)

Looks like the metadata for this document is indeed missing. I checked a few other documents and their metadata is reported correct. Unfortunately, the document was added some time ago and I don't have the document import log. The log might have revealed an issue. Also I cannot find the document in question by its title or added date. However, it shows fine when filtering for its correspondent.

**Comment by jonaswinkler** [comment]
Alright. First of all, not an issue with the migration itself, which is somewhat of a relief. Now I need to figure this out.

Please do the following:

* Find the document in the admin at `http://localhost:8000/admin/documents/document/191/change/`.
* Verify that the reported value for `filename` further down is the actual filename in the originals / archive folder. If not, please report differences.

There's also a sanity checker that checks your document archive for issues. It's not very accessible right now, but please do the following:

* In the Scheduled tasks section, find the task that says "Sanity check", and edit that. Further down, click on "today", and "now", then save.
* Paperless will then run that task within the next minute and report possible errors in the "failed tasks" section.

**Comment by Tooa** [comment]
> Alright. First of all, not an issue with the migration itself, which is somewhat of a relief. Now I need to figure this out.

Sorry for making you worry. I will change the title of the issue once I find a more appropriate one

> Verify that the reported value for filename further down is the actual filename in the originals / archive folder. If not, please report differences.

* Filename as reported by the admin interface: `2018-02-01-1und1-Kündigung.pdf`

```bash
root@server:/mnt/user/paperless-ng/media/documents# ls -ahl archive/ | grep 1und1-K
-rw-r--r-- 1 nobody users 122K Dec 31 17:48 2018-02-01-1und1-Kündigung.pdf
root@server:/mnt/user/paperless-ng/media/documents# file archive/2018-02-01-1und1-Kündigung.pdf 
archive/2018-02-01-1und1-Kündigung.pdf: PDF document, version 1.7
root@server:/mnt/user/paperless-ng/media/documents# ls -ahl originals/ | grep 1und1-K
-rw-r--r-- 1 nobody users 150K Dec 31 17:48 2018-02-01-1und1-Kündigung.pdf
root@server:/mnt/user/paperless-ng/media/documents# file originals/2018-02-01-1und1-Kündigung.pdf 
originals/2018-02-01-1und1-Kündigung.pdf: PDF document, version 1.3
```

Filename seems to match.

> There's also a sanity checker that checks your document archive for issues. It's not very accessible right now, but please do the following ... 

```
The following issuse were found by the sanity checker:
ERROR: Original of document 133 does not exist.
Warning: Document 261 has no content.
ERROR: Original of document 191 does not exist.
ERROR: Archived version of document 191 does not exist.
Warning: Orphaned file in media dir: /usr/src/paperless/media/documents/originals/2018-02-01-1und1-Kündigung.pdf
Warning: Orphaned file in media dir: /usr/src/paperless/media/documents/originals/2020-10-09-correspondent-secret-title.pdf
Warning: Orphaned file in media dir: /usr/src/paperless/media/documents/archive/2018-02-01-1und1-Kündigung.pdf
``` 

* The message `Warning: Document 261 has no content.` is fine
*  Similiar to document `133` the document `133`` has no metadata as well

**Comment by jonaswinkler** [comment]
Does `2020-10-09-correspondent-secret-title.pdf` also contain umlauts?

**Comment by Tooa** [comment]
> Does 2020-10-09-correspondent-secret-title.pdf also contain umlauts?

Yes, I added the original title as edit in my last post. I just stripped away the correspondent.

**Comment by jonaswinkler** [comment]
Are these the only files with umlauts in their name?

**Comment by Tooa** [comment]
> Are these the only files with umlauts in their name?

No, I have for example this file `2010-11-01-correspondent-Kündigungsbestätigung.pdf`. Metadata for this document shows fine and I can open it in the browser.

**Comment by jonaswinkler** [comment]
Alright. I'll try to set up a similar scenario later, and try to reproduce this. Just a few more things (sorry for that, but this is tough to figure out):

* Did you migrate from original Paperless? If so, were those documents added in original paperless?
* Are you using Postgresql?

For now, I'd probably move the reported orphaned documents from the originals directory manually, then delete 133 and 191, and add the originals again.

**Comment by Tooa** [comment]
Thanks for your help!

> Did you migrate from original Paperless? If so, were those documents added in original paperless?

Yes, I migrated from paperless according to the migration guide in the paperless-ng documentation. By looking at the `date added` for both documents (`31.12.20` and `01.11.20`), I can tell that those documents were **not** added in the original paperless.

> Are you using Postgresql?

No, SQLite.

**Comment by jonaswinkler** [comment]
> 01.11.20

Strange, that's before the first release. Early adopter? :)

Anyway, I don't think I can get any more information here, so you might want to do this:

* Move the files noted as orphaned from the media directory
* Delete 133 and 191
* Upload the original documents again and see if that works / if anything is logged / if the sanity checker still issues the errors if executed again.

**Comment by Tooa** [comment]
> Anyway, I don't think I can get any more information here, so you might want to do this:

No issues logged while importing the documents again and sanity checker does not report the issues either. I also successfully upgraded now to `v1.1.1`. Thanks for the troubleshooting.

**Comment by jonaswinkler** [comment]
Alright. This is still weird and any issues regarding missing files immediately ring some alarm bells over here.

**Comment by Tooa** [comment]
> Alright. This is still weird and any issues regarding missing files immediately ring some alarm bells over here.

I will report once I encounter a similar situation. Next time I will also be able to deliver the original file consumption logs as I've store them now in my ELK stack. 

Going to close this issue then as it works for me for now.

**Comment by totti4ever** [comment]
Hey @jonaswinkler, can we please reopen this?

I get exactly the same error. And after deleting the latest added file (after downgrading) I get the error for the doc added before after upgrading again.

So right now, I don't see a chance to upgrade vom 1.1.0 without deleting one after another file and hoping that it stops somewhen?

**Comment by jonaswinkler** [comment]
Hey @totti4ever,

The migration expects your document archive to be in good health (all referenced files present), and cannot work if it's not. If the sanity checker is giving you issues on 1.1.0, and you believe that the raised errors are false, open a new issue and describe your problem.

**Comment by totti4ever** [comment]
I didn't delete files on the file system, I deleted a doc in Paperless. I also never deleted a file before in the file system.

Furthermore, I have no problem downloading the file in question with v1.1.0 - still upgrading to 1.1.1 says, it cannot be found.

I also don't have any sanity problems reported in the log on 1.1.0...
