### ISSUE TITLE
[Other] Let's talk about the legacy problem

### ISSUE THREAD

**Issue by danielquinn** [jonaswinkler/paperless-ng#542]
Hi Jonas, I would have emailed you directly, but you haven't provided your email address here on GitHub and don't appear to have much of a web presence that I can leverage to find direct contact info, so this will have to do :-)

Let's talk about how we can solve the old paperless vs. new paperless-ng thing 'cause the state of things isn't helping anyone.  drop me an email (it's on my GitHub profile) and we can work out a time.  I have what I think is a good plan, but wanna run it by you first.

**Comment by jonaswinkler** [comment]
Drop me a mail at dev@jpwinkler.de. I've had this on my profile for quite some time, but noticed a good increase in spam around the time this picked up some steam. I guess it's too late now :)
