### ISSUE TITLE
[BUG] Mail fetch not working (Exchange, Outlook)

### ISSUE THREAD

**Issue by micadix** [jonaswinkler/paperless-ng#548]
i Just setup paperless-ng, is working fine. i'll cant get the mail fetching working

mail.log says

```
[2021-02-15 17:20:07,853] [ERROR] [paperless_mail] Rule Name: Error while processing rule: Response status "OK" expected, but "NO" received. Data: [b'[BADCHARSET (US-ASCII)] The specified charset is not supported.']

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 172, in handle_mail_account

    total_processed_files += self.handle_mail_rule(M, rule)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 214, in handle_mail_rule

    for message in messages:

  File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 100, in fetch

    nums = tuple((reversed if reverse else iter)(self.search(criteria, charset)))[limit_range]

  File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 61, in search

    check_command_status(search_result, MailboxSearchError)

  File "/usr/local/lib/python3.7/site-packages/imap_tools/utils.py", line 54, in check_command_status

    raise exception(command_result=command_result, expected=expected)

imap_tools.errors.MailboxSearchError: Response status "OK" expected, but "NO" received. Data: [b'[BADCHARSET (US-ASCII)] The specified charset is not supported.']
```

**Comment by jonaswinkler** [comment]
Looks like an issue between the library I use for accessing mail accounts and your mail server not playing nice. I don't think I can do anything about that.

**Comment by micadix** [comment]
> Looks like an issue between the library I use for accessing mail accounts and your mail server not playing nice. I don't think I can do anything about that.

thanks for your reply. can u tell me which mailserver works with your library? any freemailer? thanks

**Comment by jonaswinkler** [comment]
I don't know. I'm using paid mail hosting, but I've heard that some had success using gmail. I don't exactly know what mail providers other users use.

**Comment by anhaehne** [comment]
Outlook only support the charset US-ASCII but you specify UTF-8 in [mail.py#L203](https://github.com/jonaswinkler/paperless-ng/blob/master/src/paperless_mail/mail.py#L203).

Is it possible to make this configurable?

**Comment by git-help-eng** [comment]
@micadix

> can u tell me which mailserver works with your library?

I self-host my mail using postfix/dovecot.  The original Paperless did not seem to be able to do STARTTLS, but with paperless-ng processing of email has worked without issue for me.

**Comment by erkanKR** [comment]
Got the same issue! Like @anhaehne, i got the exception with UTF-8 and US-ASCII.

**Comment by trev142** [comment]
Can confirm that changing the line mentioned by @anhaehne in mail.py to "US-ASCII" works for outlook.com. Would be great to have the charset configurable per mail server :)

**Comment by jonaswinkler** [comment]
@trev142 done!

**Comment by jonaswinkler** [comment]
@trev142 Added in 1.4.4

**Comment by reiniertc** [comment]
> Can confirm that changing the line mentioned by @anhaehne in mail.py to "US-ASCII" works for outlook.com. Would be great to have the charset configurable per mail server :)

In my case, after changing it to US-ASCII I get the error "the specified charset is not supported"

**Comment by trev142** [comment]
@reiniertc definitely works for me. Are you using IMAP server outlook.office365.com? I know when I had the issue, the charset that the server wanted was actually logged in mail.log. Good luck!

**Comment by reiniertc** [comment]
YEs, the imap settings were correct. 
I now installed paperless-ng using portainer directly, using the most recent release of paperless-ng and now the mail fetch works

**Comment by Jonasdero** [comment]
Hi, I am having the issue again also with outlook on the newest paperless version?

How can I fix this?
