### ISSUE TITLE
[Other] Consumer Write Permissions Issue

### ISSUE THREAD

**Issue by naderinho** [jonaswinkler/paperless-ng#571]
Hello,
I am trying to get paperless-ng working on my Synology NAS in Docker. Everything seems to work right, except of the consuption with the consumtion folder. The upload via the WebUI works fine.
After starting the containers i get the following output:
```
System check identified some issues:
WARNINGS:
  ?: PAPERLESS_CONSUMPTION_DIR is not writeable
      HINT: Set the permissions of /usr/src/paperless/consume to be writeable by the user running the Paperless services
```

I mounted a shared folder on my Synology inside /usr/src/paperless/consume

If i try to log in to the console inside the paperless-container to check the file permissions I get the following output:
```
root@paperless:/usr/src/paperless# ls -l                                                                                                                        
total 8                                                                                                                                                         
drwxr-xr-x 1 paperless paperless   56 Feb 18 09:10 __pycache__                                                                                                  
drw-rw-r-- 1 paperless paperless   28 Feb 18 16:21 consume                                                                                                      
drwxr-xr-x 1 paperless paperless   44 Feb 18 13:40 data                                                                                                         
drwxr-xr-x 1 paperless paperless    0 Feb 18 09:09 export                                                                                                       
-rw-r--r-- 1 paperless paperless 1102 Feb 17 18:57 gunicorn.conf.py                                                                                             
drwxr-xr-x 1 paperless paperless   38 Feb 18 16:16 media                                                                                                        
-rw-r--r-- 1 paperless paperless 3540 Feb 17 18:57 requirements.txt                                                                                             
drwxr-xr-x 1 paperless paperless  238 Feb 18 16:16 src                                                                                                          
drwxr-xr-x 1 paperless paperless  160 Feb 17 19:01 static
```
Inside the directory I also can see the files i have uploaded and I can modify them. So i can't see the issue with the writing permissions:
```
root@paperless:/usr/src/paperless/consume# ls -l
total 1604
drwxrwxrwx 1 paperless paperless       8 Feb 18 09:20 @eaDir
-rw-rw-rw- 1 paperless paperless 1639547 Feb 18 16:18 test.pdf
```
According to the first output: the user running the Paperless services should be "paperless" right?
Does anyone has an idea how to solve this problem?
Thank you very much in advance.

**Comment by jonaswinkler** [comment]
Is your consume folder stored on an NFS filesystem?

**Comment by naderinho** [comment]
The NFS service is not activated on my Synology NAS. The file transfer from my scanner to the shared folder uses SMB.

**Comment by jonaswinkler** [comment]
Well, this really is just a warning. While trying to check for write permissions, paperless determined that it does not have write permissions on that folder. However, if everything is working (you can write files into the consumption directory, and paperless deletes them after successful consumption), you can safely ignore this. It's most likely some incompatibility between python, docker, and your specific environment that prevents paperless from properly detecting filesystem permissions.
