### ISSUE TITLE
[BUG] Can't install chi-sim as PAPERLESS_OCR_LANGUAGE

### ISSUE THREAD

**Issue by waca-tech** [jonaswinkler/paperless-ng#584]
I deployed paperless-ng using Docker method: 
https://paperless-ng.readthedocs.io/en/latest/setup.html#install-paperless-from-docker-hub

I tried to add additional language for OCR by modify file docker-compose.env. I modified 
**PAPERLESS_OCR_LANGUAGE=chi-sim**

The language code is for Simplified Chinese, which can be  found here:
https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster

After I deployed, the webserver always gave me error message below. I've tried other languages like Japanese and German, it is working fine. The issue only happens to Chinese: 

**Webserver logs**
```

Paperless-ng docker container starting...

Installing languages...

Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]

Get:2 http://deb.debian.org/debian buster InRelease [122 kB]

Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]

Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [267 kB]

Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]

Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [9504 B]

Fetched 8422 kB in 2s (5163 kB/s)

Reading package lists...

Installing package tesseract-ocr-chi-sim...

creating directory /tmp/paperless

Waiting for PostgreSQL to start...

Apply database migrations...

SystemCheckError: System check identified some issues:


ERRORS:

?: The selected ocr language chi-sim is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

Paperless-ng docker container starting...

Installing languages...

Hit:1 http://deb.debian.org/debian buster InRelease

Hit:2 http://deb.debian.org/debian buster-updates InRelease

Hit:3 http://security.debian.org/debian-security buster/updates InRelease

Reading package lists...

package tesseract-ocr-chi-sim already installed!

creating directory /tmp/paperless

Waiting for PostgreSQL to start...

Apply database migrations...

SystemCheckError: System check identified some issues:


ERRORS:

?: The selected ocr language chi-sim is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

Paperless-ng docker container starting...

Installing languages...

Hit:1 http://deb.debian.org/debian buster InRelease

Hit:2 http://deb.debian.org/debian buster-updates InRelease

Hit:3 http://security.debian.org/debian-security buster/updates InRelease

Reading package lists...

package tesseract-ocr-chi-sim already installed!

creating directory /tmp/paperless

Waiting for PostgreSQL to start...

Apply database migrations...

SystemCheckError: System check identified some issues:


ERRORS:

?: The selected ocr language chi-sim is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

Paperless-ng docker container starting...

Installing languages...

Hit:1 http://security.debian.org/debian-security buster/updates InRelease

Hit:2 http://deb.debian.org/debian buster InRelease

Hit:3 http://deb.debian.org/debian buster-updates InRelease

Reading package lists...

package tesseract-ocr-chi-sim already installed!

creating directory /tmp/paperless

Waiting for PostgreSQL to start...

Apply database migrations...
```

**Relevant information**
 - Host OS of the machine running paperless: [Debian GNU/Linux 10]
 - Version [latest]
 - Installation method: [docker]
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.

**Comment by jonaswinkler** [comment]
This is due to some weird naming differences between how Debian names the tesseract packages and how they are referred to by tesseract.

Please try this configuration:

* `PAPERLESS_OCR_LANGUAGES=chi-sim`
* `PAPERLESS_OCR_LANGUAGE=chi_sim`

The first option controls what packages to install. The second one controls what language to use. I know the naming scheme for this is really bad, but it has been like that in paperless for a very long time, and changing that will require everyone to change their configuration.

**Comment by waca-tech** [comment]
Yes, it works like a charm. Thanks a lot for your help.

**Comment by sepmein** [comment]
It took me too long to find this answer. Thank you. It would be really nice if this could be added in the doc.

**Comment by slikie** [comment]
This is something that definitely should be specified in docs. 
Languages affected: Japanese, Korean, Chinese, Old Georgian, Azerbaijani.
