### ISSUE TITLE
Document previews should be clickable

### ISSUE THREAD

**Issue by fdw** [jonaswinkler/paperless-ng#59]
If I list all or some documents, I usually want to open at least one of them. Unfortunately, there are only two relatively small buttons. It would be more comfortable if clicking the image preview would open the download directly.

Similarly, clicking the title might open the edit page.

If you are interested in this, I might try my hand at a PR :)

**Comment by jonaswinkler** [comment]
Hello!

See #55.

As for now, Making the preview images clickable conflicts with #54, which I've got partially implemented. The user would get no feedback about whether they're about to click on a tag that's displayed on top of the preview, or the preview itself. #54 will also make correspondents clickable, and having two links with different meaning next to each other with only a small colon separating them is not ideal.

There are multiple ways to go about this, and while the solution with the buttons works, it might not be the best one. Soo, uhm... I'm not entirely sure where to go from here :)

**Comment by fdw** [comment]
Ah, I see. That would certainly not be ideal :/

I had a look how the old paperless does it, and it has the tags on a separate line, not over the preview image. That could be one solution if you don't have many tags/correspondents on one file.
Another idea could be to only make the left half of the preview clickable with the right half reserved for tags and correspondants. Definitely a bit weirder, but might just work.

Another idea is to highlight the tag/correspondent when hovering. That should make it clear what you're clicking.

**Comment by jonaswinkler** [comment]
Or maybe a small, invisible, non-clickable border around the tasks.

If you want to give it a shot, go for it. I'd like to say that there's updated documentation on how to setup the dev environment in the "extending" section, but apparently ReadTheDocs is having some issues right now, since all builds of the documentation fail with no changes to its config. You'd have to build the docs from the dev branch yourself.

**Comment by jonaswinkler** [comment]
Closing this for now, since preview clicking is now used for making selections.
