### ISSUE TITLE
[BUG] Experienced an exception upon (re-)archiving of PDF documents.

### ISSUE THREAD

**Issue by git-help-eng** [jonaswinkler/paperless-ng#591]
Experienced an exception upon (re-)archiving of PDF docs.  

**To Reproduce**
1. $ cd /home/user/path_to_paperless_ng_container
2. $ docker-compose exec webserver document_archiver --overwrite
3. ~25% of documents processed (~6 with Corrupt JPEG data, and 1 with CreationDate could not be copied to XMP warnings).  The exception happened well after the two types of warning listed above.  

**Expected behavior**
It was expected that archival PDF/A documents would be (re-)created for all documents.

**Webserver logs**
New to docker, not sure where logs are kept.  Below is the output to the CLI (it is a bit mangled, but the exception should be clear).
```
$ docker-compose exec webserver document_archiver --overwrite
 15%|█████████████████████████▌                                                                                                                                           | 337/2180 [1:37:56<10:52:15, 21.23s/it]Corrupt JPEG data: 6 extraneous bytes before marker 0xd9
 16%|█████████████████████████▋                                                                                                                                            | 338/2180 [1:38:09<9:35:04, 18.73s/it]Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
 16%|██████████████████████████▎                                                                                                                                           | 346/2180 [1:39:33<7:12:22, 14.15s/it]Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
 16%|██████████████████████████▍                                                                                                                                           | 347/2180 [1:39:53<8:03:46, 15.84s/it]Corrupt JPEG data: 3 extraneous bytes before marker 0xd9
Corrupt JPEG data: 5 extraneous bytes before marker 0xd9
Corrupt JPEG data: 7 extraneous bytes before marker 0xd9
Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
 18%|█████████████████████████████▎                                                                                                                                      | 390/2180 [2:03:59<64:18:53, 129.35s/it]/usr/local/lib/python3.7/site-packages/pikepdf/models/metadata.py:372: UserWarning: The metadata field /CreationDate could not be copied to XMP
  warn(msg)
 34%|████████████████████████████████████████████████████████▉                                                                                                             | 748/2180 [4:01:17<7:41:56, 19.36s/it]
multiprocessing.pool.RemoteTraceback: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/src/paperless/src/documents/management/commands/document_archiver.py", line 34, in handle_document
    parser = parser_class(logging_group=uuid.uuid4())
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_archiver.py", line 127, in handle
    total=len(document_ids)
  File "/usr/local/lib/python3.7/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: 'NoneType' object is not callable
```

**Relevant information**
 - ~2.2K documents, all but a handful using paperless.
 - I went from bare-metal paperless to docker paperless-ng.  I manually copied the media/data/DB from paperless into the paperless-ng docker volumes.  The install was successful and I have been using/importing for ~PT1W.  I wanted to ensure that I had PDF/A for all my documents (including older documents processed with paperless) so chose to run document_archiver --overwrite.  There were a small number of documents (<= 5) which paperless-ng thought had no content, which were (maybe) poor quality for OCR.
 - Host OS: Debian Testing (bullseye) 5.10.13
 - Browser: N/A
 - Version: 1.1.4 (using SQLite)
 - Installation method: Orginally bare-metal paperless -> migrated to docker paperless-ng.
 - No changes made to `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.
 - simple-scan and pdfarranger (almost) exclusively used for scanning concatenating.

**Comment by jonaswinkler** [comment]
Hello!

Thanks for reporting, I'll address that. This question may feel a bit unrelated, but it's important here: Do you have any `.pnm` files in paperless?

* I'd like to associate the messages about corrupt jpg data with the document they occured on, but these are produced by some external program and I don't have much control over how that program prints out messages.
* What is PT1W?
* The document archiver will always attempt to create archived versions. `--overwrite` tells paperless to also redo that for documents where and archived version already exists. The next time you run it, don't use overwrite and it'll save you some time.

**Comment by git-help-eng** [comment]
- Sorry for the abbreviation, which I used incorrectly.  It was supposed to be [P1W](https://en.wikipedia.org/wiki/ISO_8601#Durations), meaning 1 week.  
  - I do not have any .pnm files in paperless (tried to locate with: $ find / -iname '*.pnm'), nor do I recall ever trying to add that document type.
  - Were the jpgs created incorrectly by paperless (not paperless-ng) initially?
  - I went with the --overwrite as I'm not sure of the probability that there might be some (maybe small) difference between the metadata of files processed with paperless vs files processed with paperless-ng.  Something like OCR in paperless-ng might give a better capture than paperless would have for the same document.  But in retrospect if paperless didn't make a PDF/A in the first place then the --overwrite is not necessary.
  
Thanks for the response, and the fix.

**Comment by jonaswinkler** [comment]
> * Were the jpgs created incorrectly by paperless (not paperless-ng) initially?

This has nothing to do with paperless. This might be a PDF document with an embedded JPG image that's corrupt, or a specific JPG file added directly to paperless.

Paperless-ng (or rather the library that's reponsible for OCR) reports these errors, whereas the OCR functions in paperless did not. This is fine in most cases, since many PDF viewers are able to deal with incorrect PDF documents to a certain degree.

> I'd be happy to try testing a fix if that would be helpful.

If you want to do that, switch to the `dev` version (swap out latest for dev in the compose file), and pull. The actual error you encountered is fixed, however, the cause for this error is most likely a file that's not correctly recognized by paperless, and we may need to investigate further.

**Comment by git-help-eng** [comment]
I trying the dev image now and the file info output for files with unknown mime types is great, and helped me to discover (and correct) that there was a non .pdf file in my document directory.  It was a .bin file, which I seemed to have inadvertently added (using paperless, not paperless-ng) with an incorrect extension.  I verified that was the only non .pdf/.png file in my document store.

I'm not sure if the following is of any use to you but there was an additional error during archiving, but it did not prevent the archiver from completing.
```
[2021-02-22 16:14:49,483] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
```

**Comment by jonaswinkler** [comment]
The change is in 1.2.0, so please switch to that once it's on the hub.

Regarding the error: I've got a couple files over here as well that raise this, but the archived pdf documents look fine. I'll try to identify what this is about.

**Comment by git-help-eng** [comment]
I only mentioned it in case you wanted to/were able to also identify the document associated with the message.

Thanks for the quick patch.
