### ISSUE TITLE
[BUG] Unclear workflow to request a new feature

### ISSUE THREAD

**Issue by jovandeginste** [jonaswinkler/paperless-ng#601]
**Describe the bug**
I don't know how to open a feature request

**To Reproduce**
1. Go to paperless-ng's GitHub page
2. Go to "Issues"
3. Click the "New issue" button
4. Read how to report either a:
    - Bug report (Something is not working)
    - Other (Anything that is not a feature request or bug)

Optional:
5. Start reporting a "Bug report"
6. Read the linked documentation, search for "feature"

**Expected behavior**
A separate button in the "New issues" page to open a "Feature request"

**Relevant information**
I don't think anything in my personal setup is relevant here :-)

**Comment by shamoon** [comment]
It’s in the read me :)
https://github.com/jonaswinkler/paperless-ng#feature-requests

Moved to Discussions so can be voted on etc. I personally think the “Other” Issue template should be removed too. Issues for bugs, everything else under Discussions (including FRs)

**Comment by jovandeginste** [comment]
Dang! Sorry :-)

**Comment by shamoon** [comment]
Ps. There’s also a link in the app sidebar to “suggest an idea” that goes right there!

**Comment by jovandeginste** [comment]
Honestly, I still don't think about "github discussions"... I have to get used to them!

**Comment by jonaswinkler** [comment]
I'm still having some issues with these discussions,, but it already helps with keeping the issue tracker reasonably clean.

**Comment by jovandeginste** [comment]
> I'm still having some issues with these discussions,, but it already helps with keeping the issue tracker reasonably clean.

Right ... I see what I did then :-)
