### ISSUE TITLE
[FEATURE] Allow closing single document from the sidebar

### ISSUE THREAD

**Issue by jovandeginste** [jonaswinkler/paperless-ng#603]
**Describe the feature**
Have the ability to "close open documents" from the sidebar, even when there is only one document open.

**Expected behavior**
When I open (edit) multiple documents, I see them appear in the sidebar. When there is more than one document, a link appears to "Close all". It often happens that I only have one document opened, and then navigated away instead of clicking the "close" button. It would save me a click (and some rendering time) to either have:
- the "close all" button even when there is only one document open
- have a selective "close" button per document
    - in this scenario, the "close all" can be shown when there is more than N documents; otherwise, you can close them separately

**Screenshots**
One document, no "close all" button:
![afbeelding](https://user-images.githubusercontent.com/3170771/108814892-e1a1b880-75b3-11eb-818b-d7a9228214f9.png)

Two documents, with "close all" button:
![afbeelding](https://user-images.githubusercontent.com/3170771/108814746-a7381b80-75b3-11eb-86d2-3d0fcf7f81e9.png)

**Webserver logs**
N/A

**Relevant information**
 - Version: 1.2.0

**Comment by jonaswinkler** [comment]
> * have a selective "close" button per document

There's already very little space to display longer titles, so I'd rather not have a dedicated close button take up space. Documents auto-close when you open enough other documents anyway, so I'd say this is fine.

Changed the "Close all" button to get displayed even with only a single open document.

**Comment by jovandeginste** [comment]
The button should not be there always - it could appear on hover?

**Comment by jonaswinkler** [comment]
Hm, good point!

**Comment by shamoon** [comment]
I can take care of this (if you haven't already) JW. Def thought about this one before

**Comment by jonaswinkler** [comment]
I haven't done anything regarding this yet.
