### ISSUE TITLE
Docker: allow defining user/group

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#63]
Right now it is fixed to id 1000 from what I saw, right? Would be good to pass desired user and group (id) via environment variable in the compose file.

I could try it myself and make a PR if that's okay

**Comment by jonaswinkler** [comment]
Please read the documentation, and the included docker-compose.env file.

**Comment by totti4ever** [comment]
sorry, just saw it. I was irritated by this part of the dockerfile

```
# add users, setup scripts
RUN addgroup --gid 1000 paperless \
	&& useradd --uid 1000 --gid paperless --home-dir /usr/src/paperless paperless \
	&& chown -R paperless:paperless . \
	&& chmod 755 /sbin/docker-entrypoint.sh
```

Everything works as expected
