### ISSUE TITLE
Bug: No error log when broker cannot be reached

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#64]
I somehow messed up mapping the correct directories, nevertheless - apparently PL-ng wasn't able to write to the docs folder and therefore uploading a file failed. But I couldn't find any proper log in the docker logs nor in the UI

**Comment by totti4ever** [comment]
webserver log
```
paperless-ng_webserver    | 172.16.0.10 - - [28/Nov/2020:21:27:35 +0000] "POST /api/documents/post_document/ HTTP/1.1" 500 145 "http://paperless-ng.home/dashboard" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
```

docker-compose excerpt
```
    volumes:
      - ./data/data:/usr/src/paperless/data
      - ./data/previews:/usr/src/paperless/media/documents/thumbnails
      - ./docs:/usr/src/paperless/media/documents/originals
      - ./consume:/usr/src/paperless/consume
```

ls -la
```
drwxrwxrwx 2 me me 4,0K Nov 28 22:24 docs/
```

**Comment by totti4ever** [comment]
Hah, figured it out - I changed the broker hostname and didn't do a proper update to the corresponding env var, so the broker couldn't be found.

Got a proper error in the log when using the consume dir - got nothing when using web ui.
After fixing it, both work fine

**Comment by jonaswinkler** [comment]
The log on the web UI is not designed to show configuration errors. It's for paperless-specific messages only.

**Comment by totti4ever** [comment]
But shouldn't the backend, i.e. docker log says something?
