### ISSUE TITLE
[Feature] Allow setting the title from the renamed file

### ISSUE THREAD

**Issue by sebastiangiffhorn** [jonaswinkler/paperless-ng#649]
Currently the initial title is set from the original filename. In my case this comes from my scanner and is rather meaningless (e.g. duplex27-02-2021-111449.pdf for a duplex scan from today).

I have started to import a lot of files and the matching for correspondent, document type and tags is pretty good. However the title is a problem for me, as I don't want to rename hundreds or thousands of titles. I have enabled file name renaming ({correspondent}/{created_year}/{document_type}-{created}) and it would be good if I could somehow automatically change the title to the renamed file name.

**Comment by jonaswinkler** [comment]
I'm not sure about this.

* This would simply copy data that's available in other fields into the title. No added benefit for searching purposes.
* What if you use `{title}` in the filename format along with other placeholders?
* While I agree that filenames from documents produced by scanners are rarely useful, some other filenames are, and I'm not sure how I'd decide whether to overwrite the given title with something constructed from metadata.
* What about saving updated correspondents / types? should the title update as well? (What if you manually changed the title?)

**Comment by sebastiangiffhorn** [comment]
I agree, it doesn't make sense in an automatic kind of way or under specific circumstances.

Maybe it would make more sense to have a bulk "Title" assign function in the "Document view", where I can select a specific subset of documents (through filtering for tags, types). With an additional dropdown I could then assign a plain string or a string with placeholders (for existing data fields like {document_type} except the previous {title}) as new title for all selected documents.

Just as an example: 100 documents where the matcher has already successfully matched the document type "Bank statements" and correspondent "My Bank" as well as the "Date created". But all titles are "scan-yyyy-mm-dd-xyz" because of the file name of the scanned file. With the new functionality I could now easily set the title for all documents to: "{document-type} - {month}/{year}"
