### ISSUE TITLE
Paperless-ng crashes webbrowser Safari (MacOS) when clicking the edit-icon

### ISSUE THREAD

**Issue by mikkelnl** [jonaswinkler/paperless-ng#65]
When I click the edit icon while using Safari, it seems that paperless-ng fully hangs, even a refresh of the site hangs/loads forever. Weird thing is, everything works fine in Edge of Chrome.

**Comment by jonaswinkler** [comment]
This is something that I cannot fix, since I don't have safari.

**Comment by mikkelnl** [comment]
I understand, strange behavior unfortunately, I'll try to figure out what is going on.

**Comment by mikkelnl** [comment]
Tried mobile safari (iphone) and that works fine.

Anyone elke can test Safari on MacOS? To make sure it isn't my system.

**Comment by totti4ever** [comment]
Tried it on MacOS 10.15.7 with Safari 14.0, no problem. Where did you click the edit button? Document list? Which view (tile, list, ..)?

**Comment by mikkelnl** [comment]
I'm on MacOS 11.0.1, Safari 14.0.1.

Tried several views (grid, list etc) and as soon as I click the edit button, the site hangs. Even refresh doesn't work. I have to open a new tab and there the site opens fine but same problem when I click the edit button. Strange stuff! It might be a Big Sur related issue, since you are on 10.15........

**Comment by totti4ever** [comment]
What if you go straight to the edit page without the button, i.e. copy the URL from e.g. Chrome?

**Comment by mikkelnl** [comment]
Same problem. For example, I can open /documents/271 just fine on Edge/Chrome, but noting happens on Safari...

Also tried Safari Tech Preview (14.1): has the same problem. Will try to test more later......

**Comment by soberhofer** [comment]
Can confirm. The Tab in Safari 14.0.1 on macOS 11.0.1, just hangs and has to be closed once i click on the pencil icon. I've also tried the Safari 14.1. Technology Preview, same behaviour.

**Comment by jonaswinkler** [comment]
If other forms are working, i.e., the tag/type/correspondent create/edit forms, the only thing that's special about this page is the inclusion of an <object> tag that displays the document.

**Comment by mikkelnl** [comment]
I can add/edit tags and correspondents without problems!

**Comment by mikkelnl** [comment]
> If other forms are working, i.e., the tag/type/correspondent create/edit forms, the only thing that's special about this page is the inclusion of an `<object>` tag that displays the document.

Hi! I was wondering if this could possibly be the fix? It is the only 'issue' that keeps me from switching to the awesome ng version :)

**Comment by jonaswinkler** [comment]
For starters, I don't know if that's really the issue.

Second, this <object> tag displays the document next to the edit form. It is required. I can't simply remove it.

Also, I don't have that browser available and can't test it.

**Comment by mikkelnl** [comment]
Too bad then I guess!

**Comment by soberhofer** [comment]
I would be happy to help with testing, if that helps. I can offer a wide variety of Safari Versions on different macOS Versions. Maybe it would make sense, to put some information in the README about Safari being not fully supported

**Comment by shamoon** [comment]
I think I have a fix in the works!

**Comment by mikkelnl** [comment]
Awesome! 💯

**Comment by jonaswinkler** [comment]
@mikkelnl Please check if the crash still happens with the new version. If not, please close.

**Comment by mikkelnl** [comment]
> @mikkelnl Please check if the crash still happens with the new version. If not, please close.

Seems to be working now, awesome! If it also works for @soberhofer I will close the issue, so far so good :) Thanks.

**Comment by shamoon** [comment]
@jonaswinkler Not sure if you saw, I tracked down this bug after an issue was filed in the Angular repo, looks like thats where it is. There isnt a fix out yet but looks like removing `type="application/pdf"` fixes it. I cant really tell if there are any downsides to doing that (other than its obviously semantically less correct). Point is it would be nice to drop this extra library, the native viewer is faster, one less thing to support etc. Not sure if you would prefer to just wait for a real resolution or use this workaround in the meantime (Ive tested it and removing that definitely fixes the bug and doesnt seem to cause any issues in browsers that I tested).

**Comment by jonaswinkler** [comment]
@shamoon I just remembered that I've read this but failed to respond :)

That's interesting. I don't have safari over here, so I can't really verify that. However, since the current setup is not causing all that mutch trouble, except for the slower PDF experience on Safari, I'd like to keep things the way they are fow now. I'm following the referenced issue, and will wait for any more insights on that issue.

**Comment by shamoon** [comment]
Sure. I can definitely verify it fixes it just not sure about whether that has any side effects (again none that I saw).

actually biggest reason I brought it up was part of #487 as the load time was noticeable there.

Seems pretty safe to me but yea NBD
