### ISSUE TITLE
[BUG] Application running in DEBUG mode

### ISSUE THREAD

**Issue by mirisbowring** [jonaswinkler/paperless-ng#652]
**Describe the bug**
I added the env var `PAPERLESS_DEBUG: 'false'` to the docker compose file and restartet all containers.
The logs still prints every debug message

**Expected behavior**
Only Info and higher level in log

**Webserver logs**
not appending due  to privacy

**Relevant information**
 - Ubuntu 18.04 (Server)
 - latest Docker and Docker-Compose
 - pulled image today -> should be up to date

**Comment by jonaswinkler** [comment]
This is intended, since it helps me to figure out what's going on when things are not working.

DEBUG only enables certain functionality that's useful for development.

**Comment by mirisbowring** [comment]
Ah, ok. This should be mentioned in the docs.

Will you implement such option (to clean the log for a default user)?

**Comment by jonaswinkler** [comment]
> Will you implement such option (to clean the log for a default user)?

Do you want an option to define the granularity of the logs?

**Comment by mirisbowring** [comment]
I thought it would be good, but the improvement would not justify the effort.

So my confusion is solved, Thank you! :)

**Comment by jonaswinkler** [comment]
Alright :)

Debug is disabled by default, so you don't even need to have that in the configuration.
