### ISSUE TITLE
[BUG] Putting a regular expression (.*anything.*) in correspondent but selecting text stops processing documents

### ISSUE THREAD

**Issue by radi5** [jonaswinkler/paperless-ng#668]
When a regular expression like (.*anything.*) into the correspondent recognition field but forgetting to set type to regular processing causes stoping of document processing with error log:

Error messagt:
[DEBUG] [paperless.consumer] Saving record to database
[ERROR] [paperless.consumer] The following error occured while consuming XXXX.pdf: missing ), unterminated subpattern at position 2

**To Reproduce**
1. Go to administration of correspondents
2. create a new one with a regular expression  (.*anything.*) as identifier and set type to Any Text (in german: Irgendein Wort)
3. Click save
4. import an document
5. see error:
[DEBUG] [paperless.consumer] Saving record to database
[ERROR] [paperless.consumer] The following error occured while consuming XXXX.pdf: missing ), unterminated subpattern at position 2

**Expected behavior**
At least a better information where the error comes from would be nice

**Comment by jonaswinkler** [comment]
Dulicate of #605
