### ISSUE TITLE
[Other] Lost admin password

### ISSUE THREAD

**Issue by lenaxia** [jonaswinkler/paperless-ng#669]
Version: Paperless-ng 1.2.1
Docker Image: jonaswinkler/paperless-ng:latest

So I installed paperless on a test basis to play with and created an "admin" user and a "self" (non-admin) user. I liked Paperless so much that I got right into getting my documents, tags, etc set up.

After getting a bunch of documents tagged and sorted, I went to log into the admin account and realized I had forgotten what I had the admin password as! Amateur hour!

Is there any way I can reset the password?

**Comment by lenaxia** [comment]
Nm, fixed it (kinda). I pulled the sqlite db, and in the auth_user table copied a good pbkdf2 password into the admin password and was able to get in.

**Comment by just-refresh** [comment]
Docker Image: jonaswinkler/paperless-ng:latest
DB: Postgres:13

Got the same Problem. Lost Username (and Password). 
But using another DB

How could i find the Username or change the Password?

Thanks for your Help!

**Comment by jonaswinkler** [comment]
`docker-compose exec webserver python3 manage.py changepassword <user_name>`

or to create a new user

`docker-compose exec webserver python3 manage.py createsuperuser`

**Comment by Tim4497** [comment]
@jonaswinkler any command to see all usernames/accounts?
