### ISSUE TITLE
[BUG] Saving a document fails with no error. 

### ISSUE THREAD

**Issue by zjean** [jonaswinkler/paperless-ng#691]
**Describe the bug**
I added a new document via the web interface. Opened it, and tried to add the metadata.
When saving the file, nothing happens.
I checked the developr tools of my browser (Chrome), and saw a network error:
HTTP 400
{"content":["Null-tekens zijn niet toegestaan."]}

**To Reproduce**
1. Go to edit a document
2. Edit its properties
3. Save
4. See error in developer console

**Expected behavior**
I expect to save the document

**Screenshots**
![image](https://user-images.githubusercontent.com/441924/109860756-cf341880-7c5e-11eb-96dc-86b91b27bc6d.png)

**Webserver logs**
```
The paper less logs don't say anything
```

**Relevant information**
 - Host OS: Debian
 - Browser Chrome
 - Version 1.2.1
 - Installation method: docker-compose
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.

Edit: I see that in the content field the value '\u0000' is present in several words. I see this character instead of the letter combination 'ti', like this (pasted from the json in the network tab, since the edit field shows a square): belas\u0000ngdienst
Removing this in the content textarea in the ui doesn't help.

**Comment by jonaswinkler** [comment]
My best guess based on that is that when this document was added, the null character `\0` (used for marking the end of a string) was somehow extracted from the PDF content and safed in the content field. The API now complains about that character being in the content field when saving.

* What happens if you cut the content field, paste that in another editor, and insert it into the content field again, then save?
* What happens if you execute the management command `document_archiver -f -d 236`?

**Comment by jonaswinkler** [comment]
> Edit: I see that in the content field the value '\u0000' is present in several words. I see this character instead of the letter combination 'ti', like this (pasted from the json in the network tab, since the edit field shows a square): belas\u0000ngdienst
> Removing this in the content textarea in the ui doesn't help.

Hm. Is that document confidential?

**Comment by zjean** [comment]
Thanks! I cut the content, and pasted it back from notepad++. That allowed me to save the document.
The document is quite confidential, sorry. If I encounter it another time with a less sensitive document, I will let you kno!

**Comment by jonaswinkler** [comment]
THe root of this issue is addressed as part of #794, so I'll go ahead and close this.
