### ISSUE TITLE
Clicking on view titles in dashboard should lead to view

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#71]
Of course I could also add them to the sidebar, but I guess this change wouldn't be a huge one and make navigating views easier.

This also should be true for the admin page of the views

**Comment by jonaswinkler** [comment]
> This also should be true for the admin page of the views

What's that?

**Comment by totti4ever** [comment]
Sorry, I meant settings not admin (guess difference is mainly that admin comes from original paperless and settings from ng, right)

<img src="https://user-images.githubusercontent.com/49901208/100552145-877baa80-3285-11eb-8ba0-9ae56aed8789.png" height=250 />

Editing the properties (e.g. switch _show in sidebar to true_ would be nice, too
