### ISSUE TITLE
Time created - does anybody use this? If not, remove it please

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#73]
Hey, this already annoyed me a lot in the original paperless!

Of course I know, that I could just ignore it - but if it is there and I can see it, I just cannot ignore it. So I was wondering whether anybody uses this level of detail anyways?

If so, I would be glad if I could disable/hide it in the settings. This could also be used for other things, people thing they don't need (e.g. ASN).

Nothing of high priority, of course. But it just pops every time up in my head, when I see it ;-)

**Comment by jonaswinkler** [comment]
I figure we can make the entire edit form a little more compact by removing that, putting both date and serial number on the same line.

Also thought about hiding the content field. That's only ever used for indexing and shouldn't be edited by users anyway.

**Comment by totti4ever** [comment]
re/ content: it's great for debugging/validating. So it would be good to still find it somewhere and of course readable only. 

I also would weight the identical content compared to the ocr-layer higher than the option to enter additional information for searching, which would be gone at the next re-index.

So maybe make it collapsible under the buttons

**Comment by jonaswinkler** [comment]
It will stay the same for now, since there's more important stuff.



> I also would weight the identical content compared to the ocr-layer higher than the option to enter additional information for searching, which would be gone at the next re-index.

I didn't quite get that! The content isn't supposed to be user-writable, but oh well. Paperless won't modify the content when reindexing. It will rather take the current content and put it in a separate search index.

**Comment by totti4ever** [comment]
yeah, I thought it might be a nice feature to add things to the index _(pro)_ - but then I thought it's hard to understand if the content shown in the front-end differs from the actual ocr-layer in the pdf and if it gets lost once a pdf is re-ocred, as through the upcoming ocrmypdf feature _(con)_
