### ISSUE TITLE
[Feature Request] Download individual pages from a document

### ISSUE THREAD

**Issue by seeers** [jonaswinkler/paperless-ng#731]
A very useful feature would be to download individual pages from a document.
Sometimes you may only need individual pages for an email or an application.
Perhaps on the browser side using this library?  https://github.com/Hopding/pdf-lib

**Comment by shamoon** [comment]
Hey @seeers , Feature requests should be submitted under Discussions: https://github.com/jonaswinkler/paperless-ng/discussions/categories/feature-requests where they can be voted on etc to help prioritize things

**Comment by shamoon** [comment]
Thanks! You can close this one too 😀
