### ISSUE TITLE
[BUG] Main Search Bar doesn't show document with title matching

### ISSUE THREAD

**Issue by xavgra2** [jonaswinkler/paperless-ng#739]
**Describe the bug**
When looking a particular document which I remember the title, I can't find it with the search Bar on top of the page.
But I can find it with document filter "title&content".

**To Reproduce**
Rename (title) a doc with a word not present in the PDF content.
Search it with "document filter" -> works
Search it via main search bar -> don't work.

**Expected behavior**
I suppose that the main search bar has the maximum coverage of search, so at least title+content.

**Relevant information**
docker installation, 1.3.0.

**Comment by xavgra2** [comment]
Hi, 
I update my bug; 
I just try to reproduce the issue, but was impossible with release 1.3.2 ... and I finally find why.

After a few more try, it seems that the issue is that the search engine need pattern.
If the title is "keywordBlaBla" : 
- Using Main search bar : keyword doesn't work
- Using Main search bar : keyword* works
- Using "Filter" in document view : keyword works.

Is it the expected situation that the behaviour is different in the 2 search boxes ?

**Comment by jonaswinkler** [comment]
Yes. the full text search searches by complete words - that's now search indexes work. That's also the reason why there's auto complete.

**Comment by christo-ph** [comment]
Hi,

I would reconsider this behaviour. It makes the workflow quite hard, if the global search box does not do a global search.

I am always begin to search with the global search field, no matter where I am currently am. And then wondering, why the documents did not come up. After a while I am realising, that I am using "extended search" - which does not seem that extended in this matter.

Thank you.
