### ISSUE TITLE
Suggestion: Preview/View-icon opens in new tab/window

### ISSUE THREAD

**Issue by mikkelnl** [jonaswinkler/paperless-ng#76]
As title, just a suggestion :)

**Comment by totti4ever** [comment]
You know that you can use _right-click_ -> _open in new tab_ or _ctrl+click_ to reach that behaviour, right? I think it is great that this standard functionality of browsers is supported!

And most of the times I find it annoying if web-apps or websites force a new tab as there is no trigger I can use to stop that like there is to force it myself.
So, although I'd say that most of the times opening in a new tab is the preferred route, I would suggest not to force this and let the user decide.

Discussion is open :-)

**Comment by mikkelnl** [comment]
Yeah, I know about the right-click option :)

And yes I guess it is a preference, sure! So not a big issue at all, no problem, I personally always like these type of previews to open in a new tab :)

**Comment by jonaswinkler** [comment]
Browsers provide various ways to open content in new tabs / windows, both foreground and background with certain button / mouse click combinations. (Edge opens content in new tabs foreground with shift + middle mouse click).

I'll not change this.
