### ISSUE TITLE
[BUG] Calendar offers too few years, but some are in the future

### ISSUE THREAD

**Issue by fdw** [jonaswinkler/paperless-ng#762]
**Describe the bug**
Year dropdown to change a document's dates does stop too soon.

**To Reproduce**
1. Edit a document.
2. Click on the calendar icon to the right of the date field
3. Open the "year" dropdown
4. Notice that it's only ten years in either direction.

**Expected behavior**
Sometimes, the detected date is far off (for example, my birthday in official documents). I can then only change the year by typing it in manually.

On the other hand, in new documents, the possible years also span ten years into the future.

I would find it more useful if the drop down contained some (maybe 10) years preveious to the selected date, but all the years up to the current one.

**Relevant information**
 - Version: Latest docker image

**Comment by jonaswinkler** [comment]
The calendar is a pre-made component and I cannot change anything regarding the year selector of that component.

On a side note, someone added PAPERLESS_IGNORE_DATES a while back. This is useful for ignoring certain dates such as birthdays that appear quite often on documents, but are rarely the date you actually want.

**Comment by fdw** [comment]
That's a pity, but thanks for the quick reply!

And that option sounds interesting.

**Comment by jonaswinkler** [comment]
As with all the other settings that affect server side behavior, only as an environment variable.
