### ISSUE TITLE
Very long title breaks UI (table width)

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#77]
So I am having a too long title without any spaces (!), which comes from a downloaded document and this breaks the UI making the columns added/created to scroll out of the right-hand side of the screen (whitespace between title and date is empty doc type):
<img src="https://user-images.githubusercontent.com/49901208/100735165-0f220000-33d1-11eb-847a-00ae9b59a1e9.png" height=40 />

I guess the problem are the missing spaces as other long names including a whitespace are broken to the next line.

Any chance to catch and cut those titles? I guess only good to do if it's fast, as fixing it on the user's side is quick!

**Comment by jonaswinkler** [comment]
I'm considering to just replace underscores with spaces, but yeah, the titles should break.

**Comment by totti4ever** [comment]
Replacing them would be fine for me. I would also think that most underscores come from filenames, which use them to prevent whitespaces, which are still kind of unpopular in filenames.
