### ISSUE TITLE
[BUG] Log "direction" is oldest first

### ISSUE THREAD

**Issue by rYR79435** [jonaswinkler/paperless-ng#774]
**Describe the bug**
The "direction" of the log in the UI is oldest first. I think I remember this as being newest first, which I find better, as no scrolling is needed to see recent entries.

I labeled this as a bug since I believe this is a regression.

**Comment by jonaswinkler** [comment]
This is intended, since the logfiles may also contain stack traces on critical errors, and these are impossible to read when reversed.
