### ISSUE TITLE
[BUG] Unnecessary scrollbar when viewing logs

### ISSUE THREAD

**Issue by rYR79435** [jonaswinkler/paperless-ng#775]
**Describe the bug**
When viewing logs I have two scroll bars, one for the log container (`div.log-container`) and one for the entire page (`main` element).
The latter only scrolls ~15px and serves no purpose; the page is sligthly largen than the screen.

**Comment by shamoon** [comment]
Hey @rYR79435 , what browser are you using?

**Comment by rYR79435** [comment]
@shamoon FireFox.

I think this has to do with the class`.mb-3`, which adds 1rem margin to `div.log-container`. Although removing this (from the container height) doesn't fix it, but reduces it to ~5px scroll.
