### ISSUE TITLE
[BUG] PAPERLESS_FILENAME_FORMAT results in filenames that contain "none"

### ISSUE THREAD

**Issue by isaacsando** [jonaswinkler/paperless-ng#777]
**Describe the bug**
Setting the PAPERLESS_FILENAME_FORMAT environment variable does not correctly name the output file in the archive directory. Also, the Correspondent and Document type fields of the document are not set correctly.

**To Reproduce**
1. Add the following line to docker-compose.env:
PAPERLESS_FILENAME_FORMAT={correspondent}_{document_type}
2. Go to Correspondents in the web browser and create a new correspondent:
Name: FCSA
Matching algorithm: Any
Matching pattern: (none)
Case insensitive: true
3. Go to Document types in the web browser and create a new document type:
Name: Statement
Matching algorithm: Any
Matching pattern: (none)
Case insensitive: true
4. Scan/create a new PDF document called "FCSA_Statement.pdf" and copy it into the consume folder (or upload using the Dashboard)
5. Once processing is complete navigate to the following:
/var/lib/docker/volumes/paperless_media/_data/documents/archive/
6. The filename is "none_none.pdf"
7. Open the document in the web browser and click Edit
8. The Correspondent and Document type picklists are blank

**Expected behavior**
The filename should be "FCSA_Statement.pdf". The Correspondent should be "FCSA" and the Document type should be "Statement".

I'm expecting that the name of the document, "FCSA_Statement.pdf", would translate to the Correspondent field being "FCSA" and the Document type field being "Statement" because I'm using the PAPERLESS_FILENAME_FORMAT environment variable.

**Relevant information**
 - Host OS of the machine running paperless: jonaswinkler/paperless-ng:latest
 - Browser: Firefox
 - Version: 1.3.1
 - Installation method: docker
 - Added to docker-compose.env:
PAPERLESS_FILENAME_FORMAT={correspondent}_{document_type}

**Comment by jonaswinkler** [comment]
`PAPERLESS_FILENAME_FORMAT` 

* determines how files are saved in the media directory. This is also explained in the documentation.
* does not cause paperless to assign metadata by guessing strings from the input filename. Currently, there's no mechanism in paperless that does this.

"none" is used in the filename when no correspondent or type is set. Everything is working as intended here.

If you specify matching algorithms and patterns, such as "Any" with a couple words that usually appear in associated documents, you'll see that the consumer will add that correspondent, type or tag and the generated filename will reflect that as well.

**Comment by isaacsando** [comment]
@jonaswinkler Thank you, this makes sense. I've played around with it a bit more, and I understand how things work now.

In the [documentation](https://paperless-ng.readthedocs.io/en/latest/advanced_usage.html#matching-tags-correspondents-and-document-types) it states that "After the consumer has tried to figure out what it could from the file name". I was assuming this meant that it did some parsing on the filename in order to populate various metadata like correspondent, document type, etc. Regarding your previous comment is there no parsing done at all on the filename? If so what does this mean in the documentation?

**Comment by jonaswinkler** [comment]
Oh. I should really edit that.

* Just as the application itself, the documentation was also forked from the-paperless-project/paperless.
* Paperless actually had a feature to detect correspondents and tags from filenames, but the patterns were *very* strict and hardwired into the system. You can read about it [here](https://paperless.readthedocs.io/en/latest/guesswork.html). I removed that because it was very inflexible, and it would produce seemingly arbitrary correspondents and tags for unaware users when they managed to hit one of these patterns by accident.
* I want to make something better, I just didn't have the time for that yet.

**Comment by isaacsando** [comment]
Yes, thank you, I must've gotten that idea from the original project as I used it some time ago. Thank you for the explanation!

**Comment by soRailicious** [comment]
@jonaswinkler sorry for the dumb question, but can i write PAPERLESS_FILENAME_FORMAT: {created_year} in the docker-compose.yml ?! i Alway get errors :(
