### ISSUE TITLE
document_exporter gives an error during the export

### ISSUE THREAD

**Issue by mikkelnl** [jonaswinkler/paperless-ng#78]
When I run 

> /usr/src/paperless/src/manage.py document_exporter /export

 it will export most of my documents fine, but crashes half way:

> Traceback (most recent call last):
>   File "/usr/src/paperless/src/manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 40, in handle
>     self.dump()
>   File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 56, in dump
>     unique_filename = f"{document.pk:07}_{document.file_name}"
>   File "/usr/src/paperless/src/documents/models.py", line 230, in file_name
>     return slugify(str(self)) + self.file_type
> TypeError: can only concatenate str (not "NoneType") to str

This does not happen with the original paperless container I am running... Anything wrong with my setup or a bug?

**Comment by jonaswinkler** [comment]
Hello!

Please give me some more information.

- Did you migrate from paperless, or did you start from scratch?
- Did you use the importer?
- Do you have documents with types different from png/jpg/pdf/txt in your archive?

**Comment by mikkelnl** [comment]
Hi!

Yes, I followed the steps in the documentation about migrating from the original Paperless.
No, I (think?) I did not use the importer.
All documents are PDF.

**Comment by jonaswinkler** [comment]
I'm sorry it's not working, however, i've got a pretty good idea. Please help me by performing the following steps.

1. docker-compose run --rm webserver shell

This will launch a python shell. Paste the following commands verbatim, one at a time, confirming each with enter. These commands will gather some file type information from the database and will not modify anything.

2. `from documents.models import Document`
3. `from django.db.models import Count`
4. `Document.objects.all().values('mime_type').annotate(total=Count('mime_type')).order_by('total')`
5. Exit with `exit()` or pressing CTRL+d.

You will see some output. It is an aggregated list of file types of your documents. Please either look for anything that is not 'mime_type': 'application/pdf' and post that. Or post the entire thing if you don't care. Its not confidential.

**Comment by mikkelnl** [comment]
Thanks!

The command for opening the python shell did not work. I am on a Synology NAS and I think it is because Synology wants you to use their package/GUI for docker. That particular command gave an error, so I tried the Synology GUI. There, it is possible to start a terminal session. I opened one and entered the command: python. Which starts the Python shell (I think).

Then, I tried your commands:

The first command:
> root@4c6dc4a83072:/usr/src/paperless/src# python                                                                           
> Python 3.7.9 (default, Oct 13 2020, 21:10:49)                                                                              
> [GCC 8.3.0] on linux                                                                                                       
> Type "help", "copyright", "credits" or "license" for more information.                                                     
> from documents.models import Document                                                                                  
> Traceback (most recent call last):                                                                                         
>   File "<stdin>", line 1, in <module>                                                                                      
>   File "/usr/src/paperless/src/documents/models.py", line 17, in <module>                                                  
>     class MatchingModel(models.Model):                                                                                     
>   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 108, in __new__                             
>     app_config = apps.get_containing_app_config(module)                                                                    
>   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 253, in get_containing_app_config            
>     self.check_apps_ready()                                                                                                
>   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 135, in check_apps_ready                     
>     settings.INSTALLED_APPS                                                                                                
>   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__                           
>     self._setup(name)                                                                                                      
>   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 68, in _setup                                
>     % (desc, ENVIRONMENT_VARIABLE))                                                                                        
> django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

The second command gave no errors, but no output.

The third command:
> Document.objects.all().values('mime_type').annotate(total=Count('mime_type')).order_by('total')                        
> Traceback (most recent call last):                                                                                         
>   File "<stdin>", line 1, in <module>                                                                                      
> NameError: name 'Document' is not defined

Sorry if these are obvious issues, I have no experience with python etc...!

**Comment by jonaswinkler** [comment]
Uh, sorry. I don't know about this synology thing.

When you are at

`root@4c6dc4a83072:/usr/src/paperless/src#`

type `python manage.py shell` to open a python shell adn try 2-5 again.

**Comment by mikkelnl** [comment]
No problem, I actually got a step further, I guess there is one item that is causing a problem...?

> <QuerySet [{'mime_type': 'application/octet-stream', 'total': 1}, {'mime_type': 'image/jpeg', 'total': 2}, {'mime_type': 'application/pdf', 'total': 212}]>

**Comment by jonaswinkler** [comment]
Alright, thanks. That's exactly what I needed. I'll fix that in the next release, which will be this weekend, if it goes according to plan.

**Comment by mikkelnl** [comment]
Awesome, thanks!

**Comment by jonaswinkler** [comment]
Explanation. Paperless uses this type to generate file names. 'image/jpeg' will add .jpg to file names and so on. It just doesn't know what to do with that one file. 'application/octet-stream' is usually a type for binary files that have no particular type.

Maybe some file got into paperless which was named file.pdf but isn't actually a pdf file.

For the time being, you can identify the document in question by performing all steps from before again, however, **replace** the long command from step 5 with: `Document.objects.filter(mime_type="application/octet-stream").values('id', 'title')`

This will print the ID of the document, which you can paste into the URL of paperless. (i.e. `/documents/<id>/`)

**Comment by mikkelnl** [comment]
Thanks!

I found the item in question. It seems to be a PDF file, which at first sight is pretty normal. Not sure why it would cause problems, but I'll try the exporter soon without this file.

**Comment by jonaswinkler** [comment]
@mikkelnl  I know this is a couple days old by now, but do you remember if that file might have been stored with GnuPG encryption enabled?

**Comment by mikkelnl** [comment]
Sorry, I have no idea. I remember the file did show something about encryption in the file properties, but I removed the file and don't have it anymore, sorry...

**Comment by jonaswinkler** [comment]
No worries.
