### ISSUE TITLE
[BUG] Empty document type leads to none folder when using {document_type} macro.

### ISSUE THREAD

**Issue by lenucksi** [jonaswinkler/paperless-ng#804]
**Describe the bug**
I use `PAPERLESS_FILENAME_FORMAT` to structure my documents on disk and use the `{document_type}` macro within it.
Documents that do not have a document type assigned are put into a folder `none`.

**To Reproduce**
- Set up `PAPERLESS_FILENAME_FORMAT` to use `{document_type}` macro 
- Add a document without a document type.
- Documents ends up in a folder named `none`
- Repeat with a document with document type - it is placed in a properly named folder. 

**Expected behavior**
In the case of an empty document type, the file should not be put in a `none` subfolder but left in the folder that the `none` folder would be created in.

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu + Docker
 - Browser: independent of browser
 - Version: 1.3.2
 - Installation method: docker
 - config changes see bug description

**Comment by jonaswinkler** [comment]
This is intended and other users probably depend on it working this way.
