### ISSUE TITLE
[Feature request] Copy typed but non-existent tag / correspondent into new tag / correspondent window

### ISSUE THREAD

**Issue by kftb** [jonaswinkler/paperless-ng#817]
Hi! 

I am setting up paperless-ng these days and am figuring out a workflow. Whenever a new tag is non-existent, I check by typing and then having to retype it once I decide to set it up. 

**Current workflow:** 

1. I edit a document and type a tag into the tag field to see if it exists
2. No existing tag is shown, so I decide to add a new tag
3. I click on the + button
4. I have to retype the tag again

**Desired workflow:** 
1. I edit a document and type a tag into the tag field to see if it exists
2. No existing tag is shown, so I decide to add a new tag
3. I click on the + button
4. The tag string I typed in earlier is already copied into "name" field of the new tag modal

Same workflow for the Correspondent

This is a tiny improvement but would improve the user experience during the tedious setup phase

**Comment by shamoon** [comment]
Hi @kftb , as noted in the issue templates, feature requests are meant to go under https://github.com/jonaswinkler/paperless-ng/discussions where they can be voted on, organized, etc.

Anyway, I like this idea. If you agree @jonaswinkler I can take care of it.

**Comment by kftb** [comment]
Thank you for pointing it it, been my first post on GitHub, so still learning the ropes!

**Comment by jonaswinkler** [comment]
Sounds like a good idea.

**Comment by shamoon** [comment]
See #818
Video below =)

https://user-images.githubusercontent.com/4887959/112372850-8c81c100-8c9d-11eb-8ee5-f1a6aae021b3.mov
