### ISSUE TITLE
[BUG] Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by TruffelNL** [jonaswinkler/paperless-ng#829]
**Describe the bug**
With only one particular PDF (attached), containing 5 pages, I get the `Failed to load resource: the server responded with a status of 400 (Bad Request)       https://paperless.link/api/documents/209/` error when trying to save the document. This error only shows up in the Javascript console window of my browser. It does not appear in the Paperless-NG logs. The document is uploaded and processed but when I try to change the title or tags I cannot save the changes. The page never reloads and the changes are not saved to the database. The title in `Open Documents` does change until I reload the page.

**To Reproduce**
1. Go to 'Dashboard'
2. Upload attached file by dragging it to the upload box 
3. Edit the uploaded file
4. Click on 'Save' and do not see anything change

**Expected behavior**
I expected the file to be processed like all the other files or that the system would show an error.

**Webserver logs**
```
21:10:40 [Q] INFO Process-1:5320 processing [Thanks for your purchase.pdf]
[2021-03-25 21:10:41,114] [INFO] [paperless.consumer] Consuming Thanks for your purchase.pdf
[2021-03-25 21:10:57,019] [INFO] [paperless.consumer] Document 2021-03-22 Thanks for your purchase consumption finished
21:10:57 [Q] INFO Process-1:5320 stopped doing work
21:10:57 [Q] INFO Processed [Thanks for your purchase.pdf]
21:10:57 [Q] INFO recycled worker Process-1:5320
21:10:57 [Q] INFO Process-1:5322 ready for work at 32090
[2021-03-25 21:11:49,575] [WARNING] [django.request] Bad Request: /api/documents/209/
[2021-03-25 21:12:50,762] [WARNING] [django.request] Bad Request: /api/documents/209/
[2021-03-25 21:18:50,024] [WARNING] [django.request] Bad Request: /api/documents/209/
[2021-03-25 21:19:00,290] [WARNING] [django.request] Bad Request: /api/documents/209/
```

**Relevant information**
 - Host OS of the machine running paperless: Synology NAS (DSM 6.2.3-25426 Update 3)
 - Browser: Safari
 - Version 1.2.1
 - Installation method: docker

**Comment by jonaswinkler** [comment]
It would be really helpful if you could open up the development tools of your browser (F12), go to the network tab, look for the reponse of the failed save request and paste that here.

**Comment by jonaswinkler** [comment]
Also, are you using Postgres or SQLite?

**Comment by TruffelNL** [comment]
The response is:

```{
    "detail": "JSON parse error - Invalid \\escape: line 1 column 1435 (char 1434)"
}```

I use Postgres. I've found out it has got something to do with the "Content" tab, when I remove the last coupe of new lines/empty lines between the text it saves the file. The content tab for this file was automatically generated and not altered by me (before the removal of the lines).

**Comment by jfinas** [comment]
I have had a similar problem(using SQLite).
```{"content":["Nullzeichen sind nicht erlaubt."]}```
It seems to have to do with some weird, broken character contained in `foo@ bar.baz`(I replaced some parts since it was my private email) in the content of the file. Replacing this one character after the @ resolves the issue.

**Comment by jonaswinkler** [comment]
Thanks for reporting. I've addressed the root cause for this (the PDF text extraction library returns null characters for some documents), but documents that are already scanned into the database might still have null characters in their content. I'll make a migration later that fixes this issue automatically.
