### ISSUE TITLE
Rescan all documents?

### ISSUE THREAD

**Issue by SimplyCorbett** [jonaswinkler/paperless-ng#835]
In paperless-ng/docker is there a way to rescan all documents (OCR, etc) that already exist? I have a couple thousand pdf's and would like to scan them again.

**Comment by lukyjay** [comment]
Hi @SimplyCorbett, I don't think there's a way to re-process existing documents without removing them and readding them.

Once removing them, to readd: there is an 'originals' folder which holds all the PDF files. Just drag and drop those PDFs into your consumer/input folder and the software will start processing them again.

**Comment by SimplyCorbett** [comment]
I ended up doing this. Thank you!
