### ISSUE TITLE
[BUG] Actions not applied on found mails

### ISSUE THREAD

**Issue by MeikelLP** [jonaswinkler/paperless-ng#840]
**Describe the bug**
The mail scraper does find mails but it's not applying actions on all of them.

**To Reproduce**
-

**Expected behavior**
If I match 19 mails I want 19x actions to be run right?

**Screenshots**
-

**Webserver logs**
```
[2021-03-28 19:28:47,803] [DEBUG] [paperless_mail] Rule Posteo.Posteo Rechnungen: Selecting folder Rechnungen
[2021-03-28 19:28:47,835] [DEBUG] [paperless_mail] Rule Posteo.Posteo Rechnungen: Searching folder with criteria (SINCE 26-Feb-2021 UNSEEN)
[...]
[2021-03-28 19:28:49,150] [DEBUG] [paperless_mail] Rule Posteo.Posteo Rechnungen: Processed 19 matching mail(s)
[2021-03-28 19:28:49,151] [DEBUG] [paperless_mail] Rule Posteo.Posteo Rechnungen: Running mail actions on 3 mails
```

**Relevant information**
 - Raspbian GNU/Linux 10 (buster)
 - MS Edge
 - Paperless-ng 1.3.2
 - Installation method: docker
 
env
```env
PAPERLESS_OCR_CLEAN=clean-final
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_OCR_LANGUAGES=deu eng
```

Related to #404 and #650 (the difference: It does find emails but does not apply the actions)

**Comment by jonaswinkler** [comment]
Your filter probably matched some mails that do not have attachments. These don't get processed.

**Comment by MeikelLP** [comment]
My filters are basically empty
![image](https://user-images.githubusercontent.com/11669846/112767224-c3493580-9015-11eb-8138-872678dae6f7.png)

**Comment by jonaswinkler** [comment]
As I can see it, there are probably 19 mails in that mailbox, but paperless only processed 3 of them. Might be that the other 16 don't have any (supported) attachments. Paperless won't touch these mails, even though they match the filter.

**Comment by MeikelLP** [comment]
I can send you some of the untouched and some of the touched ones. I doubt they'll be much different

**Comment by MeikelLP** [comment]
The value is acutally decreased from 19 to 16 (as 3 are processed). Why are the other 16 not processed?

**Comment by jonaswinkler** [comment]
Do they have attachments?

**Comment by MeikelLP** [comment]
Yes. For me as a human they all look absolutely identical. Have a look:

![image](https://user-images.githubusercontent.com/11669846/112857984-b712b600-90b1-11eb-896c-010ae3e46833.png)

(I removed potential personal data)

**Comment by git-help-eng** [comment]
If I am understanding the email inbox screenshot correctly it looks like each email that was processed is ~30 larger than the emails that were not processed.  This may indicate that the nature of the email, or more directly their attachments, may not be as identical as you currently percieve them to be.

**Comment by MeikelLP** [comment]
You are right. The attachment icon indicates images in the mail but no PDF attachment.

Thanks for pointing out!
