### ISSUE TITLE
[Other] django warning about wrong retry to timeout ration

### ISSUE THREAD

**Issue by fleixi** [jonaswinkler/paperless-ng#857]
Since update to django 3.1.7-1, maybe before too

Apr 02 23:27:48 donald python3[2911]:   warn("""Retry and timeout are misconfigured. Set retry larger than timeout,
Apr 02 23:27:48 donald python3[2911]:         See https://django-q.readthedocs.io/en/latest/configure.html#retry for details.
Apr 02 23:27:48 donald python3[2911]:         failure to do so will cause the tasks to be retriggered before completion.
Apr 02 23:27:48 donald python3[2911]: /usr/lib/python3.9/site-packages/django_q/conf.py:136: UserWarning: Retry and timeout are misconfigured. Set retry larger than timeout,

i didnt change any part of django so the defaults are wrong. Where could i change them and maybe it need to be changed by you to

**Comment by jonaswinkler** [comment]
Paperless depends on django-q, version 1.3.4. This is a warning introduced with 1.3.5, but it does not apply to paperless. See https://github.com/Koed00/django-q/pull/509.

**Comment by fleixi** [comment]
oh ok than there is nothing to do about this.
