### ISSUE TITLE
[BUG] Starting paperless-ng container takes too long

### ISSUE THREAD

**Issue by jovandeginste** [jonaswinkler/paperless-ng#861]
**Describe the bug**
When I do a clean start of the paperless-ng container, it takes longer than I expect. Investigating this, learns that a chown is running at start:

```bash
chown -R paperless:paperless ../
```

This is [this line](https://github.com/jonaswinkler/paperless-ng/blob/master/docker/docker-entrypoint.sh#L85)

I have the "export" folder there containing the last export, which doubles the amount of files (currently total of 17K files)

**To Reproduce**
1. Have about 2800 documents in paperless
2. Run the document_exporter (to a host-mounted volume)
3. Verify the number of files in the container: `docker exec paperless find .. | wc -l`
4. Restart the container (with the export volume mounted)
5. Check the progress with `docker logs -f` - it will hang a while on "creating directory /tmp/paperless"
6. Check with `ps aux | grep chown` - you will see it is running `chown`

**Expected behavior**
Only chown files that need to be chowned

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu 20.04.1 LTS
 - Version: 1.3.2
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`:
     - volumes:
        - /home/containers/documents/data:/usr/src/paperless/data
        - /home/containers/documents/media:/usr/src/paperless/media
        - /mnt/backups/documents/current:/usr/src/paperless/export
        - /home/containers/documents/consume:/usr/src/paperless/consume
    - FS is mix of ext4 and btrfs 

** Possible fix

Only chown files that need to be chowned:

```bash
PAPERLESS_UID=$(id -u paperless)
PAPERLESS_GID=$(id -g paperless)

find .. -not \( -uid "${PAPERLESS_UID}" -and -gid "${PAPERLESS_GID}" \) -exec chown "${PAPERLESS_UID}:${PAPERLESS_GID}" {} +
```

**Comment by jonaswinkler** [comment]
fixed in 1.4.4
