### ISSUE TITLE
PAPERLESS_DBPORT not acknowledged in `docker-entrypoint.sh`

### ISSUE THREAD

**Issue by cellerich** [jonaswinkler/paperless-ng#87]
Hi Jonas

I have an issue with the latest docker image. I'm connecting to a local Postgres server which runs on port 5433 instead of 5432.
When the image is starting up it looks for the DB server in `docker-entrypoint.sh`. There the port is fixed to 5432 :-(

```shell
wait_for_postgres() {
	attempt_num=1
	max_attempts=5

	echo "Waiting for PostgreSQL to start..."

	host="${PAPERLESS_DBHOST}"

	while !</dev/tcp/$host/5432 ;
	do

		if [ $attempt_num -eq $max_attempts ]
		then
			echo "Unable to connect to database."
			exit 1
		else
			echo "Attempt $attempt_num failed! Trying again in 5 seconds..."

		fi

		attempt_num=$(expr "$attempt_num" + 1)
		sleep 5
	done
}
```
I think the correct way should be like that:

```shell
wait_for_postgres() {
	attempt_num=1
	max_attempts=5

	echo "Waiting for PostgreSQL to start..."

	host="${PAPERLESS_DBHOST}"
        port="${PAPERLESS_DDBPORT}" 

	while !</dev/tcp/$host/$port ;
	do

		if [ $attempt_num -eq $max_attempts ]
		then
			echo "Unable to connect to database."
			exit 1
		else
			echo "Attempt $attempt_num failed! Trying again in 5 seconds..."

		fi

		attempt_num=$(expr "$attempt_num" + 1)
		sleep 5
	done
}
```

Thanks for a fix and the great work you did already!

**Comment by jonaswinkler** [comment]
Good catch, will fix that in the next update. If you want to get going right now, you could go with the larger release that builds the image from scratch, edit the relevant file, and then build it.

**Comment by cellerich** [comment]
Tried to build it on my Windows box with Linux subsystem (WSL2) but not successful yet. Will try harder tomorrow.

PS: Just noticed a typo in my suggested code: “PAPERLESS_DDBPORT” instead of “PAPERLESS_DBPORT”.

**Comment by jonaswinkler** [comment]
Builds fine with WSL, just need to be aware that you'll have to use `PAPERLESS_CONSUMER_POLLING`, no filesystem notifications in WSL docker volumes.
