### ISSUE TITLE
Result of document upload (via api POST) e.g fails ocr or is duplicate results in "OK" response

### ISSUE THREAD

**Issue by canDry** [jonaswinkler/paperless-ng#888]
When I upload a document (via api POST) and it fails e.g. is a duplicate file or OCR fails (teseract) - the response is "OK".   
  
Remotely, it seems you can only determine that an error actually occurred if you retrieve the full log via get(url/api/logs/paperless/) then parse that text.  Or, perhaps get a list of all documents before the upload and compare the after result.  This won't give a reason for the error - but at least the remote will know it failed.
  
Am I missing something i.e. how to easily determine (via the api) whether the last action (e.g. document upload) was actually successful _or_ why not?

**Comment by jonaswinkler** [comment]
Well, the actual API upload was successful. That's what the reponse indicates. The consumption process takes some time, and I cannot wait with sending a response until that's done.

You can also use websockets and connect to wss://paperless:post/ws/status/ - paperless will announce consumption status updates on that channel.

**Comment by canDry** [comment]
Thanks for the quick response.

> You can also use websockets and connect to wss://paperless:post/ws/status/ - paperless will announce consumption status updates on that channel.  
Would it be possible to get an api call that returns the last 'job#' and its consumption status?  Then, at the beginning of the remote upload one could query that (to set the last job#), then query again after each upload to check if subsequent ones succeeded or failed?   
  
p.s. hope my request isn't too unusual...  I'm creating a way to organizing (sorting/collating) scanned documents at a remote location that will be uploaded to paperless.  Great tool!
