### ISSUE TITLE
[BUG] All output of document_retagger has same loglevel

### ISSUE THREAD

**Issue by jovandeginste** [jonaswinkler/paperless-ng#889]
**Describe the bug**
When running document_retagger, there is no difference in log levels; since I have over 2500 documents, there is a lot of output, and only a limited amount of useful lines (the actual changes)

**To Reproduce**
1. Run `python manage.py document_retagger -T -v X` (with X 0, 1, 2, 3)
2. See the same verbose output

**Expected behavior**
A different output depending on the log level

Eg. don't show `[INFO] [paperless.management.retagger] Processing document XYZ` when loglevel below some level

**Relevant information**
Docker container image based on v1.4.0, with Dutch language packs

**Comment by jonaswinkler** [comment]
I#ve changed the log output somewhat, maybe that's better now with 1.4.1.

**Comment by jovandeginste** [comment]
Perfect! Thanks!
