### ISSUE TITLE
[BUG] some pdf files are not consumed with "Unsupported mime type application/octet-stream" error

### ISSUE THREAD

**Issue by kurti500** [jonaswinkler/paperless-ng#906]
Some pdf files are not processed with following error, even though the file properly opens in a pdf reader without any issue.
Cannot figure out why its not consumed?

[2021-04-13 12:01:18,783] [INFO] [paperless.consumer] Consuming ID(116434_2)_Date(Sun, 21 Sep 2014 11_41_44 +0200)_PDF_Rechnung_M211140099558173_05-2014.pdf
[2021-04-13 12:01:18,792] [DEBUG] [paperless.consumer] Detected mime type: application/octet-stream
[2021-04-13 12:01:18,805] [ERROR] [paperless.consumer] Unsupported mime type application/octet-stream

Host OS of the machine running paperless: [e.g. Archlinux / Ubuntu 20.04] Synology Linux OS
Browser [e.g. chrome, safari] Chrome
Version [e.g. 1.0.0] 1.4.0
Installation method: [docker / bare metal] docker
Any configuration changes you made in docker-compose.yml, docker-compose.env or paperless.conf. no change, just added tika and gotenberg

**Comment by C0nsultant** [comment]
It seems that libgamic (https://github.com/ahupp/python-magic) has problems figuring out the file type.
Can you check the output of `file --mime-type yourdoc.pdf`?

**Comment by kurti500** [comment]
> file --mime-type yourdoc.pdf

Sorry for the noob question: where/how do I run the command within my SynologyNAS with paperless running within docker.
SSH on the Synology and running the command brings back
-sh: file: command not found

**Comment by C0nsultant** [comment]
You should be able to run this on any linux system where you have the file available.
Preferably, you would run this in the same environment your instance of NG is running in (so _inside_ the docker container).

**Comment by kurti500** [comment]
got it :-) same format as shown in my log in the first post:

`root@62a7e7bb2065:/usr/src/paperless/media# file --mime-type 116434_2.pdf
116434_2.pdf: application/octet-stream`

apparently its detected as binary file instead of pdf, however the file properly opens as pdf in any pdf reader?

Is the check of "file" too strict raising this as a false error?

**Comment by jonaswinkler** [comment]
It's highly likely that the file in question does not conform to the PDF specification (probably some leading characters before the magic "%PDF" string). Most PDF viewers are able to deal with that, but paperless expects valid PDF documents.

**Comment by kurti500** [comment]
Hm, the strange thing is that other documents from the same sender go through without any issues, the example file is an invoice from O2/Telefonica. Just wondering if they would really render their invoices differently case by case.
Any way to make paperless a bit more flexible in accepting such files?
How can I check if this file is wrongly formatted?

**Comment by jonaswinkler** [comment]
Well, `file` is the check to verify the type of a file.

Some users had success with opening the document in some kind of PDF editor, and saving it under a new name.

I need to identify the type of a file in order to pick the correct parser. There's a parser for PDF, for text files, and for office documents.

Specifically for PDF, even if I were to relax the requirements, I believe that OCRmyPDF would complain as well. Not tested though.

**Comment by kurti500** [comment]
Thanks for the feedback, understood. Will close the ticket then. Workaround for cases like this is to recreate the PDF.
