### ISSUE TITLE
How to delete documents ?

### ISSUE THREAD

**Issue by wechsler42** [jonaswinkler/paperless-ng#92]
Hi Jonas,
first of all: I am impressed. Thank you for reviving the paperless project in such a good manner.
Jonas, perhaps I am to old to find it, but how can I delete an erroneously uploaded document?

**Comment by jonaswinkler** [comment]
There's a red delete button on the document edit page in the top right corner.

**Comment by wechsler42** [comment]
It seems I am too old ...
Thanks for the hint, I found delete button now
