### ISSUE TITLE
IMAP rule with subfolder

### ISSUE THREAD

**Issue by genlinut** [jonaswinkler/paperless-ng#922]
Hey all,

i'm sure it's easy, but i don't get it. How can I use subfolder in E-Mail rules? I tried: "/" -> folder/subfolder without success. I also tried \ and - ... 

I also didn't find anything in the web or in the manual. So, maybe it isn't possible?

best regards
genlinut

**Comment by martinpichlo** [comment]
Try „INBOX.Foldername“

**Comment by genlinut** [comment]
Great! Now, it works like a charm! Thank you!

**Comment by henfri** [comment]
Hello,

for me, it is also a / and **NOT** a dot that works.
Thanks @andreheuer , I would not have tried that without your hint, as the webinterface says the opposite.

Provider is Ionos.

Best regards,
Hendrik

**Comment by balajeek** [comment]
i trying to figure out how i can set the folder for my icloud mailbox where i created a folder called USPS and provided the following and nothing worked.
INBOX.USPS
INBOX/USPS

any help?
