### ISSUE TITLE
[Other] Exporter can't be run from a crontab or script in general

### ISSUE THREAD

**Issue by freaky33** [jonaswinkler/paperless-ng#923]
Hey, 

I am trying to automate the Document Exporter and therefore created a small script:

```
#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/paperless/
cd /home/paperless/paperless-ng/
docker-compose exec webserver document_exporter ../export
```

The sh-file is located in /usr/local/bin and can be perfectly executed by running it manually. It also works If I replace the last line with "docker-compose down" or "up". Just the exporter does not seem to work when I call the script via Crontab or via Duplicati.

What could be the issue here?

**Comment by wiphi** [comment]
This one is working for me:
```
#!/bin/bash

PAPERLESS_DIR="/paperless/docker"
PAPERLESS_CONTAINER="webserver"

cd $PAPERLESS_DIR

docker-compose exec -T $PAPERLESS_CONTAINER python manage.py document_exporter -c ../export --compare-checksums --delete --use-filename-format
```

**Comment by martinpichlo** [comment]
https://github.com/jonaswinkler/paperless-ng/discussions/903

:-)

**Comment by freaky33** [comment]
> #903
> 
> :-)

Wow! Thank you two! The argument "-T" works for me too! Thanks
