### ISSUE TITLE
[Other] Upgrading instance installed with shell script

### ISSUE THREAD

**Issue by minorsecond** [jonaswinkler/paperless-ng#924]
I've installed Paperless-NG via the shell script (docker-compose, etc) and am wondering how to go about keeping the installation up to date. Could I simply add watchtower to the docker-compose.yml file to automatically keep it up to date? Is there a script to run occasionally to update?

**Comment by jonaswinkler** [comment]
See https://paperless-ng.readthedocs.io/en/latest/administration.html#docker-route.

Or watchtower, yes. I believe that providing instructions for watchtower is out of scope for paperless. But since paperless is just another docker image, follow their instructions to get automatic updates.
