### ISSUE TITLE
Supply jbig2enc with paperless

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#93]
This library reduces the size of archived PDF documents considerably, but it is generally not available in package managers, since it was patented until 2017 or so.

https://ocrmypdf.readthedocs.io/en/latest/jbig2.html

**Comment by rssfed23** [comment]
If this is added, would it be possible to add a command/task to automatically re-generate the pdf/A's with the updated compression method?

**Comment by jonaswinkler** [comment]
This is already in paperless. Look up the `document_archiver`management command in the documentation.

I believe that's what you're looking for?

**Comment by rssfed23** [comment]
Doh. That's exactly it - sorry 👍
