### ISSUE TITLE
[BUG] Very large PDFs can't be previewed in Firefox - pdf.js crashes

### ISSUE THREAD

**Issue by jfinas** [jonaswinkler/paperless-ng#935]
**Describe the bug**
When adding very large PDFs, in my case: 2 Pages colored at 600dpi = ~20 MB (I know this is probably excessive, but since storage is cheap I'd like my archived PDFs to be in the highest quality possible). While processing and thumbnail generation works the preview fails to show the PDF and crashes.

**To Reproduce**
1. Add a sufficiently large PDF File & wait for it to be processed
2. Preview it either by hovering over the eye icon or clicking it
3. wait for it to be loaded
4. The PDF is only white and Firefox shows an error(according to console pdf.js crashes):
![](https://user-images.githubusercontent.com/32193107/115152563-e5146600-a071-11eb-96b7-014a54e16426.png)

console output:
```
Beim Darstellen der Seite trat ein Fehler auf.
PDF.js Version 2.8.117 (build: 3d80c21a8)
Nachricht: 
Aufrufliste: putBinaryImageData@resource://pdf.js/build/pdf.js:4893:13
CanvasGraphics_paintInlineImageXObject@resource://pdf.js/build/pdf.js:6385:27
CanvasGraphics_paintImageXObject@resource://pdf.js/build/pdf.js:6335:12
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:5131:22
_next@resource://pdf.js/build/pdf.js:3879:39
_scheduleNext/<@resource://pdf.js/build/pdf.js:3867:16
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.js:3866:16
renderContinueCallback@resource://pdf.js/web/viewer.js:11744:9
paintOnCanvas/renderTask.onContinue@resource://pdf.js/web/viewer.js:11899:16
_continue@resource://pdf.js/build/pdf.js:3858:19
operatorListChanged@resource://pdf.js/build/pdf.js:3847:12
_renderPageChunk@resource://pdf.js/build/pdf.js:2556:34
pump/<@resource://pdf.js/build/pdf.js:2589:14
viewer.js:1419:15

renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pdf.js/build/pdf.js :: putBinaryImageData :: line 4893"  data: no]"

...
```
- Downloading the PDF works as expected and okular can display the downloaded PDF correctly.
- Preview in Chromium 90.0.4430.72 works as expected.

**Expected behavior**
The PDF is shown correctly.

**Webserver logs**
```
no errors in server logs...
```

**Relevant information**
 - Host OS of the machine running paperless: Debian Buster
 - Browser Firefox 87.0 on Arch Linux
 - Version 1.4.0 
 - Installation method: Docker - Redis + SQLite
 - Any configuration changes you made: set ocr-language, time-zone, allowed-hosts/CORS, file-name-format and redis-url

**Comment by jfinas** [comment]
I know this is probably not a bug you can fix directly, but a solution might be to prepare a lower resolution preview version for large PDFs. This would result in faster preview everywhere and work around the problem with Firefox.

**Comment by jonaswinkler** [comment]
There's a switch in the web ui settings that selects a different PDF viewer. Maybe that works better for you?

**Comment by jfinas** [comment]
Sadly no, same problem…

**Comment by jfinas** [comment]
It works (no matter whether paperless or browser viewer is used) as expected with smaller PDFs (for example 7 Pages, ~5mb).

**Comment by jonaswinkler** [comment]
Try with

```
PAPERLESS_OCR_USER_ARGS={"optimize": 3, "jbig2_lossy": true}
```

Restart paperless for that to take effect, as always.

This will enable some aggressive compression methods of OCRmyPDF, which is what paperless uses under the hood to do OCR. I have not tried that myself though.

**Comment by jfinas** [comment]
Thanks, I will try that in the next few days. :+1:

**Comment by jfinas** [comment]
To be honest, I totally forgot to answer to this, had a lot of other stuff on my mind and did not actually test your suggestion.
I think scanning in higher quality and then compressing to a lower quality somewhat misses the point since in want to archive in the highest quality possible.
The real problem seems to lie with Firefox's integrated PDF viewer and not paperless-ng(which works completely fine).
Since I recently switched to a chromium based browser anyways I don't really have that problem anymore.

**Comment by SigHunter** [comment]
thanks, I always wondered why some of my pdfs didn't display but most of them did. I now always switch to MS Edge when doing stuff in Paperless-ng
