### ISSUE TITLE
paperless-ng icon

### ISSUE THREAD

**Issue by after99** [jonaswinkler/paperless-ng#948]
have u [icon for homer](https://github.com/NX211/homer-icons)?

**Comment by jonaswinkler** [comment]
https://raw.githubusercontent.com/jonaswinkler/paperless-ng/master/src-ui/src/assets/logo.svg

**Comment by after99** [comment]
![paperless-ng](https://user-images.githubusercontent.com/63257521/115958086-d01a5580-a4fd-11eb-9273-6f2bd749bcef.png)

**Comment by jonaswinkler** [comment]
Looks good to me!
