### ISSUE TITLE
Docker: webserver container fails to start on aarch64

### ISSUE THREAD

**Issue by trahflow** [jonaswinkler/paperless-ng#95]
I'm trying to start the postgres image (pretty much standard configuration) on a fresh ubuntu 20.20 host system on arm64 (rasberry pi 4):
`$ uname -a
Linux ubuntu 5.8.0-1008-raspi #11-Ubuntu SMP PREEMPT Thu Nov 12 15:49:32 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
`
The webserver container fails to come up (restarting forever) and the logs show the following error:
`standard_init_linux.go:219: exec user process caused: exec format error`

Reading through some of the issues mentioned here, it seems that piwheels.org is used to pull python wheels. It seems that piwheels.org only provides wheels for 32-bit arm, not for 64 bit.

Just a wild guess, but could the error I'm seeing be related to this? Googling for that error leads to this SO question, where one of the answers suggests such errors can be related to architecture mismatches: https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error

**Comment by jonaswinkler** [comment]
Huh, I wasn't even aware up until now that there are 64 bit raspberry pis out there. I can't test that.

If you tried to run the image from docker hub (I don't even know if that's possible due to the architecture mismatch), then that's the issue. It contains amd64 binaries, which do not run on your hardware.

If you tried to go with the source archive and do a "docker-compose build", then something must have went wrong during that process. If you did not try that, do that, but no promises.

If piwheels does not supply 64 bit wheels and the 32 bit wheels are unable to execute on aarch64, building the image won't work. Paperless depends on a couple python packages that come with binaries. Without piwheels, these have to be compile on the pi itself, which a) requires additional development dependencies that the image currently does not have and b) takes hours. I've tried it overnight, and it wasn't done yet.

**Comment by trahflow** [comment]
Thanks for the very fast reply!

> Huh, I wasn't even aware up until now that there are 64 bit raspberry pis out there. I can't test that.
The hardware supports 64 bit since the Pi 3, only there is no stable release of raspberry pi OS for 64 bit yet. Which is why I'm using ubuntu 20.20 for raspberry pi, since my Pi 4 has 8GB of RAM. ubuntu 2020 aarch64 should also run on a Pi 3 though.

> If you tried to run the image from docker hub, then that's the issue
Ohh, yes that's the issue. I'm just migrating from paperless-original, where simply `docker-compose up` works, but I just realized that this does build the image rather than pulling it from docker hub (even though there exists an image on docker hub, which is why I was confused I guess).

I'm currently running `docker-compose build` as you suggested, but that does already seem to build the wheels (at least for scikit-learn), so it'll probably take some time until I know whether it worked.

**Comment by trahflow** [comment]
Hmm, actually the build just failed with:
`ERROR: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly
`

Detailed error:

```
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp73_t_gv9
       cwd: /tmp/pip-install-skihem67/pikepdf_6bff90dae4f944e19382cbc4b413f33c
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.7
  creating build/lib.linux-aarch64-3.7/pikepdf
  copying src/pikepdf/__init__.py -> build/lib.linux-aarch64-3.7/pikepdf
  copying src/pikepdf/objects.py -> build/lib.linux-aarch64-3.7/pikepdf
  copying src/pikepdf/_methods.py -> build/lib.linux-aarch64-3.7/pikepdf
  copying src/pikepdf/codec.py -> build/lib.linux-aarch64-3.7/pikepdf
  copying src/pikepdf/_cpphelpers.py -> build/lib.linux-aarch64-3.7/pikepdf
  copying src/pikepdf/jbig2.py -> build/lib.linux-aarch64-3.7/pikepdf
  copying src/pikepdf/_version.py -> build/lib.linux-aarch64-3.7/pikepdf
  creating build/lib.linux-aarch64-3.7/pikepdf/models
  copying src/pikepdf/models/__init__.py -> build/lib.linux-aarch64-3.7/pikepdf/models
  copying src/pikepdf/models/encryption.py -> build/lib.linux-aarch64-3.7/pikepdf/models
  copying src/pikepdf/models/image.py -> build/lib.linux-aarch64-3.7/pikepdf/models
  copying src/pikepdf/models/matrix.py -> build/lib.linux-aarch64-3.7/pikepdf/models
  copying src/pikepdf/models/outlines.py -> build/lib.linux-aarch64-3.7/pikepdf/models
  copying src/pikepdf/models/metadata.py -> build/lib.linux-aarch64-3.7/pikepdf/models
  copying src/pikepdf/py.typed -> build/lib.linux-aarch64-3.7/pikepdf
  running build_ext
  building 'pikepdf._qpdf' extension
  creating build/temp.linux-aarch64-3.7
  creating build/temp.linux-aarch64-3.7/src
  creating build/temp.linux-aarch64-3.7/src/qpdf
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-szw9hn5x/overlay/lib/python3.7/site-packages/pybind11/include -I/usr/local/include/python3.7m -c src/qpdf/object.cpp -o build/temp.linux-aarch64-3.7/src/qpdf/object.o -std=c++14 -fvisibility=hidden -g0
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-szw9hn5x/overlay/lib/python3.7/site-packages/pybind11/include -I/usr/local/include/python3.7m -c src/qpdf/object_convert.cpp -o build/temp.linux-aarch64-3.7/src/qpdf/object_convert.o -std=c++14 -fvisibility=hidden -g0
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-szw9hn5x/overlay/lib/python3.7/site-packages/pybind11/include -I/usr/local/include/python3.7m -c src/qpdf/annotation.cpp -o build/temp.linux-aarch64-3.7/src/qpdf/annotation.o -std=c++14 -fvisibility=hidden -g0
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-szw9hn5x/overlay/lib/python3.7/site-packages/pybind11/include -I/usr/local/include/python3.7m -c src/qpdf/object_repr.cpp -o build/temp.linux-aarch64-3.7/src/qpdf/object_repr.o -std=c++14 -fvisibility=hidden -g0
  src/qpdf/annotation.cpp:11:10: fatal error: qpdf/Constants.h: No such file or directory
   #include <qpdf/Constants.h>
            ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-szw9hn5x/overlay/lib/python3.7/site-packages/pybind11/include -I/usr/local/include/python3.7m -c src/qpdf/page.cpp -o build/temp.linux-aarch64-3.7/src/qpdf/page.o -std=c++14 -fvisibility=hidden -g0
  /usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'
    warnings.warn(msg)
  src/qpdf/object.cpp:11:10: fatal error: qpdf/Constants.h: No such file or directory
   #include <qpdf/Constants.h>
            ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  src/qpdf/object_repr.cpp:23:10: fatal error: qpdf/Constants.h: No such file or directory
   #include <qpdf/Constants.h>
            ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  src/qpdf/object_convert.cpp:17:10: fatal error: qpdf/Constants.h: No such file or directory
   #include <qpdf/Constants.h>
            ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  In file included from src/qpdf/page.cpp:14:
  src/qpdf/pikepdf.h:15:10: fatal error: qpdf/PointerHolder.hh: No such file or directory
   #include <qpdf/PointerHolder.hh>
            ^~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  ----------------------------------------
  ERROR: Failed building wheel for pikepdf
```

**Comment by trahflow** [comment]
Adding libqpdf-dev to build dependencies fixes the build error.
I've created a PR

**Comment by jonaswinkler** [comment]
@trahflow please close this if you feel that the issue is resolved. I can't test that.

**Comment by trahflow** [comment]
Yes it's resolved. Thanks!
