### ISSUE TITLE
[BUG] Sorting of search results doesn't work

### ISSUE THREAD

**Issue by CSchlipp** [jonaswinkler/paperless-ng#975]
**Describe the bug**
Documents in Paperless cannot be sorted in search results.

**To Reproduce**
1. Search for a keyword that gives multiple results
2. Try to sort, e.g. by date
3. Observe that the order doesn't change (see e.g. screenshots, same behavior for all columns!)

**Expected behavior**
Documents should be sorted by selected column/order.

**Screenshots**
Search results:
![image](https://user-images.githubusercontent.com/4139563/116820460-91c40c80-ab75-11eb-910c-56242cdc817b.png)
Ordered by date (Desc):
![image](https://user-images.githubusercontent.com/4139563/116820477-adc7ae00-ab75-11eb-8932-a99d9c12c081.png)
Ordered by date (Asc):
![image](https://user-images.githubusercontent.com/4139563/116820502-c637c880-ab75-11eb-8e5f-d6c61d804d9d.png)

**Webserver logs**
```
n/a, no logs for this
```

**Relevant information**
 - Ubuntu 20.04
 - Chrome and Edge
 - Version 1.4.2
 - Installation method: docker
 - Changed config: 
   - Traefik reverse proxy
   - PAPERLESS_AUTO_LOGIN_USERNAME
   - PAPERLESS_OCR_USER_ARGS: "{\"max_image_mpixels\": 260}"
   - PAPERLESS_IGNORE_DATES

**Comment by Kumen** [comment]
Does not work for me either. 

Ubuntu 20.04
Firefox (latest)
Version 1.4.2
Installation method: docker
Changed config: 
- nothing -> vanilla

**Comment by jonaswinkler** [comment]
I'm aware of that. The search results are always sorted by relevance to the search term. I did have some trouble getting this to work for full text search as well.

**Comment by plasmac0r** [comment]
I can't confirm. Works for me. It's sorting like expected if I either click on the sort button (inkl. asc/desc) or on the column title bar.

Ubuntu 20.10 (Groovy Gorilla)
Firefox 88.0
Version: 1.4.2 (fresh install yesterday)
Installation method: docker
Changed config: nothing -> vanilla
Circa 350 documents

**Comment by CSchlipp** [comment]
> I'm aware of that. The search results are always sorted by relevance to the search term. I did have some trouble getting this to work for full text search as well.

I don't want to turn this into a feature request, but if possible, "relevance" may be given as a dedicated option/column to sort the results?

**Comment by jonaswinkler** [comment]
Absolutely. I've had some trouble getting this implemented, and did not want to delay the update further. Already have some ideas about how to do it, just need some time.

**Comment by amenk** [comment]
Same problem exists for the advanced search (master branch), for example with

`asn:[1 to 100]` and then trying to order by ASN or title

http://localhost:8000/api/documents/?page=1&page_size=50&ordering=-archive_serial_number&query=asn:%5B1%20to%204%5D

**Comment by amenk** [comment]
I added some failing tests for convenience and looked into it, but have no clue ;-) Looks like a fix is on the way though - so I leave this up to you @jonaswinkler - thanks :-)

**Comment by jonaswinkler** [comment]
Oh well, seems we both did the same thing.

https://github.com/jonaswinkler/paperless-ng/commit/8ee2e8b23d2b0f5a3603a8816cccdf2a6f1f46a2

**Comment by amenk** [comment]
> Oh well, seems we both did the same thing.
> 
> [8ee2e8b](https://github.com/jonaswinkler/paperless-ng/commit/8ee2e8b23d2b0f5a3603a8816cccdf2a6f1f46a2)

Great you got it fixed :)

**Comment by CSchlipp** [comment]
Awesome work, thank you!
