### ISSUE TITLE
[BUG] Dark mode issues/missing

### ISSUE THREAD

**Issue by rYR79435** [jonaswinkler/paperless-ng#985]
The login and logout pages are not in dark mode. This is true for when Paperless is set to follow system theme and when specifically setting dark mode.

**Comment by shamoon** [comment]
Fair enough. Since the user isnt logged in (obviously) we will just use the browser / system preference. I have a PR

**Comment by jonaswinkler** [comment]
This is as good as it gets. It might be inconsistent with the actual front end, depending on settings.
